obj-m += devhost_probe.o
ccflags-y += ${DEVHOST_API_CFLAGS}
ccflags-y += "-I$(srctree)/uapps/devhost/ldk_ext/probe/include"
ccflags-y += "-I$(srctree)/uapps/devhost/include"
ccflags-y += -I${HMSDKSYSROOTPATH}/usr/include
