/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2023. All rights reserved.
 * Description: ffts_ddr_map.h
 * Create: 2023-05-06
 */

#ifndef __FFTS_DDR_MAP_H__
#define __FFTS_DDR_MAP_H__

#include "soc_ffts_interface.h"

#define FFTS_RESERVED_DDR_BASE_ADDR   (0x32F00000) /* 0x32F00000 */
#define FFTS_RESERVED_MEMORY_SIZE     (0x480000) /* 0x480000 */
#define FFTS_ACPU_NORMAL_INT_QUEUE_DDR_LEN  0x4000
#define FFTS_ACPU_ABNORMAL_INT_QUEUE_DDR_LEN  0x4000

/* the index of ffts reserved memory used scene */
typedef enum {
	FFTS_PROCCTX_DDR,
	FFTS_THREADCTX_DDR,
	FFTS_TASKCTX_DDR,
	FFTS_VERCTX_DDR,
	FFTS_SIGCTX_DDR,
	FFTS_HWRTB_DDR,
	FFTS_ACPU_INT_QUEUE_DDR,
	FFTS_ISP_INT_QUEUE_DDR,
	FFTS_SR_DDR,
	FFTS_HTS_AUTH_TABLE_DDR,
	FFTS_RESMEM_MAX,
} ffts_resmem_type_t;

/* the size of ffts reserved memory used scene, total 0x446000 */
enum ffts_resmem_size_t {
    FFTS_PROCCTX_DDR_LEN = 0x10000,
    FFTS_THREADCTX_DDR_LEN = 0x80000,
    FFTS_TASKCTX_DDR_LEN = 0x100000,
    FFTS_VERCTX_DDR_LEN = 0x80000,
    FFTS_SIGCTX_DDR_LEN = 0x200000,
    FFTS_HWRTB_DDR_LEN = 0x20000,
    FFTS_ACPU_INT_QUEUE_DDR_LEN = 0x8000,
    FFTS_ISP_INT_QUEUE_DDR_LEN = 0x8000,
    FFTS_SR_DDR_LEN = 0x5000,
    FFTS_HTS_AUTH_TABLE_DDR_LEN = 0x1000,
};

/* ffts ddr map */
#define FFTS_PROCCTX_BASE_ADDR			(FFTS_RESERVED_DDR_BASE_ADDR)
#define FFTS_THREADCTX_BASE_ADDR		(FFTS_PROCCTX_BASE_ADDR + FFTS_PROCCTX_DDR_LEN)
#define FFTS_TASKCTX_BASE_ADDR			(FFTS_THREADCTX_BASE_ADDR + FFTS_THREADCTX_DDR_LEN)
#define FFTS_VERCTX_BASE_ADDR			(FFTS_TASKCTX_BASE_ADDR + FFTS_TASKCTX_DDR_LEN)
#define FFTS_SIGCTX_BASE_ADDR			(FFTS_VERCTX_BASE_ADDR + FFTS_VERCTX_DDR_LEN)
#define FFTS_HWRTB_BASE_ADDR			(FFTS_SIGCTX_BASE_ADDR + FFTS_SIGCTX_DDR_LEN)
#define FFTS_ACPU_INT_QUEUE_BASE_ADDR	(FFTS_HWRTB_BASE_ADDR + FFTS_HWRTB_DDR_LEN)
#define FFTS_ISP_INT_QUEUE_BASE_ADDR	(FFTS_ACPU_INT_QUEUE_BASE_ADDR + FFTS_ACPU_INT_QUEUE_DDR_LEN)
#define FFTS_SR_BASE_ADDR				(FFTS_ISP_INT_QUEUE_BASE_ADDR + FFTS_ISP_INT_QUEUE_DDR_LEN)
#define FFTS_HTS_AUTH_TABLE_BASE_DDR    (FFTS_SR_BASE_ADDR + FFTS_SR_DDR_LEN)

#endif /* __FFTS_DDR_MAP_H__ */
