/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2025 All rights reserved.
 * Description: lpm_runtime_offset.h
 * Create: 2023-10-15
 */
#ifndef _LPM_RUNTIME_OFFSET_H_
#define _LPM_RUNTIME_OFFSET_H_

#ifndef RUNTIME_VAR_BASE
#define RUNTIME_VAR_BASE                        (0) /* 0x140 */
#define RUNTIME_VAR_SIZE                        0x338 /* 824Bytes */
#endif

#ifndef BYTE_REF
#define BYTE_REF(address)			(*((unsigned char volatile *)(uintptr_t)(address)))
#endif

#ifndef WORD_REF
#define WORD_REF(address)			(*((unsigned int volatile *)(uintptr_t)(address)))
#endif

#ifndef WORD_PTR
#define WORD_PTR(address)			(*((unsigned int volatile **)(uintptr_t)(address)))
#endif

#ifndef HALFWORD_REF
#define HALFWORD_REF(address)			(*((unsigned short volatile *)(uintptr_t)(address)))
#endif


/* initial state is passed by other cores (for example: fastboot->lpm3), and the address needs to be of a fixed type */
#define RUNTIME_CPU_VAR_ADDR		RUNTIME_VAR_BASE
#define RUNTIME_CPU_VAR_SIZE		0x40U /* cpu SIZE:0x40 */
#define RUNTIME_CPU_DVS_STATUS_ADDR(n)           (RUNTIME_VAR_BASE + 0x30 + ((n) * 1))
#define CPU_DVS_STATUS(n)                        (BYTE_REF(RUNTIME_CPU_DVS_STATUS_ADDR(n)))

#define RUNTIME_GPU_VAR_ADDR				(RUNTIME_CPU_VAR_ADDR + RUNTIME_CPU_VAR_SIZE) /* offset 0x40 */
#define RUNTIME_GPU_VAR_SIZE				0x20U
#define RUNTIME_GPU_CURRENT_ADDR			(RUNTIME_VAR_BASE + 0x40)
#define RUNTIME_GPUTOP_TARGET_ADDR			(RUNTIME_VAR_BASE + 0x53)
#define RUNTIME_GPU_VAR_END					(RUNTIME_GPUTOP_TARGET_ADDR)

#define RUNTIME_TMP_VAR_ADDR				(RUNTIME_GPU_VAR_ADDR + RUNTIME_GPU_VAR_SIZE) /* offset 0x60 */
#define RUNTIME_TMP_VAR_SIZE				(0x20U)
#define RUNTIME_LOWTMP_CUR_ADDR				(RUNTIME_VAR_BASE + 0x76)
#define RUNTIME_TMP_VAR_END					(RUNTIME_LOWTMP_CUR_ADDR)

#define RUNTIME_GEN_VAR_ADDR				(RUNTIME_TMP_VAR_ADDR + RUNTIME_TMP_VAR_SIZE) /* offset 0x80 */
#define RUNTIME_GEN_VAR_SIZE				0x20U

#define RUNTIME_PERIL_VAR_ADDR 				(RUNTIME_GEN_VAR_ADDR + RUNTIME_GEN_VAR_SIZE) /* offset 0xA0 */
#define RUNTIME_PERIL_VAR_SIZE 				(0x20U)
#define RUNTIME_CPU_LOWTEMP_VOLT_BIAS_ADDR(n) 	(RUNTIME_VAR_BASE + 0xB2 + (n) * 1) /* n = 0,1,2,3 */
#define RUNTIME_PERIL_VAR_END				(RUNTIME_CPU_LOWTEMP_VOLT_BIAS_ADDR(3))

#define RUNTIME_DDR_VAR_ADDR				(RUNTIME_PERIL_VAR_ADDR + RUNTIME_PERIL_VAR_SIZE) /* offset 0xC0 */
/* ddr */
#define RUNTIME_DDR_STATUS_ADDR				(RUNTIME_DDR_VAR_ADDR)
#define DDR_STATUS				(HALFWORD_REF(RUNTIME_DDR_STATUS_ADDR)) /* 2 bytes */
#define RUNTIME_DDR_INITFREQ_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x002)
#define INITFREQ				(BYTE_REF(RUNTIME_DDR_INITFREQ_ADDR))
#define RUNTIME_DDR_TMP_PERIOD_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x003)
#define DDR_TMP_PERIOD				(BYTE_REF(RUNTIME_DDR_TMP_PERIOD_ADDR))
#define RUNTIME_DDR_PD_PERIOD_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x004)
#define DDR_PD_PRD				(HALFWORD_REF(RUNTIME_DDR_PD_PERIOD_ADDR))
#define RUNTIME_DDR_ASREF_PERIOD_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x006)
#define DDR_ASREF_PRD				(HALFWORD_REF(RUNTIME_DDR_ASREF_PERIOD_ADDR))
#define RUNTIME_DDR_FREQ_LOAD_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x008) /* 2*8 bytes */
#define DDR_FREQ_LOAD(n)			(HALFWORD_REF(RUNTIME_DDR_FREQ_LOAD_ADDR + ((n) * 2)))
#define RUNTIME_DDR_MIN_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x018)
#define DDR_MIN					(BYTE_REF(RUNTIME_DDR_MIN_ADDR))
#define RUNTIME_DDR_MAX_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x019)
#define DDR_MAX					(BYTE_REF(RUNTIME_DDR_MAX_ADDR))
#define RUNTIME_DDR_LAST_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x01A)
#define DDR_LAST				(BYTE_REF(RUNTIME_DDR_LAST_ADDR))
#define RUNTIME_DDR_CURRENT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x01B)
#define DDR_CURRENT				(BYTE_REF(RUNTIME_DDR_CURRENT_ADDR))
#define RUNTIME_DDR_TARGET_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x01C)
#define DDR_TARGET				(BYTE_REF(RUNTIME_DDR_TARGET_ADDR))
#define RUNTIME_DDR_DN_LIMIT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x01D)
#define DDR_DN_LIMIT				(BYTE_REF(RUNTIME_DDR_DN_LIMIT_ADDR))
#define RUNTIME_DDR_UP_LIMIT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x01E)
#define DDR_UP_LIMIT				(BYTE_REF(RUNTIME_DDR_UP_LIMIT_ADDR))
#define RUNTIME_DDR_PLL_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x01F)
#define DDR_PLL					(BYTE_REF(RUNTIME_DDR_PLL_ADDR))
#define RUNTIME_DDR_LAST_PLL_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x020)
#define DDR_LAST_PLL				(BYTE_REF(RUNTIME_DDR_LAST_PLL_ADDR))

/* reserved 3bytes for align */
#define RUNTIME_CMD_CNT_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x024) /* 0\1\2\3 */
#define CMD_CNT					(WORD_REF(RUNTIME_CMD_CNT_ADDR))
#define RUNTIME_DATA_CNT_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x028)
#define DATA_CNT				(WORD_REF(RUNTIME_DATA_CNT_ADDR))
#define RUNTIME_L1BUS_MIN_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x02C)
#define L1BUS_MIN				(HALFWORD_REF(RUNTIME_L1BUS_MIN_ADDR))
#define RUNTIME_L1BUS_MAX_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x02E)
#define L1BUS_MAX				(HALFWORD_REF(RUNTIME_L1BUS_MAX_ADDR))
#define RUNTIME_L1BUS_LAST_ADDR				(RUNTIME_DDR_VAR_ADDR + 0x030)
#define L1BUS_LAST				(HALFWORD_REF(RUNTIME_L1BUS_LAST_ADDR))
#define RUNTIME_L1BUS_CURRENT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x032)
#define L1BUS_CURRENT				(HALFWORD_REF(RUNTIME_L1BUS_CURRENT_ADDR))
#define RUNTIME_L1BUS_TARGET_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x034)
#define L1BUS_TARGET				(HALFWORD_REF(RUNTIME_L1BUS_TARGET_ADDR))
#define RUNTIME_L1BUS_DN_LIMIT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x036)
#define L1BUS_DN_LIMIT				(HALFWORD_REF(RUNTIME_L1BUS_DN_LIMIT_ADDR))
#define RUNTIME_L1BUS_UP_LIMIT_ADDR			(RUNTIME_DDR_VAR_ADDR + 0x038)
#define L1BUS_UP_LIMIT				(HALFWORD_REF(RUNTIME_L1BUS_UP_LIMIT_ADDR))
/* warning:if add new status at last,must sync modify RUNTIME_SHARE_MEM_END_ADDR */
#define RUNTIME_DDR_RUNTIME_END_ADDR			(RUNTIME_L1BUS_UP_LIMIT_ADDR)

/* don't modify this */
#define RUNTIME_SHARE_MEM_SIZE			(0x100)
#define RUNTIME_SHARE_MEM_END_ADDR		(RUNTIME_VAR_BASE + RUNTIME_SHARE_MEM_SIZE) /* must be divided by 4 */
#if (RUNTIME_DDR_RUNTIME_END_ADDR >= RUNTIME_SHARE_MEM_END_ADDR)
	#error "runtime share memory overflow!!!"
#endif

/* state variables that only start to be used after lpm3 is started */
#define RUNTIME_LPMCU_RUN_VAR_SIZE		0x50

#define RUNTIME_LPM3_CFG_ADDR				(RUNTIME_SHARE_MEM_END_ADDR + 0x000)
#define LPM3_CFG				(BYTE_REF(RUNTIME_LPM3_CFG_ADDR))
#define RUNTIME_TASK_CYCLE_STATUS_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x001)
#define TASK_CYCLE_STATUS			(BYTE_REF(RUNTIME_TASK_CYCLE_STATUS_ADDR))
/* reserved 2bytes for align */
#define RUNTIME_MAX_IRQ_MAST_PERIOD_ADDR		(RUNTIME_SHARE_MEM_END_ADDR + 0x004)
#define MAX_IRQ_MAST_PERIOD			(WORD_REF(RUNTIME_MAX_IRQ_MAST_PERIOD_ADDR))
#define RUNTIME_MAX_IRQ_MASK_FUNC_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x008)
#define MAX_IRQ_MASK_FUNC			(WORD_REF(RUNTIME_MAX_IRQ_MASK_FUNC_ADDR))
#define RUNTIME_IRQ_MAST_PERIOD_SUM_ADDR		(RUNTIME_SHARE_MEM_END_ADDR + 0x00C)
#define IRQ_MAST_PERIOD_SUM			(WORD_REF(RUNTIME_IRQ_MAST_PERIOD_SUM_ADDR))
#define RUNTIME_IRQ_MASK_TIMES_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x010)
#define IRQ_MASK_TIMES				(WORD_REF(RUNTIME_IRQ_MASK_TIMES_ADDR))
#define RUNTIME_SYNC_IPC_TASK_MSG_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x014)
#define SYNC_IPC_TASK_MSG			(WORD_REF(RUNTIME_SYNC_IPC_TASK_MSG_ADDR))
#define RUNTIME_ASYNC_IPC_TASK_MSG_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x018)
#define ASYNC_IPC_TASK_MSG			(WORD_REF(RUNTIME_ASYNC_IPC_TASK_MSG_ADDR))
#define RUNTIME_LPM3_DDR_LOG_WP_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x01C)
#define LPM3_DDR_LOG_WP				(WORD_REF(RUNTIME_LPM3_DDR_LOG_WP_ADDR))
#define RUNTIME_LPM3_DDR_LOG_RP_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x020)
#define LPM3_DDR_LOG_RP				(WORD_REF(RUNTIME_LPM3_DDR_LOG_RP_ADDR))
#define RUNTIME_LPM3_DDR_LOG_FLAG_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x024)
#define LPM3_DDR_LOG_FLAG			(WORD_REF(RUNTIME_LPM3_DDR_LOG_FLAG_ADDR))
#define RUNTIME_AUDIO_STATE_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x028)
#define AUDIO_STATE				(WORD_REF(RUNTIME_AUDIO_STATE_ADDR))
#define RUNTIME_ASP_CLK_STATE_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x02C)
#define ASP_CLK_STATE				(WORD_REF(RUNTIME_ASP_CLK_STATE_ADDR))
#define RUNTIME_ASP_CLK_STATE2_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x030)
#define ASP_CLK_STATE2				(WORD_REF(RUNTIME_ASP_CLK_STATE2_ADDR))
#define RUNTIME_PLL_UNLOCK_STAT_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x034)
#define PLL_UNLOCK_STAT				(WORD_REF(RUNTIME_PLL_UNLOCK_STAT_ADDR))
#define RUNTIME_OS_TIMER_CALLBACK_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x038)
#define OS_TIMER_CALLBACK				(WORD_REF(RUNTIME_OS_TIMER_CALLBACK_ADDR))
#define RUNTIME_DDR_UNAVAILABLE_ADDR		(RUNTIME_SHARE_MEM_END_ADDR + 0x03C)
#define DDR_UNAVAILABLE_STATE		(WORD_REF(RUNTIME_DDR_UNAVAILABLE_ADDR)) /* 4 bytes */
#define RUNTIME_SYNC_IPC_TASK_DATA_ADDR		(RUNTIME_SHARE_MEM_END_ADDR + 0x040)
#define SYNC_IPC_TASK_DATA			(WORD_REF(RUNTIME_SYNC_IPC_TASK_DATA_ADDR))
#define RUNTIME_IPC_IRQ_DATA_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x044)
#define IPC_IRQ_DATA			(WORD_REF(RUNTIME_IPC_IRQ_DATA_ADDR))
#define RUNTIME_BUGON_REASON_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x048)
#define LPMCU_BUGON_REASON			(WORD_REF(RUNTIME_BUGON_REASON_ADDR))

#define RUNTIME_HIFI_IPC_RCV_TIME_ADDR			(RUNTIME_SHARE_MEM_END_ADDR + 0x04C)
#define HIFI_IPC_RCV_TIME			(WORD_REF(RUNTIME_HIFI_IPC_RCV_TIME_ADDR))

/* warning:if add new status at last,must sync modify RUNTIME_LPMCU_RUN_VAR_END_ADDR */
#define RUNTIME_LPMCU_RUN_VAR_END_ADDR		(RUNTIME_HIFI_IPC_RCV_TIME_ADDR)
#if (RUNTIME_LPMCU_RUN_VAR_END_ADDR >= (RUNTIME_SHARE_MEM_END_ADDR + RUNTIME_LPMCU_RUN_VAR_SIZE))
	#error "runtime lpmcu run memory overflow!!!"
#endif

#define RUNTIME_SR_VAR_BASE_ADDR		(RUNTIME_SHARE_MEM_END_ADDR + RUNTIME_LPMCU_RUN_VAR_SIZE)
/* SR */
#define RUNTIME_WAKE_STATUS_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x000)
#define WAKE_STATUS				(WORD_REF(RUNTIME_WAKE_STATUS_ADDR))
#define RUNTIME_DEEP_SLEEP_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x004)
#define SYS_DSLEEP_CNT				(WORD_REF(RUNTIME_DEEP_SLEEP_CNT_ADDR))
#define RUNTIME_DEEP_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x008)
#define SYS_DWAKE_CNT				(WORD_REF(RUNTIME_DEEP_WAKE_CNT_ADDR))
#define RUNTIME_SLEEP_CNT_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x00C)
#define SYS_SLEEP_CNT				(WORD_REF(RUNTIME_SLEEP_CNT_ADDR))
#define RUNTIME_SLEEP_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x010)
#define SYS_SLEEP_WAKE_CNT			(WORD_REF(RUNTIME_SLEEP_WAKE_CNT_ADDR))
#define RUNTIME_DOZE1_CNT_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x014)
#define SYS_DOZE1_CNT				(WORD_REF(RUNTIME_DOZE1_CNT_ADDR))
#define RUNTIME_DOZE2_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x018)
#define SYS_DOZE2_CNT			(WORD_REF(RUNTIME_DOZE2_CNT_ADDR))
#define RUNTIME_LIGHT_SLEEP_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x01C)
#define LIGHT_SLEEP_CNT			(WORD_REF(RUNTIME_LIGHT_SLEEP_CNT_ADDR))
#define RUNTIME_LIGHT_SLEEP_RESUME_CNT_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x020)
#define LIGHT_SLEEP_RESUME_CNT			(WORD_REF(RUNTIME_LIGHT_SLEEP_RESUME_CNT_ADDR))
#define RUNTIME_AP_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x024)
#define AP_WAKE_CNT				(WORD_REF(RUNTIME_AP_WAKE_CNT_ADDR))
#define RUNTIME_HIFI_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x028)
#define HIFI_WAKE_CNT				(WORD_REF(RUNTIME_HIFI_WAKE_CNT_ADDR))
#define RUNTIME_MODEM_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x02C)
#define MODEM_WAKE_CNT				(WORD_REF(RUNTIME_MODEM_WAKE_CNT_ADDR))
#define RUNTIME_IOMCU_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x030)
#define IOM3_WAKE_CNT				(WORD_REF(RUNTIME_IOMCU_WAKE_CNT_ADDR))
#define RUNTIME_LPMCU_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x034)
#define LPM3_WAKE_CNT				(WORD_REF(RUNTIME_LPMCU_WAKE_CNT_ADDR))
#define RUNTIME_GENERAL_SEE_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x038)
#define GENERAL_SEE_WAKE_CNT				(WORD_REF(RUNTIME_GENERAL_SEE_WAKE_CNT_ADDR))
#define RUNTIME_AP_SUSPEND_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x03C)
#define AP_SUSPEND_CNT				(WORD_REF(RUNTIME_AP_SUSPEND_CNT_ADDR))
#define RUNTIME_AP_RESUME_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x040)
#define AP_RESUME_CNT				(WORD_REF(RUNTIME_AP_RESUME_CNT_ADDR))
#define RUNTIME_MODEM_SUSPEND_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x044)
#define MODEM_SUSPEND_CNT			(WORD_REF(RUNTIME_MODEM_SUSPEND_CNT_ADDR))
#define RUNTIME_MODEM_RESUME_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x048)
#define MODEM_RESUME_CNT			(WORD_REF(RUNTIME_MODEM_RESUME_CNT_ADDR))
#define RUNTIME_HIFI_SUSPEND_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x04C)
#define HIFI_SUSPEND_CNT			(WORD_REF(RUNTIME_HIFI_SUSPEND_CNT_ADDR))
#define RUNTIME_HIFI_RESUME_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x050)
#define HIFI_RESUME_CNT				(WORD_REF(RUNTIME_HIFI_RESUME_CNT_ADDR))
#define RUNTIME_IOMCU_SUSPEND_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x054)
#define IOM3_SUSPEND_CNT			(WORD_REF(RUNTIME_IOMCU_SUSPEND_CNT_ADDR))
#define RUNTIME_IOMCU_RESUME_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x058)
#define IOM3_RESUME_CNT				(WORD_REF(RUNTIME_IOMCU_RESUME_CNT_ADDR))
#define RUNTIME_GENERAL_SEE_SUSPEND_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x05C)
#define GENERAL_SEE_SUSPEND_CNT			(WORD_REF(RUNTIME_GENERAL_SEE_SUSPEND_CNT_ADDR))
#define RUNTIME_GENERAL_SEE_RESUME_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x060)
#define GENERAL_SEE_RESUME_CNT			(WORD_REF(RUNTIME_GENERAL_SEE_RESUME_CNT_ADDR))
#define RUNTIME_LIGHTSLEEP_WAKE_IRQ_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x064)
#define LIGHTSLEEP_WAKE_IRQ			(WORD_REF(RUNTIME_LIGHTSLEEP_WAKE_IRQ_ADDR))
#define RUNTIME_LIGHTSLEEP_WAKE_IRQ1_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x068)
#define LIGHTSLEEP_WAKE_IRQ1			(WORD_REF(RUNTIME_LIGHTSLEEP_WAKE_IRQ1_ADDR))
#define RUNTIME_SLOW_WAKE_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x06C)
#define SLOW_WAKE_IRQ				(WORD_REF(RUNTIME_SLOW_WAKE_IRQ_ADDR))
#define RUNTIME_SLOW_WAKE_IRQ1_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x070)
#define SLOW_WAKE_IRQ1				(WORD_REF(RUNTIME_SLOW_WAKE_IRQ1_ADDR))
#define RUNTIME_SLEEP_WAKE_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x074)
#define SLEEP_WAKE_IRQ				(WORD_REF(RUNTIME_SLEEP_WAKE_IRQ_ADDR))
#define RUNTIME_SLEEP_WAKE_IRQ1_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x078)
#define SLEEP_WAKE_IRQ1				(WORD_REF(RUNTIME_SLEEP_WAKE_IRQ1_ADDR))
#define RUNTIME_WAKE_IRQ_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x07C)
#define WAKE_IRQ				(WORD_REF(RUNTIME_WAKE_IRQ_ADDR))
#define RUNTIME_WAKE_IRQ1_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x080)
#define WAKE_IRQ1				(WORD_REF(RUNTIME_WAKE_IRQ1_ADDR))
#define RUNTIME_WAKE_IRQ2_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x084)
#define WAKE_IRQ2				(WORD_REF(RUNTIME_WAKE_IRQ2_ADDR))
#define RUNTIME_WAKE_IRQ3_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x088)
#define WAKE_IRQ3				(WORD_REF(RUNTIME_WAKE_IRQ3_ADDR))
#define RUNTIME_AP_WAKE_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x08c)
#define AP_WAKE_IRQ				(WORD_REF(RUNTIME_AP_WAKE_IRQ_ADDR))
#define RUNTIME_MODEM_WAKE_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x090)
#define MODEM_WAKE_IRQ				(WORD_REF(RUNTIME_MODEM_WAKE_IRQ_ADDR))
#define RUNTIME_HIFI_WAKE_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x094)
#define HIFI_WAKE_IRQ				(WORD_REF(RUNTIME_HIFI_WAKE_IRQ_ADDR))
#define RUNTIME_AP_NSIPC_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x098)
#define AP_NSIPC_IRQ				(WORD_REF(RUNTIME_AP_NSIPC_IRQ_ADDR))
#define RUNTIME_AP_AO_NSIPC_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x09c)
#define AP_AO_NSIPC_IRQ				(WORD_REF(RUNTIME_AP_AO_NSIPC_IRQ_ADDR))
#define RUNTIME_SYS_LS2STD_BYCONF_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x0a0)
#define SYS_LS2STD_BYCONF_CNT				(WORD_REF(RUNTIME_SYS_LS2STD_BYCONF_CNT_ADDR))
#define RUNTIME_IOMCU_WAKEIRQ_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x100)
#define IOMCU_WAKEIRQ_CNT			(WORD_REF(RUNTIME_IOMCU_WAKEIRQ_CNT_ADDR))
#define RUNTIME_CPU_MEMORY_STEP0_VOLT_BIAS_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x104)
#define RUNTIME_CPU_MEMORY_STEP1_VOLT_BIAS_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x108)
#define CPU_MEMVOLT_STEP1_BIAS			(WORD_REF(RUNTIME_CPU_MEMORY_STEP1_VOLT_BIAS_ADDR))
#define RUNTIME_CPU_MEMORY_STEP2_VOLT_BIAS_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x10C)
#define CPU_MEMVOLT_STEP2_BIAS			(WORD_REF(RUNTIME_CPU_MEMORY_STEP2_VOLT_BIAS_ADDR))
#define RUNTIME_SLEEP_TIME_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x110) /* 0x202D0 32K SLEEP TIME */
#define SYS_SLEEP_TIME					(WORD_REF(RUNTIME_SLEEP_TIME_ADDR))
#define RUNTIME_SLEEP_CAN_ENTER_CNT_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x114)
#define SYS_SLEEP_CAN_ENTER_CNT			(WORD_REF(RUNTIME_SLEEP_CAN_ENTER_CNT_ADDR))
#define RUNTIME_CCPUNR_SUSPEND_CNT_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x118)
#define CCPUNR_SUSPEND_CNT			(WORD_REF(RUNTIME_CCPUNR_SUSPEND_CNT_ADDR))
#define RUNTIME_CCPUNR_RESUME_CNT_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x11C)
#define CCPUNR_RESUME_CNT			(WORD_REF(RUNTIME_CCPUNR_RESUME_CNT_ADDR))
#define RUNTIME_AP_WAKE_IRQ_PIE_ADDR		(RUNTIME_SR_VAR_BASE_ADDR + 0x120)
#define AP_WAKE_IRQ_PIE				(WORD_REF(RUNTIME_AP_WAKE_IRQ_PIE_ADDR))
#define RUNTIME_MODEM_NR_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x124)
#define MODEM_NR_WAKE_CNT			(WORD_REF(RUNTIME_MODEM_NR_WAKE_CNT_ADDR))
#define RUNTIME_OTHER_WAKE_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x128)
#define OTHER_WAKE_CNT			(WORD_REF(RUNTIME_OTHER_WAKE_CNT_ADDR))
#define RUNTIME_WAKE_IRQ4_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x12C)
#define WAKE_IRQ4				(WORD_REF(RUNTIME_WAKE_IRQ4_ADDR))
#define RUNTIME_WAKE_IRQ5_ADDR				(RUNTIME_SR_VAR_BASE_ADDR + 0x130)
#define WAKE_IRQ5				(WORD_REF(RUNTIME_WAKE_IRQ5_ADDR))
#define RUNTIME_CLENT_VOTE_TIME_ADDR(n)     (RUNTIME_SR_VAR_BASE_ADDR + 0x134 + (n) * 4)
#define CLENT_VOTE_TIME(n)      (WORD_REF(RUNTIME_CLENT_VOTE_TIME_ADDR(n)))
#define RUNTIME_STANDBY_CNT_ADDR            (RUNTIME_SR_VAR_BASE_ADDR + 0x15C)
#define SYS_STANDBY_CNT         (WORD_REF(RUNTIME_STANDBY_CNT_ADDR))
#define RUNTIME_STANDBY_WAKE_CNT_ADDR           (RUNTIME_SR_VAR_BASE_ADDR + 0x160)
#define SYS_STANDBY_WAKE_CNT            (WORD_REF(RUNTIME_STANDBY_WAKE_CNT_ADDR))
#define RUNTIME_LIGHTSLEEP_CNT_ADDR         (RUNTIME_SR_VAR_BASE_ADDR + 0x164)
#define SYS_LIGHTSLEEP_CNT          (WORD_REF(RUNTIME_LIGHTSLEEP_CNT_ADDR))
#define RUNTIME_LIGHTSLEEP_WAKE_CNT_ADDR            (RUNTIME_SR_VAR_BASE_ADDR + 0x168)
#define SYS_LIGHTSLEEP_WAKE_CNT         (WORD_REF(RUNTIME_LIGHTSLEEP_WAKE_CNT_ADDR))
#define RUNTIME_SYS_STD2LS_BYINT_CNT_ADDR           (RUNTIME_SR_VAR_BASE_ADDR + 0x16C)
#define SYS_STD2LS_BYINT_CNT            (WORD_REF(RUNTIME_SYS_STD2LS_BYINT_CNT_ADDR))
#define RUNTIME_SYS_STD2LS_BYCONF_CNT_ADDR          (RUNTIME_SR_VAR_BASE_ADDR + 0x170)
#define SYS_STD2LS_BYCONF_CNT           (WORD_REF(RUNTIME_SYS_STD2LS_BYCONF_CNT_ADDR))
#define RUNTIME_SYS_LS2STD_BYINT_CNT_ADDR           (RUNTIME_SR_VAR_BASE_ADDR + 0x174)
#define SYS_LS2STD_BYINT_CNT            (WORD_REF(RUNTIME_SYS_LS2STD_BYINT_CNT_ADDR))
#define RUNTIME_AP_NSIPC_IRQ1_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x178)
#define AP_NSIPC_IRQ1				(WORD_REF(RUNTIME_AP_NSIPC_IRQ1_ADDR))
#define RUNTIME_LPMCU_MAX_WAKEUP_IRQ_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x17C)
#define LPMCU_MAX_WAKEUP_IRQ			(WORD_REF(RUNTIME_LPMCU_MAX_WAKEUP_IRQ_ADDR))

#define RUNTIME_FER_ERR_CNT_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x180)
#define FER_ERR_CNT				(WORD_REF(RUNTIME_FER_ERR_CNT_ADDR))
#define RUNTIME_FER_ERR_TIME_ADDR			(RUNTIME_SR_VAR_BASE_ADDR + 0x184)
#define FER_ERR_TIME				(WORD_REF(RUNTIME_FER_ERR_TIME_ADDR))
#define RUNTIME_PCTRL_PERI_STAT_ADDR(n)        (RUNTIME_SR_VAR_BASE_ADDR + 0x18C + (n) * 4) /* n < 12 */
#define PCTRL_PERI_STAT(n)          (WORD_REF(RUNTIME_PCTRL_PERI_STAT_ADDR(n)))
#define RUNTIME_ACTRL_NONSEC_STATUS35_ADDR      (RUNTIME_SR_VAR_BASE_ADDR + 0x1BC)
#define ACTRL_NONSEC_STATUS35       (WORD_REF(RUNTIME_ACTRL_NONSEC_STATUS35_ADDR))
#define RUNTIME_ACTRL_NONSEC_STATUS36_ADDR      (RUNTIME_SR_VAR_BASE_ADDR + 0x1C0)
#define ACTRL_NONSEC_STATUS36       (WORD_REF(RUNTIME_ACTRL_NONSEC_STATUS36_ADDR))
#define RUNTIME_ACTRL_NONSEC_STATUS48_ADDR      (RUNTIME_SR_VAR_BASE_ADDR + 0x1C4)
#define ACTRL_NONSEC_STATUS48       (WORD_REF(RUNTIME_ACTRL_NONSEC_STATUS48_ADDR))
#define RUNTIME_ACTRL_NONSEC_STATUS49_ADDR      (RUNTIME_SR_VAR_BASE_ADDR + 0x1C8)
#define ACTRL_NONSEC_STATUS49       (WORD_REF(RUNTIME_ACTRL_NONSEC_STATUS49_ADDR))
#define RUNTIME_ACTRL_SEC_STATUS1_ADDR          (RUNTIME_SR_VAR_BASE_ADDR + 0x1CC)
#define ACTRL_SEC_STATUS1           (WORD_REF(RUNTIME_ACTRL_SEC_STATUS1_ADDR))
#define RUNTIME_SCTRL_SYS_STAT_0_ADDR       (RUNTIME_SR_VAR_BASE_ADDR + 0x1D0)
#define SCTRL_SYS_STAT_0            (WORD_REF(RUNTIME_SCTRL_SYS_STAT_0_ADDR))
#define RUNTIME_SCTRL_SC_STAT_0_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1D4)
#define SCTRL_SC_STAT_0             (WORD_REF(RUNTIME_SCTRL_SC_STAT_0_ADDR))

#define RUNTIME_PPLL_CHECK_TIME_STAMP_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1D8)
#define PPLL_CHECK_TIME_STAMP             (WORD_REF(RUNTIME_PPLL_CHECK_TIME_STAMP_ADDR))
#define RUNTIME_PPLL1_CHECK_VOTE_STATUS_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1DC)
#define PPLL1_CHECK_VOTE_STATUS             (HALFWORD_REF(RUNTIME_PPLL1_CHECK_VOTE_STATUS_ADDR))
#define RUNTIME_PPLL2_CHECK_VOTE_STATUS_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1DE)
#define PPLL2_CHECK_VOTE_STATUS             (HALFWORD_REF(RUNTIME_PPLL2_CHECK_VOTE_STATUS_ADDR))
#define RUNTIME_PPLL2B_CHECK_VOTE_STATUS_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1E0)
#define PPLL2B_CHECK_VOTE_STATUS             (HALFWORD_REF(RUNTIME_PPLL2B_CHECK_VOTE_STATUS_ADDR))
#define RUNTIME_PRE_CHECK_STATUS_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1E2)
#define PRE_CHECK_STATUS             (HALFWORD_REF(RUNTIME_PRE_CHECK_STATUS_ADDR))
#define RUNTIME_PPLL_CHECK_STATUS_ADDR        (RUNTIME_SR_VAR_BASE_ADDR + 0x1E4)
#define PPLL_CHECK_STATUS             (WORD_REF(RUNTIME_PPLL_CHECK_STATUS_ADDR))

/* warning:if add new status at last,must sync modify RUNTIME_SPACE_ADDR_END */
#define RUNTIME_SPACE_ADDR_END			(RUNTIME_PPLL_CHECK_STATUS_ADDR)
#if (RUNTIME_SPACE_ADDR_END >= (RUNTIME_VAR_BASE + RUNTIME_VAR_SIZE))
	#error "runtime space overflow!!!"
#endif

/* SR OFFSET */
#define WAKE_STATUS_OFFSET			(RUNTIME_WAKE_STATUS_ADDR - RUNTIME_VAR_BASE)
#define SYS_DSLEEP_CNT_OFFSET				(RUNTIME_DEEP_SLEEP_CNT_ADDR - RUNTIME_VAR_BASE)
#define SYS_DWAKE_CNT_OFFSET		(RUNTIME_DEEP_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define SYS_SLEEP_CNT_OFFSET		(RUNTIME_SLEEP_CNT_ADDR - RUNTIME_VAR_BASE)
#define LIGHT_SLEEP_CNT_OFFSET		(RUNTIME_LIGHT_SLEEP_CNT_ADDR - RUNTIME_VAR_BASE)
#define LIGHT_SLEEP_RESUME_CNT_OFFSET		(RUNTIME_LIGHT_SLEEP_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define AP_WAKE_CNT_OFFSET		(RUNTIME_AP_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define MODEM_WAKE_CNT_OFFSET		(RUNTIME_MODEM_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define HIFI_WAKE_CNT_OFFSET			(RUNTIME_HIFI_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define IOMCU_WAKE_CNT_OFFSET		(RUNTIME_IOMCU_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define LPM3_WAKE_CNT_OFFSET		(RUNTIME_LPMCU_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define AP_SUSPEND_CNT_OFFSET		(RUNTIME_AP_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define AP_RESUME_CNT_OFFSET		(RUNTIME_AP_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define MODEM_SUSPEND_CNT_OFFSET		(RUNTIME_MODEM_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define MODEM_RESUME_CNT_OFFSET		(RUNTIME_MODEM_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define HIFI_SUSPEND_CNT_OFFSET		(RUNTIME_HIFI_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define HIFI_RESUME_CNT_OFFSET		(RUNTIME_HIFI_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define IOMCU_SUSPEND_CNT_OFFSET		(RUNTIME_IOMCU_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define IOMCU_RESUME_CNT_OFFSET		(RUNTIME_IOMCU_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define GENERAL_SEE_SUSPEND_CNT_OFFSET		(RUNTIME_GENERAL_SEE_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define GENERAL_SEE_RESUME_CNT_OFFSET		(RUNTIME_GENERAL_SEE_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define SLEEP_WAKE_IRQ_OFFSET		(RUNTIME_SLEEP_WAKE_IRQ_ADDR - RUNTIME_VAR_BASE)
#define SLEEP_WAKE_IRQ1_OFFSET		(RUNTIME_SLEEP_WAKE_IRQ1_ADDR - RUNTIME_VAR_BASE)
#define WAKE_IRQ_OFFSET		(RUNTIME_WAKE_IRQ_ADDR - RUNTIME_VAR_BASE)
#define WAKE_IRQ1_OFFSET		(RUNTIME_WAKE_IRQ1_ADDR - RUNTIME_VAR_BASE)
#define WAKE_IRQ2_OFFSET		(RUNTIME_WAKE_IRQ2_ADDR - RUNTIME_VAR_BASE)
#define WAKE_IRQ3_OFFSET		(RUNTIME_WAKE_IRQ3_ADDR - RUNTIME_VAR_BASE)
#define AP_WAKE_IRQ_OFFSET		(RUNTIME_AP_WAKE_IRQ_ADDR - RUNTIME_VAR_BASE)
#define AP_NSIPC_IRQ_OFFSET		(RUNTIME_AP_NSIPC_IRQ_ADDR - RUNTIME_VAR_BASE)
#define AP_NSIPC_IRQ1_OFFSET    (RUNTIME_AP_NSIPC_IRQ1_ADDR - RUNTIME_VAR_BASE)
#define AP_AO_NSIPC_IRQ_OFFSET		(RUNTIME_AP_AO_NSIPC_IRQ_ADDR - RUNTIME_VAR_BASE)
#define GIC_OUT_IRQ_OFFSET		(RUNTIME_GIC_OUT_IRQ_ADDR - RUNTIME_VAR_BASE)
#define SYS_SLEEP_TIME_OFFSET		(RUNTIME_SLEEP_TIME_ADDR - RUNTIME_VAR_BASE)
#define SYS_SLEEP_CAN_ENTER_CNT_OFFSET	(RUNTIME_SLEEP_CAN_ENTER_CNT_ADDR - RUNTIME_VAR_BASE)
#define CCPUNR_SUSPEND_CNT_OFFSET	(RUNTIME_CCPUNR_SUSPEND_CNT_ADDR - RUNTIME_VAR_BASE)
#define CCPUNR_RESUME_CNT_OFFSET	(RUNTIME_CCPUNR_RESUME_CNT_ADDR - RUNTIME_VAR_BASE)
#define AP_WAKE_IRQ_PIE_OFFSET	(RUNTIME_AP_WAKE_IRQ_PIE_ADDR - RUNTIME_VAR_BASE)
#define MODEM_NR_WAKE_CNT_OFFSET	(RUNTIME_MODEM_NR_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define OTHER_WAKE_CNT_OFFSET	(RUNTIME_OTHER_WAKE_CNT_ADDR - RUNTIME_VAR_BASE)
#define CLENT_VOTE_TIME_OFFSET(n)   (RUNTIME_CLENT_VOTE_TIME_ADDR(n) - RUNTIME_VAR_BASE)

#define PM_GPIO_DEBUG_SWITCH_OFFSET	(RUNTIME_SLOW_WAKE_IRQ1_ADDR - RUNTIME_VAR_BASE)
#define LPMCU_MAX_WAKEUP_IRQ_OFFSET	(RUNTIME_LPMCU_MAX_WAKEUP_IRQ_ADDR - RUNTIME_VAR_BASE)
#define FER_ERR_CNT_OFFSET	(RUNTIME_FER_ERR_CNT_ADDR - RUNTIME_VAR_BASE)
#define FER_ERR_TIME_OFFSET	(RUNTIME_FER_ERR_TIME_ADDR- RUNTIME_VAR_BASE)

#endif
