/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2001-2023. All rights reserved.
 *
 * Description: file name soc_ffap1_interface.h
 * Author     : Generated by tool
 * Create     : 2023-5-8 10:31:07
 */

#ifndef __SOC_FFAP1_INTERFACE_H__
#define __SOC_FFAP1_INTERFACE_H__


/*****************************************************************************
  1 Other head file
*****************************************************************************/


#ifdef __cplusplus
#if __cplusplus
    extern "C" {
#endif
#endif


/*****************************************************************************
  2 macro
*****************************************************************************/

/****************************************************************************
                     (1/1) RTL_reg
 ****************************************************************************/
#ifndef __SOC_H_FOR_ASM__


/* Register description: 控制寄存器
   Bit domain definition UNION:  SOC_FFAP1_CTRL_UNION */
#define SOC_FFAP1_CTRL_ADDR(base)                             ((base) + (0x1000UL))

/* Register description: 建链寄存器
   Bit domain definition UNION:  SOC_FFAP1_CONNECT_REQ_UNION */
#define SOC_FFAP1_CONNECT_REQ_ADDR(base)                      ((base) + (0x1004UL))

/* Register description: 建链状态寄存器
   Bit domain definition UNION:  SOC_FFAP1_CONNECT_ST_UNION */
#define SOC_FFAP1_CONNECT_ST_ADDR(base)                       ((base) + (0x1008UL))

/* Register description: FFAP1断链延迟配置
   Bit domain definition UNION:  SOC_FFAP1_DRAIN_TH_UNION */
#define SOC_FFAP1_DRAIN_TH_ADDR(base)                         ((base) + (0x100CUL))

/* Register description: DFX维侧回读寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_COMM_UNION */
#define SOC_FFAP1_DFX_COMM_ADDR(base)                         ((base) + (0x1010UL))

/* Register description: PUSHTASK计数维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_PT_CNT_UNION */
#define SOC_FFAP1_DFX_PT_CNT_ADDR(base)                       ((base) + (0x1014UL))

/* Register description: TASKDONE计数维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_TD_CNT_UNION */
#define SOC_FFAP1_DFX_TD_CNT_ADDR(base)                       ((base) + (0x1018UL))

/* Register description: 记录维侧控制寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_RECORD_CTRL_UNION */
#define SOC_FFAP1_DFX_RECORD_CTRL_ADDR(base)                  ((base) + (0x101CUL))

/* Register description: PUSHTASK记录维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_PUSHTASK_UNION */
#define SOC_FFAP1_DFX_PUSHTASK_ADDR(base, PT_NUM)             ((base) + ((PT_NUM)*4+0x1020UL))

/* Register description: TASKDONE记录维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_TASKDONE_UNION */
#define SOC_FFAP1_DFX_TASKDONE_ADDR(base)                     ((base) + (0x102CUL))


#else


/* Register description: 控制寄存器
   Bit domain definition UNION:  SOC_FFAP1_CTRL_UNION */
#define SOC_FFAP1_CTRL_ADDR(base)                             ((base) + (0x1000))

/* Register description: 建链寄存器
   Bit domain definition UNION:  SOC_FFAP1_CONNECT_REQ_UNION */
#define SOC_FFAP1_CONNECT_REQ_ADDR(base)                      ((base) + (0x1004))

/* Register description: 建链状态寄存器
   Bit domain definition UNION:  SOC_FFAP1_CONNECT_ST_UNION */
#define SOC_FFAP1_CONNECT_ST_ADDR(base)                       ((base) + (0x1008))

/* Register description: FFAP1断链延迟配置
   Bit domain definition UNION:  SOC_FFAP1_DRAIN_TH_UNION */
#define SOC_FFAP1_DRAIN_TH_ADDR(base)                         ((base) + (0x100C))

/* Register description: DFX维侧回读寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_COMM_UNION */
#define SOC_FFAP1_DFX_COMM_ADDR(base)                         ((base) + (0x1010))

/* Register description: PUSHTASK计数维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_PT_CNT_UNION */
#define SOC_FFAP1_DFX_PT_CNT_ADDR(base)                       ((base) + (0x1014))

/* Register description: TASKDONE计数维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_TD_CNT_UNION */
#define SOC_FFAP1_DFX_TD_CNT_ADDR(base)                       ((base) + (0x1018))

/* Register description: 记录维侧控制寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_RECORD_CTRL_UNION */
#define SOC_FFAP1_DFX_RECORD_CTRL_ADDR(base)                  ((base) + (0x101C))

/* Register description: PUSHTASK记录维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_PUSHTASK_UNION */
#define SOC_FFAP1_DFX_PUSHTASK_ADDR(base, PT_NUM)             ((base) + ((PT_NUM)*4+0x1020))

/* Register description: TASKDONE记录维侧寄存器
   Bit domain definition UNION:  SOC_FFAP1_DFX_TASKDONE_UNION */
#define SOC_FFAP1_DFX_TASKDONE_ADDR(base)                     ((base) + (0x102C))


#endif




/*****************************************************************************
  3 enums
*****************************************************************************/



/*****************************************************************************
  4 message head
*****************************************************************************/



/*****************************************************************************
  5 message
*****************************************************************************/



/*****************************************************************************
  6 struct
*****************************************************************************/



/*****************************************************************************
  7 union
*****************************************************************************/

/****************************************************************************
                     (1/1) RTL_reg
 ****************************************************************************/
/*****************************************************************************
 struct               : SOC_FFAP1_CTRL_UNION
 struct description   : CTRL Register structure definition
                        Address Offset:0x1000 Initial:0x00000000 Width:32
 register description : 控制寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  ckg_bypass : 1;  /* bit[0]   : Bypass时钟门控 */
        unsigned int  ckg_ext    : 1;  /* bit[1]   : 时钟门控延长 */
        unsigned int  reserved   : 30; /* bit[2-31]:  */
    } reg;
} SOC_FFAP1_CTRL_UNION;
#endif
#define SOC_FFAP1_CTRL_ckg_bypass_START  (0)
#define SOC_FFAP1_CTRL_ckg_bypass_END    (0)
#define SOC_FFAP1_CTRL_ckg_ext_START     (1)
#define SOC_FFAP1_CTRL_ckg_ext_END       (1)


/*****************************************************************************
 struct               : SOC_FFAP1_CONNECT_REQ_UNION
 struct description   : CONNECT_REQ Register structure definition
                        Address Offset:0x1004 Initial:0x00000000 Width:32
 register description : 建链寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  connect_req    : 1;  /* bit[0]   : 请求建链 */
        unsigned int  disconnect_req : 1;  /* bit[1]   : 请求断链 */
        unsigned int  reserved       : 30; /* bit[2-31]: reserved. */
    } reg;
} SOC_FFAP1_CONNECT_REQ_UNION;
#endif
#define SOC_FFAP1_CONNECT_REQ_connect_req_START     (0)
#define SOC_FFAP1_CONNECT_REQ_connect_req_END       (0)
#define SOC_FFAP1_CONNECT_REQ_disconnect_req_START  (1)
#define SOC_FFAP1_CONNECT_REQ_disconnect_req_END    (1)


/*****************************************************************************
 struct               : SOC_FFAP1_CONNECT_ST_UNION
 struct description   : CONNECT_ST Register structure definition
                        Address Offset:0x1008 Initial:0x00000000 Width:32
 register description : 建链状态寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  connect_status : 2;  /* bit[0-1] : 建断链状态：
                                                         0：已断链
                                                         1：正在建链过程中
                                                         2：已建链
                                                         3：正在断链过程中 */
        unsigned int  reserved       : 30; /* bit[2-31]:  */
    } reg;
} SOC_FFAP1_CONNECT_ST_UNION;
#endif
#define SOC_FFAP1_CONNECT_ST_connect_status_START  (0)
#define SOC_FFAP1_CONNECT_ST_connect_status_END    (1)


/*****************************************************************************
 struct               : SOC_FFAP1_DRAIN_TH_UNION
 struct description   : DRAIN_TH Register structure definition
                        Address Offset:0x100C Initial:0x00000010 Width:32
 register description : FFAP1断链延迟配置
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  drain_th : 8;  /* bit[0-7] : 等待阈值 */
        unsigned int  reserved : 24; /* bit[8-31]:  */
    } reg;
} SOC_FFAP1_DRAIN_TH_UNION;
#endif
#define SOC_FFAP1_DRAIN_TH_drain_th_START  (0)
#define SOC_FFAP1_DRAIN_TH_drain_th_END    (7)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_COMM_UNION
 struct description   : DFX_COMM Register structure definition
                        Address Offset:0x1010 Initial:0x00000000 Width:32
 register description : DFX维侧回读寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_credit_num   : 8;  /* bit[0-7]  : 当前Credit个数 */
        unsigned int  dfx_connnect_fsm : 3;  /* bit[8-10] : 建链状态机状态 */
        unsigned int  dfx_busy         : 1;  /* bit[11]   : FFAP1除APB_SLV外的busy状态 */
        unsigned int  reserved         : 20; /* bit[12-31]:  */
    } reg;
} SOC_FFAP1_DFX_COMM_UNION;
#endif
#define SOC_FFAP1_DFX_COMM_dfx_credit_num_START    (0)
#define SOC_FFAP1_DFX_COMM_dfx_credit_num_END      (7)
#define SOC_FFAP1_DFX_COMM_dfx_connnect_fsm_START  (8)
#define SOC_FFAP1_DFX_COMM_dfx_connnect_fsm_END    (10)
#define SOC_FFAP1_DFX_COMM_dfx_busy_START          (11)
#define SOC_FFAP1_DFX_COMM_dfx_busy_END            (11)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_PT_CNT_UNION
 struct description   : DFX_PT_CNT Register structure definition
                        Address Offset:0x1014 Initial:0x00000000 Width:32
 register description : PUSHTASK计数维侧寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_pushtask_cnt    : 16; /* bit[0-15] : 发往加速器侧pushtask计数值 */
        unsigned int  dfx_pushtask_cnt_en : 1;  /* bit[16]   : 发往加速器侧pushtask计数使能 */
        unsigned int  reserved            : 15; /* bit[17-31]:  */
    } reg;
} SOC_FFAP1_DFX_PT_CNT_UNION;
#endif
#define SOC_FFAP1_DFX_PT_CNT_dfx_pushtask_cnt_START     (0)
#define SOC_FFAP1_DFX_PT_CNT_dfx_pushtask_cnt_END       (15)
#define SOC_FFAP1_DFX_PT_CNT_dfx_pushtask_cnt_en_START  (16)
#define SOC_FFAP1_DFX_PT_CNT_dfx_pushtask_cnt_en_END    (16)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_TD_CNT_UNION
 struct description   : DFX_TD_CNT Register structure definition
                        Address Offset:0x1018 Initial:0x00000000 Width:32
 register description : TASKDONE计数维侧寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_taskdone_cnt    : 16; /* bit[0-15] : 接收加速器侧taskdone计数值 */
        unsigned int  dfx_taskdone_cnt_en : 1;  /* bit[16]   : 接收加速器侧taskdone计数使能 */
        unsigned int  reserved            : 15; /* bit[17-31]:  */
    } reg;
} SOC_FFAP1_DFX_TD_CNT_UNION;
#endif
#define SOC_FFAP1_DFX_TD_CNT_dfx_taskdone_cnt_START     (0)
#define SOC_FFAP1_DFX_TD_CNT_dfx_taskdone_cnt_END       (15)
#define SOC_FFAP1_DFX_TD_CNT_dfx_taskdone_cnt_en_START  (16)
#define SOC_FFAP1_DFX_TD_CNT_dfx_taskdone_cnt_en_END    (16)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_RECORD_CTRL_UNION
 struct description   : DFX_RECORD_CTRL Register structure definition
                        Address Offset:0x101C Initial:0x00000000 Width:32
 register description : 记录维侧控制寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_taskdone_record : 1;  /* bit[0]   : 接收加速器侧taskdone记录使能 */
        unsigned int  dfx_pushtask_record : 1;  /* bit[1]   : 发往加速器侧pushtask记录使能 */
        unsigned int  reserved            : 30; /* bit[2-31]:  */
    } reg;
} SOC_FFAP1_DFX_RECORD_CTRL_UNION;
#endif
#define SOC_FFAP1_DFX_RECORD_CTRL_dfx_taskdone_record_START  (0)
#define SOC_FFAP1_DFX_RECORD_CTRL_dfx_taskdone_record_END    (0)
#define SOC_FFAP1_DFX_RECORD_CTRL_dfx_pushtask_record_START  (1)
#define SOC_FFAP1_DFX_RECORD_CTRL_dfx_pushtask_record_END    (1)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_PUSHTASK_UNION
 struct description   : DFX_PUSHTASK Register structure definition
                        Address Offset:(PT_NUM)*4+0x1020 Initial:0x00000000 Width:32
 register description : PUSHTASK记录维侧寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_pushtask_data : 32; /* bit[0-31]: 上一次发往加速器的PUSHTASK */
    } reg;
} SOC_FFAP1_DFX_PUSHTASK_UNION;
#endif
#define SOC_FFAP1_DFX_PUSHTASK_dfx_pushtask_data_START  (0)
#define SOC_FFAP1_DFX_PUSHTASK_dfx_pushtask_data_END    (31)


/*****************************************************************************
 struct               : SOC_FFAP1_DFX_TASKDONE_UNION
 struct description   : DFX_TASKDONE Register structure definition
                        Address Offset:0x102C Initial:0x00000000 Width:32
 register description : TASKDONE记录维侧寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  dfx_taskdone_data : 32; /* bit[0-31]: 上一次接收加速器的TASKDONE */
    } reg;
} SOC_FFAP1_DFX_TASKDONE_UNION;
#endif
#define SOC_FFAP1_DFX_TASKDONE_dfx_taskdone_data_START  (0)
#define SOC_FFAP1_DFX_TASKDONE_dfx_taskdone_data_END    (31)






/*****************************************************************************
  8 others
*****************************************************************************/



/*****************************************************************************
  9 global values
*****************************************************************************/



/*****************************************************************************
  10 global functions
*****************************************************************************/


#ifdef __cplusplus
#if __cplusplus
    }
#endif
#endif

#endif /* end of soc_ffap1_interface.h */
