/*
 *  Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 *  Description: soc spec
 *  Author : HISI_DRV
 *  Create : 2024/01/23
 */

#ifndef __SOC_SPEC_INFO_H__
#define __SOC_SPEC_INFO_H__

#if defined(CONFIG_SOC_PG_INFO_IN_LPRAM)
#define SOC_PG_INFO_ADDR 0x70000
#define SOC_PG_INFO_ADDR_IN_DDR 0x1099F000
#elif defined(CONFIG_SOC_PG_INFO_IN_SC)
#define SOC_PG_INFO_ADDR 0xD00F4000
#define SOC_PG_INFO_ADDR_IN_DDR 0x1099F000
#elif defined(CONFIG_SOC_PG_INFO_IN_DDR)
#define SOC_PG_INFO_ADDR 0x1099F000
#elif defined(CONFIG_SOC_PG_INFO)
#define SOC_PG_INFO_ADDR 0x1099F000
#endif

#define SOC_PG_INFO_SIZE 0x1000

typedef enum soc_spec_level {
	SOC_SPEC_LEVEL1_EFUSE_NONE = 0,
	SOC_SPEC_LEVEL1,
	SOC_SPEC_PHONE,
	SOC_SPEC_LITE_PHONE,
	SOC_SPEC_WIFI,
	SOC_SPEC_WIFI_LITE,
	SOC_SPEC_WIFI_MINI,
	SOC_SPEC_WIFI_BASIC,
	SOC_SPEC_WIFI_ENTRY,
	SOC_SPEC_INVALID,
	SOC_SPEC_MAX
} SOC_SPEC_LEVEL;

enum soc_component_pg_info_index {
	SOC_COMPONENT_INFO_START     = 0,
	SOC_COMPONENT_CHIP_TYPE_INFO = SOC_COMPONENT_INFO_START,
	SOC_COMPONENT_PROFILE_STRATEGY_INFO,
	SOC_COMPONENT_PG_TEST_VERSION_INFO,
	SOC_COMPONENT_CPUB_CORE_INFO,
	SOC_COMPONENT_CPUM_CORE_INFO,
	SOC_COMPONENT_CPUL_CORE_INFO,
	SOC_COMPONENT_HC_CAPACITY_INFO,
	SOC_COMPONENT_CPUB_FREQ_INFO,
	SOC_COMPONENT_CPUM_FREQ_INFO,
	SOC_COMPONENT_CPUL_FREQ_INFO,
	SOC_COMPONENT_HC_FREQ_INFO,
	SOC_COMPONENT_MODEM_INFO,
	SOC_COMPONENT_GPU_CORE_INFO,
	SOC_COMPONENT_NPU_INFO,
	SOC_COMPONENT_MEDIA2_ISP_INFO,
	SOC_COMPONENT_VENC_INFO,
	SOC_COMPONENT_SC_CAPACITY_INFO,
	SOC_COMPONENT_SC_SF_CAPACITY_INFO,
	SOC_COMPONENT_USB3_DP_INFO,
	SOC_COMPONENT_MIPI_FREQ_INFO,
	SOC_COMPONENT_DDR_FREQ_INFO,
	SOC_COMPONENT_INFO_END,
	SOC_COMPONENT_INFO_MAX = 512,  // 4k / sizeof(struct soc_component_pg_info) = 512
};

#endif  // __SOC_SPEC_INFO_H__
