/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2001-2023. All rights reserved.
 *
 * Description: file name soc_npu_hw_exp_irq_interface.h
 *              Auto gen from file "Hi36C0 V100 ES SOC寄存器手册_NPU_HW_EXP_IRQ.xml"
 * Author     : Generated by tool
 * Create     : 2023-3-18 09:24:51
 */

#ifndef __SOC_NPU_HW_EXP_IRQ_INTERFACE_H__
#define __SOC_NPU_HW_EXP_IRQ_INTERFACE_H__


/*****************************************************************************
  1 Other head file
*****************************************************************************/


#ifdef __cplusplus
#if __cplusplus
    extern "C" {
#endif
#endif


/*****************************************************************************
  2 macro
*****************************************************************************/

/****************************************************************************
                     (1/1) npu_hw_exp_irq
 ****************************************************************************/
#ifndef __SOC_H_FOR_ASM__


/* Register description: HW Level IRQ置位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_SET_UNION */
#define SOC_NPU_HW_EXP_IRQ_SET_ADDR(base)                     ((base) + (0x000UL))

/* Register description: HW Level IRQ清位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_CLR_UNION */
#define SOC_NPU_HW_EXP_IRQ_CLR_ADDR(base)                     ((base) + (0x004UL))

/* Register description: HW Level IRQ状态寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_STAT_UNION */
#define SOC_NPU_HW_EXP_IRQ_STAT_ADDR(base)                    ((base) + (0x008UL))

/* Register description: HW Pulse IRQ置位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_SET_P_UNION */
#define SOC_NPU_HW_EXP_IRQ_SET_P_ADDR(base)                   ((base) + (0x00CUL))

/* Register description: HW IRQ配置寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_CFG_UNION */
#define SOC_NPU_HW_EXP_IRQ_CFG_ADDR(base)                     ((base) + (0x100UL))


#else


/* Register description: HW Level IRQ置位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_SET_UNION */
#define SOC_NPU_HW_EXP_IRQ_SET_ADDR(base)                     ((base) + (0x000))

/* Register description: HW Level IRQ清位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_CLR_UNION */
#define SOC_NPU_HW_EXP_IRQ_CLR_ADDR(base)                     ((base) + (0x004))

/* Register description: HW Level IRQ状态寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_STAT_UNION */
#define SOC_NPU_HW_EXP_IRQ_STAT_ADDR(base)                    ((base) + (0x008))

/* Register description: HW Pulse IRQ置位寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_SET_P_UNION */
#define SOC_NPU_HW_EXP_IRQ_SET_P_ADDR(base)                   ((base) + (0x00C))

/* Register description: HW IRQ配置寄存器
   Bit domain definition UNION:  SOC_NPU_HW_EXP_IRQ_CFG_UNION */
#define SOC_NPU_HW_EXP_IRQ_CFG_ADDR(base)                     ((base) + (0x100))


#endif




/*****************************************************************************
  3 enums
*****************************************************************************/



/*****************************************************************************
  4 message head
*****************************************************************************/



/*****************************************************************************
  5 message
*****************************************************************************/



/*****************************************************************************
  6 struct
*****************************************************************************/



/*****************************************************************************
  7 union
*****************************************************************************/

/****************************************************************************
                     (1/1) npu_hw_exp_irq
 ****************************************************************************/
/*****************************************************************************
 struct               : SOC_NPU_HW_EXP_IRQ_SET_UNION
 struct description   : SET Register structure definition
                        Address Offset:0x000 Initial:0x00000000 Width:32
 register description : HW Level IRQ置位寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  npu_hw_exp_irq_set : 4;  /* bit[0-3] : bit3:0由软件定义功能，独立控制。与pulse共享4根中断线。
                                                             0 = no operation
                                                             1 = SW sets a level IRQ event */
        unsigned int  reserved           : 28; /* bit[4-31]: 保留 */
    } reg;
} SOC_NPU_HW_EXP_IRQ_SET_UNION;
#endif
#define SOC_NPU_HW_EXP_IRQ_SET_npu_hw_exp_irq_set_START  (0)
#define SOC_NPU_HW_EXP_IRQ_SET_npu_hw_exp_irq_set_END    (3)


/*****************************************************************************
 struct               : SOC_NPU_HW_EXP_IRQ_CLR_UNION
 struct description   : CLR Register structure definition
                        Address Offset:0x004 Initial:0x00000000 Width:32
 register description : HW Level IRQ清位寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  npu_hw_exp_irq_clr : 4;  /* bit[0-3] : bit3:0由软件定义功能，独立控制。
                                                             0 = no operation
                                                             1 = SW clears a level IRQ event in HW_EXP_IRQ_STAT */
        unsigned int  reserved           : 28; /* bit[4-31]: 保留 */
    } reg;
} SOC_NPU_HW_EXP_IRQ_CLR_UNION;
#endif
#define SOC_NPU_HW_EXP_IRQ_CLR_npu_hw_exp_irq_clr_START  (0)
#define SOC_NPU_HW_EXP_IRQ_CLR_npu_hw_exp_irq_clr_END    (3)


/*****************************************************************************
 struct               : SOC_NPU_HW_EXP_IRQ_STAT_UNION
 struct description   : STAT Register structure definition
                        Address Offset:0x008 Initial:0x00000000 Width:32
 register description : HW Level IRQ状态寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  npu_hw_exp_irq_stat : 4;  /* bit[0-3] : bit3:0由软件定义功能。
                                                              0 = no level IRQ
                                                              1 = level IRQ */
        unsigned int  reserved            : 28; /* bit[4-31]: 保留 */
    } reg;
} SOC_NPU_HW_EXP_IRQ_STAT_UNION;
#endif
#define SOC_NPU_HW_EXP_IRQ_STAT_npu_hw_exp_irq_stat_START  (0)
#define SOC_NPU_HW_EXP_IRQ_STAT_npu_hw_exp_irq_stat_END    (3)


/*****************************************************************************
 struct               : SOC_NPU_HW_EXP_IRQ_SET_P_UNION
 struct description   : SET_P Register structure definition
                        Address Offset:0x00C Initial:0x00000000 Width:32
 register description : HW Pulse IRQ置位寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  npu_hw_exp_irq_set_p : 4;  /* bit[0-3] : bit3:0由软件定义功能，独立控制。与level共享8根中断线。
                                                               0 = no operation
                                                               1 = SW sets a pulse IRQ event */
        unsigned int  reserved             : 28; /* bit[4-31]: 保留 */
    } reg;
} SOC_NPU_HW_EXP_IRQ_SET_P_UNION;
#endif
#define SOC_NPU_HW_EXP_IRQ_SET_P_npu_hw_exp_irq_set_p_START  (0)
#define SOC_NPU_HW_EXP_IRQ_SET_P_npu_hw_exp_irq_set_p_END    (3)


/*****************************************************************************
 struct               : SOC_NPU_HW_EXP_IRQ_CFG_UNION
 struct description   : CFG Register structure definition
                        Address Offset:0x100 Initial:0x00000000 Width:32
 register description : HW IRQ配置寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union {
    unsigned int      value;
    struct {
        unsigned int  npu_hw_exp_irq_cfg : 4;  /* bit[0-3] : bit3:0由软件定义功能，独立控制。pulse与level共享4根中断线
                                                             0 = level (corresponding STAT will be set)
                                                             1 = pulse (corresponding STAT will not be set) */
        unsigned int  reserved           : 28; /* bit[4-31]: 保留 */
    } reg;
} SOC_NPU_HW_EXP_IRQ_CFG_UNION;
#endif
#define SOC_NPU_HW_EXP_IRQ_CFG_npu_hw_exp_irq_cfg_START  (0)
#define SOC_NPU_HW_EXP_IRQ_CFG_npu_hw_exp_irq_cfg_END    (3)






/*****************************************************************************
  8 others
*****************************************************************************/



/*****************************************************************************
  9 global values
*****************************************************************************/



/*****************************************************************************
  10 global functions
*****************************************************************************/


#ifdef __cplusplus
#if __cplusplus
    }
#endif
#endif

#endif /* end of soc_npu_hw_exp_irq_interface.h */
