ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/secmem
obj-$(CONFIG_DMABUF_HEAPS) += heaps/
obj-$(CONFIG_DMABUF_MM) += mm/
obj-$(CONFIG_DMABUF_RECLAIM) += dmabuf_reclaim/
obj-$(CONFIG_DMABUF_SWAP) += dmabuf_reclaim/
