# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
# Description: Makefile for the KERNEL SG
# Create: 2022-07-23
#

obj-$(CONFIG_HW_KERNEL_SG) += hw_kernel_sg_module.o hw_kernel_sg_proc.o     \
			hw_kernel_sg_scanner.o hw_kernel_sg_uploader.o

flags += -Wdate-time -Wfloat-equal
