

#ifndef __NPU_DDR_MAP_H__
#define __NPU_DDR_MAP_H__

#define NPU_TS_CPU_UNRST_ADDR                       0xC0000000
#define NPU_NONSEC_RESERVED_MEMORY_SIZE     0xD00000
#define NPU_SEC_RESERVED_DDR_SIZE           0xA00000

/* the index of npu unsec reserved memory used scene */
enum tag_reserved_memory_idx {
    NPU_TSCPU_FW_IDX = 0,
    NPU_CTRL_INFO_IDX = 1,
    NPU_LOG_MEM_IDX = 2,
    NPU_BBOX_MEM_IDX = 3,
    NPU_COMM_SQCQ_RESMEM_IDX = 4,
    NPU_DFX_SQCQ_RESMEM_IDX = 5,
    NPU_HWTS_SDMA_SQCQ_RESMEM_IDX = 6,
    NPU_TS_SDMA_SQCQ_RESMEM_IDX = 7,
    NPU_TS_CONFIG_RESMEM_IDX = 8,
    NPU_NPU_CFG_IDX = 9,
    NPU_PROF_MEM_IDX = 10,    // only index, the base addr in npu_platform_resource.h
    NPU_FFRT_MDC_IDX = 11,
    NPU_FFRT_SWAP_BUFF_IDX = 12,
    NPU_ISPNN_INFO_BUFF_IDX = 13,
    NPU_ISPNN_IPC_BUFF_IDX = 14,
    NPU_MAX_RESMEM_IDX = 15,
};

/* the size of npu unsec reserved memory used scene */
enum tag_npu_nonsec_reserved_ddr {
    NPU_NS_TSCPU_FW_SIZE = 0x400000,
    NPU_NS_CTRL_INFO_SIZE = 0x80000,
    NPU_NS_LOG_SIZE = 0x80000,
    NPU_NS_BBOX_SIZE = 0x40000,
    NPU_NS_COMM_SQCQ_SIZE = 0x200000,
    NPU_NS_DFX_SQCQ_SIZE = 0x80000,
    NPU_NS_HWTS_SDMA_SQ_SIZE = 0x0,
    NPU_NS_TS_SDMA_SQCQ_SIZE = 0x0,
    NPU_NS_TS_CONFIG_SIZE = 0x40000,
    NPU_NS_NPU_CONFIG_SIZE = 0x1000,
    NPU_NS_HWTS_SWAP_BUFF_SIZE = 0x1000,
    NPU_NS_HWTS_FFRT_MDC_BUFF_SIZE = 0x2000,
    NPU_NS_HWTS_FFRT_SWAP_BUFF_SIZE = 0x8000,
    NPU_NS_ISPNN_INFO_SIZE = 0x1000,
    NPU_NS_ISPNN_IPC_BUFF_SIZE = 0x1000,
};

/* the size of npu unsec reserved memory without ts unsec fw reserved memory */
#define NPU_NS_TSCPU_RESERVED_SIZE   0x900000

/* non-sec ddr map */
#define NPU_NS_CTRL_INFO_BASE_OFFSET            (0)
#define NPU_NS_LOG_BASE_OFFSET                  (NPU_NS_CTRL_INFO_SIZE + NPU_NS_CTRL_INFO_BASE_OFFSET)
#define NPU_NS_BBOX_BASE_OFFSET                 (NPU_NS_LOG_SIZE + NPU_NS_LOG_BASE_OFFSET)
#define NPU_NS_COMM_SQCQ_BASE_OFFSET            (NPU_NS_BBOX_SIZE + NPU_NS_BBOX_BASE_OFFSET)
#define NPU_NS_DFX_SQCQ_BASE_OFFSET             (NPU_NS_COMM_SQCQ_SIZE + NPU_NS_COMM_SQCQ_BASE_OFFSET)
#define NPU_NS_HWTS_SDMA_SQ_BASE_OFFSET         (NPU_NS_DFX_SQCQ_SIZE + NPU_NS_DFX_SQCQ_BASE_OFFSET)
#define NPU_NS_TS_SDMA_SQCQ_BASE_OFFSET         (NPU_NS_HWTS_SDMA_SQ_SIZE + NPU_NS_HWTS_SDMA_SQ_BASE_OFFSET)
#define NPU_NS_TS_CONFIG_BASE_OFFSET            (NPU_NS_TS_SDMA_SQCQ_SIZE + NPU_NS_TS_SDMA_SQCQ_BASE_OFFSET)
#define NPU_NS_NPU_CONFIG_BASE_OFFSET           (NPU_NS_TS_CONFIG_SIZE + NPU_NS_TS_CONFIG_BASE_OFFSET)
#define NPU_NS_HWTS_SWAP_BUFF_BASE_OFFSET       (NPU_NS_NPU_CONFIG_SIZE + NPU_NS_NPU_CONFIG_BASE_OFFSET)
#define NPU_NS_HWTS_FFRT_MDC_BUFF_BASE_OFFSET   (NPU_NS_HWTS_SWAP_BUFF_SIZE + NPU_NS_HWTS_SWAP_BUFF_BASE_OFFSET)
#define NPU_NS_HWTS_FFRT_SWAP_BUFF_BASE_OFFSET  (NPU_NS_HWTS_FFRT_MDC_BUFF_SIZE + NPU_NS_HWTS_FFRT_MDC_BUFF_BASE_OFFSET)
#define NPU_NS_ISPNN_INFO_BUFF_BASE_OFFSET      (NPU_NS_HWTS_FFRT_SWAP_BUFF_SIZE + NPU_NS_HWTS_FFRT_SWAP_BUFF_BASE_OFFSET)
#define NPU_NS_ISPNN_IPC_BUFF_BASE_OFFSET       (NPU_NS_ISPNN_INFO_SIZE + NPU_NS_ISPNN_INFO_BUFF_BASE_OFFSET)

/* npu sec memory use */
enum tag_npu_sec_reserved_ddr {
    NPU_S_NPU_CONFIG_SIZE = 0x1000,
    NPU_S_HWTS_SQCQ_SIZE = 0x400000,
    NPU_S_SMMU_QUEUE_SIZE = 0xE000,
    NPU_S_HWTS_SWAP_BUFF_SIZE = 0x1000,
    NPS_S_HWTS_AIV_CTX_SWITCH_BUFF_SIZE = 0x100000,
};

#endif /* __NPU_DDR_MAP_H__ */