#ifndef __FFTS_INTERFACE_H__
#define __FFTS_INTERFACE_H__

enum LDK_FFTS_MINOR_CMD {
	LDK_MINOR_CMD_FFTS_SAVE_BBOX = 0,
	LDK_MINOR_CMD_FFTS_RDR_REPORT = 1,
	LDK_MINOR_CMD_FFTS_INVOKE_HW_RELEASE = 2,
	LDK_MINOR_CMD_FFTS_MAX,
};

#endif /* __FFTS_INTERFACE_H__ */