EXTRA_CFLAGS += -I$(srctree)/include/platform_include/ffrt/ffts
EXTRA_CFLAGS += -I$(srctree)/samples/ldk/vendor
EXTRA_CFLAGS += -I$(srctree)/include/
obj-$(CONFIG_FFRT_FFTS_OHOS) += ffts_interface.o ffts_black_box.o ffts_proc_block.o