ccflags-y += -I$(srctree)/drivers/dma-buf/heaps/
ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/dma-buf/heaps/

obj-$(CONFIG_DMABUF_RECLAIM) += dmabuf_reclaim_fd.o dmabuf_reclaim_dev.o dmabuf_reclaim_manage.o