/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2018-2020. All rights reserved.
 * Description: Permission
 * Author: Huawei OS Kernel Lab
 * Create: Mon Sep 23 09:45:35 2018
 */
/*
 * Must choose one GRANT type from ALL/NO/COARSE/FINE
 * Must choose one GRANTMOVE type from ALL/NO/COARSE
 */
CAPTYPE(Permission, 15, CAPNOGRANT(Permission)
			CAPNOGRANTMOVE(Permission)
			CAPNODEFAULTCREF(Permission)
			CAPRAWCREFRLOOKUP(Permission)
			CAPDEFAULTSIZE(Permission),
	CAPMETHOD(Permission, Stat)

	CAPERRNO(Permission, EPERM, PERMISSION_NORIGHT,		"E_HM_PERMISSION_NORIGHT")
	CAPERRNO(Permission, EINVAL, PERMISSION_INVAL_CREF,	"E_HM_PERMISSION_INVAL_CREF")
)

#ifdef CAP_EXPORT_API
#ifndef CAP_PERMISSION_API_EXPORTED
#define CAP_PERMISSION_API_EXPORTED

enum {
	CRIGHT_PERMISSION_MAX
};

enum {
	CPERMISSION_NEW_PERMISSION_BIT,
	CPERMISSION_NEW_VSPACE_BIT,
	CPERMISSION_NEW_VM_BIT,
	CPERMISSION_NEW_CPUCONTEXT_PMU_BIT,
	CPERMISSION_NEW_CPUCONTEXT_DEBUG_BIT,
	CPERMISSION_NEW_CPUCONTEXT_VCPU_BIT,
	CPERMISSION_LOAD_PREV_STAT_BIT,
	CPERMISSION_STORE_PREV_UCTX_BIT,
	CPERMISSION_ACTV_READ_CALLER_VM_BIT,
	CPERMISSION_ACTV_WRITE_CALLER_VM_BIT,
	CPERMISSION_ACTV_READ_XACT_VM_BIT,
	CPERMISSION_ACTV_WRITE_XACT_VM_BIT,
	CPERMISSION_PMEM_STAT_PADDR_BIT,
	CPERMISSION_NEW_DEL_PMEM_BIT,
	CPERMISSION_SELFCHAIN_LOAD_PREV_STAT_BIT,
	CPERMISSION_SELFCHAIN_STORE_PREV_UCTX_BIT,
	CPERMISSION_SPECCHAIN_LOAD_PREV_STAT_BIT,
	CPERMISSION_SPECCHAIN_STORE_PREV_UCTX_BIT,
	CPERMISSION_SCHED_ADMIN_BIT,
	CPERMISSION_KLOG_BIT,
	CPERMISSION_ALARM_TIMER_BIT,
	CPERMISSION_REDUCE_CAP_RIGHTS_BIT,
	CPERMISSION_KCONSOLE_BIT,
	CPERMISSION_THREAD_BIND_ACTVPOOL_BIT,
	CPERMISSION_REVOKE_GRANT_BIT,
	CPERMISSION_NEW_DEL_ACTVPOOL_BIT,
	CPERMISSION_NEW_DEL_THREAD_BIT,
	CPERMISSION_NEW_DEL_SCHEDULER_BIT,
	CPERMISSION_SCHED_PREEMPT_BIT,
	CPERMISSION_CNODE_PROXY_GRANT_BIT,
	CPERMISSION_WATCHDOG_BIT,
	CPERMISSION_IDLE_BIT,
	CPERMISSION_CPUFREQ_BIT,
	CPERMISSION_POWER_IOCTL_BIT,
	CPERMISSION_KEV_READ_BIT,
	CPERMISSION_KEV_SAMPLE_BIT,
	CPERMISSION_KEV_KLOG_BIT,
	CPERMISSION_KEV_AUDIT_BIT,
	CPERMISSION_HMSIG_MASK_NONMASKABLE_BIT,
	CPERMISSION_KLIVEPATCH_BIT,
	CPERMISSION_EVENT_CHANNEL,
	CPERMISSION_NEW_EPOLL_BIT,
	CPERMISSION_PEK_BIT,
	CPERMISSION_LSYSCALL_BIT,
	CPERMISSION_SYSADMIN_BIT,
	CPERMISSION_DSUCTX_NEW_BIT,
	CPERMISSION_NEW_FDTABLE_BIT,
	CPERMISSION_FLUSH_CACHE_BY_PA_BIT,
	CPERMISSION_BIND_FDTABLE_BIT,
	CPERMISSION_VIRQ_MAP_BIT,
	CPERMISSION_ACTV_BINDER_BIT,
	CPERMISSION_POWERCTRL_BIT,
	CPERMISSION_BASE_ACTV_G1_CRED_BIT,
	CPERMISSION_ULWT_ADMIN_BIT,
	CPERMISSION_TIMER_START_BIT,
	CPERMISSION_THREAD_PTRACE_BIT,
	CPERMISSION_DEVHOST_GENERAL_BIT,
	CPERMISSION_TRACECTRL_BIT,
	CPERMISSION_MAX
};

#define CPERMISSION_NEW_PERMISSION		(1ULL << CPERMISSION_NEW_PERMISSION_BIT)
#define CPERMISSION_NEW_VSPACE			(1ULL << CPERMISSION_NEW_VSPACE_BIT)
#define CPERMISSION_NEW_VM			(1ULL << CPERMISSION_NEW_VM_BIT)
#define CPERMISSION_NEW_CPUCONTEXT_PMU		(1ULL << CPERMISSION_NEW_CPUCONTEXT_PMU_BIT)
#define CPERMISSION_NEW_CPUCONTEXT_DEBUG	(1ULL << CPERMISSION_NEW_CPUCONTEXT_DEBUG_BIT)
#define CPERMISSION_NEW_CPUCONTEXT_VCPU		(1ULL << CPERMISSION_NEW_CPUCONTEXT_VCPU_BIT)
/* permisson to load stat of previous actv */
#define CPERMISSION_LOAD_PREV_STAT		(1ULL << CPERMISSION_LOAD_PREV_STAT_BIT)
/* permisson to store uctx of previous actv */
#define CPERMISSION_STORE_PREV_UCTX		(1ULL << CPERMISSION_STORE_PREV_UCTX_BIT)
#define CPERMISSION_ACTV_READ_CALLER_VM		(1ULL << CPERMISSION_ACTV_READ_CALLER_VM_BIT)
#define CPERMISSION_ACTV_WRITE_CALLER_VM	(1ULL << CPERMISSION_ACTV_WRITE_CALLER_VM_BIT)
#define CPERMISSION_ACTV_READ_XACT_VM		(1ULL << CPERMISSION_ACTV_READ_XACT_VM_BIT)
#define CPERMISSION_ACTV_WRITE_XACT_VM		(1ULL << CPERMISSION_ACTV_WRITE_XACT_VM_BIT)
#define CPERMISSION_PMEM_STAT_PADDR		(1ULL << CPERMISSION_PMEM_STAT_PADDR_BIT)
/*
 * permission to create/destory the cap of pmem, which is only
 * owned by sysmgr
 */
#define CPERMISSION_NEW_DEL_PMEM		(1ULL << CPERMISSION_NEW_DEL_PMEM_BIT)
/*
 * permission to load stat or store uctx of previous actv of a
 * specific actv in self call chain
 */
#define CPERMISSION_SELFCHAIN_LOAD_PREV_STAT	(1ULL << CPERMISSION_SELFCHAIN_LOAD_PREV_STAT_BIT)
#define CPERMISSION_SELFCHAIN_STORE_PREV_UCTX	(1ULL << CPERMISSION_SELFCHAIN_STORE_PREV_UCTX_BIT)
/*
 * permission to load stat or store uctx of previous actv of a
 * specific actv in a specific call chain
 */
#define CPERMISSION_SPECCHAIN_LOAD_PREV_STAT	(1ULL << CPERMISSION_SPECCHAIN_LOAD_PREV_STAT_BIT)
#define CPERMISSION_SPECCHAIN_STORE_PREV_UCTX	(1ULL << CPERMISSION_SPECCHAIN_STORE_PREV_UCTX_BIT)

/* permission for setting system scheduling properties, such as loadlance, system scheduler switch */
#define CPERMISSION_SCHED_ADMIN			(1ULL << CPERMISSION_SCHED_ADMIN_BIT)

/* permission to output klog to kernel buffer */
#define CPERMISSION_KLOG			(1ULL << CPERMISSION_KLOG_BIT)

/* permission to set alarm timer */
#define CPERMISSION_ALARM_TIMER			(1ULL << CPERMISSION_ALARM_TIMER_BIT)

#define CPERMISSION_REDUCE_CAP_RIGHTS		(1ULL << CPERMISSION_REDUCE_CAP_RIGHTS_BIT)

/* permission to output data to kernel kconsole, which is only owned by devhost */
#define CPERMISSION_KCONSOLE			(1ULL << CPERMISSION_KCONSOLE_BIT)

/* permission to bind actvpool for thread, which is only owned by sysmgr */
#define CPERMISSION_THREAD_BIND_ACTVPOOL	(1ULL << CPERMISSION_THREAD_BIND_ACTVPOOL_BIT)

/* permission to enable/disable hard/soft watchdog */
#define CPERMISSION_WATCHDOG                    (1ULL << CPERMISSION_WATCHDOG_BIT)

/*
 * permission to revoke the cnode grant, which is only owned by sysmgr.
 *
 * NOTE: Currently, if the authorization of the cnode to the sysmgr is
 * revoked, the sysmgr cannot relcaim the resoures of the cnode anymore.
 * To avoid this, temporarily add a new permission, to forbid the uapp
 * (not sysmgr) revoking the cnode uref.
 *
 * In future, might be necessary to perfect the base infrastructure of
 * the capability mechanism to solve this problem utterly.
 */
#define CPERMISSION_REVOKE_GRANT		(1ULL << CPERMISSION_REVOKE_GRANT_BIT)

/* permission to create/destory the cap of actvpool, which is owned by server processes,
 * such as sysmgr, devhost, and so on */
#define CPERMISSION_NEW_DEL_ACTVPOOL		(1ULL << CPERMISSION_NEW_DEL_ACTVPOOL_BIT)

/* permission to create/destory the cap of thread, which is only created by sysmgr */
#define CPERMISSION_NEW_DEL_THREAD		(1ULL << CPERMISSION_NEW_DEL_THREAD_BIT)

/* permission to create/destory the cap of scheduler, which is only owned by sysmgr */
#define CPERMISSION_NEW_DEL_SCHEDULER		(1ULL << CPERMISSION_NEW_DEL_SCHEDULER_BIT)

/* permission to disable/enable preempt of scheduler */
#define CPERMISSION_SCHED_PREEMPT		(1ULL << CPERMISSION_SCHED_PREEMPT_BIT)

/* permission to establish and reject the proxy authorization. */
#define CPERMISSION_CNODE_PROXY_GRANT		(1ULL << CPERMISSION_CNODE_PROXY_GRANT_BIT)

/* permission to query the recent timeout of timer, which is only owned by tppmgr */
#define CPERMISSION_IDLE	(1ULL << CPERMISSION_IDLE_BIT)

/* permission to notifier kernel cpufreq module, which is only owned by tppmgr */
#define CPERMISSION_CPUFREQ	(1ULL << CPERMISSION_CPUFREQ_BIT)

/* permission to call module ioctl to kernel pm class module */
#define CPERMISSION_POWER_IOCTL			(1ULL << CPERMISSION_POWER_IOCTL_BIT)

/* permission to read different type of the kev data */
#define CPERMISSION_KEV_READ 			(1ULL << CPERMISSION_KEV_READ_BIT)
#define CPERMISSION_KEV_SAMPLE 			(1ULL << CPERMISSION_KEV_SAMPLE_BIT)
#define CPERMISSION_KEV_KLOG 			(1ULL << CPERMISSION_KEV_KLOG_BIT)
#define CPERMISSION_KEV_AUDIT 			(1ULL << CPERMISSION_KEV_AUDIT_BIT)

#define CPERMISSION_HMSIG_MASK_NONMASKABLE	(1ULL << CPERMISSION_HMSIG_MASK_NONMASKABLE_BIT)

#define CPERMISSION_KLIVEPATCH			(1ULL << CPERMISSION_KLIVEPATCH_BIT)

/*
 * permission to create/destory cap_EcEp/cap_EcChn, connect cap_EcEp to
 * cap_EcChn and disconnect cap_EcEp from cap_EcChn, which is only owned by
 * sysmgr
 */
#define CPERMISSION_EVENT_CHANNEL		(1ULL << CPERMISSION_EVENT_CHANNEL)

/* permisson to create epoll */
#define CPERMISSION_NEW_EPOLL			(1ULL << CPERMISSION_NEW_EPOLL_BIT)

#define CPERMISSION_DSUCTX_NEW			(1ULL << CPERMISSION_DSUCTX_NEW_BIT)

#define CPERMISSION_PEK				(1ULL << CPERMISSION_PEK_BIT)
#define CPERMISSION_NEW_FDTABLE			(1ULL << CPERMISSION_NEW_FDTABLE_BIT)

#define CPERMISSION_BIND_FDTABLE		(1ULL << CPERMISSION_BIND_FDTABLE_BIT)

#define CPERMISSION_VIRQ_MAP			(1ULL << CPERMISSION_VIRQ_MAP_BIT)


/* permission to flush pa */
#define CPERMISSION_FLUSH_CACHE_BY_PA		(1ULL << CPERMISSION_FLUSH_CACHE_BY_PA_BIT)
#define CPERMISSION_LSYSCALL			(1ULL << CPERMISSION_LSYSCALL_BIT)

/* permission to cache seccomp, which is only owned by sysmgr */
#define CPERMISSION_SYSADMIN		(1ULL << CPERMISSION_SYSADMIN_BIT)
/* permission to access the actv binder driver */
#define CPERMISSION_ACTV_BINDER			(1ULL << CPERMISSION_ACTV_BINDER_BIT)

/* permission to ctrl poweroff/reboot */
#define CPERMISSION_POWERCTRL			(1ULL << CPERMISSION_POWERCTRL_BIT)

/* permission to acquire credential of base actv */
#define CPERMISSION_BASE_ACTV_G1_CRED			(1ULL << CPERMISSION_BASE_ACTV_G1_CRED_BIT)

/* permission to ulwt admin */
#define CPERMISSION_ULWT_ADMIN		(1ULL << CPERMISSION_ULWT_ADMIN_BIT)

/* permission to capability call TimerStart */
#define CPERMISSION_TIMER_START			(1ULL << CPERMISSION_TIMER_START_BIT)

/* permission to change ptrace state of tcb, which is only owned by sysmgr */
#define CPERMISSION_THREAD_PTRACE		(1ULL << CPERMISSION_THREAD_PTRACE_BIT)

/* permission to do some general operations, which is only owned by devhost */
#define CPERMISSION_DEVHOST_GENERAL		(1ULL << CPERMISSION_DEVHOST_GENERAL_BIT)

/* permission to trace ctrl, which is only owned by sysmgr */
#define CPERMISSION_TRACECTRL		(1ULL << CPERMISSION_TRACECTRL_BIT)

#define CPERMISSION_ALL \
	(CPERMISSION_NEW_PERMISSION		| \
	 CPERMISSION_NEW_VSPACE			| \
	 CPERMISSION_NEW_VM			| \
	 CPERMISSION_NEW_CPUCONTEXT_PMU		| \
	 CPERMISSION_NEW_CPUCONTEXT_DEBUG	| \
	 CPERMISSION_NEW_CPUCONTEXT_VCPU	| \
	 CPERMISSION_LOAD_PREV_STAT		| \
	 CPERMISSION_STORE_PREV_UCTX		| \
	 CPERMISSION_ACTV_READ_CALLER_VM	| \
	 CPERMISSION_ACTV_WRITE_CALLER_VM	| \
	 CPERMISSION_ACTV_READ_XACT_VM		| \
	 CPERMISSION_ACTV_WRITE_XACT_VM		| \
	 CPERMISSION_PMEM_STAT_PADDR		| \
	 CPERMISSION_NEW_DEL_PMEM		| \
	 CPERMISSION_SELFCHAIN_LOAD_PREV_STAT	| \
	 CPERMISSION_SELFCHAIN_STORE_PREV_UCTX	| \
	 CPERMISSION_SPECCHAIN_LOAD_PREV_STAT	| \
	 CPERMISSION_SPECCHAIN_STORE_PREV_UCTX	| \
	 CPERMISSION_SCHED_ADMIN		| \
	 CPERMISSION_KLOG			| \
	 CPERMISSION_ALARM_TIMER		| \
	 CPERMISSION_REDUCE_CAP_RIGHTS		| \
	 CPERMISSION_KCONSOLE			| \
	 CPERMISSION_THREAD_BIND_ACTVPOOL	| \
	 CPERMISSION_REVOKE_GRANT		| \
	 CPERMISSION_NEW_DEL_ACTVPOOL		| \
	 CPERMISSION_NEW_DEL_THREAD		| \
	 CPERMISSION_NEW_DEL_SCHEDULER		| \
	 CPERMISSION_CNODE_PROXY_GRANT		| \
	 CPERMISSION_WATCHDOG			| \
	 CPERMISSION_SCHED_PREEMPT		| \
	 CPERMISSION_IDLE	| \
	 CPERMISSION_CPUFREQ			| \
	 CPERMISSION_POWER_IOCTL		| \
	 CPERMISSION_KEV_READ			| \
	 CPERMISSION_KEV_SAMPLE			| \
	 CPERMISSION_KEV_KLOG			| \
	 CPERMISSION_KEV_AUDIT			| \
	 CPERMISSION_HMSIG_MASK_NONMASKABLE	| \
	 CPERMISSION_KLIVEPATCH			| \
	 CPERMISSION_EVENT_CHANNEL		| \
	 CPERMISSION_NEW_EPOLL			| \
	 CPERMISSION_PEK			| \
	 CPERMISSION_NEW_FDTABLE		| \
	 CPERMISSION_DSUCTX_NEW			| \
	 CPERMISSION_LSYSCALL			| \
	 CPERMISSION_SYSADMIN			| \
	 CPERMISSION_BIND_FDTABLE		| \
	 CPERMISSION_VIRQ_MAP			| \
	 CPERMISSION_ACTV_BINDER		| \
	 CPERMISSION_BASE_ACTV_G1_CRED		| \
	 CPERMISSION_ULWT_ADMIN			| \
	 CPERMISSION_TIMER_START		| \
	 CPERMISSION_POWERCTRL			| \
	 CPERMISSION_THREAD_PTRACE		| \
	 CPERMISSION_DEVHOST_GENERAL)

#endif
#endif
