#
# Copyright (c) Hisilicon Technologies Co., Ltd. 2021-2021. All rights reserved.
#

DEFINES += -DHVGR_TRACE_INCLUDE_PATH=$(HVGR_ROOT)/utils/log

SRC += \
	$(HVGR_ROOT)/utils/log/hvgr_log.c \
	$(HVGR_ROOT)/utils/log/hvgr_trace.c
