/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Description: ******
 * Author: Huawei OS Kernel Lab
 * Create: Wed Dec 28 23:18:01 2022
 */
#include <stdio.h>

int main(int argc, char *argv[])
{
	(void)(argc);
	unsigned int counter;

	printf("/* Auto generated by %s */\n", argv[0]);
	printf("#ifndef ASM_CAP_METHOD_NUMBERS\n");
	printf("#define ASM_CAP_METHOD_NUMBERS\n");
#define CAPERRNO(type, perrno, ename, desc)

#define CAPMETHOD(type, method)				\
	counter++;					\
	printf("#define CAPMETHOD_NUM_" #type #method " %u\n", counter);

#define CAPTYPE(name, number, skip, content)		\
	counter = 0;					\
	printf("#define CAP_NUM_" #name " %d\n", number);	\
	content

#include <hmkernel/capability/captypes.h>
	printf("#endif\n");

	return 0;
}
