obj-y += base/
obj-y += fipc_agent/
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/include/
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/config/msg/public
subdir-ccflags-y += -Werror
