/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: lsyscall definition
 * Author: Huawei OS Kernel Lab
 * Create: Mon Jan 09 16:48:52 2023
 */

#ifndef UAPI_HMKERNEL_EXTENSIONS_LSYSCALL_H
#define UAPI_HMKERNEL_EXTENSIONS_LSYSCALL_H

#include <hmasm/ucontext.h>

#define __LSYSCALL_MAX_SYS_NO 514

/* Max to 7 args can be passed for lsyscall */
#define __LSYSCALL_MAX_ARGS_NUM 7

#define HM_SECCOMP_MASK 0xFFFFF000
#define HM_SECCOMP_ERRNO_AC 0x0FFF
#define HM_SECCOMP_ERRNO_TAG 0xFFFFE000
#define HM_SECCOMP_ROLLBACK_TAG 0xFFFFD000

enum lsyscall_server_type {
	__LSYSCALL_SVR_INVALID = 0,
	__LSYSCALL_SVR_KERNEL,
	__LSYSCALL_SVR_SYSMGR,
	__LSYSCALL_SVR_ROOTFS,
	__LSYSCALL_SVR_NETWORK,
	__LSYSCALL_SVR_DEVHOST,
	__LSYSCALL_SVR_TPPMGR,
	__LSYSCALL_SVR_CRYPTO,
	__LSYSCALL_SVR_KEYMGR,
	__LSYSCALL_SVR_DEVMGR,
	__LSYSCALL_SVR_MAX,
};

#define __LSYSCALL_SVR_FS __LSYSCALL_SVR_ROOTFS
#define __LSYSCALL_SVR_HMNET __LSYSCALL_SVR_NETWORK
#define __LSYSCALL_SVR_PWRMGR __LSYSCALL_SVR_TPPMGR

enum lsyscall_ret_type {
	__LSYSCALL_RET_TYPE_INT = 0,
	__LSYSCALL_RET_TYPE_LONG,
	__LSYSCALL_RET_TYPE_UINT,
	__LSYSCALL_RET_TYPE_NONE,
	__LSYSCALL_RET_TYPE_INVALID,
};

/* lcallno used to test LSYSCALL call */
enum {
	__LSYSCALL_COMPAT_EPOLL_CREATE = 470,  /* fake svc no for aarch64  */
	__LSYSCALL_COMPAT_EPOLL_WAIT,          /* fake svc no for aarch64  */
	__LSYSCALL_KEVENTFD_CREATE, /* fake svc no for aarch64  */
	__LSYSCALL_TEST_SYSMGR_ARG0_CALLNO = 501,
	__LSYSCALL_TEST_SYSMGR_ARG1_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG2_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG3_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG4_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG5_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG6_CALLNO,
	__LSYSCALL_TEST_SYSMGR_ARG7_CALLNO,
	__LSYSCALL_TEST_SYSMGR_THREAD_CREF,
	__LSYSCALL_TEST_MAX_CALLNO,
};

#define ____LSYSCALL_COMPAT_EPOLL_CREATE __LSYSCALL_COMPAT_EPOLL_CREATE
#define ____LSYSCALL_COMPAT_EPOLL_WAIT __LSYSCALL_COMPAT_EPOLL_WAIT
#define ____LSYSCALL_KEVENTFD_CREATE __LSYSCALL_KEVENTFD_CREATE
#define ____LSYSCALL_TEST_SYSMGR_ARG0_CALLNO __LSYSCALL_TEST_SYSMGR_ARG0_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG1_CALLNO __LSYSCALL_TEST_SYSMGR_ARG1_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG2_CALLNO __LSYSCALL_TEST_SYSMGR_ARG2_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG3_CALLNO __LSYSCALL_TEST_SYSMGR_ARG3_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG4_CALLNO __LSYSCALL_TEST_SYSMGR_ARG4_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG5_CALLNO __LSYSCALL_TEST_SYSMGR_ARG5_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG6_CALLNO __LSYSCALL_TEST_SYSMGR_ARG6_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG7_CALLNO __LSYSCALL_TEST_SYSMGR_ARG7_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_THREAD_CREF __LSYSCALL_TEST_SYSMGR_THREAD_CREF

#define ____LSYSCALL_KEVENTFD_CREATE_COMPAT __LSYSCALL_KEVENTFD_CREATE
#define ____LSYSCALL_TEST_SYSMGR_ARG0_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG0_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG1_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG1_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG2_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG2_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG3_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG3_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG4_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG4_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG5_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG5_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG6_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG6_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_ARG7_CALLNO_COMPAT __LSYSCALL_TEST_SYSMGR_ARG7_CALLNO
#define ____LSYSCALL_TEST_SYSMGR_THREAD_CREF_COMPAT __LSYSCALL_TEST_SYSMGR_THREAD_CREF

typedef void (*lsyscall_uentry_t)(const struct arch_uctx *base_uctx,
				  const struct arch_uctx *curr_uctx,
				  void *sp);

#endif
