/*
 * Copyright (c) Huawei Technologies CO., Ltd. 2019-2020. All rights reserved.
 * Description: bbox_diaginfo_map.h
 * Author: Hisilicon
 * Create: 2019-10-29
 */
#ifndef __DIAGINFO_MAP
#define __DIAGINFO_MAP(x,y,z,k)
#endif

#ifndef __DIAGINFO_MODULE_MAP
#define __DIAGINFO_MODULE_MAP(x)
#endif

// X: Error id, Y:Module , Z: Log level, K: error type
__DIAGINFO_MAP(L3_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(L3_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU_UP_FAIL, SoC_AP, CRITICAL, HW)
__DIAGINFO_MAP(CPU_PANIC_INFO, SoC_AP, CRITICAL, HW)
__DIAGINFO_MAP(ACPU_LIT_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_MID_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_BIG_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(LOWPOWER_GPU_AVS_VAL, SoC_AP, WARNING, HW)

__DIAGINFO_MAP(ACPU_CL0_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL0_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_L3_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_L3_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL3_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL4_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL5_SH_CNT, SoC_AP, INFO, HW)

__DIAGINFO_MAP(ACPU_CL0_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL3_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL4_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL5_DFV_SH_CNT, SoC_AP, INFO, HW)

__DIAGINFO_MAP(NOC_FAULT_INFO, SoC_AP, CRITICAL, HW)
__DIAGINFO_MAP(SERROR_FAULT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(AP_WDT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(LPM3_EXC_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(BLOCK_DMD_CP_IO, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(BLOCK_DMD_NORMAL_IO, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(FBE_DIAG_FAIL_ID, SoC_AP, WARNING, SW)
__DIAGINFO_MAP(LPM3_DDR_FAIl, DDR, CRITICAL, HW)
__DIAGINFO_MAP(LPM3_DDR_PA_SENSOR, DDR, CRITICAL, HW)
__DIAGINFO_MAP(LPM3_DDR_TRAINING, DDR, CRITICAL, HW)
__DIAGINFO_MAP(CLOCK_PLL_AP, CLK, CRITICAL, HW)
__DIAGINFO_MAP(CLOCK_PLL_LPMCU, CLK, CRITICAL, HW)

__DIAGINFO_MAP(IGS_DMD_FDUL_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_FDUL_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_HWTS_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_HWTS_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_AIC_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_AIC_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_IR_PW, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_TIMEOUT, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_SLEEP_FUSION, FDUL, WARNING, SW)
__DIAGINFO_MAP(IGS_DMD_NPU_PLL_RETRY, FDUL, WARNING, SW)

__DIAGINFO_MAP(IOMCU_EXC_INFO, IOMCU_SH, WARNING, HW)

__DIAGINFO_MAP(PERI_SH_PV, SOC_PERI, INFO, HW)
__DIAGINFO_MAP(PERI_SH_CNT, SOC_PERI, INFO, HW)

/* HISP START */
__DIAGINFO_MAP(DMD_ISP_TIMEOUT_SH_CNT, ISP, INFO, HW)
/* HISP END */

/* Module name map */
__DIAGINFO_MODULE_MAP(SoC_AP)
__DIAGINFO_MODULE_MAP(DSS)
__DIAGINFO_MODULE_MAP(DDR)
__DIAGINFO_MODULE_MAP(FDUL)
__DIAGINFO_MODULE_MAP(CLK)
__DIAGINFO_MODULE_MAP(ISP)
__DIAGINFO_MODULE_MAP(SOC_PERI)
__DIAGINFO_MODULE_MAP(IOMCU_SH)
