/*
 * Copyright (c) Huawei Technologies CO., Ltd. 2019-2020. All rights reserved.
 * Description: m3_rdr_ddr_map.h
 * Author: Hisilicon
 * Create: 2019-10-29
 */
#ifndef __M3_RDR_DDR_MAP_H__
#define __M3_RDR_DDR_MAP_H__

/************************M3 RDR DDR SYSTEM CONTEXT*************************
 *注意:
 *      1、使用时，请先判断 M3_RDR_SYS_CONTEXT_BASE_ADDR 是否为NULL或0
 *
 *      2、kernel侧，地址为ioremap的虚拟地址
 *         legacy侧，为实际的ddr物理地址
 *         lpmcu侧，为实际的ddr物理地址
---------------------------------------------------------------------------
 Addr:               Contents:                              Size:
 0x00000 ~ 0x00080   rdr_mem_map_index                      (0x80)
 0x00080 ~ 0x00100   exc_special                            (0x80)
 0x00100 ~ 0x00200   sys context head                       (0x100)
 0x00200 ~ 0x00400   m3 core regs                           (0x200)
 0x00400 ~ 0x04000   m3 nvic regs                           (0xF00*4=0x3C00)
 0x04000 ~ 0x05000   m3 text logs                           (0x1000)
 0x05000 ~ 0x05400   m3 private logs                        (0x400)
 0x05400 ~ 0x05800   peri ip regs (ddr, sysnoc, etc..)      (0x400)
 0x05800 ~ 0x05900   run time var reserved                  (0x100)
 0x05900 ~ 0x06900   lpmcu stat                             (0x1000)
 0x06900 ~ 0x06B00   kernel stat                            (0x200)
 0x06B00 ~ 0x07700   expose storage                         (0xC00)
 0x07700 ~ 0x07B00   noc regs                               (0x400)
 0x07B00 ~ 0x07F00   run time var                           (0x400)
 0x07F00 ~ 0x08300   modem data                             (0x400)
 0x08300 ~ 0x09300   crg peri                               (0x1000)
 0x09300 ~ 0x0A300   sctrl                                  (0x1000)
 0x0A300 ~ 0x0B300   pmctrl                                 (0x1000)
 0x0B300 ~ 0x0C300   pctrl                                  (0x1000)
 0x0C300 ~ 0x0C400   iomcu regs                             (0x100)
 0x0C400 ~ 0x0D000   ddr regs                               (0xC00)
 0x0D000 ~ 0x0D040   pmu regs                               (0x040)
 0x0D040 ~ 0x0E440   ddr mntn                               (0x1400)
 0x0E440 ~ 0x0E6B0   little cluster profile                 (0x270)
 0x0E6B0 ~ 0x0E920   mid cluster profile                    (0x270)
 0x0E920 ~ 0x0EB90   big cluster profile                    (0x270)
 0x0EB90 ~ 0x0EE00   L3 cluster profile                     (0x270)
 0x0EE00 ~ 0x0F000   GPU base profile                       (0x200)
 0x0F000 ~ 0x16000   gic regs                               (0x7000)
 0x16000 ~ 0x16400   periavs para                           (0x400)
 0x16000 ~ 0x16600   aoavs para                             (0x200)
 0x16600 ~ 0x16A00   sr info                                (0x400)
 0x16A00 ~ 0x17A00   ipc track                              (0x1000)
 0x17A00 ~ 0x17A80   thermal freq limit                     (0x80)
 0x17A80 ~ 0x17A88   cpu current volt cfg                   (0x8)
 0x17A88 ~ 0x20000   reserved                               (0x8580)
 0x20000 ~ 0x50000   m3 sys image                           (0x30000=192k)
--------------------------------------------------------------------------*/
/*注意: 使用时，请先判断 M3_RDR_SYS_CONTEXT_BASE_ADDR 是否为NULL或0*/

#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        (0)
#define M3_RDR_SYS_CONTEXT_SIZE 				(0x80000)

#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_OFFSET		(0x0U) /*0x0*/
#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR) /*0x0*/
#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_SIZE		(0x80)

#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET	 		(M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_OFFSET + M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_SIZE)
#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_ADDR	 		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET)  /*0x80*/
#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_SIZE			(0x80)

#define M3_RDR_SYS_CONTEXT_HEAD_OFFSET				(M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET + M3_RDR_SYS_CONTEXT_EXC_SPECIAL_SIZE)
#define M3_RDR_SYS_CONTEXT_HEAD_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_HEAD_OFFSET)  /*0x100*/
#define M3_RDR_SYS_CONTEXT_HEAD_SIZE				(0x100)

#define M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET			(M3_RDR_SYS_CONTEXT_HEAD_OFFSET + M3_RDR_SYS_CONTEXT_HEAD_SIZE)
#define M3_RDR_SYS_CONTEXT_M3_COREREG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET)  /*0x200*/
#define M3_RDR_SYS_CONTEXT_M3_COREREG_SIZE			(0x200)

#define M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET			(M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET + M3_RDR_SYS_CONTEXT_M3_COREREG_SIZE)
#define M3_RDR_SYS_CONTEXT_M3_NVICREG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET) /*0x400*/
#define M3_RDR_SYS_CONTEXT_M3_NVICREG_SIZE			(0xF00*4)

#define M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET			(M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET+M3_RDR_SYS_CONTEXT_M3_NVICREG_SIZE)
#define M3_RDR_SYS_CONTEXT_M3_LOG_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET)/*0x4000*/
#define M3_RDR_SYS_CONTEXT_M3_LOG_SIZE				(0x1000)

#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET		(M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET+M3_RDR_SYS_CONTEXT_M3_LOG_SIZE)
#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET)/*0x5000*/
#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_SIZE			(0x400)

#define M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET			(M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET + M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_SIZE)
#define M3_RDR_SYS_CONTEXT_PERI_IPREG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET)/*0x5400*/
#define M3_RDR_SYS_CONTEXT_PERI_IPREG_SIZE			(0x400)

#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET		(M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET + M3_RDR_SYS_CONTEXT_PERI_IPREG_SIZE)
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET)/*0x5800*/
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_SIZE		(0x100)

#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET			(M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET+M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_SIZE)
#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET)/*0x5900*/
#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_SIZE			(0x1000)

#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET			(M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET+M3_RDR_SYS_CONTEXT_LPMCU_STAT_SIZE)
#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET)/*0x6900*/
#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_SIZE			(0x200)

#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET		(M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET+M3_RDR_SYS_CONTEXT_KERNEL_STAT_SIZE)
#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET)/*0x6B00*/
#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_SIZE			(0xC00)

#define M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET			(M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET+M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_SIZE)
#define M3_RDR_SYS_CONTEXT_NOC_REG_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET)/*0x7700*/
#define M3_RDR_SYS_CONTEXT_NOC_REG_SIZE				(0x400)

#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET			(M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET+M3_RDR_SYS_CONTEXT_NOC_REG_SIZE)
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET)/*0x7B00*/
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_SIZE			(0x400)

#define M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET			(M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET+M3_RDR_SYS_CONTEXT_RUNTIME_VAR_SIZE)
#define M3_RDR_SYS_CONTEXT_MODEM_DATA_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET)/*0x7F00*/
#define M3_RDR_SYS_CONTEXT_MODEM_DATA_SIZE			(0x400)

#define M3_RDR_CRG_PERI_OFFSET					(M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET + M3_RDR_SYS_CONTEXT_MODEM_DATA_SIZE)
#define M3_RDR_CRG_PERI_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_CRG_PERI_OFFSET)/*0x8300*/
#define M3_RDR_CRG_PERI_SIZE					(0x1000)

#define M3_RDR_SCTRL_OFFSET					(M3_RDR_CRG_PERI_OFFSET + M3_RDR_CRG_PERI_SIZE)
#define M3_RDR_SCTRL_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SCTRL_OFFSET)/*0x9300*/
#define M3_RDR_SCTRL_SIZE					(0x1000)

#define M3_RDR_PMCTRL_OFFSET					(M3_RDR_SCTRL_OFFSET + M3_RDR_SCTRL_SIZE)
#define M3_RDR_PMCTRL_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMCTRL_OFFSET)/*0xA300*/
#define M3_RDR_PMCTRL_SIZE					(0x1000)

#define M3_RDR_PCTRL_OFFSET					(M3_RDR_PMCTRL_OFFSET + M3_RDR_PMCTRL_SIZE)
#define M3_RDR_PCTRL_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PCTRL_OFFSET)/*0xB300*/
#define M3_RDR_PCTRL_SIZE					(0x1000)

#define M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET			(M3_RDR_PCTRL_OFFSET+M3_RDR_PCTRL_SIZE)
#define M3_RDR_SYS_CONTEXT_IOMCU_REG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET)/*0xC300*/
#define M3_RDR_SYS_CONTEXT_IOMCU_REG_SIZE			(0x100)

#define M3_RDR_DDR_REG_OFFSET					(M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET + M3_RDR_SYS_CONTEXT_IOMCU_REG_SIZE)
#define M3_RDR_DDR_REG_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_DDR_REG_OFFSET)/*0xC400*/
#define M3_RDR_DDR_REG_SIZE					(0xC00)

#define M3_RDR_PMU_REG_OFFSET					(M3_RDR_DDR_REG_OFFSET + M3_RDR_DDR_REG_SIZE)
#define M3_RDR_PMU_REG_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMU_REG_OFFSET)/*0xD000*/
#define M3_RDR_PMU_REG_SIZE					(0x40)

/*ddr mntn used 5K in fastboot*/
#define M3_RDR_DDR_MNTN_OFFSET					(M3_RDR_PMU_REG_OFFSET + M3_RDR_PMU_REG_SIZE)
#define M3_RDR_DDR_MNTN_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_DDR_MNTN_OFFSET)/*0xD040*/
#define M3_RDR_DDR_MNTN_SIZE					(5*1024)

/*save big/little/GPU profile*/
#define M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET			(M3_RDR_DDR_MNTN_OFFSET + M3_RDR_DDR_MNTN_SIZE)
#define M3_RDR_LITTLE_CLUSTER_PROFILE_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET)/*0xE440*/
#define M3_RDR_LITTLE_CLUSTER_PROFILE_SIZE			(0X270)

#define M3_RDR_MID_CLUSTER_PROFILE_OFFSET			(M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET + M3_RDR_LITTLE_CLUSTER_PROFILE_SIZE)
#define M3_RDR_MID_CLUSTER_PROFILE_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_MID_CLUSTER_PROFILE_OFFSET)/*0xE6B0*/
#define M3_RDR_MID_CLUSTER_PROFILE_SIZE				(0X270)

#define M3_RDR_BIG_CLUSTER_PROFILE_OFFSET			(M3_RDR_MID_CLUSTER_PROFILE_OFFSET + M3_RDR_MID_CLUSTER_PROFILE_SIZE)
#define M3_RDR_BIG_CLUSTER_PROFILE_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_BIG_CLUSTER_PROFILE_OFFSET)/*0xE920*/
#define M3_RDR_BIG_CLUSTER_PROFILE_SIZE				(0X270)

#define M3_RDR_L3_CLUSTER_PROFILE_OFFSET			(M3_RDR_BIG_CLUSTER_PROFILE_OFFSET + M3_RDR_BIG_CLUSTER_PROFILE_SIZE)
#define M3_RDR_L3_CLUSTER_PROFILE_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_L3_CLUSTER_PROFILE_OFFSET)/*0xEB90*/
#define M3_RDR_L3_CLUSTER_PROFILE_SIZE				(0X270)

#define M3_RDR_GPU_BASE_PROFILE_OFFSET				(M3_RDR_L3_CLUSTER_PROFILE_OFFSET + M3_RDR_L3_CLUSTER_PROFILE_SIZE)
#define M3_RDR_GPU_BASE_PROFILE_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_GPU_BASE_PROFILE_OFFSET)/*0xEE00*/
#define M3_RDR_GPU_BASE_PROFILE_SIZE				(0X200)

#define M3_RDR_GIC_REG_OFFSET					(M3_RDR_GPU_BASE_PROFILE_OFFSET + M3_RDR_GPU_BASE_PROFILE_SIZE)
#define M3_RDR_GIC_REG_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_GIC_REG_OFFSET)/*0xF000*/
#define M3_RDR_GIC_REG_SIZE					(0x7000)

#define M3_RDR_PERIAVS_PARA_OFFSET				(M3_RDR_GIC_REG_OFFSET + M3_RDR_GIC_REG_SIZE)
#define M3_RDR_PERIAVS_PARA_ADDR				(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PERIAVS_PARA_OFFSET)/*0x16000*/
#define M3_RDR_PERIAVS_PARA_SIZE				(0x400)

#define M3_RDR_AOAVS_PARA_OFFSET				(M3_RDR_PERIAVS_PARA_OFFSET + M3_RDR_PERIAVS_PARA_SIZE)
#define M3_RDR_AOAVS_PARA_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_AOAVS_PARA_OFFSET) /* 0x16400 */
#define M3_RDR_AOAVS_PARA_SIZE					(0x200)

#define M3_RDR_SR_INFO_OFFSET					(M3_RDR_AOAVS_PARA_OFFSET + M3_RDR_AOAVS_PARA_SIZE)
#define M3_RDR_SR_INFO_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SR_INFO_OFFSET) /* 0x16600 */
#define M3_RDR_SR_INFO_SIZE					(0x400)

#define M3_RDR_IPC_TRACK_OFFSET					(M3_RDR_SR_INFO_OFFSET + M3_RDR_SR_INFO_SIZE)
#define M3_RDR_IPC_TRACK_ADDR					(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_IPC_TRACK_OFFSET) /* 0x16A00 */
#define M3_RDR_IPC_TRACK_SIZE					(0x1000)

#define M3_RDR_THERMAL_FREQ_LIMIT_OFFSET        (M3_RDR_IPC_TRACK_OFFSET + M3_RDR_IPC_TRACK_SIZE)
#define M3_RDR_THERMAL_FREQ_LIMIT_ADDR	        (M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_THERMAL_FREQ_LIMIT_OFFSET) /* 0x17A00 */
#define M3_RDR_THERMAL_FREQ_LIMIT_SIZE	        (0x80)

#define M3_RDR_DDR_VOTE_TIME_OFFSET		(M3_RDR_THERMAL_FREQ_LIMIT_OFFSET + M3_RDR_THERMAL_FREQ_LIMIT_SIZE)
#define M3_RDR_DDR_VOTE_TIME_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_DDR_VOTE_TIME_OFFSET) /* 0x17A80 */
#define M3_RDR_DDR_VOTE_TIME_SIZE		0x5A0

#define M3_RDR_DDR_LOWPOWER_TIME_OFFSET		(M3_RDR_DDR_VOTE_TIME_OFFSET + M3_RDR_DDR_VOTE_TIME_SIZE)
#define M3_RDR_DDR_LOWPOWER_TIME_ADDR \
	(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_DDR_LOWPOWER_TIME_OFFSET) /* 0x18020 */
#define M3_RDR_DDR_LOWPOWER_TIME_SIZE		0x280

#define M3_RDR_CPU_CURRENT_VOLT_OFFSET		(M3_RDR_DDR_LOWPOWER_TIME_OFFSET + M3_RDR_DDR_LOWPOWER_TIME_SIZE)
#define M3_RDR_CPU_CURRENT_VOLT_ADDR \
	(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_CPU_CURRENT_VOLT_OFFSET) /* 0x182A0 */
#define M3_RDR_CPU_CURRENT_VOLT_SIZE		0x8
#define M3_RDR_CXPU_SEC_DATA_OFFSET M3_RDR_CPU_CURRENT_VOLT_OFFSET /*use this def in parse func*/
#define M3_RDR_CXPU_SEC_DATA_SIZE	M3_RDR_CPU_CURRENT_VOLT_SIZE /*use this def in parse func*/

#define M3_RDR_SYS_CONTEXT_RESERVED_ADDR \
	(M3_RDR_CPU_CURRENT_VOLT_ADDR + M3_RDR_CPU_CURRENT_VOLT_SIZE) /* 0x182A8 */

#if ( (M3_RDR_SYS_CONTEXT_RESERVED_ADDR) > (M3_RDR_SYS_CONTEXT_BASE_ADDR+0x20000))
#error "rdr space overflow! please reorganize the rdr space"
#endif

/* m3 sysimage at the last 192K */
#define M3_RDR_SYS_CONTEXT_M3_IMAGE_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR+0x20000)         /* sys img offset 0x20000 */
#define M3_RDR_SYS_CONTEXT_M3_IMAGE_SIZE			(0x30000)


#undef M3_RDR_SYS_CONTEXT_BASE_ADDR
#if defined(__KERNEL__)
#if defined(CONFIG_LPMCU_BB)
extern char *g_lpmcu_rdr_ddr_addr;
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        g_lpmcu_rdr_ddr_addr
#else
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        (0)
#endif
#elif defined(__CMSIS_RTOS)
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        LPM3_RDR_DDR_ADDR
#elif defined(FASTBOOT_MNTN) || defined(CONFIG_BL2_LOAD_LPMCU)
extern unsigned long long g_lpmcu_rdr_ddr_addr;
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        g_lpmcu_rdr_ddr_addr
#else
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        (0)
#endif


#endif /* __M3_RDR_DDR_MAP_H__ */
