/*
 * Copyright (c) Huawei Technologies CO., Ltd. 2019-2020. All rights reserved.
 * Description: soc_npu_ts_sysctrl_reg_offset.h
 * Author: Hisilicon
 * Create: 2019-10-29
 */

#ifndef __TS_SYSCTRL_REG_OFFSET_H__
#define __TS_SYSCTRL_REG_OFFSET_H__

/* TS_SYSCTRL Base address of Module's Register */
#define SOC_TS_SYSCTRL_BASE                       (0xe4030000)

/******************************************************************************/
/*                      SOC TS_SYSCTRL Registers' Definitions                            */
/******************************************************************************/

#define SOC_TS_SYSCTRL_SC_CTRL_REG      (SOC_TS_SYSCTRL_BASE + 0x0)   /* Reserved */
#define SOC_TS_SYSCTRL_SC_SYSSTAT0_REG  (SOC_TS_SYSCTRL_BASE + 0x8)   /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT1_REG  (SOC_TS_SYSCTRL_BASE + 0xC)   /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT2_REG  (SOC_TS_SYSCTRL_BASE + 0x10)  /* AXI总线deadlock DFX寄存器。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT3_REG  (SOC_TS_SYSCTRL_BASE + 0x14)  /* AXI总线deadlock 端口状态寄存器。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT4_REG  (SOC_TS_SYSCTRL_BASE + 0x18)  /* SVT_TIDM状态寄存器0。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT5_REG  (SOC_TS_SYSCTRL_BASE + 0x1C)  /* SVT_PA状态寄存器1。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT6_REG  (SOC_TS_SYSCTRL_BASE + 0x20)  /* SVT_PA状态寄存器2。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT7_REG  (SOC_TS_SYSCTRL_BASE + 0x24)  /* LVT_TIDM状态寄存器。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT8_REG  (SOC_TS_SYSCTRL_BASE + 0x28)  /* LVT_PA状态寄存器1。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT9_REG  (SOC_TS_SYSCTRL_BASE + 0x2C)  /* LVT_PA状态寄存器2。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT10_REG (SOC_TS_SYSCTRL_BASE + 0x30)  /* CNT低32位寄存器。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT11_REG (SOC_TS_SYSCTRL_BASE + 0x34)  /* CNT高32位寄存器。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT12_REG (SOC_TS_SYSCTRL_BASE + 0x38)  /* HPM状态信号。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT13_REG (SOC_TS_SYSCTRL_BASE + 0x3C)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT14_REG (SOC_TS_SYSCTRL_BASE + 0x40)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT15_REG (SOC_TS_SYSCTRL_BASE + 0x44)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT16_REG (SOC_TS_SYSCTRL_BASE + 0x48)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT17_REG (SOC_TS_SYSCTRL_BASE + 0x4C)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT18_REG (SOC_TS_SYSCTRL_BASE + 0x50)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT19_REG (SOC_TS_SYSCTRL_BASE + 0x54)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT20_REG (SOC_TS_SYSCTRL_BASE + 0x58)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT21_REG (SOC_TS_SYSCTRL_BASE + 0x5C)  /* 保留。 */
#define SOC_TS_SYSCTRL_SC_SYSSTAT22_REG (SOC_TS_SYSCTRL_BASE + 0x60)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL0_REG  (SOC_TS_SYSCTRL_BASE + 0x9C)  /* 中断测试； */
#define SOC_TS_SYSCTRL_PERIPHCTRL1_REG  (SOC_TS_SYSCTRL_BASE + 0xA0)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL2_REG  (SOC_TS_SYSCTRL_BASE + 0xA4)  /* TS 特殊功能控制寄存器2。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL3_REG  (SOC_TS_SYSCTRL_BASE + 0xA8)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL4_REG  (SOC_TS_SYSCTRL_BASE + 0xAC)  /* TS AXI BUS硬件自动门控使能寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL5_REG  (SOC_TS_SYSCTRL_BASE + 0xB0)  /* TS AXI总线挂死状态清除寄存器 */
#define SOC_TS_SYSCTRL_PERIPHCTRL6_REG  (SOC_TS_SYSCTRL_BASE + 0xB4)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL7_REG  (SOC_TS_SYSCTRL_BASE + 0xB8)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL8_REG  (SOC_TS_SYSCTRL_BASE + 0xBC)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL9_REG  (SOC_TS_SYSCTRL_BASE + 0xC0)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL10_REG (SOC_TS_SYSCTRL_BASE + 0xC4)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL11_REG (SOC_TS_SYSCTRL_BASE + 0xC8)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL12_REG (SOC_TS_SYSCTRL_BASE + 0xCC)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL13_REG (SOC_TS_SYSCTRL_BASE + 0xD0)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL14_REG (SOC_TS_SYSCTRL_BASE + 0xD4)  /* TS内部的DATA口QOS配置寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL15_REG (SOC_TS_SYSCTRL_BASE + 0xD8)  /* NPU内部的CFG口QOS配置寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL16_REG (SOC_TS_SYSCTRL_BASE + 0xDC)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL17_REG (SOC_TS_SYSCTRL_BASE + 0xE0)  /* NPU DOORBELL MEM控制寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL18_REG (SOC_TS_SYSCTRL_BASE + 0xE4)  /* NPU SRAM MEM控制寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL19_REG (SOC_TS_SYSCTRL_BASE + 0xE8)  /* NPU AXI BUS总线优先级控制寄存器。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL20_REG (SOC_TS_SYSCTRL_BASE + 0xEC)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL21_REG (SOC_TS_SYSCTRL_BASE + 0xF0)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL22_REG (SOC_TS_SYSCTRL_BASE + 0xF4)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL23_REG (SOC_TS_SYSCTRL_BASE + 0xF8)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL24_REG (SOC_TS_SYSCTRL_BASE + 0xFC)  /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL25_REG (SOC_TS_SYSCTRL_BASE + 0x100) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL26_REG (SOC_TS_SYSCTRL_BASE + 0x104) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL27_REG (SOC_TS_SYSCTRL_BASE + 0x108) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL28_REG (SOC_TS_SYSCTRL_BASE + 0x10C) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL29_REG (SOC_TS_SYSCTRL_BASE + 0x110) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL30_REG (SOC_TS_SYSCTRL_BASE + 0x114) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL31_REG (SOC_TS_SYSCTRL_BASE + 0x118) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL32_REG (SOC_TS_SYSCTRL_BASE + 0x11C) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL33_REG (SOC_TS_SYSCTRL_BASE + 0x120) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL34_REG (SOC_TS_SYSCTRL_BASE + 0x124) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL35_REG (SOC_TS_SYSCTRL_BASE + 0x128) /* 保留。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL50_REG (SOC_TS_SYSCTRL_BASE + 0x164) /* 模拟IP控制寄存器0。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL51_REG (SOC_TS_SYSCTRL_BASE + 0x168) /* 模拟IP控制寄存器1。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL52_REG (SOC_TS_SYSCTRL_BASE + 0x16C) /* 模拟IP控制寄存器2。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL53_REG (SOC_TS_SYSCTRL_BASE + 0x170) /* 模拟IP控制寄存器3。 */
#define SOC_TS_SYSCTRL_PERIPHCTRL54_REG (SOC_TS_SYSCTRL_BASE + 0x174) /* 模拟IP控制寄存器4。 */
#define SOC_TS_SYSCTRL_SC_TESTREG0_REG  (SOC_TS_SYSCTRL_BASE + 0xBE0) /* 软件测试寄存器0。 */
#define SOC_TS_SYSCTRL_SC_TESTREG1_REG  (SOC_TS_SYSCTRL_BASE + 0xBE4) /* 软件测试寄存器1。 */
#define SOC_TS_SYSCTRL_SC_TESTREG2_REG  (SOC_TS_SYSCTRL_BASE + 0xBE8) /* 软件测试寄存器2。 */
#define SOC_TS_SYSCTRL_SC_TESTREG3_REG  (SOC_TS_SYSCTRL_BASE + 0xBEC) /* 软件测试寄存器3。 */
#define SOC_TS_SYSCTRL_SC_TESTREG4_REG  (SOC_TS_SYSCTRL_BASE + 0xBF0) /* 软件测试寄存器4。 */
#define SOC_TS_SYSCTRL_SC_TESTREG5_REG  (SOC_TS_SYSCTRL_BASE + 0xBF4) /* 软件测试寄存器5。 */
#define SOC_TS_SYSCTRL_SC_TESTREG6_REG  (SOC_TS_SYSCTRL_BASE + 0xBF8) /* 软件测试寄存器6。 */
#define SOC_TS_SYSCTRL_SC_TESTREG7_REG  (SOC_TS_SYSCTRL_BASE + 0xBFC) /* 软件测试寄存器7。 */
#define SOC_TS_SYSCTRL_SC_TESTREG8_REG  (SOC_TS_SYSCTRL_BASE + 0xC00) /* 软件测试寄存器8。 */
#define SOC_TS_SYSCTRL_SC_TESTREG9_REG  (SOC_TS_SYSCTRL_BASE + 0xC04) /* 软件测试寄存器9。 */
#define SOC_TS_SYSCTRL_SC_TESTREG10_REG (SOC_TS_SYSCTRL_BASE + 0xC08) /* 软件测试寄存器10。 */
#define SOC_TS_SYSCTRL_SC_TESTREG11_REG (SOC_TS_SYSCTRL_BASE + 0xC0C) /* 软件测试寄存器11。 */
#define SOC_TS_SYSCTRL_SC_TESTREG12_REG (SOC_TS_SYSCTRL_BASE + 0xC10) /* 软件测试寄存器12。 */
#define SOC_TS_SYSCTRL_SC_TESTREG13_REG (SOC_TS_SYSCTRL_BASE + 0xC14) /* 软件测试寄存器13。 */
#define SOC_TS_SYSCTRL_SC_TESTREG14_REG (SOC_TS_SYSCTRL_BASE + 0xC18) /* 软件测试寄存器14。 */
#define SOC_TS_SYSCTRL_SC_TESTREG15_REG (SOC_TS_SYSCTRL_BASE + 0xC1C) /* 软件测试寄存器15。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG0_REG  (SOC_TS_SYSCTRL_BASE + 0xC20) /* 硬件信号量寄存器0。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG1_REG  (SOC_TS_SYSCTRL_BASE + 0xC24) /* 硬件信号量寄存器1。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG2_REG  (SOC_TS_SYSCTRL_BASE + 0xC28) /* 硬件信号量寄存器2。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG3_REG  (SOC_TS_SYSCTRL_BASE + 0xC2C) /* 硬件信号量寄存器3。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG4_REG  (SOC_TS_SYSCTRL_BASE + 0xC30) /* 硬件信号量寄存器4。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG5_REG  (SOC_TS_SYSCTRL_BASE + 0xC34) /* 硬件信号量寄存器5。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG6_REG  (SOC_TS_SYSCTRL_BASE + 0xC38) /* 硬件信号量寄存器6。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG7_REG  (SOC_TS_SYSCTRL_BASE + 0xC3C) /* 硬件信号量寄存器7。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG8_REG  (SOC_TS_SYSCTRL_BASE + 0xC40) /* 硬件信号量寄存器8。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG9_REG  (SOC_TS_SYSCTRL_BASE + 0xC44) /* 硬件信号量寄存器9。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG10_REG (SOC_TS_SYSCTRL_BASE + 0xC48) /* 硬件信号量寄存器10。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG11_REG (SOC_TS_SYSCTRL_BASE + 0xC4C) /* 硬件信号量寄存器11。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG12_REG (SOC_TS_SYSCTRL_BASE + 0xC50) /* 硬件信号量寄存器12。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG13_REG (SOC_TS_SYSCTRL_BASE + 0xC54) /* 硬件信号量寄存器13。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG14_REG (SOC_TS_SYSCTRL_BASE + 0xC58) /* 硬件信号量寄存器14。 */
#define SOC_TS_SYSCTRL_SC_SEMAREG15_REG (SOC_TS_SYSCTRL_BASE + 0xC5C) /* 硬件信号量寄存器15。 */
#define SOC_TS_SYSCTRL_SC_TESTREG16_REG (SOC_TS_SYSCTRL_BASE + 0xC60) /* 软件测试寄存器16。 */
#define SOC_TS_SYSCTRL_SC_TESTREG17_REG (SOC_TS_SYSCTRL_BASE + 0xC64) /* 软件测试寄存器17。 */
#define SOC_TS_SYSCTRL_SCPROTREG_REG    (SOC_TS_SYSCTRL_BASE + 0xC68) /* TS复位保护寄存器。 */

#endif // __TS_SYSCTRL_REG_OFFSET_H__
