/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2024. All rights reserved.
 * Description: linear vibrator head File.
 * Create: 2024-04-09
 */

#ifndef _LINEAR_VIBRATOR_PMIC21_H
#define _LINEAR_VIBRATOR_PMIC21_H

#define LINEAR_VIBRATOR_DEFAULT_NAME "vibrator"
#define LINEAR_VIBRATOR_CDEVIE_NAME "haptics"
#define LINEAR_VIBRATOR_HAPTIC_CFG_STR "haptics-cfg"

#define LINEAR_VIBRATOR_CLK_GATE 0x4E

#define LINEAR_VIBRATOR_ON 0x7000
#define LINEAR_VIBRATOR_BRAKE 0x7001

#define LINEAR_VIBRATOR_DUTY_NORMAL_CFG_L 0x7010
#define LINEAR_VIBRATOR_DUTY_NORMAL_CFG_H 0x7011

#define LINEAR_VIBRATOR_OUT_NML_VBEMF_L 0x7041
#define LINEAR_VIBRATOR_OUT_NML_VBEMF_H 0x7042
#define LINEAR_VIBRATOR_UREAL_DATA_L 0x7045
#define LINEAR_VIBRATOR_UREAL_DATA_H 0x7046
#define LINEAR_VIBRATOR_ADC_ZERO_L 0x704B
#define LINEAR_VIBRATOR_ADC_ZERO_H 0x704C
#define LINEAR_VIBRATOR_KFIT_DATA_L 0x704D
#define LINEAR_VIBRATOR_KFIT_DATA_H 0x704E
#define LINEAR_VIBRATOR_LRA_NML_TIME_L 0x70AF
#define LINEAR_VIBRATOR_LRA_NML_TIME_M 0x70B0
#define LINEAR_VIBRATOR_LRA_NML_TIME_H 0x70B1
#define LINEAR_VIBRATOR_LRA_NML_BEML_L 0x70B2
#define LINEAR_VIBRATOR_LRA_NML_BEML_H 0x70B3

#define LINEAR_VIBRATOR_RESET_REG           0x00AE
#define LINEAR_VIBRATOR_CALI_RESET          0xAC
#define LINEAR_VIBRATOR_CALI_DEASSERT_RESET 0x5A

#define LINEAR_VIBRATOR_SPEL_TIME_REG0 0x7050
#define LINEAR_VIBRATOR_SPEL_TIME_REG6 0x7056
#define LINEAR_VIBRATOR_SPEL_TIME_REG_NUM 4
#define LINEAR_VIBRATOR_LADD_PARA_REG 0x702B
#define LINEAR_VIBRATOR_LADD_PARA_REG_NUM 20
#define LINEAR_VIBRATOR_SPEL_DUTY_REG 0x7065
#define LINEAR_VIBRATOR_REG_CFG_NUM LINEAR_VIBRATOR_LADD_PARA_REG_NUM

#define LINEAR_VIBRATOR_SPEL_TIME_REG2 0x7052
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE2_6 0x2A
#define LINEAR_VIBRATOR_SPEL_TIME_REG3 0x7053
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE3_6 0x23
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE3_8 0x2E
#define LINEAR_VIBRATOR_SPEL_TIME_REG4 0x7054
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE4_8 0x23
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE4_10 0x30
#define LINEAR_VIBRATOR_SPEL_TIME_REG5 0x7055
#define LINEAR_VIBRATOR_SPEL_TIME_VALUE5_10 0x23
#define LINEAR_VIBRATOR_HAPTIC_NUM 10
#define LINEAR_VIBRATOR_HAPTIC_1 1
#define LINEAR_VIBRATOR_HAPTIC_2 2
#define LINEAR_VIBRATOR_HAPTIC_3 3
#define LINEAR_VIBRATOR_HAPTIC_4 4
#define LINEAR_VIBRATOR_HAPTIC_5 5
#define LINEAR_VIBRATOR_HAPTIC_6 6

#define LINEAR_VIBRATOR_LRA_ANA_CFG2 0x708F
#define LINEAR_VIBRATOR_LRA_ANA_VALUE 0x0

#define LINEAR_VIBRATOR_MODE_STANDBY 0x00
#define LINEAR_VIBRATOR_MODE_RTP 0x01
#define LINEAR_VIBRATOR_MODE_HAPTICS 0x02
#define LINEAR_VIBRATOR_BRK_EN 0x01

#define LINEAR_VIBRATOR_OVDR_DUTY_L 0x700D
#define LINEAR_VIBRATOR_OVDR_DUTY_H 0x700E

#define LINEAR_VIBRATOR_TH_BOOST_L 0x701A
#define LINEAR_VIBRATOR_TH_BOOST_H 0x701B

#define LINEAR_VIBRATOR_DRV_NMU 0x7002
#define LINEAR_VIBRATOR_DRV_NUM_VALUE 0x94

#define LINEAR_VIBRATOR_BRAKE_DUTY_L 0x7013
#define LINEAR_VIBRATOR_BRAKE_DUTY_H 0x7014

#define LINEAR_VIBRATOR_GATE_VOLTAGE1_L 0x701C
#define LINEAR_VIBRATOR_GATE_VOLTAGE1_VALUE_L 0xA0
#define LINEAR_VIBRATOR_GATE_VOLTAGE1_H 0x701D
#define LINEAR_VIBRATOR_GATE_VOLTAGE1_VALUE_H 0x0
#define LINEAR_VIBRATOR_GATE_VOLTAGE2_L 0x701E
#define LINEAR_VIBRATOR_GATE_VOLTAGE2_VALUE_L 0x60
#define LINEAR_VIBRATOR_GATE_VOLTAGE2_H 0x701F
#define LINEAR_VIBRATOR_GATE_VOLTAGE2_VALUE_H 0x0
#define LINEAR_VIBRATOR_GATE_VOLTAGE3_L 0x7020
#define LINEAR_VIBRATOR_GATE_VOLTAGE3_VALUE_L 0x20
#define LINEAR_VIBRATOR_GATE_VOLTAGE3_H 0x7021
#define LINEAR_VIBRATOR_GATE_VOLTAGE3_VALUE_H 0x0
#define LINEAR_VIBRATOR_STATUS 0x704F

#define OVDR_DUTY_A 94060
#define OVDR_DUTY_B 35914000

#define TH_BOOST_A 273147
#define TH_BOOST_B 371927000

#define BRAKE_DUTY_A 135169
#define BRAKE_DUTY_B 40406000

#define LRA_NML_TIME 0x411
#define LRA_CYCLE_NUM 0x10
#define LRA_TIME_NUM 0x3D090
#define LRA_TIME_NUM1 0x61A8
#define LRA_HAPTIC_NUM 0xA
#define LRA_HAPTIC_NUM1 0x5
#define LRA_DEFAULT_FREQ 0x4FC97

#define LINEAR_VIBRATOR_BRAKE_TIME_OUT 100
#define POWER_USED_BOOST_5V 1
#define POWER_NOTUSED_BOOST_5V 0
#define LINEAR_VIBRATOR_POWER_ON 1
#define LINEAR_VIBRATOR_POWER_OFF 0
#define LED_VIBRATOR_OFF 0

#define LINEAR_VIBRATOR_FREQ_MAX 0x5AD7D
#define LINEAR_VIBRATOR_FREQ_MIN 0x4C87C

#define DUTY_NUM 240
#define VOLTAGE_NUM 3200

#define LINEAR_VIBRATOR_HAP_BUF_LENGTH 16
#define LINEAR_VIBRATOR_VOL_LEVEL_1 1
#define LINEAR_VIBRATOR_VOL_LEVEL_10 10
#define LINEAR_VIBRATOR_VOL_LEVEL_16 16
#define LINEAR_VIBRATOR_STRENGTH_STEP1 200 // 200mv
#define LINEAR_VIBRATOR_STRENGTH_STEP2 500 // 500mv

#define LINEAR_IRQ_L3_LRA_RPT 0x01B9
#define LINEAR_VIBRATOR_IRQ_COUNTS 5
#define LINEAR_VIBRATOR_EVENTOCP BIT(0)
#define LINEAR_VIBRATOR_EVENTOUT BIT(1)
#define LINEAR_VIBRATOR_EVENTUND BIT(2)
#define LINEAR_VIBRATOR_EVENTOVE BIT(3)
#define LINEAR_VIBRATOR_EVENTADC BIT(4)

/* ERM REG */
#define LINEAR_VIBRATOR_ERM_LOCK              0x70BC
#define LINEAR_VIBRATOR_ERM_MODE_CFG          0x70BD
#define LINEAR_VIBRATOR_FRQC_SEL_CFG          0x70BE
#define LINEAR_VIBRATOR_ERM_DUTY_OVDR_CFG_L   0x70BF
#define LINEAR_VIBRATOR_ERM_DUTY_OVDR_CFG_H   0x70C0
#define LINEAR_VIBRATOR_ERM_DUTY_NML_CFG_L    0x70C1
#define LINEAR_VIBRATOR_ERM_DUTY_NML_CFG_H    0x70C2
#define LINEAR_VIBRATOR_ERM_DUTY_BRK_CFG_L    0x70C3
#define LINEAR_VIBRATOR_ERM_DUTY_BRK_CFG_H    0x70C4

#define ERM_OVDR_VAL_L     0x0
#define ERM_OVDR_VAL_H     0x8
#define ERM_BREAK_VAL_L    0x40
#define ERM_BREAK_VAL_H    0x6

#define ERM_UNLOCK             0x7D
#define ERM_MODE_CLOSE_LOOP    0x1
#define ERM_MODE_NO_SAMPL      0x2
#define ERM_MODE_OPEN_LOOP     0x3
#define ERM_PWM_150K      0x0
#define ERM_PWM_300K      0x1
#define ERM_PWM_600K      0x2
#define ERM_PWM_1200K     0x3

#define ERM_DUTY_NUM      128
#define ERM_VOLTAGE_IN    5000

#define LINEAR_VIBRATOR_TIMEOUT_MIN 50
#define VIBRATOR_TIMEOUT_MIN_SIZE 16

/* for duty change */
#define LINEAR_WEAK_TYPE_DEFULT 0
#define LINEAR_STRENGTH_DEFULT 1400
#define LINEAR_WEAK_TYPE_1 (-1)
#define LINEAR_WEAK_STRENGTH_1 800
#define LINEAR_WEAK_TYPE_2 (-2)
#define LINEAR_WEAK_STRENGTH_2 600

#ifndef UNUSED
#define UNUSED(x) (void)(x)
#endif
#endif
