OBB_PRODUCT_NAME ?= $(platform)

-include $(srctree)/drivers/platform_drivers/modem/modem_env.mak
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk

ifeq ($(strip $(CFG_CONFIG_DPA_STACK)),YES)
endif

