OBB_PRODUCT_NAME ?= $(platform)

-include $(srctree)/drivers/platform_drivers/modem/modem_env.mak
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk

obj-$(CONFIG_DPA_DRIVERS) += dpa/
obj-$(CONFIG_DPA_API) += interface/host/
