/*
 * phone_pcm_dma_buf_layout.h -- phone pcm dma buf layout info
 *
 * Copyright (c) 2024-2024 Huawei Technologies Co., Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#ifndef __PHONE_PCM_DMA_BUF_LAYOUT_H__
#define __PHONE_PCM_DMA_BUF_LAYOUT_H__

#include "audio_ddr_map.h"

#ifdef CONFIG_HIFI_MEMORY_15M
/* sampling rate * time * bit width * channel num * buf num */
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 4 * 2 * 2)
#define PCM_DMA_BUF_PLAYBACK_DIRECT_LEN (48 * 20 * 4 * 2 * 4)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 4 * 8)
#define PCM_DMA_BUF_CAPTURE_DIRECT_LEN ((60 + 19) * 1024)
#define PCM_DMA_BUF_SPATIAL_AUDIO_LEN (48 * 20 * 4 * 16 * 4)
#define PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN 256
#else
#define PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN (48 * 20 * 2 * 4 * 4)
#define PCM_DMA_BUF_PLAYBACK_DIRECT_LEN (384 * 20 * 4 * 2 * 4)
#define PCM_DMA_BUF_CAPTURE_PRIMARY_LEN (48 * 20 * 2 * 13 * 8)
#define PCM_DMA_BUF_SPATIAL_AUDIO_LEN (48 * 20 * 4 * 16 * 4)
#define PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN 256
#endif

#define PCM_DMA_BUF_0_PLAYBACK_BASE (PCM_PLAY_BUFF_LOCATION)
#define PCM_DMA_BUF_0_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)
#define PCM_DMA_BUF_0_CAPTURE_BASE  (PCM_DMA_BUF_0_PLAYBACK_BASE + PCM_DMA_BUF_0_PLAYBACK_LEN)
#define PCM_DMA_BUF_0_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_PRIMARY_LEN)

#define PCM_DMA_BUF_1_PLAYBACK_BASE (PCM_DMA_BUF_0_CAPTURE_BASE + PCM_DMA_BUF_0_CAPTURE_LEN)
#define PCM_DMA_BUF_1_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_DIRECT_LEN)
#define PCM_DMA_BUF_1_CAPTURE_BASE  (PCM_DMA_BUF_1_PLAYBACK_BASE + PCM_DMA_BUF_1_PLAYBACK_LEN)
#ifdef CONFIG_HIFI_MEMORY_15M
#define PCM_DMA_BUF_1_CAPTURE_LEN   (PCM_DMA_BUF_CAPTURE_DIRECT_LEN)
#else
#define PCM_DMA_BUF_1_CAPTURE_LEN   (193 * 1024)
#endif

#define PCM_DMA_BUF_2_PLAYBACK_BASE (PCM_DMA_BUF_1_CAPTURE_BASE + PCM_DMA_BUF_1_CAPTURE_LEN)
#define PCM_DMA_BUF_2_PLAYBACK_LEN  (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)
#define PCM_DMA_BUF_2_CAPTURE_BASE  (PCM_DMA_BUF_2_PLAYBACK_BASE + PCM_DMA_BUF_2_PLAYBACK_LEN)
#define PCM_DMA_BUF_2_CAPTURE_LEN   (PCM_DMA_BUF_PLAYBACK_PRIMARY_LEN)

/* mmap device */
#define PCM_DMA_BUF_3_PLAYBACK_BASE (PCM_DMA_BUF_2_CAPTURE_BASE + PCM_DMA_BUF_2_CAPTURE_LEN)
#define PCM_DMA_BUF_3_PLAYBACK_LEN  (PCM_DMA_BUF_MMAP_MAX_SIZE)
#define PCM_DMA_BUF_3_CAPTURE_BASE  (PCM_DMA_BUF_3_PLAYBACK_BASE + PCM_DMA_BUF_3_PLAYBACK_LEN)
#define PCM_DMA_BUF_3_CAPTURE_LEN   (PCM_DMA_BUF_MMAP_MAX_SIZE)

/* spatial audio */
#define PCM_DMA_BUF_4_PLAYBACK_BASE (PCM_DMA_BUF_3_CAPTURE_BASE + PCM_DMA_BUF_3_CAPTURE_LEN)
#define PCM_DMA_BUF_4_PLAYBACK_LEN  (PCM_DMA_BUF_SPATIAL_AUDIO_LEN)
#define PCM_DMA_BUF_4_CAPTURE_BASE  (PCM_DMA_BUF_4_PLAYBACK_BASE + PCM_DMA_BUF_4_PLAYBACK_LEN)
#define PCM_DMA_BUF_4_CAPTURE_LEN   (PCM_DMA_BUF_SPATIAL_AUDIO_CAPTURE_LEN)

#define PCM_DMA_BUF_END_ADDR        (PCM_DMA_BUF_4_CAPTURE_BASE + PCM_DMA_BUF_4_CAPTURE_LEN)

#define DSP_AP_MMAP_OUT_DATA_BASE   (PCM_DMA_BUF_3_PLAYBACK_BASE + 2048)

#endif /* __PHONE_PCM_DMA_BUF_LAYOUT_H__ */
