/**
 * @defgroup  hitls_cookie hitls_cookie.h
 * @ingroup   tls
 * @copyright Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * @brief     TLS COOKIE callback type
 */

#ifndef HITLS_COOKIE_H
#define HITLS_COOKIE_H

#include <stdint.h>
#include "hitls_type.h"

#ifdef __cplusplus
extern "C" {
#endif

#define HITLS_COOKIE_GENERATE_SUCCESS 1       /* Cookie Generated successfully */
#define HITLS_COOKIE_GENERATE_ERROR 0         /* Cookie Generation failed */
#define HITLS_COOKIE_VERIFY_SUCCESS 1         /* Cookie verification succeeded */
#define HITLS_COOKIE_VERIFY_ERROR 0           /* Cookie verification failed */

/**
 * @ingroup hitls_config
 * @brief   Cookie callback prototype generated by the server.
 * @param   ctx  [IN] Ctx context.
 * @param   cookie    [OUT] Cookie written back by the user.
 * @param   cookieLen   [OUT] Cookie length written back by the user.
 * @return  HITLS_COOKIE_GENERATE_SUCCESS, indicates that the generation is successful.
            HITLS_COOKIE_GENERATE_ERROR, indicates that the generation is failed.
 */
typedef int32_t (*HITLS_AppGenCookieCb)(HITLS_Ctx *ctx, uint8_t *cookie, uint32_t *cookieLen);

/**
 * @ingroup hitls_config
 * @brief   The server verifies the cookie callback prototype.
 * @param   ctx  [IN] Ctx context.
 * @param   cookie    [IN] Cookie received by the server.
 * @param   cookieLen   [IN] Cookie length received by the server.
 * @return  HITLS_COOKIE_VERIFY_SUCCESS, indicates that the verification is successful.
            HITLS_COOKIE_VERIFY_ERROR, indicates that the authentication fails.
 */
typedef int32_t (*HITLS_AppVerifyCookieCb)(HITLS_Ctx *ctx, const uint8_t *cookie, uint32_t cookieLen);

/**
 * @ingroup hitls_config
 * @brief   Sets the callback for generating cookies on the server.
 * @param   config  [OUT] Config context.
 * @param   callback    [IN] Cookie generate callback.
 * @return  HITLS_SUCCESS, if successful.
 *          For details about other error codes, see hitls_error.h.
 */
int32_t HITLS_CFG_SetCookieGenCb(HITLS_Config *config, HITLS_AppGenCookieCb callback);

/**
 * @ingroup hitls_config
 * @brief   Set the cookie verification callback on the server.
 * @param   config  [OUT] Config context.
 * @param   callback    [IN] Cookie verification callback.
 * @return  HITLS_SUCCESS, if successful.
 *          For details about other error codes, see hitls_error.h.
 */
int32_t HITLS_CFG_SetCookieVerifyCb(HITLS_Config *config, HITLS_AppVerifyCookieCb callback);

#ifdef __cplusplus
}
#endif

#endif // HITLS_COOKIE_H