obj-$(or $(CONFIG_SCHARGER_V700),$(CONFIG_SCHARGER_V800)) += scharger_coul/
obj-$(CONFIG_COUL_PMIC6X55V500)      += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X21V900)      += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X21BV100)     += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X56V200)      += pmic_coul/
obj-$(CONFIG_COUL_PMIC6X55V800)      += pmic_coul/
obj-y                                += pmic_hrst.o