/* Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved. 
   extract macros used in imocu from the global_ddr_map and iomcu_ddr_map header files
*/

#ifndef __IOMCU_MEM_H__
#define __IOMCU_MEM_H__

#ifdef CONFIG_HEADER_FILE_REPLACE_EXTRACT

#define RESERVED_SENSORHUB_SHMEMEXT_PHYMEM_BASE     	 0x10000000
#define RESERVED_SENSORHUB_SHMEMEXT_PHYMEM_SIZE     	 (0x300000)
#define RESERVED_SENSORHUB_SHMEM_PHYMEM_BASE        	 0x10300000
#define RESERVED_SENSORHUB_SHMEM_PHYMEM_SIZE        	 (0x40000)
#define RESERVED_SENSORHUB_SHARE_MEM_PHYMEM_BASE       	 0x10340000
#define RESERVED_SENSORHUB_SHARE_MEM_PHYMEM_SIZE       	 (0x380000)
#define RESERVED_SENSORHUB_PHYMEM_BASE              	 0x12900000
#define RESERVED_SENSORHUB_PHYMEM_SIZE                 	 (0xD00000)
#define RESERVED_SENSORHUB_SDC_BASE					 	 0x14500000
#define RESERVED_SENSORHUB_SDC_SIZE					 	 (0x100000)
#define DDR_SHMEMEXT_ADDR_AP              			 	 RESERVED_SENSORHUB_SHMEMEXT_PHYMEM_BASE
#define DDR_SHMEMEXT_SIZE                 			 	 RESERVED_SENSORHUB_SHMEMEXT_PHYMEM_SIZE
#define DDR_RESERVE_ADDR_AP                 			 RESERVED_SENSORHUB_PHYMEM_BASE
#define DDR_RESERVE_SIZE                    			 RESERVED_SENSORHUB_PHYMEM_SIZE
#define DDR_SHMEM1_ADDR_AP                  			 RESERVED_SENSORHUB_SHMEM_PHYMEM_BASE
#define DDR_SHMEM1_SIZE                     			 RESERVED_SENSORHUB_SHMEM_PHYMEM_SIZE
#define DDR_SHMEM_ADDR_AP								 RESERVED_SENSORHUB_SHARE_MEM_PHYMEM_BASE
#define DDR_SHMEM_SIZE								 	 RESERVED_SENSORHUB_SHARE_MEM_PHYMEM_SIZE
#define DDR_IOMCU_RESERVED_ADDR_AP         		     	 (DDR_SHMEM_ADDR_AP)
#define DDR_IOMCU_RESERVED_SIZE            		     	 (0x1000)
#define DDR_SHELL_DBG_ADDR_AP              			 	 (DDR_IOMCU_RESERVED_ADDR_AP + DDR_IOMCU_RESERVED_SIZE)
#define DDR_SHELL_DBG_SIZE                 			 	 (0x1000)
#define DDR_CONFIG_ADDR_AP                 			 	 (DDR_SHELL_DBG_ADDR_AP + DDR_SHELL_DBG_SIZE)
#define DDR_CONFIG_SIZE                    			 	 (0x1000)
#define DDR_IMAGE_BASE_AP                  			 	 (DDR_RESERVE_ADDR_AP)
#define DDR_IMAGE_SIZE                     			 	 (0x5FE000)
#define DDR_IMAGE_END_AP                   			 	 (DDR_IMAGE_BASE_AP + DDR_IMAGE_SIZE)
#define DDR_F2L_CONFIG_ADDR_AP             			 	 DDR_IMAGE_END_AP
#define DDR_F2L_CONFIG_SIZE                			 	 (0xFFC)
#define DDR_F2L_CONFIG_END_AP              			 	 (DDR_F2L_CONFIG_ADDR_AP + DDR_F2L_CONFIG_SIZE)
#define DDR_F2L_RANDOM_DATA_AP             			 	 DDR_F2L_CONFIG_END_AP
#define DDR_F2L_RANDOM_DATA_SIZE           			 	 (0x4)
#define DDR_F2L_RANDOM_DATA_END_AP         			 	 (DDR_F2L_RANDOM_DATA_AP + DDR_F2L_RANDOM_DATA_SIZE)
#define DDR_RESERVED_4K_SIZE               			 	 (0x1000)
#define DDR_CODE_BASE_AP                   			 	 DDR_F2L_RANDOM_DATA_END_AP + DDR_RESERVED_4K_SIZE
#define DDR_CODE_SIZE                      			 	 (0x400000)
#define DDR_CODE_END_AP                    			 	 (DDR_CODE_BASE_AP + DDR_CODE_SIZE)
#define DDR_HEAP_START_AP                  			 	 DDR_CODE_END_AP
#define DDR_HEAP_SIZE                      			 	 (0x200000)
#define DDR_HEAP_END_AP                    			 	 (DDR_HEAP_START_AP + DDR_HEAP_SIZE)
#define DDR_IPCNS_SHM_RX_START_AP          			 	 DDR_HEAP_END_AP
#define DDR_IPCNS_SHM_RX_SIZE              			 	 (0x12C00)
#define DDR_IPCNS_SHM_RX_END_AP            			 	 (DDR_IPCNS_SHM_RX_START_AP + DDR_IPCNS_SHM_RX_SIZE)
#define DDR_DTS_CONFIG_ADDR_AP              			 DDR_SHMEM1_ADDR_AP
#define DDR_DTS_CONFIG_SIZE                 			 (0x5000)
#define DDR_THERMAL_SHMEM_PHYMEM_BASE_AP    			 (DDR_DTS_CONFIG_ADDR_AP + DDR_DTS_CONFIG_SIZE)
#define DDR_THERMAL_SHMEM_PHYMEM_SIZE       			 (0x1C00)
#define DDR_LOADMONITOR_PHYMEM_BASE_AP      			 (DDR_THERMAL_SHMEM_PHYMEM_BASE_AP + DDR_THERMAL_SHMEM_PHYMEM_SIZE)
#define DDR_LOADMONITOR_PHYMEM_SIZE         			 (0x1000)
#define DDR_SHMEM_LARGE_BLK_BASE_AP         			 (DDR_LOADMONITOR_PHYMEM_BASE_AP + DDR_LOADMONITOR_PHYMEM_SIZE)
#define DDR_SHMEM_LARGE_BLK_SIZE            			 (DDR_SHMEM1_ADDR_AP + DDR_SHMEM1_SIZE - DDR_SHMEM_LARGE_BLK_BASE_AP)
#define DDR_SHMEM_CH_SEND_ADDR_AP           			 DDR_SHMEM_LARGE_BLK_BASE_AP
#define DDR_SHMEM_CH_SEND_SIZE              			 (DDR_SHMEM_LARGE_BLK_SIZE - DDR_IPCNS_SHM_RX_SIZE)
#define DDR_SHMEM_AP_SEND_ADDR_AP           			 (DDR_SHMEM_CH_SEND_ADDR_AP + DDR_SHMEM_CH_SEND_SIZE)
#define DDR_SHMEM_AP_SEND_SIZE              			 (DDR_IPCNS_SHM_RX_SIZE)
#define DDR_LOG_BUFF_ADDR_AP               			 	 (DDR_CONFIG_ADDR_AP + DDR_CONFIG_SIZE)
#define DDR_LOG_BUFF_SIZE                  		 	 	 (0x7D000)
#define DDR_AOD_BASE_AP                    			 	 (DDR_LOG_BUFF_ADDR_AP + DDR_LOG_BUFF_SIZE)
#define DDR_AOD_SIZE                       			 	 (0x300000)
#define DDR_FLP_BASE_AP                   			 	 DDR_SHMEMEXT_ADDR_AP
#define DDR_FLP_SIZE                      			 	 (0x180000)
#define DDR_FLP_END_AP                    			 	 (DDR_SHMEMEXT_ADDR_AP + DDR_FLP_SIZE)
#define OFFLINE_CELL_MMAP_SIZE            			 	 (0x180000)
#define DDR_DUMP_BASE_AP                   		     	 DDR_FLP_END_AP
#define DDR_DUMP_SIZE                      			 	 (0x100000)
#define DDR_DUMP_END_AP                    			 	 (DDR_DUMP_BASE_AP + DDR_DUMP_SIZE)
#define DDR_JPEGD_LB_BASE_AP               			 	 DDR_DUMP_END_AP
#define DDR_JPEGD_LB_SIZE                  			 	 (0x20000)
#define DDR_JPEGD_LB_END_AP                			 	 (DDR_JPEGD_LB_BASE_AP + DDR_JPEGD_LB_SIZE)
#define DDR_DPU_CMDLIST_BASE_AP            			 	 DDR_JPEGD_LB_END_AP
#define DDR_DPU_CMDLIST_SIZE               			 	 (0x10000)
#define DDR_DPU_CMDLIST_END_AP             			 	 (DDR_DPU_CMDLIST_BASE_AP + DDR_DPU_CMDLIST_SIZE)
#define DDR_IGS_SCAN_CODE_BASE_AP            			 DDR_DPU_CMDLIST_END_AP
#define DDR_IGS_SCAN_CODE_SIZE               			 (0x50000)
#define DDR_IGS_SCAN_CODE_END_AP             			 (DDR_IGS_SCAN_CODE_BASE_AP + DDR_IGS_SCAN_CODE_SIZE)
#define DDR_SHMEM_SDC_ACC_ADDR_AP           			 RESERVED_SENSORHUB_SDC_BASE
#define DDR_SHMEM_SDC_ACC_SIZE              			 0xF000
#define DDR_SHMEM_SDC_MAG_ADDR_AP           			 (DDR_SHMEM_SDC_ACC_ADDR_AP + DDR_SHMEM_SDC_ACC_SIZE)
#define DDR_SHMEM_SDC_MAG_SIZE              			 0xF000
#define DDR_SHMEM_SDC_ORIENTATION_ADDR_AP   			 (DDR_SHMEM_SDC_MAG_ADDR_AP + DDR_SHMEM_SDC_MAG_SIZE)
#define DDR_SHMEM_SDC_ORIENTATION_SIZE      			 0xF000
#define DDR_SHMEM_SDC_GYRO_ADDR_AP          			 (DDR_SHMEM_SDC_ORIENTATION_ADDR_AP + DDR_SHMEM_SDC_ORIENTATION_SIZE)
#define DDR_SHMEM_SDC_GYRO_SIZE             			 0xF000
#define DDR_SHMEM_SDC_LINEAR_ACC_ADDR_AP    			 (DDR_SHMEM_SDC_GYRO_ADDR_AP + DDR_SHMEM_SDC_GYRO_SIZE)
#define DDR_SHMEM_SDC_LINEAR_ACC_SIZE       			 0xF000
#define DDR_SHMEM_SDC_ROTATION_VECTOR_ADDR_AP  		 	 (DDR_SHMEM_SDC_LINEAR_ACC_ADDR_AP + DDR_SHMEM_SDC_LINEAR_ACC_SIZE)
#define DDR_SHMEM_SDC_ROTATION_VECTOR_SIZE  			 0xF000
#define DDR_SHMEM_SDC_GRAVITY_ADDR_AP           		 (DDR_SHMEM_SDC_ROTATION_VECTOR_ADDR_AP + DDR_SHMEM_SDC_ROTATION_VECTOR_SIZE)
#define DDR_SHMEM_SDC_GRAVITY_SIZE              		 0xF000
#define DDR_SHMEM_SDC_MAG_UNCALI_ADDR_AP           	 	 (DDR_SHMEM_SDC_GRAVITY_ADDR_AP + DDR_SHMEM_SDC_GRAVITY_SIZE)
#define DDR_SHMEM_SDC_MAG_UNCALI_SIZE              	 	 0xF000
#define DDR_SHMEM_SDC_GEOMAGNETIC_RV_ADDR_AP           	 (DDR_SHMEM_SDC_MAG_UNCALI_ADDR_AP + DDR_SHMEM_SDC_MAG_UNCALI_SIZE)
#define DDR_SHMEM_SDC_GEOMAGNETIC_RV_SIZE              	 0xF000
#define DDR_SHMEM_SDC_GYRO_UNCALI_ADDR_AP           	 (DDR_SHMEM_SDC_GEOMAGNETIC_RV_ADDR_AP + DDR_SHMEM_SDC_GEOMAGNETIC_RV_SIZE)
#define DDR_SHMEM_SDC_GYRO_UNCALI_SIZE              	 0xF000
#define DDR_SHMEM_SDC_ACC_UNCALI_ADDR_AP           	 	 (DDR_SHMEM_SDC_GYRO_UNCALI_ADDR_AP + DDR_SHMEM_SDC_GYRO_UNCALI_SIZE)
#define DDR_SHMEM_SDC_ACC_UNCALI_SIZE              	 	 0xF000
#define DDR_SHMEM_SDC_ACC1_ADDR_AP           			 (DDR_SHMEM_SDC_ACC_UNCALI_ADDR_AP + DDR_SHMEM_SDC_ACC_UNCALI_SIZE)
#define DDR_SHMEM_SDC_ACC1_SIZE              			 0xF000
#define DDR_SHMEM_SDC_GYRO1_ADDR_AP           		 	 (DDR_SHMEM_SDC_ACC1_ADDR_AP + DDR_SHMEM_SDC_ACC1_SIZE)
#define DDR_SHMEM_SDC_GYRO1_SIZE              	 	 	 0xF000
#define DDR_SHMEM_SDC_ACC2_ADDR_AP           			 (DDR_SHMEM_SDC_GYRO1_ADDR_AP + DDR_SHMEM_SDC_GYRO1_SIZE)
#define DDR_SHMEM_SDC_ACC2_SIZE              			 0xF000
#define DDR_SHMEM_SDC_GYRO2_ADDR_AP           		 	 (DDR_SHMEM_SDC_ACC2_ADDR_AP + DDR_SHMEM_SDC_ACC2_SIZE)
#define DDR_SHMEM_SDC_GYRO2_SIZE              		 	 0xF000
#define DDR_SHMEM_SDC_GAME_RV_ADDR_AP                    (DDR_SHMEM_SDC_GYRO2_ADDR_AP + DDR_SHMEM_SDC_GYRO2_SIZE)
#define DDR_SHMEM_SDC_GAME_RV_SIZE              		 0xF000
#define DDR_SHMEM_SDC_PRESSURE_ADDR_AP           		 (DDR_SHMEM_SDC_GAME_RV_ADDR_AP + DDR_SHMEM_SDC_GAME_RV_SIZE)
#define DDR_SHMEM_SDC_PRESSURE_SIZE              		 0xF000

#endif
#endif