#ifndef UAPI_HMKERNEL_DRIVERS_CPU_INTELLISENSE_COMMON_H
#define UAPI_HMKERNEL_DRIVERS_CPU_INTELLISENSE_COMMON_H
 
#define __CPU_INTELLISENSE_MODULE_NAME "cpu_smart_class"

#define POLICY_CMD_MASK 0xF
#define POLICY_MASK 0xF0
#define POLICY_SHIFT 4

#define __BOOT_POLICY_ENABLE 0x0UL
#define __BOOT_POLICY_CPUMASK 0x1UL
#define __BOOT_POLICY_THRESHOLD 0x2UL
#define __BOOT_POLICY_REPRESSION 0x3UL
#define __BOOT_POLICY_LAZY_DISABLE_CPUMASK 0x4UL

#define __PERIODIC_POLICY_ENABLE 0x0UL
#define __PERIODIC_POLICY_THRESHOLD 0x1UL
#define __PERIODIC_POLICY_CPUMASK 0x2UL
#define __PERIODIC_POLICY_BOUND_UPPER 0x3UL
#define __PERIODIC_POLICY_BOUND_LOWER 0x4UL

#endif