ccflags-y += -I$(srctree)/drivers/dma-buf/heaps/
ccflags-y += -I$(srctree)/platform_source/basicplatform/drivers/dma-buf/heaps/

obj-$(CONFIG_DMABUF_SWAP) += dmabuf_swap.o
obj-$(CONFIG_DMABUF_RECLAIM) += dmabuf_reclaim.o dmabuf_map_info.o
obj-$(CONFIG_DMABUF_RECLAIM_TEST) += dmabuf_reclaim_test.o
