#
# Copyright (c) Hisilicon Technologies Co., Ltd. 2021-2021. All rights reserved.
#

INCLUDE_DIR += \
	-I$(HVGR_PATH)/platform \
	-I$(HVGR_PATH)/platform/$(HVGR_PLATFORM_NAME) \
	-I$(HVGR_PATH)/platform/pdefault

ifeq ($(HVGR_PLATFORM_NAME), p0000301)
	SRC += \
		$(HVGR_ROOT)/platform/hvgr_smc.c \
		$(HVGR_ROOT)/platform/hvgr_ffa.c
else ifeq ($(HVGR_PLATFORM_NAME), p0000000)
	SRC += \
		$(HVGR_ROOT)/platform/hvgr_smc.c
else
	SRC += \
		$(HVGR_ROOT)/platform/hvgr_ffa.c
endif

include $(HVGR_PATH)/platform/pdefault/Kbuild
include $(HVGR_PATH)/platform/$(HVGR_PLATFORM_NAME)/Kbuild
