add_hm_library(hm_mem.c)
add_hm_library(hm_ashm.c)
add_hm_library(hm_kshm.c)
add_hm_library(hm_procmgr.c)
add_hm_library(hm_signal.c)
add_hm_library(hm_hmsignal.c)
add_hm_library(hmsrv_sys.c)
add_hm_library(hm_mqueue.c)
add_hm_library(hm_path.c)
add_hm_library(hm_thread.c)
add_hm_library(hm_timer.c)
add_hm_library(hm_timer_kernel_space.c)
add_hm_library(hm_sysctrl.c)
add_hm_library(hm_timer_utils.c)
add_hm_library(hm_timer_utils_public.c)
add_hm_library(hm_futex.c)
add_hm_library(hm_security.c)
add_hm_library(hm_uvmm.c)
add_hm_library(hm_vm.c)
add_hm_library(hm_select_common.c)
add_hm_library(hm_ipc_shm.c)
add_hm_library(hm_log.c)
add_hm_library(hm_ipc_msg.c)
add_hm_library(hm_ipc_sem.c)
add_hm_library(hm_module.c)
add_hm_library(hm_dump.c)
add_hm_library(hm_atfork.c)
add_hm_library(hm_inject_fault.c)
add_hm_library(hm_ct_task.c)
add_hm_library(hm_init.c)
add_hm_library(hm_watchdog.c)
add_hm_library(hm_proc_affinity.c)
add_hm_library(hm_idle_state.c)
add_hm_library(hm_vdso.c)
add_hm_library(hm_livepatch.c)
add_hm_library(hm_hkip.c)

append_src_flag(hm_signal.c "-D_GNU_SOURCE -Wno-strict-prototypes")
append_src_flag(hm_procmgr.c "-D_GNU_SOURCE -Wno-strict-prototypes")
append_src_flag(hm_mem.c "-D_GNU_SOURCE -Wno-strict-prototypes")
append_src_flag(hm_ipc_msg.c "-D_GNU_SOURCE -Wno-strict-prototypes")
append_src_flag(hm_proc_affinity.c "-D_GNU_SOURCE -Wno-strict-prototypes")
