/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: ctrlmem system call related defeinitions
 * Author: Huawei OS Kernel Lab
 * Create: Tue Jun 27 14:57:26 2023
 */

#ifndef MAPI_UAPI_HMKERNEL_CTRLMEM_SYSCALLS_H
#define MAPI_UAPI_HMKERNEL_CTRLMEM_SYSCALLS_H

#define __CTRLMEM_SYSCALL_UNKNOWN		0U
#define __CTRLMEM_SYSCALL_MAP_PGVA		1U
#define __CTRLMEM_SYSCALL_CLEAR_ABIT		2U
#define __CTRLMEM_SYSCALL_CLEAN_SET_KOBJVS	3U
#define __CTRLMEM_SYSCALL_REMAP_PGVA_KOBJVS	4U
#define __CTRLMEM_SYSCALL_MAP_PGSTRVA		5U
#define __CTRLMEM_SYSCALL_BATCH_MAP_PGVA	6U
#define __CTRLMEM_SYSCALL_TLBGATHER_UNMAP	7U
#define __CTRLMEM_SYSCALL_BATCH_TLBG_UNMAP	8U
#define __CTRLMEM_SYSCALL_RANGE_MPROTECT	9U
#define __CTRLMEM_SYSCALL_RANGE_MUNMAP		10U
#define __CTRLMEM_SYSCALL_RANGE_VSCPY		11U
#define __CTRLMEM_SYSCALL_VSMKDEAD		12U
#define __CTRLMEM_SYSCALL_CHANNELPG_UNLOCK	13U
#define __CTRLMEM_SYSCALL_PGSTR_NML2IOFA	14U
#define __CTRLMEM_SYSCALL_MAX			15U

#endif
