obj-$(CONFIG_PERF_INTERNAL_PROFILING) := internal-profiling/perf.o
obj-$(CONFIG_PERF_INTERNAL_PROFILING) += internal-profiling/arm_pmu_common.o
obj-$(CONFIG_AARCH64_PMUV3) += pmuv3.o
obj-$(CONFIG_ARM_PMUV1) += pmuv1.o
obj-$(CONFIG_AARCH64_DSU) += dsu_pmu.o
obj-y += perf.o
obj-y += proc_maps.o
