/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: Hmseharmony header file for class bitmap
 * Author: Huawei OS Kernel Lab
 * Create: Mon June 05 11:49:29 2023
 */
#ifndef CLASS_BITMAP_SYSMGR_H
#define CLASS_BITMAP_SYSMGR_H

CLASS_SET(HM_SECCLASS_CAPABILITY);
CLASS_SET(HM_SECCLASS_CAPABILITY2);
CLASS_SET(HM_SECCLASS_CAP_USERNS);
CLASS_SET(HM_SECCLASS_CAP2_USERNS);
CLASS_SET(HM_SECCLASS_FILE);
CLASS_SET(HM_SECCLASS_PROCESS);
CLASS_SET(HM_SECCLASS_PROCESS2);
CLASS_SET(HM_SECCLASS_MSG);
CLASS_SET(HM_SECCLASS_MSGQ);
CLASS_SET(HM_SECCLASS_SEM);
CLASS_SET(HM_SECCLASS_SHM);
CLASS_SET(HM_SECCLASS_SYSTEM);
CLASS_SET(HM_SECCLASS_MEMPROTECT);
CLASS_SET(HM_SECCLASS_XPM);
CLASS_SET(HM_SECCLASS_PERF_EVENT);
CLASS_SET(HM_SECCLASS_UNIX_DGRAM_SOCKET);
CLASS_SET(HM_SECCLASS_UNIX_STREAM_SOCKET);
CLASS_SET(HM_SECCLASS_HMCAP);

#endif
