/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: Hmseharmony header file for class bitmap
 * Author: Huawei OS Kernel Lab
 * Create: Mon June 05 11:49:29 2023
 */
#ifndef CLASS_BITMAP_VFS_H
#define CLASS_BITMAP_VFS_H

CLASS_SET(HM_SECCLASS_CAPABILITY);
CLASS_SET(HM_SECCLASS_CAPABILITY2);
CLASS_SET(HM_SECCLASS_CAP_USERNS);
CLASS_SET(HM_SECCLASS_CAP2_USERNS);
CLASS_SET(HM_SECCLASS_FILESYSTEM);
CLASS_SET(HM_SECCLASS_DIR);
CLASS_SET(HM_SECCLASS_FD);
CLASS_SET(HM_SECCLASS_FILE);
CLASS_SET(HM_SECCLASS_SOCK_FILE);
CLASS_SET(HM_SECCLASS_LNK_FILE);
CLASS_SET(HM_SECCLASS_BLK_FILE);
CLASS_SET(HM_SECCLASS_CHR_FILE);
CLASS_SET(HM_SECCLASS_FIFO_FILE);
CLASS_SET(HM_SECCLASS_PROCESS);
CLASS_SET(HM_SECCLASS_BINDER);
CLASS_SET(HM_SECCLASS_XPM);
CLASS_SET(HM_SECCLASS_CODE_SIGN);
CLASS_SET(HM_SECCLASS_SECURITY);
CLASS_SET(HM_SECCLASS_HMCAP);
#endif
