/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: Hmseharmony header file for class bitmap
 * Author: Huawei OS Kernel Lab
 * Create: Mon June 05 11:49:29 2023
 */
#ifndef CLASS_BITMAP_DEVHOST_H
#define CLASS_BITMAP_DEVHOST_H

CLASS_SET(HM_SECCLASS_CAPABILITY);
CLASS_SET(HM_SECCLASS_CAPABILITY2);
CLASS_SET(HM_SECCLASS_CAP_USERNS);
CLASS_SET(HM_SECCLASS_CAP2_USERNS);
CLASS_SET(HM_SECCLASS_SECURITY);
CLASS_SET(HM_SECCLASS_CHR_FILE);
CLASS_SET(HM_SECCLASS_FD);
CLASS_SET(HM_SECCLASS_DMAHEAP);

#endif
