obj-$(CONFIG_HW_SMARTCOM_NSTACK) += nstack.o
obj-$(CONFIG_HW_SMARTCOM_NSTACK) += fi/
obj-$(CONFIG_HW_NSTACK_MINTP) += mintp/mintp.o mintp/mintp_congestion.o mintp/mintp_conn.o mintp/mintp_input.o mintp/mintp_output.o mintp/mintp_rack.o mintp/mintp_timer.o mintp/mintp_tls.o mintp/mintp_rate.o mintp/mintp_opt.o
obj-$(CONFIG_HW_SMARTCOM_NSTACK) += dnet/
