/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2025. All rights reserved.
 * Description: seccomp
 * Author: Huawei OS Kernel Lab
 * Create: Tue Apr 29 01:09:43 2025
 */

#ifndef HMKERNEL_ACTIVATION_SECCOMP_H
#define HMKERNEL_ACTIVATION_SECCOMP_H

#define MAX_SECCOMP_ARGS	6

#define HM_SECCOMP_ARM		40
#define HM_SECCOMP_AARCH64	183
#define HM_SECCOMP_ARCH_64BIT	0x80000000
#define HM_SECCOMP_ARCH_LE	0x40000000
#define HM_SECCOMP_ARCH_AARCH64	(HM_SECCOMP_AARCH64 | HM_SECCOMP_ARCH_64BIT | HM_SECCOMP_ARCH_LE)
#define HM_SECCOMP_ARCH_ARM	( HM_SECCOMP_ARM | HM_SECCOMP_ARCH_LE)

#ifdef CONFIG_AARCH64
#define HM_SECCOMP_ARCH_NATIVE	HM_SECCOMP_ARCH_AARCH64
#ifdef CONFIG_COMPAT
#define HM_SECCOMP_ARCH_COMPAT	HM_SECCOMP_ARCH_ARM
#endif
#else /* !CONFIG_AARCH64 */
#define HM_SECCOMP_ARCH_NATIVE	HM_SECCOMP_ARCH_ARM
#endif

#endif
