/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2022-2024. All rights reserved.
 * Author: Huawei Dresden Research Center
 * WARNING: file generated automatically. Please do not modify manually.
 */
#ifndef VSYNC_ATOMIC_MAPPING_H
#define VSYNC_ATOMIC_MAPPING_H
/*******************************************************************************
 * @file compat.h
 * @brief Set of functions backward compatible with libvsync 1.0
 *
 * check atomic.h for detailed documentation. Compat is only available for
 * `atomic32_t`, `atomic64_t` and `atomicptr_t`, which map to
 * `vatomic32_t`, `vatomic64_t` and `vatomicptr_t` respectively.
 *
 *
 * These functions are deprecated. Please, use the new vatomic interface.
 ******************************************************************************/

#define ATOMIC_INIT(v) VATOMIC_INIT(v)

#define atomic_t vatomic32_t
#define atomic32_t vatomic32_t
#define atomic64_t vatomic64_t
#define atomicptr_t vatomicptr_t

#define atomic32_add(a, v) vatomic32_add_get(a, v)
#define atomic_add(a, v) vatomic32_add_get(a, v)
#define atomic32_add_rel(a, v) vatomic32_add_get_rel(a, v)
#define atomic_add_rel(a, v) vatomic32_add_get_rel(a, v)
#define atomic32_add_rlx(a, v) vatomic32_add_get_rlx(a, v)
#define atomic_add_rlx(a, v) vatomic32_add_get_rlx(a, v)
#define atomic32_and(a, v) vatomic32_and_get(a, v)
#define atomic_and(a, v) vatomic32_and_get(a, v)
#define atomic32_and_rel(a, v) vatomic32_and_get_rel(a, v)
#define atomic_and_rel(a, v) vatomic32_and_get_rel(a, v)
#define atomic32_and_rlx(a, v) vatomic32_and_get_rlx(a, v)
#define atomic_and_rlx(a, v) vatomic32_and_get_rlx(a, v)

#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic_await_counter_neq(a, v, c) vatomic32_await_counter_neq(a, v, c)
#define atomic32_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic_await_counter_neq_acq(a, v, c) \
	vatomic32_await_counter_neq_acq(a, v, c)
#define atomic32_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic_await_counter_neq_rlx(a, v, c) \
	vatomic32_await_counter_neq_rlx(a, v, c)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic_await_mask_neq(a, v, mask) vatomic32_await_mask_neq(a, v, mask)
#define atomic32_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic_await_mask_neq_acq(a, v, mask) \
	vatomic32_await_mask_neq_acq(a, v, mask)
#define atomic32_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic_await_mask_neq_rlx(a, v, mask) \
	vatomic32_await_mask_neq_rlx(a, v, mask)
#define atomic32_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic_await_ge(a, v) vatomic32_await_ge(a, v)
#define atomic32_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic_await_ge_acq(a, v) vatomic32_await_ge_acq(a, v)
#define atomic32_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic_await_neq_add(a, c, v) vatomic32_await_neq_add(a, c, v)
#define atomic32_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic_await_neq_add_acq(a, c, v) vatomic32_await_neq_add_acq(a, c, v)
#define atomic32_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic_await_neq_add_rel(a, c, v) vatomic32_await_neq_add_rel(a, c, v)
#define atomic32_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic_await_neq_add_rlx(a, c, v) vatomic32_await_neq_add_rlx(a, c, v)
#define atomic32_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic_await_ge_rlx(a, v) vatomic32_await_ge_rlx(a, v)
#define atomic32_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic_await_neq_set(a, c, v) vatomic32_await_neq_set(a, c, v)
#define atomic32_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic_await_neq_set_acq(a, c, v) vatomic32_await_neq_set_acq(a, c, v)
#define atomic32_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic_await_neq_set_rel(a, c, v) vatomic32_await_neq_set_rel(a, c, v)
#define atomic32_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic_await_neq_set_rlx(a, c, v) vatomic32_await_neq_set_rlx(a, c, v)
#define atomic32_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic_await_neq_sub(a, c, v) vatomic32_await_neq_sub(a, c, v)
#define atomic32_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic_await_neq_sub_acq(a, c, v) vatomic32_await_neq_sub_acq(a, c, v)
#define atomic32_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic_await_neq_sub_rel(a, c, v) vatomic32_await_neq_sub_rel(a, c, v)
#define atomic32_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic_await_neq_sub_rlx(a, c, v) vatomic32_await_neq_sub_rlx(a, c, v)
#define atomic32_cmpxchg(a, exp, v) vatomic32_cmpxchg(a, exp, v)
#define atomic_cmpxchg(a, exp, v) vatomic32_cmpxchg(a, exp, v)
#define atomic32_cmpxchg_acq(a, exp, v) vatomic32_cmpxchg_acq(a, exp, v)
#define atomic_cmpxchg_acq(a, exp, v) vatomic32_cmpxchg_acq(a, exp, v)
#define atomic32_cmpxchg_rel(a, exp, v) vatomic32_cmpxchg_rel(a, exp, v)
#define atomic_cmpxchg_rel(a, exp, v) vatomic32_cmpxchg_rel(a, exp, v)
#define atomic32_cmpxchg_rlx(a, exp, v) vatomic32_cmpxchg_rlx(a, exp, v)
#define atomic_cmpxchg_rlx(a, exp, v) vatomic32_cmpxchg_rlx(a, exp, v)

#define atomic32_dec(a) vatomic32_dec_get(a)
#define atomic_dec(a) vatomic32_dec_get(a)

#define atomic32_dec_rel(a) vatomic32_dec_get_rel(a)
#define atomic_dec_rel(a) vatomic32_dec_get_rel(a)
#define atomic32_dec_rlx(a) vatomic32_dec_get_rlx(a)
#define atomic_dec_rlx(a) vatomic32_dec_get_rlx(a)

#define atomic32_get_add(a, v) vatomic32_get_add(a, v)
#define atomic_get_add(a, v) vatomic32_get_add(a, v)
#define atomic32_get_add_acq(a, v) vatomic32_get_add_acq(a, v)
#define atomic_get_add_acq(a, v) vatomic32_get_add_acq(a, v)
#define atomic32_get_add_rel(a, v) vatomic32_get_add_rel(a, v)
#define atomic_get_add_rel(a, v) vatomic32_get_add_rel(a, v)
#define atomic32_get_add_rlx(a, v) vatomic32_get_add_rlx(a, v)
#define atomic_get_add_rlx(a, v) vatomic32_get_add_rlx(a, v)
#define atomic32_get_and(a, v) vatomic32_get_and(a, v)
#define atomic_get_and(a, v) vatomic32_get_and(a, v)
#define atomic32_get_and_acq(a, v) vatomic32_get_and_acq(a, v)
#define atomic_get_and_acq(a, v) vatomic32_get_and_acq(a, v)
#define atomic32_get_and_rel(a, v) vatomic32_get_and_rel(a, v)
#define atomic_get_and_rel(a, v) vatomic32_get_and_rel(a, v)
#define atomic32_get_and_rlx(a, v) vatomic32_get_and_rlx(a, v)
#define atomic_get_and_rlx(a, v) vatomic32_get_and_rlx(a, v)
#define atomic32_get_dec(a) vatomic32_get_dec(a)
#define atomic_get_dec(a) vatomic32_get_dec(a)
#define atomic32_get_dec_acq(a) vatomic32_get_dec_acq(a)
#define atomic_get_dec_acq(a) vatomic32_get_dec_acq(a)
#define atomic32_get_dec_rel(a) vatomic32_get_dec_rel(a)
#define atomic_get_dec_rel(a) vatomic32_get_dec_rel(a)
#define atomic32_get_dec_rlx(a) vatomic32_get_dec_rlx(a)
#define atomic_get_dec_rlx(a) vatomic32_get_dec_rlx(a)
#define atomic32_get_inc(a) vatomic32_get_inc(a)
#define atomic_get_inc(a) vatomic32_get_inc(a)
#define atomic32_get_inc_acq(a) vatomic32_get_inc_acq(a)
#define atomic_get_inc_acq(a) vatomic32_get_inc_acq(a)
#define atomic32_get_inc_rel(a) vatomic32_get_inc_rel(a)
#define atomic_get_inc_rel(a) vatomic32_get_inc_rel(a)
#define atomic32_get_inc_rlx(a) vatomic32_get_inc_rlx(a)
#define atomic_get_inc_rlx(a) vatomic32_get_inc_rlx(a)
#define atomic32_get_max(a, v) vatomic32_get_max(a, v)
#define atomic_get_max(a, v) vatomic32_get_max(a, v)
#define atomic32_get_max_acq(a, v) vatomic32_get_max_acq(a, v)
#define atomic_get_max_acq(a, v) vatomic32_get_max_acq(a, v)
#define atomic32_get_max_rel(a, v) vatomic32_get_max_rel(a, v)
#define atomic_get_max_rel(a, v) vatomic32_get_max_rel(a, v)
#define atomic32_get_max_rlx(a, v) vatomic32_get_max_rlx(a, v)
#define atomic_get_max_rlx(a, v) vatomic32_get_max_rlx(a, v)
#define atomic32_get_or(a, v) vatomic32_get_or(a, v)
#define atomic_get_or(a, v) vatomic32_get_or(a, v)
#define atomic32_get_or_acq(a, v) vatomic32_get_or_acq(a, v)
#define atomic_get_or_acq(a, v) vatomic32_get_or_acq(a, v)
#define atomic32_get_or_rel(a, v) vatomic32_get_or_rel(a, v)
#define atomic_get_or_rel(a, v) vatomic32_get_or_rel(a, v)
#define atomic32_get_or_rlx(a, v) vatomic32_get_or_rlx(a, v)
#define atomic_get_or_rlx(a, v) vatomic32_get_or_rlx(a, v)
#define atomic32_get_sub(a, v) vatomic32_get_sub(a, v)
#define atomic_get_sub(a, v) vatomic32_get_sub(a, v)
#define atomic32_get_sub_acq(a, v) vatomic32_get_sub_acq(a, v)
#define atomic_get_sub_acq(a, v) vatomic32_get_sub_acq(a, v)
#define atomic32_get_sub_rel(a, v) vatomic32_get_sub_rel(a, v)
#define atomic_get_sub_rel(a, v) vatomic32_get_sub_rel(a, v)
#define atomic32_get_sub_rlx(a, v) vatomic32_get_sub_rlx(a, v)
#define atomic_get_sub_rlx(a, v) vatomic32_get_sub_rlx(a, v)
#define atomic32_get_xor(a, v) vatomic32_get_xor(a, v)
#define atomic_get_xor(a, v) vatomic32_get_xor(a, v)
#define atomic32_get_xor_acq(a, v) vatomic32_get_xor_acq(a, v)
#define atomic_get_xor_acq(a, v) vatomic32_get_xor_acq(a, v)
#define atomic32_get_xor_rel(a, v) vatomic32_get_xor_rel(a, v)
#define atomic_get_xor_rel(a, v) vatomic32_get_xor_rel(a, v)
#define atomic32_get_xor_rlx(a, v) vatomic32_get_xor_rlx(a, v)
#define atomic_get_xor_rlx(a, v) vatomic32_get_xor_rlx(a, v)

#define atomic32_inc(a) vatomic32_inc_get(a)
#define atomic_inc(a) vatomic32_inc_get(a)
#define atomic32_inc_rel(a) vatomic32_inc_get_rel(a)
#define atomic_inc_rel(a) vatomic32_inc_get_rel(a)
#define atomic32_inc_rlx(a) vatomic32_inc_get_rlx(a)
#define atomic_inc_rlx(a) vatomic32_inc_get_rlx(a)

#ifndef atomic_init
#define atomic_init(a, v) vatomic32_init(a, v)
#endif

#define atomic32_init(a, v) vatomic32_init(a, v)
#define atomic32_max(a, v) vatomic32_max_get(a, v)
#define atomic_max(a, v) vatomic32_max_get(a, v)

#define atomic32_max_rel(a, v) vatomic32_max_get_rel(a, v)
#define atomic_max_rel(a, v) vatomic32_max_get_rel(a, v)
#define atomic32_max_rlx(a, v) vatomic32_max_get_rlx(a, v)
#define atomic_max_rlx(a, v) vatomic32_max_get_rlx(a, v)

#define atomic32_or(a, v) vatomic32_or_get(a, v)
#define atomic_or(a, v) vatomic32_or_get(a, v)
#define atomic32_or_rel(a, v) vatomic32_or_get_rel(a, v)
#define atomic_or_rel(a, v) vatomic32_or_get_rel(a, v)
#define atomic32_or_rlx(a, v) vatomic32_or_get_rlx(a, v)
#define atomic_or_rlx(a, v) vatomic32_or_get_rlx(a, v)

#define atomic32_read(a) vatomic32_read(a)
#define atomic_read(a) vatomic32_read(a)
#define atomic32_read_acq(a) vatomic32_read_acq(a)
#define atomic_read_acq(a) vatomic32_read_acq(a)
#define atomic32_read_rlx(a) vatomic32_read_rlx(a)
#define atomic_read_rlx(a) vatomic32_read_rlx(a)

#define atomic32_sub(a, v) vatomic32_sub_get(a, v)
#define atomic_sub(a, v) vatomic32_sub_get(a, v)
#define atomic32_sub_rel(a, v) vatomic32_sub_get_rel(a, v)
#define atomic_sub_rel(a, v) vatomic32_sub_get_rel(a, v)
#define atomic32_sub_rlx(a, v) vatomic32_sub_get_rlx(a, v)
#define atomic_sub_rlx(a, v) vatomic32_sub_get_rlx(a, v)

#define atomic32_write(a, v) vatomic32_write(a, v)
#define atomic_write(a, v) vatomic32_write(a, v)
#define atomic32_write_rel(a, v) vatomic32_write_rel(a, v)
#define atomic_write_rel(a, v) vatomic32_write_rel(a, v)
#define atomic32_write_rlx(a, v) vatomic32_write_rlx(a, v)
#define atomic_write_rlx(a, v) vatomic32_write_rlx(a, v)

#define atomic32_xchg(a, v) vatomic32_xchg(a, v)
#define atomic_xchg(a, v) vatomic32_xchg(a, v)
#define atomic32_xchg_acq(a, v) vatomic32_xchg_acq(a, v)
#define atomic_xchg_acq(a, v) vatomic32_xchg_acq(a, v)
#define atomic32_xchg_rel(a, v) vatomic32_xchg_rel(a, v)
#define atomic_xchg_rel(a, v) vatomic32_xchg_rel(a, v)
#define atomic32_xchg_rlx(a, v) vatomic32_xchg_rlx(a, v)
#define atomic_xchg_rlx(a, v) vatomic32_xchg_rlx(a, v)
#define atomic32_xor(a, v) vatomic32_xor_get(a, v)
#define atomic_xor(a, v) vatomic32_xor_get(a, v)
#define atomic32_xor_rel(a, v) vatomic32_xor_get_rel(a, v)
#define atomic_xor_rel(a, v) vatomic32_xor_get_rel(a, v)
#define atomic32_xor_rlx(a, v) vatomic32_xor_get_rlx(a, v)
#define atomic_xor_rlx(a, v) vatomic32_xor_get_rlx(a, v)
#define atomic64_add(a, v) vatomic64_add_get(a, v)
#define atomic64_add_rel(a, v) vatomic64_add_get_rel(a, v)
#define atomic64_add_rlx(a, v) vatomic64_add_get_rlx(a, v)
#define atomic64_and(a, v) vatomic64_and_get(a, v)
#define atomic64_and_rel(a, v) vatomic64_and_get_rel(a, v)
#define atomic64_and_rlx(a, v) vatomic64_and_get_rlx(a, v)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_counter_neq(a, v, c) vatomic64_await_counter_neq(a, v, c)
#define atomic64_await_counter_neq_acq(a, v, c) \
	vatomic64_await_counter_neq_acq(a, v, c)
#define atomic64_await_counter_neq_rlx(a, v, c) \
	vatomic64_await_counter_neq_rlx(a, v, c)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_mask_neq(a, v, mask) vatomic64_await_mask_neq(a, v, mask)
#define atomic64_await_mask_neq_acq(a, v, mask) \
	vatomic64_await_mask_neq_acq(a, v, mask)
#define atomic64_await_mask_neq_rlx(a, v, mask) \
	vatomic64_await_mask_neq_rlx(a, v, mask)
#define atomic64_await_ge(a, v) vatomic64_await_ge(a, v)
#define atomic64_await_ge_acq(a, v) vatomic64_await_ge_acq(a, v)
#define atomic64_await_neq_add(a, c, v) vatomic64_await_neq_add(a, c, v)
#define atomic64_await_neq_add_acq(a, c, v) vatomic64_await_neq_add_acq(a, c, v)
#define atomic64_await_neq_add_rel(a, c, v) vatomic64_await_neq_add_rel(a, c, v)
#define atomic64_await_neq_add_rlx(a, c, v) vatomic64_await_neq_add_rlx(a, c, v)
#define atomic64_await_ge_rlx(a, v) vatomic64_await_ge_rlx(a, v)
#define atomic64_await_neq_set(a, c, v) vatomic64_await_neq_set(a, c, v)
#define atomic64_await_neq_set_acq(a, c, v) vatomic64_await_neq_set_acq(a, c, v)
#define atomic64_await_neq_set_rel(a, c, v) vatomic64_await_neq_set_rel(a, c, v)
#define atomic64_await_neq_set_rlx(a, c, v) vatomic64_await_neq_set_rlx(a, c, v)
#define atomic64_await_neq_sub(a, c, v) vatomic64_await_neq_sub(a, c, v)
#define atomic64_await_neq_sub_acq(a, c, v) vatomic64_await_neq_sub_acq(a, c, v)
#define atomic64_await_neq_sub_rel(a, c, v) vatomic64_await_neq_sub_rel(a, c, v)
#define atomic64_await_neq_sub_rlx(a, c, v) vatomic64_await_neq_sub_rlx(a, c, v)
#define atomic64_cmpxchg(a, exp, v) vatomic64_cmpxchg(a, exp, v)
#define atomic64_cmpxchg_acq(a, exp, v) vatomic64_cmpxchg_acq(a, exp, v)
#define atomic64_cmpxchg_rel(a, exp, v) vatomic64_cmpxchg_rel(a, exp, v)
#define atomic64_cmpxchg_rlx(a, exp, v) vatomic64_cmpxchg_rlx(a, exp, v)
#define atomic64_dec(a) vatomic64_dec_get(a)
#define atomic64_dec_rel(a) vatomic64_dec_get_rel(a)
#define atomic64_dec_rlx(a) vatomic64_dec_get_rlx(a)

#define atomic64_get_add(a, v) vatomic64_get_add(a, v)
#define atomic64_get_add_acq(a, v) vatomic64_get_add_acq(a, v)
#define atomic64_get_add_rel(a, v) vatomic64_get_add_rel(a, v)
#define atomic64_get_add_rlx(a, v) vatomic64_get_add_rlx(a, v)
#define atomic64_get_and(a, v) vatomic64_get_and(a, v)
#define atomic64_get_and_acq(a, v) vatomic64_get_and_acq(a, v)
#define atomic64_get_and_rel(a, v) vatomic64_get_and_rel(a, v)
#define atomic64_get_and_rlx(a, v) vatomic64_get_and_rlx(a, v)
#define atomic64_get_dec(a) vatomic64_get_dec(a)
#define atomic64_get_dec_acq(a) vatomic64_get_dec_acq(a)
#define atomic64_get_dec_rel(a) vatomic64_get_dec_rel(a)
#define atomic64_get_dec_rlx(a) vatomic64_get_dec_rlx(a)
#define atomic64_get_inc(a) vatomic64_get_inc(a)
#define atomic64_get_inc_acq(a) vatomic64_get_inc_acq(a)
#define atomic64_get_inc_rel(a) vatomic64_get_inc_rel(a)
#define atomic64_get_inc_rlx(a) vatomic64_get_inc_rlx(a)
#define atomic64_get_max(a, v) vatomic64_get_max(a, v)
#define atomic64_get_max_acq(a, v) vatomic64_get_max_acq(a, v)
#define atomic64_get_max_rel(a, v) vatomic64_get_max_rel(a, v)
#define atomic64_get_max_rlx(a, v) vatomic64_get_max_rlx(a, v)
#define atomic64_get_or(a, v) vatomic64_get_or(a, v)
#define atomic64_get_or_acq(a, v) vatomic64_get_or_acq(a, v)
#define atomic64_get_or_rel(a, v) vatomic64_get_or_rel(a, v)
#define atomic64_get_or_rlx(a, v) vatomic64_get_or_rlx(a, v)
#define atomic64_get_sub(a, v) vatomic64_get_sub(a, v)
#define atomic64_get_sub_acq(a, v) vatomic64_get_sub_acq(a, v)
#define atomic64_get_sub_rel(a, v) vatomic64_get_sub_rel(a, v)
#define atomic64_get_sub_rlx(a, v) vatomic64_get_sub_rlx(a, v)
#define atomic64_get_xor(a, v) vatomic64_get_xor(a, v)
#define atomic64_get_xor_acq(a, v) vatomic64_get_xor_acq(a, v)
#define atomic64_get_xor_rel(a, v) vatomic64_get_xor_rel(a, v)
#define atomic64_get_xor_rlx(a, v) vatomic64_get_xor_rlx(a, v)
#define atomic64_inc(a) vatomic64_inc_get(a)

#define atomic64_inc_rel(a) vatomic64_inc_get_rel(a)
#define atomic64_inc_rlx(a) vatomic64_inc_get_rlx(a)
#define atomic64_init(a, v) vatomic64_init(a, v)
#define atomic64_max(a, v) vatomic64_max_get(a, v)
#define atomic64_max_rel(a, v) vatomic64_max_get_rel(a, v)
#define atomic64_max_rlx(a, v) vatomic64_max_get_rlx(a, v)
#define atomic64_or(a, v) vatomic64_or_get(a, v)
#define atomic64_or_rel(a, v) vatomic64_or_rel(a, v)
#define atomic64_or_rlx(a, v) vatomic64_or_rlx(a, v)
#define atomic64_read(a) vatomic64_read(a)
#define atomic64_read_acq(a) vatomic64_read_acq(a)
#define atomic64_read_rlx(a) vatomic64_read_rlx(a)

#define atomic64_sub(a, v) vatomic64_sub_get(a, v)
#define atomic64_sub_rel(a, v) vatomic64_sub_get_rel(a, v)
#define atomic64_sub_rlx(a, v) vatomic64_sub_get_rlx(a, v)

#define atomic64_write(a, v) vatomic64_write(a, v)
#define atomic64_write_rel(a, v) vatomic64_write_rel(a, v)
#define atomic64_write_rlx(a, v) vatomic64_write_rlx(a, v)

#define atomic64_xchg(a, v) vatomic64_xchg(a, v)
#define atomic64_xchg_acq(a, v) vatomic64_xchg_acq(a, v)
#define atomic64_xchg_rel(a, v) vatomic64_xchg_rel(a, v)
#define atomic64_xchg_rlx(a, v) vatomic64_xchg_rlx(a, v)

#define atomic64_xor(a, v) vatomic64_xor_get(a, v)
#define atomic64_xor_rel(a, v) vatomic64_xor_get_rel(a, v)
#define atomic64_xor_rlx(a, v) vatomic64_xor_get_rlx(a, v)

#define atomic_fence() vatomic_fence()
#define atomic_fence_acq() vatomic_fence_acq()
#define atomic_fence_rel() vatomic_fence_rel()
#define atomic_fence_rlx() vatomic_fence_rlx()
#define atomicptr_await_counter_neq(a, v, c) \
	vatomicptr_await_counter_neq(a, v, c)
#define atomicptr_await_counter_neq_acq(a, v, c) \
	vatomicptr_await_counter_neq_acq(a, v, c)
#define atomicptr_await_counter_neq_rlx(a, v, c) \
	vatomicptr_await_counter_neq_rlx(a, v, c)
#define atomicptr_await_counter_neq(a, v, c) \
	vatomicptr_await_counter_neq(a, v, c)
#define atomicptr_await_counter_neq_acq(a, v, c) \
	vatomicptr_await_counter_neq_acq(a, v, c)
#define atomicptr_await_counter_neq_rlx(a, v, c) \
	vatomicptr_await_counter_neq_rlx(a, v, c)
#define atomicptr_await_neq(a, v) vatomicptr_await_neq(a, v)
#define atomicptr_await_neq_acq(a, v) vatomicptr_await_neq_acq(a, v)
#define atomicptr_await_neq_rlx(a, v) vatomicptr_await_neq_rlx(a, v)
#define atomicptr_await_neq_set(a, c, v) vatomicptr_await_neq_set(a, c, v)
#define atomicptr_await_neq_set_acq(a, c, v) \
	vatomicptr_await_neq_set_acq(a, c, v)
#define atomicptr_await_neq_set_rel(a, c, v) \
	vatomicptr_await_neq_set_rel(a, c, v)
#define atomicptr_await_neq_set_rlx(a, c, v) \
	vatomicptr_await_neq_set_rlx(a, c, v)
#define atomicptr_await_neq(a, v) vatomicptr_await_neq(a, v)
#define atomicptr_await_neq_acq(a, v) vatomicptr_await_neq_acq(a, v)
#define atomicptr_await_neq_rlx(a, v) vatomicptr_await_neq_rlx(a, v)
#define atomicptr_await_neq_set(a, c, v) vatomicptr_await_neq_set(a, c, v)
#define atomicptr_await_neq_set_acq(a, c, v) \
	vatomicptr_await_neq_set_acq(a, c, v)
#define atomicptr_await_neq_set_rel(a, c, v) \
	vatomicptr_await_neq_set_rel(a, c, v)
#define atomicptr_await_neq_set_rlx(a, c, v) \
	vatomicptr_await_neq_set_rlx(a, c, v)
#define atomicptr_cmpxchg(a, exp, v) vatomicptr_cmpxchg(a, exp, v)
#define atomicptr_cmpxchg_acq(a, exp, v) vatomicptr_cmpxchg_acq(a, exp, v)
#define atomicptr_cmpxchg_rel(a, exp, v) vatomicptr_cmpxchg_rel(a, exp, v)
#define atomicptr_cmpxchg_rlx(a, exp, v) vatomicptr_cmpxchg_rlx(a, exp, v)
#define atomicptr_init(a, v) vatomicptr_init(a, v)
#define atomicptr_read(a) vatomicptr_read(a)
#define atomicptr_read_acq(a) vatomicptr_read_acq(a)
#define atomicptr_read_rlx(a) vatomicptr_read_rlx(a)
#define atomicptr_write(a, v) vatomicptr_write(a, v)
#define atomicptr_write_rel(a, v) vatomicptr_write_rel(a, v)
#define atomicptr_write_rlx(a, v) vatomicptr_write_rlx(a, v)
#define atomicptr_xchg(a, v) vatomicptr_xchg(a, v)
#define atomicptr_xchg_acq(a, v) vatomicptr_xchg_acq(a, v)
#define atomicptr_xchg_rel(a, v) vatomicptr_xchg_rel(a, v)
#define atomicptr_xchg_rlx(a, v) vatomicptr_xchg_rlx(a, v)

#endif /* VSYNC_ATOMIC_MAPPING_H */
