/* Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved. */
#ifndef __DDR_NMANAGER_EXTEND_H__
#define __DDR_NMANAGER_EXTEND_H__
#include <soc_pmctrl_unit_xpu_interface.h>

/* nmanager */
#define SOC_QICE_TBED_ABNML_NS_INT_ST_trace_int_START		28
#define SOC_QICE_TBED_ABNML_NS_INT_ST_trace_int_END		28

/* SOC_DDR_PHY_PHY_PLL_CFG_UNION */
#define SOC_DDR_PHY_PHY_PLL_CFG_ADDR(base)		((base) + (0x0710UL))


/* SOC_DDR_PACK_DXCTL_BYPASS_UNION */
// todo: fix this later
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN0_START                    20
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN0_END                      20
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN1_START                    21
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN1_END                      21
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN2_START                    22
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN2_END                      22
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN3_START                    23
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN3_END                      23
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN4_START                    24
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN4_END                      24
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN5_START                    25
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN5_END                      25
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN6_START                    26
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN6_END                      26
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN7_START                    27
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN7_END                      27
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN8_START                    28
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN8_END                      28
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN9_START                    29
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN9_END                      29
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN10_START                   30
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN10_END                     30

/* SOC_DDR_PHY_AC_SFIO_CTRL1_UNION */
#define SOC_DDR_PHY_AC_SFIO_CTRL1_SFIO_RONSEL_8_6_START	(SOC_DDR_PHY_AC_SFIO_CTRL1_SFIO_RONSEL_START + 6)
#define SOC_DDR_PHY_AC_SFIO_CTRL1_SFIO_RONSEL_8_6_END	(SOC_DDR_PHY_AC_SFIO_CTRL1_SFIO_RONSEL_START + 8)

/* SOC_BISR_CTRL_REPAIR_ACK_0_UNION */
#define SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_19_START  (SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_START + 19)
#define SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_19_END    (SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_START + 19)
#define SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_20_START  (SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_START + 20)
#define SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_20_END    (SOC_BISR_CTRL_REPAIR_ACK_0_repair_ack_0_START + 20)

/* SOC_DDR_PHY_AC_REV_REG_0_UNION */
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_bypass_ff_START   0
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_bypass_ff_END     0
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_add_di_ui_START   1
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_add_di_ui_END     15
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_dio_refsel_START  16
#define SOC_DDR_PHY_AC_REV_REG_0_ac_rev_reg_0_dio_refsel_END    17

/* SOC_DDR_PHY_AC_REV_REG_1_UNION */
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_gated_woph_pck_START    0
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_gated_woph_pck_END      0
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_parking_clock_tx_en_START   1
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_parking_clock_tx_en_END     1
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_parking_clock_ratio_START   2
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_parking_clock_ratio_END     3
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_clock_out_sel_START     4
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_clock_out_sel_END       4
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_rx_dphy_free_START   6
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_rx_dphy_free_END     6
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_tx_dphy_free_START   7
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_tx_dphy_free_END     7
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_wck_dphy_free_START  8
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_wck_dphy_free_END    8
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_ac_dphy_free_START   9
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_ac_dphy_free_END     9
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_ck_dphy_free_START   10
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_dficlk_ck_dphy_free_END     10
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_clk_inv_START           11
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_clk_inv_END             11
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pck_bypclk_sel_START        12
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pck_bypclk_sel_END          12
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_phase_clock_gate_START  15
#define SOC_DDR_PHY_AC_REV_REG_1_ac_rev_reg_1_pll_phase_clock_gate_END    15

/* SOC_DDR_PHY_AC_REV_REG_2_UNION */
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_pll_8x_sync_sel_START  0
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_pll_8x_sync_sel_END    0
#define SOC_DDR_PHY_AC_REV_REG_2_RG_TEST_DLL_START                   1
#define SOC_DDR_PHY_AC_REV_REG_2_RG_TEST_DLL_END                     2
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_dqs_dq_oe_en_START     14
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_dqs_dq_oe_en_END       14
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_wck_dq_oe_sel_START    15
#define SOC_DDR_PHY_AC_REV_REG_2_ac_rev_reg_2_wck_dq_oe_sel_END      15

/* SOC_DDR_PHY_AC_TESTCTRL1_UNION */
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TI_CKE_START  25
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TI_CKE_END    26

/* SOC_DDR_PHY_DX_TESTCTRL1_UNION */
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_DQS_START				9
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_DQS_END					9
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_DUMMY_IO_START			10
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_DUMMY_IO_END			10
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_WCK_START				11
#define SOC_DDR_PHY_DX_TESTCTRL1_DX_IO_TE_WCK_END					11

/* SOC_DDR_PHY_DX_DA_PHASE_CTRL_UNION */
#define SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_0_7_START     (SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_START + 0)
#define SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_0_7_END       (SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_START + 7)
#define SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_8_START     (SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_START + 8)
#define SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_8_END       (SOC_DDR_PHY_DX_DA_PHASE_CTRL_DX_DA_PHASE_DELAY_DQ_EN_START + 8)

/* SOC_DDR_PHY_AC_DA_PHASE_CTRL_UNION */
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_0_5_START     (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 0)
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_0_5_END       (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 5)
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_6_7_START     (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 6)
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_6_7_END       (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 7)
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_8_9_START     (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 8)
#define SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_8_9_END       (SOC_DDR_PHY_AC_DA_PHASE_CTRL_AC_DA_PHASE_DELAY_DQ_EN_START + 9)

/* SOC_DDR_PHY_DXCTL_BYPASS_UNION */
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_0_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 0)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_0_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 0)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_1_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 1)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_1_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 1)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_2_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 2)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_2_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 2)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_3_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 3)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_3_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 3)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_4_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 4)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_4_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 4)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_5_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 5)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_5_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 5)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_6_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 6)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_6_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 6)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_7_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 7)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_7_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 7)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_8_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 8)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_8_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 8)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_10_START	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 10)
#define SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_10_END	(SOC_DDR_PHY_DXCTL_BYPASS_DX_BIAS_EN_START + 10)


/* SOC_DDR_PHY_DX_RONCTRL1_UNION */
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_0_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 0)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_0_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 0)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_1_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 1)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_1_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 1)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_2_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 2)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_2_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 2)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_3_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 3)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_3_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 3)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_4_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 4)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_4_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 4)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_5_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 5)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_5_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 5)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_6_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 6)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_6_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 6)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_7_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 7)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_7_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 7)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_8_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 8)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_8_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 8)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_9_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 9)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_9_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_B_START + 9)

#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_A_0_START	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_A_START + 0)
#define SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_A_0_END	(SOC_DDR_PHY_DX_RONCTRL1_DX_IO_ODTEN_A_START + 0)

/* SOC_DDR_PHY_DX_IOEQCTRL3_UNION */
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_base_START  	24
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_base_END    	30
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_xrank_en_START  31
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_xrank_en_END    31

/* SOC_DDR_PHY_DX_TESTCTRL0_UNION */
#define SOC_DDR_PHY_DX_TESTCTRL0_dqs_bit_START  9
#define SOC_DDR_PHY_DX_TESTCTRL0_dqs_bit_END    9
#define SOC_DDR_PHY_DX_TESTCTRL0_wck_bit_START  11
#define SOC_DDR_PHY_DX_TESTCTRL0_wck_bit_END    11

/* SOC_DDR_PHY_DX_RG_TEST_CTL2_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_RDQS_CTRL_START	10
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_RDQS_CTRL_END	10
/* SOC_DDR_PHY_AC_TESTCTRL1_UNION */
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cs0_START		6
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cs0_END		6
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cs1_START		7
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cs1_END		7
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cke0_START	9
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cke0_END		9
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cke1_START	10
#define SOC_DDR_PHY_AC_TESTCTRL1_AC_IO_TE_cke1_END		10

/* SOC_CRGPERIPH_PLL_GT_VOTE_CTRL1_UNION */
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_ppll0_gt_vote_ddr_START  1
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_ppll0_gt_vote_ddr_END    1

/* SOC_CRGPERIPH_PLL_EN_VOTE_CTRL1_UNION */
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL2_ppll0_en_vote_ddr_START  1
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL2_ppll0_en_vote_ddr_END    1

/* SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL1_UNION */
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL2_ppll0_bypass_vote_ddr_START  1
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL2_ppll0_bypass_vote_ddr_END    1

/* SOC_CRGPERIPH_PLL_GT_VOTE_CTRL0_UNION */
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE0_ppll1_en_fsm_vote_ddr_START  1
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE0_ppll1_en_fsm_vote_ddr_END    1
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE0_ppll3_en_fsm_vote_ddr_START  11
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE0_ppll3_en_fsm_vote_ddr_END    11

/* SOC_CRGPERIPH_PLL_GT_VOTE_CTRL0_UNION */
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL0_ppll2_gt_vote_ddr_START  6
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL0_ppll2_gt_vote_ddr_END    6

/* SOC_CRGPERIPH_PLL_EN_VOTE_CTRL0_UNION */
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL0_ppll2_en_vote_ddr_START  6
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL0_ppll2_en_vote_ddr_END    6

/* SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_UNION */
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE1_ppll2_b_en_fsm_vote_ddr_START  6
#define SOC_CRGPERIPH_PLL_FSM_NS_VOTE1_ppll2_b_en_fsm_vote_ddr_END    6

/* SOC_PMCTRL_UNIT_XPU_PDVFS_INSTR_LIST_UNION */
#define SOC_XPU_LP_CTRL_CFG_DDR_SW_RESERVED_ADDR(base, id) SOC_PMCTRL_UNIT_XPU_PDVFS_INSTR_LIST_ADDR(base, id)

/* SOC_PMCTRL_UNIT_XPU_PWR_UP_INSTR_LIST_UNION */
#define SOC_XPU_LP_CTRL_CFG_INTR_TO_LPMCU_DATA_ADDR(base, id) SOC_PMCTRL_UNIT_XPU_PWR_UP_INSTR_LIST_ADDR(base, id)

/* SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_1_UNION */
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_1_reserved_START  16
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_1_reserved_END    31

/* SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_2_UNION */
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_2_reserved_START  16
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_2_reserved_END    31

/* SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_3_UNION */
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_3_reserved_5_START  16
#define SOC_PMCTRL_PERI_VOTE_VOL_RANK_SFT_3_reserved_5_END    31

/* no define in nmanager */
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C0_7_START		7
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C0_7_END		7
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C1_7_START		15
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C1_7_END		15
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C2_7_START		23
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C2_7_END		23
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C3_7_START		31
#define SOC_DDR_PHY_AC_IOEQCTRL0_AC_IO_EQ_C3_7_END		31

#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C4_7_START		7
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C4_7_END		7
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C5_7_START		15
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C5_7_END		15
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C6_7_START		23
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C6_7_END		23
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C7_7_START		31
#define SOC_DDR_PHY_AC_IOEQCTRL1_AC_IO_EQ_C7_7_END		31

#define SOC_DDR_PHY_AC_IOEQCTRL4_AC_IO_EQ_C8_7_START		7
#define SOC_DDR_PHY_AC_IOEQCTRL4_AC_IO_EQ_C8_7_END		7
#define SOC_DDR_PHY_AC_IOEQCTRL4_AC_IO_EQ_C9_7_START		15
#define SOC_DDR_PHY_AC_IOEQCTRL4_AC_IO_EQ_C9_7_END		15

#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C0_7_START		7
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C0_7_END		7
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C1_7_START		15
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C1_7_END		15
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C2_7_START		23
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C2_7_END		23
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C3_7_START		31
#define SOC_DDR_PHY_DX_IOEQCTRL0_DX_IO_EQ_C3_7_END		31

#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C4_7_START		7
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C4_7_END		7
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C5_7_START		15
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C5_7_END		15
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C6_7_START		23
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C6_7_END		23
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C7_7_START		31
#define SOC_DDR_PHY_DX_IOEQCTRL1_DX_IO_EQ_C7_7_END		31

/* SOC_DDR_PHY_DX_IOEQCTRL3_UNION */
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_7_START	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_7_END	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP7_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP6_7_START	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP6_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP6_7_END	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP6_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP5_7_START	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP5_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP5_7_END	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP5_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP4_7_START	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP4_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP4_7_END	(SOC_DDR_PHY_DX_IOEQCTRL3_DX_IO_EQ_RP4_START + 7)

/* SOC_DDR_PHY_DX_IOEQCTRL2_UNION */
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP3_7_START	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP3_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP3_7_END	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP3_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP2_7_START	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP2_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP2_7_END	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP2_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP1_7_START	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP1_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP1_7_END	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP1_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP0_7_START	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP0_START + 7)
#define SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP0_7_END	(SOC_DDR_PHY_DX_IOEQCTRL2_DX_IO_EQ_RP0_START + 7)

#define SOC_DDR_PHY_DX_IOEQCTRL4_DX_IO_EQ_C8_7_START		7
#define SOC_DDR_PHY_DX_IOEQCTRL4_DX_IO_EQ_C8_7_END		7
#define SOC_DDR_PHY_DX_IOEQCTRL4_DX_IO_EQ_C9_7_START		15
#define SOC_DDR_PHY_DX_IOEQCTRL4_DX_IO_EQ_C9_7_END		15

#define SOC_HIPACK_DLL_DCC_CTRL0_RG_SQ_DI_WCK_2_START	23
#define SOC_HIPACK_DLL_DCC_CTRL0_RG_SQ_DI_WCK_2_END		23
#define SOC_HIPACK_DLL_DCC_CTRL0_RG_SQ_DI_DQS_2_START	26
#define SOC_HIPACK_DLL_DCC_CTRL0_RG_SQ_DI_DQS_2_END		26

#define SOC_HIPACK_DLL_DCC_CTRL1_RG_SQ_DI_CK_2_START		12
#define SOC_HIPACK_DLL_DCC_CTRL1_RG_SQ_DI_CK_2_END		12

/* SOC_DDR_PHY_AC_PLL_CTRL_A2_UNION */
#define SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_1_START		(SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_START + 1)
#define SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_1_END		(SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_START + 1)
#define SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_2_3_START	(SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_START + 2)
#define SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_2_3_END		(SOC_DDR_PHY_AC_PLL_CTRL_A2_RG_DMY_CTR_A_START + 3)

/* SOC_DDR_PHY_AC_PLL_CTRL_B2_UNION */
#define SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_1_START		(SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_START + 1)
#define SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_1_END		(SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_START + 1)
#define SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_2_3_START	(SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_START + 2)
#define SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_2_3_END		(SOC_DDR_PHY_AC_PLL_CTRL_B2_RG_DMY_CTR_B_START + 3)

/* SOC_DDR_PHY_AC_RG_TEST_CTL0_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST3_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST3_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST3_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST3_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST2_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST2_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST2_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST2_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST1_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST1_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST1_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST1_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST0_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST0_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST0_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_AC_RG_TEST0_2_START + 1)

/* SOC_DDR_PHY_AC_RG_TEST_CTL1_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST7_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST7_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST7_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST7_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST6_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST6_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST6_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST6_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST5_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST5_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST5_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST5_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST4_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST4_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST4_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_AC_RG_TEST4_2_START + 1)

/* SOC_DDR_PHY_AC_RG_TEST_CTL2_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_1_END	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_2_END	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_4_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 4)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_4_END	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST10_2_START + 4)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_1_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_1_END		(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_4_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 4)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_4_END		(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST9_2_START + 4)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST8_4_0_START	(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST8_4_START + 0)
#define SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST8_4_0_END		(SOC_DDR_PHY_AC_RG_TEST_CTL2_AC_RG_TEST8_4_START + 0)

/* SOC_DDR_PHY_AC_RG_TEST_CTL3_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_0_START	(SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_START + 0)
#define SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_0_END	(SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_START + 0)
#define SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_3_4_START	(SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_START + 3)
#define SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_3_4_END	(SOC_DDR_PHY_AC_RG_TEST_CTL3_AC_RG_TEST8_HSB_START + 4)

/* SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST3_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST3_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST3_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST3_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST2_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST2_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST2_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST2_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST1_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST1_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST1_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST1_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST0_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST0_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST0_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL0_HSB_AC_RG_TEST0_HSB_START + 2)

/* SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_UNION */
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST7_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST7_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST7_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST7_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST6_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST6_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST6_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST6_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST5_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST5_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST5_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST5_HSB_START + 2)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST4_HSB_1_2_START	(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST4_HSB_START + 1)
#define SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST4_HSB_1_2_END		(SOC_DDR_PHY_AC_RG_TEST_CTL1_HSB_AC_RG_TEST4_HSB_START + 2)

/* SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST3_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST2_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST1_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_HSB_DX_RG_TEST0_HSB_START + 1)

/* SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST7_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST6_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST5_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_HSB_DX_RG_TEST4_HSB_START + 1)

/* SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST10_HSB_1_2_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST10_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST10_HSB_1_2_END	(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST10_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_2_START		(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_2_END		(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_1_START		(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_START + 1)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_1_END		(SOC_DDR_PHY_DX_RG_TEST_CTL2_HSB_DX_RG_TEST8_HSB_START + 1)

/* SOC_DDR_PHY_DX_RG_TEST_CTL0_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST3_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST3_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST3_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST3_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST2_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST2_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST2_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST2_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST1_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST1_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST1_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST1_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST0_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST0_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST0_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL0_DX_RG_TEST0_3_START + 0)

/* SOC_DDR_PHY_DX_RG_TEST_CTL1_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST7_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST7_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST7_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST7_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST6_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST6_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST6_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST6_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST5_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST5_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST5_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST5_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST4_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST4_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST4_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL1_DX_RG_TEST4_3_START + 0)

/* SOC_DDR_PHY_DX_RG_TEST_CTL2_UNION */
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST11_4_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST11_4_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST11_4_0_END	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST11_4_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST10_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST10_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST10_3_0_END	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST10_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_3_2_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_START + 2)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_3_2_END	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST9_4_START + 3)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST8_3_0_START	(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST8_3_START + 0)
#define SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST8_3_0_END		(SOC_DDR_PHY_DX_RG_TEST_CTL2_DX_RG_TEST8_3_START + 0)

/* SOC_DDR_PHY_DX_DQS_IE_EXTEND_UNION */
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_4_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 4)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_4_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 4)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_3_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 3)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_3_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 3)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_2_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 2)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_2_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 2)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_0_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 0)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_0_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST9_HSB_START + 0)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_4_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 4)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_4_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 4)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_3_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 3)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_3_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 3)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_0_START	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 0)
#define SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_0_END	(SOC_DDR_PHY_DX_DQS_IE_EXTEND_DX_RG_TEST11_HSB_START + 0)

/* SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL0_UNION */
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL0_ppll2_bypass_vote_ddr_START  6
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL0_ppll2_bypass_vote_ddr_END    6

/* SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_UNION */
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_ppll2_b_gt_vote_ddr_START  11
#define SOC_CRGPERIPH_PLL_GT_VOTE_CTRL2_ppll2_b_gt_vote_ddr_END    11

/* SOC_CRGPERIPH_PLL_EN_VOTE_CTRL2_UNION */
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL2_ppll2_b_en_vote_ddr_START  11
#define SOC_CRGPERIPH_PLL_EN_VOTE_CTRL2_ppll2_b_en_vote_ddr_END    11

/* SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL2_UNION */
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL2_ppll2_b_bypass_vote_ddr_START  11
#define SOC_CRGPERIPH_PLL_BYPASS_VOTE_CTRL2_ppll2_b_bypass_vote_ddr_END    11

/* SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_UNION */
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_uce_dfi_access_gt_vote_bypass_START     12
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_uce_dfi_access_gt_vote_bypass_END       12
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_lpm3_dfi_access_gt_vote_bypass_START     13
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_lpm3_dfi_access_gt_vote_bypass_END       13
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_xpu_dfi_access_gt_vote_bypass_START     14
#define SOC_DDR_DUMREG_DDRC_COMMON_CTRL2_xpu_dfi_access_gt_vote_bypass_END       14

#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos0_START	0
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos0_END	7
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos1_START	8
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos1_END	15
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos2_START	16
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos2_END	23
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos3_START	24
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT0_rqos3_END	31

#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos4_START	0
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos4_END	7
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos5_START	8
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos5_END	15
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos6_START	16
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos6_END	23
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos7_START	24
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT1_rqos7_END	31

#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos0_START	0
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos0_END	7
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos1_START	8
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos1_END	15
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos2_START	16
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos2_END	23
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos3_START	24
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT2_wqos3_END	31

#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos4_START	0
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos4_END	7
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos5_START	8
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos5_END	15
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos6_START	16
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos6_END	23
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos7_START	24
#define SOC_DDR_DUMREG_DAS_MAP_TIMEOUT3_wqos7_END	31

#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos0_START	0
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos0_END		3
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos1_START	4
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos1_END		7
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos2_START	8
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos2_END		11
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos3_START	12
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos3_END		15
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos4_START	16
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos4_END		19
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos5_START	20
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos5_END		23
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos6_START	24
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos6_END		27
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos7_START	28
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT0_rqos7_END		31

#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos0_START	0
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos0_END		3
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos1_START	4
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos1_END		7
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos2_START	8
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos2_END		11
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos3_START	12
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos3_END		15
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos4_START	16
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos4_END		19
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos5_START	20
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos5_END		23
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos6_START	24
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos6_END		27
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos7_START	28
#define SOC_DDR_DUMREG_DAS_MAP_ADAPT1_wqos7_END		31

#define SOC_PCTRL_PERI_CTRL2_reserved_3_START         (16)
#define SOC_PCTRL_PERI_CTRL2_reserved_3_END           (31)
#define SOC_PCTRL_PERI_CTRL103_reserved_3_START       (16)
#define SOC_PCTRL_PERI_CTRL103_reserved_3_END         (31)
#define SOC_ACTRL_AO_MEM_CTRL1_reserved_START         (16)
#define SOC_ACTRL_AO_MEM_CTRL1_reserved_END           (31)
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_reserve_START     (16)
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_reserve_END       (31)

#define SOC_LATSTAT_BUS_STAT_bus_busy_START            0
#define SOC_LATSTAT_BUS_STAT_bus_busy_END              1

/* SOC_ACTRL_ISO_EN_GROUP0_PERI_UNION */
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_actrl2core_iso_en_group0_sc_dmc1_iso_en_START  7
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_actrl2core_iso_en_group0_sc_dmc1_iso_en_END    7
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_actrl2core_iso_en_group0_sc_dmc_iso_en_START   11
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_actrl2core_iso_en_group0_sc_dmc_iso_en_END     11

#define SOC_ACTRL_ISO_EN_GROUP0_PERI_sc_dmc1_iso_en_START  7
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_sc_dmc1_iso_en_END    7
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_sc_dmc_iso_en_START   11
#define SOC_ACTRL_ISO_EN_GROUP0_PERI_sc_dmc_iso_en_END     11

/* SOC_PCTRL_PERI_STAT5_UNION */
#define SOC_PCTRL_PERI_STAT5_sc_mdm2ap_status_qice2cpu_START  (27)
#define SOC_PCTRL_PERI_STAT5_sc_mdm2ap_status_qice2cpu_END    (27)

/* SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_UNION */
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq0_START       (0)
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq0_END         (0)
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq1_START       (1)
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq1_END         (1)
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq2_START       (2)
#define SOC_DDR_UCE_SCTRL_UCE_MCU_IRQ_uce_mcu_irq2_END         (2)

/* SOC_PCTRL_PERI_CTRL122_UNION */
#define SOC_PCTRL_PERI_CTRL122_dss_poweron_state_START     0
#define SOC_PCTRL_PERI_CTRL122_dss_poweron_state_END       0
/* SOC_PCTRL_PERI_CTRL123_UNION */
#define SOC_PCTRL_PERI_CTRL123_dss2_poweron_state_START    0
#define SOC_PCTRL_PERI_CTRL123_dss2_poweron_state_END      0

/* SOC_PMCTRL_VDDC_MEM_VOTE_VOL_RANK_SFT_1_UNION */
#define SOC_PMCTRL_VDDC_MEM_VOTE_VOL_RANK_SFT_1_reserved_1_START  (16)
#define SOC_PMCTRL_VDDC_MEM_VOTE_VOL_RANK_SFT_1_reserved_1_END    (31)

/* SOC_PMCTRL_VDDC_MEM_VOTE_VOL_VALID_UNION */
#define SOC_PMCTRL_VDDC_MEM_VOTE_VOL_VALID_reserved_START  (16)
#define SOC_PMCTRL_VDDC_MEM_VOTE_VOL_VALID_reserved_END    (31)

/* SOC_DDR_PHY_AC_PLL_RSV_CTRL_UNION */
#define SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_B_15_7_START	(SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_B_START + 7)
#define SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_B_15_7_END	(SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_B_START + 15)
#define SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_A_15_7_START	(SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_A_START + 7)
#define SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_A_15_7_END	(SOC_DDR_PHY_AC_PLL_RSV_CTRL_RG_PLL_RESERVE_A_START + 15)

/* SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_UNION */
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_0_START	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_0_END	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_1_START	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_START + 1)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_1_END	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_A_RG_FLL_PREDIV_CTRL_A_START + 1)

/* SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_UNION */
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_0_START	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_0_END	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_1_START	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_START + 1)
#define SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_1_END	(SOC_DDR_PHY_AC_RG_NSV_FLL_CTL_B_RG_FLL_PREDIV_CTRL_B_START + 1)

/* SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_UNION */
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_1_0_START	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_1_0_END	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_START + 1)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_6_4_START	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_START + 4)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_6_4_END	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_A_RG_KBAND_SEAECH_RANGE_A_START + 6)

/* SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_UNION */
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_1_0_START	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_START + 0)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_1_0_END	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_START + 1)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_6_4_START	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_START + 4)
#define SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_6_4_END	(SOC_DDR_PHY_AC_RG_NSV_KBAND_CTL_B_RG_KBAND_SEAECH_RANGE_B_START + 6)

/* SOC_XPU_LP_CTRL_CFG_XPU_TCP_MEM_CTRL1_UNION */
#define SOC_XPU_LP_CTRL_CFG_XPU_TCP_MEM_CTRL1_xpu_tcp_mem_ctrl_1_START	(SOC_XPU_LP_CTRL_CFG_XPU_TCP_MEM_CTRL1_xpu_tcp_mem_ctrl_START + 1)
#define SOC_XPU_LP_CTRL_CFG_XPU_TCP_MEM_CTRL1_xpu_tcp_mem_ctrl_1_END	(SOC_XPU_LP_CTRL_CFG_XPU_TCP_MEM_CTRL1_xpu_tcp_mem_ctrl_START + 1)

/* SOC_SCTRL_SCSPMIADDR15_UNION */
#define SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_pmu_addr_START	(SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_START + 0)
#define SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_pmu_addr_END	(SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_START + 15)
#define SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_pmu_sid_START	(SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_START + 16)
#define SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_pmu_sid_END	(SOC_SCTRL_SCSPMIADDR15_spmi_avs_addr15_START + 19)

/* SOC_SCTRL_SCSPMIADDR14_UNION */
#define SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_pmu_addr_START	(SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_START + 0)
#define SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_pmu_addr_END	(SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_START + 15)
#define SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_pmu_sid_START	(SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_START + 16)
#define SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_pmu_sid_END	(SOC_SCTRL_SCSPMIADDR14_spmi_avs_addr14_START + 19)

/* SOC_SCTRL_SCEFUSEDATA2_UNION */
#define SOC_SCTRL_SCEFUSEDATA2_efuse_package_ctrl_START		18
#define SOC_SCTRL_SCEFUSEDATA2_efuse_package_ctrl_END		19
#define SOC_SCTRL_SCEFUSEDATA2_bhs_ack_dflt_START		24
#define SOC_SCTRL_SCEFUSEDATA2_bhs_ack_dflt_END			28

#define SOC_DDR_DASRAM_DAS_SRAM_VEC_ADDR(base, scene_div, feature_id)                 ((base) + scene_div * 0x80UL + feature_id * 4)
#endif /* __DDR_NMANAGER_EXTEND_H__ */
