/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 * Description: Contexthub 9030 driver.
 * Create: 2024-11-30
 */
#ifndef __IODIE__HIPHYIO__DEF__
#define __IODIE__HIPHYIO__DEF__

enum iodie_sys_status {
	IODIE_ST_PRE_INITED,
	IODIE_ST_INITED,
	IODIE_ST_ERR,
	IODIE_ST_NONE,
	IODIE_ST_DRV_ERR,
	IODIE_ST_END,
};

/* sub state of IODIE_ST_INITED */
enum iodie_runtime_status {
	IODIE_RT_SUSPEND,
	IODIE_RT_NORMAL_LOW,
	IODIE_RT_RESERVED,
	IODIE_RT_NORMAL_HIGH,
	IODIE_RT_ERROR,
	IODIE_RT_END,
};

/* sub state of IODIE_ST_ERR */
enum iodie_err_status {
	IODIE_ERR_NO,
	IODIE_ERR_I2S,
	IODIE_ERR_SPI,
	IODIE_ERR_HIPHY,
	IODIE_ERR_IODIE,
	IODIE_ERR_SYS,
	IODIE_ERR_END,
};

enum iodie_abrl_src {
	IODIE_ABRL_INTR,
	IODIE_ABRL_RETRY,
	IODIE_ABRL_HIPHYIO_SPEED,
	IODIE_ABRL_PERI,
	IODIE_ARRL_FNPLL,
	IODIE_ARRL_ULPPLL,
	IODIE_ARRL_END,
};

enum iodie_user {
	IODIE_USER_AP_BT,
	IODIE_USER_AP_GNSS,
	IODIE_USER_AP_CAM,
	IODIE_USER_AP_AUDIO,
	IODIE_USER_AP_SPI,
	IODIE_USER_AUDIO_BT,
	IODIE_USER_SH_110X,
	IODIE_USER_SH_SPI,
	IODIE_USER_I2S,
	IODIE_USER_AP_SPMI,
	IODIE_USER_SH_SPMI,
	IODIE_USER_SH_SWING,
	IODIE_USER_SH_SENSOR,
	IODIE_USER_AP_BATTERY,
	IODIE_USER_IGS,
	IODIE_USER_ISP_I2C,
	IODIE_USER_GPIO,
	IODIE_USER_END,
};

enum iodie_module {
	IODIE_IP_AO_SEC_REGION = 0,
	IODIE_IP_AO_CFG = 1,
	IODIE_IP_AO_CRG = 2,
	IODIE_IP_EFUSE = 3,
	IODIE_IP_HIPHYIO = 4,
	IODIE_IP_I2C0 = 5,
	IODIE_IP_I2C1 = 6,
	IODIE_IP_I2C3 = 7,
	IODIE_IP_I2C5 = 8,
	IODIE_IP_I3C1 = 9,
	IODIE_IP_USIM0 = 10,
	IODIE_IP_USIM1 = 11,
	IODIE_IP_ADC = 12,
	IODIE_IP_GPIO0 = 13,
	IODIE_IP_GPIO1 = 14,
	IODIE_IP_GPIO2 = 15,
	IODIE_IP_GPIO3 = 16,
	IODIE_IP_GPIO4 = 17,
	IODIE_IP_IOC = 18,
	IODIE_IP_AO_QIC_DFX = 19,
	IODIE_IP_RAM = 20,
	IODIE_IP_PERI_SEC_REGION = 21,
	IODIE_IP_DSPI = 22,
	IODIE_IP_DMA0 = 23,
	IODIE_IP_PERI_CRG = 24,
	IODIE_IP_PERI_CFG = 25,
	IODIE_IP_I3C0 = 26,
	IODIE_IP_I3C2 = 27,
	IODIE_IP_I2C2 = 28,
	IODIE_IP_I2C4 = 29,
	IODIE_IP_ISP_I2C0 = 30,
	IODIE_IP_ISP_I2C1 = 31,
	IODIE_IP_UART0 = 32,
	IODIE_IP_UART1 = 33,
	IODIE_IP_UART2 = 34,
	IODIE_IP_SPMI = 35,
	IODIE_IP_UART_AUDIO = 36,
	IODIE_IP_ONEWIRE0 = 37,
	IODIE_IP_ONEWIRE1 = 38,
	IODIE_IP_PERI_QIC_DFX = 39,
	IODIE_IP_END,
};

enum iodie_clk_out_op {
	IODIE_CLK_OUT_CMD_OPEN,
	IODIE_CLK_OUT_CMD_CLOSE,
	IODIE_CLK_CAM_REF_OPEN,
	IODIE_CLK_CAM_REF_CLOSE,
	IODIE_CLK_CAM_REF_SEL,
	IODIE_CLK_OUT_CMD_END,
};

enum INTR_HUB_L2_ID {
	INTR_HUB_L2_ID_START = 6,
	INTR_HUB_L2_ID_6 = INTR_HUB_L2_ID_START,
	INTR_HUB_L2_ID_7,
	INTR_HUB_L2_ID_8,
	INTR_HUB_L2_ID_END,
};

typedef void (*iodie_user_func)(enum iodie_sys_status sys_st, enum iodie_err_status err_st);

#endif