/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Description: dev_secinfo_auth cmd id define
 * Create: 2024/06/13
 */
#ifndef __DEV_SECINFO_AUTH_CMD_ID_H__
#define __DEV_SECINFO_AUTH_CMD_ID_H__

#ifndef DEV_SECINFO_AUTH_INTERNAL
	#error Do not include this file directly!
#endif

enum dev_secinfo_auth_cmd_id {
	DEV_SECINFO_AUTH_CMD_ID_VERIFY_BF = 0x0,
	DEV_SECINFO_AUTH_CMD_ID_GET_TRAIT_HASH,
	DEV_SECINFO_AUTH_CMD_ID_GET_PACKAGE_VERSION,
	DEV_SECINFO_AUTH_CMD_ID_GET_AUTH_CTX,
	DEV_SECINFO_AUTH_CMD_ID_SET_UAPP_ENABLE_STATE,
	DEV_SECINFO_AUTH_CMD_ID_GET_SOCID,
	DEV_SECINFO_AUTH_CMD_ID_GET_SECCFG,
	DEV_SECINFO_AUTH_CMD_ID_GET_SE_TYPE,
	DEV_SECINFO_AUTH_CMD_ID_GET_DCU_STATUS,
	DEV_SECINFO_AUTH_CMD_ID_GET_EMPOWER_FLAG,
	DEV_SECINFO_AUTH_CMD_ID_UPDATE_ALL_NVCNT,
	DEV_SECINFO_AUTH_CMD_ID_NOTIFY_HUK2_INFO,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_SEC_IMAGE_HASH,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_VB_IMAGE_HASH,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_BOOT_MODE,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_LOCKDOWN_STATE,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_DEVELOPER_STATE,
	DEV_SECINFO_AUTH_CMD_ID_GEN_TRND,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_FASTBOOT_LOCK_STATE,
	DEV_SECINFO_AUTH_CMD_ID_IMAGE_TYPE,
	DEV_SECINFO_AUTH_CMD_ID_MODULE_UPDATE_VERIFY_BF,
	DEV_SECINFO_AUTH_CMD_ID_MODULE_UPDATE_VERIFY_HASH,
	DEV_SECINFO_AUTH_CMD_ID_UPDATE_HUK2_ENHANCE_CNT,
	DEV_SECINFO_AUTH_CMD_ID_RECORD_BOOT_STAGE,
#ifdef CONFIG_DEV_SECINFO_AUTH_DEBUG
	DEV_SECINFO_AUTH_CMD_ID_EFUSE_TC = 0xA0,
	DEV_SECINFO_AUTH_CMD_ID_MSPE_TEST,
	DEV_SECINFO_AUTH_CMD_ID_DICE_TC,
#endif
	DEV_SECINFO_AUTH_CMD_ID_MAX
};

#endif /* __DEV_SECINFO_AUTH_CMD_ID_H__ */
