
obj-y += cee/
obj-y += basicplatform/
obj-y += see/
obj-y += smart/
obj-y += ai/
obj-y += maligpu/
obj-y += audio/
obj-y += camera/
obj-y += display/
obj-y += isp/
obj-y += vcodec/
obj-y += ffrt_ohos/