/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: Hmseharmony header file for class bitmap
 * Author: Huawei OS Kernel Lab
 * Create: Mon June 05 11:49:29 2023
 */
#ifndef CLASS_BITMAP_NETWORK_H
#define CLASS_BITMAP_NETWORK_H

CLASS_SET(HM_SECCLASS_CAPABILITY);
CLASS_SET(HM_SECCLASS_CAPABILITY2);
CLASS_SET(HM_SECCLASS_CAP_USERNS);
CLASS_SET(HM_SECCLASS_CAP2_USERNS);
CLASS_SET(HM_SECCLASS_SOCK_FILE);
CLASS_SET(HM_SECCLASS_SOCKET);
CLASS_SET(HM_SECCLASS_TCP_SOCKET);
CLASS_SET(HM_SECCLASS_UDP_SOCKET);
CLASS_SET(HM_SECCLASS_RAWIP_SOCKET);
CLASS_SET(HM_SECCLASS_NODE);
CLASS_SET(HM_SECCLASS_NETIF);
CLASS_SET(HM_SECCLASS_NETLINK_SOCKET);
CLASS_SET(HM_SECCLASS_PACKET_SOCKET);
CLASS_SET(HM_SECCLASS_KEY_SOCKET);
CLASS_SET(HM_SECCLASS_UNIX_STREAM_SOCKET);
CLASS_SET(HM_SECCLASS_UNIX_DGRAM_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_ROUTE_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_TCPDIAG_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_NFLOG_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_XFRM_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_SELINUX_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_ISCSI_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_AUDIT_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_FIB_LOOKUP_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_CONNECTOR_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_NETFILTER_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_DNRT_SOCKET);
CLASS_SET(HM_SECCLASS_ASSOCIATION);
CLASS_SET(HM_SECCLASS_NETLINK_KOBJECT_UEVENT_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_GENERIC_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_SCSITRANSPORT_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_RDMA_SOCKET);
CLASS_SET(HM_SECCLASS_NETLINK_CRYPTO_SOCKET);
CLASS_SET(HM_SECCLASS_APPLETALK_SOCKET);
CLASS_SET(HM_SECCLASS_PACKET);
CLASS_SET(HM_SECCLASS_DCCP_SOCKET);
CLASS_SET(HM_SECCLASS_PEER);
CLASS_SET(HM_SECCLASS_TUN_SOCKET);
CLASS_SET(HM_SECCLASS_SCTP_SOCKET);
CLASS_SET(HM_SECCLASS_ICMP_SOCKET);
CLASS_SET(HM_SECCLASS_AX25_SOCKET);
CLASS_SET(HM_SECCLASS_IPX_SOCKET);
CLASS_SET(HM_SECCLASS_NETROM_SOCKET);
CLASS_SET(HM_SECCLASS_ATMPVC_SOCKET);
CLASS_SET(HM_SECCLASS_X25_SOCKET);
CLASS_SET(HM_SECCLASS_ROSE_SOCKET);
CLASS_SET(HM_SECCLASS_DECNET_SOCKET);
CLASS_SET(HM_SECCLASS_ATMSVC_SOCKET);
CLASS_SET(HM_SECCLASS_RDS_SOCKET);
CLASS_SET(HM_SECCLASS_IRDA_SOCKET);
CLASS_SET(HM_SECCLASS_PPPOX_SOCKET);
CLASS_SET(HM_SECCLASS_LLC_SOCKET);
CLASS_SET(HM_SECCLASS_CAN_SOCKET);
CLASS_SET(HM_SECCLASS_TIPC_SOCKET);
CLASS_SET(HM_SECCLASS_BLUETOOTH_SOCKET);
CLASS_SET(HM_SECCLASS_IUCV_SOCKET);
CLASS_SET(HM_SECCLASS_RXRPC_SOCKET);
CLASS_SET(HM_SECCLASS_ISDN_SOCKET);
CLASS_SET(HM_SECCLASS_PHONET_SOCKET);
CLASS_SET(HM_SECCLASS_IEEE802154_SOCKET);
CLASS_SET(HM_SECCLASS_CAIF_SOCKET);
CLASS_SET(HM_SECCLASS_ALG_SOCKET);
CLASS_SET(HM_SECCLASS_NFC_SOCKET);
CLASS_SET(HM_SECCLASS_VSOCK_SOCKET);
CLASS_SET(HM_SECCLASS_KCM_SOCKET);
CLASS_SET(HM_SECCLASS_QIPCRTR_SOCKET);
CLASS_SET(HM_SECCLASS_SMC_SOCKET);
CLASS_SET(HM_SECCLASS_INFINIBAND_PKEY);
CLASS_SET(HM_SECCLASS_INFINIBAND_ENDPORT);
CLASS_SET(HM_SECCLASS_BPF);
CLASS_SET(HM_SECCLASS_XDP_SOCKET);

#endif
