/*
 * Copyright (c) Huawei Technologies CO., Ltd. 2019-2020. All rights reserved.
 * Description: bbox_diaginfo_map.h
 * Author: Hisilicon
 * Create: 2019-10-29
 */
#ifndef __DIAGINFO_MAP
#define __DIAGINFO_MAP(x,y,z,k)
#endif

#ifndef __DIAGINFO_MODULE_MAP
#define __DIAGINFO_MODULE_MAP(x)
#endif

// X: Error id, Y:Module , Z: Log level, K: error type
__DIAGINFO_MAP(L3_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(L3_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU0_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU1_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU2_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU3_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU4_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU5_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU6_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU7_L1_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU0_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU1_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU2_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU3_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU4_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU5_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU6_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU7_L2_ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU0_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU1_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU2_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU3_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU4_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU5_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU6_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU7_L1_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU0_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU1_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU2_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU3_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU4_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU5_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU6_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(CPU7_L2_ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(ECC_CE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(ECC_DE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(ECC_UE, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(ACPU_LIT_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_MID_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_BIG_AVS_VAL, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL0_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL0_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_L3_SH_PV, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_L3_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL3_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL4_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL5_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL0_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL1_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL2_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL3_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL4_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(ACPU_CL5_DFV_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(DMD_SOC_ACPU_LU_SH_CNT, SoC_AP, INFO, HW)
__DIAGINFO_MAP(CPU_UP_FAIL, SoC_AP, CRITICAL, HW)
__DIAGINFO_MAP(CPU_PANIC_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(NOC_FAULT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(QIC_FAULT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(SERROR_FAULT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(AP_WDT_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(LPM3_EXC_INFO, SoC_AP, CRITICAL, SW)
__DIAGINFO_MAP(BLOCK_DMD_CP_IO, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(BLOCK_DMD_NORMAL_IO, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(MSPC_SECFLASH_ERR_INFO, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(MSPC_SECFLASH_WARN_INFO, SoC_AP, WARNING, SW)
__DIAGINFO_MAP(MSPC_DIAG_INFO, SoC_AP, WARNING, SW)
__DIAGINFO_MAP(MSPC_PIN_ERROR, SoC_AP, WARNING, SW)
__DIAGINFO_MAP(FBE_DIAG_FAIL_ID, SoC_AP, WARNING, SW)
__DIAGINFO_MAP(LPM3_PERI_PA_SENSOR, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(DMD_PERI_AVS_VAL, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(LOWPOWER_GPU_AVS_VAL, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(LOWPOWER_GPU_PA_SENSOR, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(LOWPOWER_NPU_AVS_VAL, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(DMD_NPU_PA_SENSOR, SoC_AP, WARNING, HW)
__DIAGINFO_MAP(LPM3_DDR_FAIl, DDR, CRITICAL, HW)
__DIAGINFO_MAP(LPM3_DDR_PA_SENSOR, DDR, WARNING, HW)
__DIAGINFO_MAP(LPM3_DDR_TRAINING, DDR, WARNING, HW)
__DIAGINFO_MAP(LPM3_DDR_AVS_VAL, DDR, WARNING, HW)

__DIAGINFO_MAP(PERI_SH_PV, SOC_PERI, INFO, HW)
__DIAGINFO_MAP(PERI_SH_CNT, SOC_PERI, INFO, HW)

__DIAGINFO_MAP(IGS_DMD_FDUL_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_FDUL_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_HWTS_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_HWTS_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_AIC_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_AIC_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_PW_ON, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_PW_OFF, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_IR_PW, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_CAM_TIMEOUT, FDUL, WARNING, HW)
__DIAGINFO_MAP(IGS_DMD_SLEEP_FUSION, FDUL, WARNING, SW)
__DIAGINFO_MAP(IGS_DMD_NPU_PLL_RETRY, FDUL, WARNING, SW)

__DIAGINFO_MAP(IOMCU_EXC_INFO, IOMCU_SH, WARNING, HW)

/* DSS START */
__DIAGINFO_MAP(DMD_DSS_SCL_LAYER, DSS, INFO, SW)
__DIAGINFO_MAP(DMD_DSS_ROT_LAYER, DSS, INFO, SW)
__DIAGINFO_MAP(DMD_DSS_LBUF_INFO, DSS, INFO, SW)
__DIAGINFO_MAP(DMD_DSS_POLICY_INFO, DSS, INFO, SW)
__DIAGINFO_MAP(DMD_DSS_DSI_FAULT, DSS, CRITICAL, SW)
__DIAGINFO_MAP(DMD_SOC_DSS_DP_ERROR, DSS, WARNING, HW)
__DIAGINFO_MAP(DMD_SOC_DSS_DP_INFO, DSS, INFO, SW)
__DIAGINFO_MAP(DMD_DSS_SH_VOTE_M1, DSS, CRITICAL, SW)
/* DSS END */

/* HIGPU DMD START */
__DIAGINFO_MAP(DMD_HIGPU_JOB_FAIL,    HIGPU, WARNING, SW)
__DIAGINFO_MAP(DMD_HIGPU_JOB_HANG,    HIGPU, WARNING, SW)
__DIAGINFO_MAP(DMD_HIGPU_ZAP_FAULT,     HIGPU, WARNING, SW)
__DIAGINFO_MAP(DMD_HIGPU_HARD_RESET,    HIGPU, WARNING, SW)
__DIAGINFO_MAP(DMD_HIGPU_PAGE_FAULT,    HIGPU, WARNING, SW)

__DIAGINFO_MAP(DMD_HIGPU_BUS_FAULT,    HIGPU, WARNING, HW)
__DIAGINFO_MAP(DMD_HIGPU_BIT_STUCK,    HIGPU, WARNING, HW)
__DIAGINFO_MAP(DMD_HIGPU_PW_ONOFF_FAIL, HIGPU, WARNING, HW)
__DIAGINFO_MAP(DMD_HIGPU_FCP_LOAD_FAIL, HIGPU, WARNING, HW)
__DIAGINFO_MAP(DMD_HIGPU_SH_INFO, HIGPU, WARNING, HW)

/* HIGPU DMD END */

/* HISP START */
__DIAGINFO_MAP(DMD_ISP_TIMEOUT_SH_CNT, ISP, INFO, HW)
/* HISP END */

/* HISES START */
__DIAGINFO_MAP(DMD_HISES_CPU_FAULT, HISES, CRITICAL, SW)
__DIAGINFO_MAP(DMD_HISES_HW_ATK, HISES, CRITICAL, HW)
__DIAGINFO_MAP(DMD_HISES_KEY_REG_DUMP, HISES, CRITICAL, HW)
__DIAGINFO_MAP(DMD_HISES_INVOKE_E_RET, HISES, CRITICAL, SW)
__DIAGINFO_MAP(DMD_HISES_FLASH_ECC_1B, HISES, CRITICAL, HW)
__DIAGINFO_MAP(DMD_HISES_FLASH_ECC_2B, HISES, CRITICAL, HW)
__DIAGINFO_MAP(DMD_HISES_FLASH_ECC_E, HISES, CRITICAL, SW)
__DIAGINFO_MAP(DMD_HISES_INFO_EVENT, HISES, WARNING, SW)
/* HISES END */

/* npu START */
__DIAGINFO_MAP(DMD_NPU_SH_PV_CNT, NPU_SH, WARNING, HW)
__DIAGINFO_MAP(DMD_FDUL_SH_PV_CNT, FDUL, WARNING, HW)
/* npu END */

/* ddr_sec */
__DIAGINFO_MAP(DMD_DDR_SEC_CNT, DDR_SEC, WARNING, HW)


/* SC START */
__DIAGINFO_MAP(DMD_SC_ECC_SINGLE_BIT, SC, WARNING, HW)
__DIAGINFO_MAP(DMD_SC_ECC_MULTI_BIT, SC, WARNING, HW)
/* SC END */

/* Module name map */
__DIAGINFO_MODULE_MAP(SoC_AP)
__DIAGINFO_MODULE_MAP(DSS)
__DIAGINFO_MODULE_MAP(DDR)
__DIAGINFO_MODULE_MAP(FDUL)
__DIAGINFO_MODULE_MAP(HIGPU)
__DIAGINFO_MODULE_MAP(ISP)
__DIAGINFO_MODULE_MAP(SOC_PERI)
__DIAGINFO_MODULE_MAP(HISES)
__DIAGINFO_MODULE_MAP(IOMCU_SH)
__DIAGINFO_MODULE_MAP(NPU_SH)
__DIAGINFO_MODULE_MAP(DDR_SEC)
__DIAGINFO_MODULE_MAP(SC)