/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: m3_rdr_ddr_map.h
 * Create: 2023-08-10
 */
#ifndef M3_RDR_DDR_MAP_H
#define M3_RDR_DDR_MAP_H

/*
 * **********************M3 RDR DDR SYSTEM CONTEXT*************************
 * note:
 *       1. When using, please judge whether M3_RDR_SYS_CONTEXT_BASE_ADDR is NULL or 0
 *
 *       2. On the kernel side, the address is the virtual address of ioremap
 *          Legacy side, the actual ddr physical address
 *          lpmcu side is the actual ddr physical address
 * ---------------------------------------------------------------------------
 * Addr:               Contents:                              Size:
 * 0x00000 ~ 0x00080   rdr_mem_map_index                      (0x80)
 * 0x00080 ~ 0x00100   exc_special                            (0x80)
 * 0x00100 ~ 0x00200   sys context head                       (0x100)
 * 0x00200 ~ 0x00600   m3 core regs                           (0x400)
 * 0x00600 ~ 0x04000   m3 nvic regs                           (0x3A00)
 * 0x04000 ~ 0x05000   m3 text logs                           (0x1000)
 * 0x05000 ~ 0x05400   m3 private logs                        (0x400)
 * 0x05400 ~ 0x05800   peri ip regs (ddr, sysnoc, etc..)      (0x400)
 * 0x05800 ~ 0x05900   run time var reserved                  (0x100)
 * 0x05900 ~ 0x06900   lpmcu stat                             (0x1000)
 * 0x06900 ~ 0x06B00   kernel stat                            (0x200)
 * 0x06B00 ~ 0x07A00   expose storage                         (0xF00)
 * 0x07A00 ~ 0x07C00   noc regs                               (0x200)
 * 0x07C00 ~ 0x08000   run time var                           (0x400)
 * 0x08000 ~ 0x09000   crg peri                               (0x1000)
 * 0x09000 ~ 0x0A000   sctrl                                  (0x1000)
 * 0x0A000 ~ 0x0B000   pmctrl                                 (0x1000)
 * 0x0B000 ~ 0x0D000   pctrl                                  (0x2000)
 * 0x0D000 ~ 0x0E000   actrl                                  (0x1000)
 * 0x0E000 ~ 0x0E100   iomcu regs                             (0x100)
 * 0x0E100 ~ 0x0ED00   ddr regs                               (0xC00)
 * 0x0ED00 ~ 0x0EE00   pmu regs                               (0x100)
 * 0x0EE00 ~ 0x10200   ddr mntn                               (0x1400)
 * 0x10200 ~ 0x10470   little cluster profile                 (0x270)
 * 0x10470 ~ 0x106E0   mid cluster profile                    (0x270)
 * 0x106E0 ~ 0x10950   big base profile                       (0x270)
 * 0x10950 ~ 0x10BC0   l3 base profile                        (0x270)
 * 0x10BC0 ~ 0x10E00   gpu base profile                       (0x240)
 * 0x10E00 ~ 0x17E00   gic regs                               (0x7000)
 * 0x17E00 ~ 0x18A00   periavs_para                           (0xC00)
 * 0x18A00 ~ 0x18C00   aoavs_para                             (0x200)
 * 0x18C00 ~ 0x19900   aotcp                                  (0xD00)
 * 0x19900 ~ 0x1A900   cpu pmc                                (0x1000)
 * 0x1A900 - 0x1B900   gpu pmc                                (0x1000)
 * 0x1B900 - 0x1BEA0   ddr vote time                          (0x5A0)
 * 0x1BEA0 - 0x1C2A0   ddr lowtemp time                       (0x400)
 * 0x1C2A0 - 0x242A0   cxpu ram                               (0x8000)
 * 0x242A0 - 0x2C2A0   gxpu ram                               (0x8000)
 * 0x2C2A0 - 0x2C6A0   sr info                                (0x400)
 * 0x2C6A0 - 0x2D6A0   ipc track                              (0x1000)
 * 0x2D6A0 - 0x2D720   thermal freq limit                     (0x80)
 * 0x2D720 - 0x2E720   LPCS                                   (0x1000)
 * 0x2E720 - 0x2F720   FCM_LOCAL_PERI                         (0x1000)
 * 0x2F720 - 0x2F820   RSV_CORE                               (0x100)
 * 0x2F820 - 0x2F940   sc info                                (0x120)
 * 0x2F940 ~ 0x30000   reserved                               (0x6C0)
 * 0x30000 ~ 0x62000   m3 sys image                           (0x32000=200k)
 */

#define M3_RDR_SYS_CONTEXT_BASE_ADDR				0
#define M3_RDR_SYS_CONTEXT_SIZE					0x90000

/* 0x0 */
#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_OFFSET		0x0U
/* 0x0 */
#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR)
#define M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_SIZE		0x80

#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET \
	(M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_OFFSET + M3_RDR_SYS_CONTEXT_RDR_MEM_MAP_INDEX_SIZE)
/* 0x80 */
#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET)
#define M3_RDR_SYS_CONTEXT_EXC_SPECIAL_SIZE	0x80

#define M3_RDR_SYS_CONTEXT_HEAD_OFFSET	(M3_RDR_SYS_CONTEXT_EXC_SPECIAL_OFFSET + M3_RDR_SYS_CONTEXT_EXC_SPECIAL_SIZE)
/* 0x100 */
#define M3_RDR_SYS_CONTEXT_HEAD_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_HEAD_OFFSET)
#define M3_RDR_SYS_CONTEXT_HEAD_SIZE		0x100

#define M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET	(M3_RDR_SYS_CONTEXT_HEAD_OFFSET + M3_RDR_SYS_CONTEXT_HEAD_SIZE)
/* 0x200 */
#define M3_RDR_SYS_CONTEXT_M3_COREREG_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET)
#define M3_RDR_SYS_CONTEXT_M3_COREREG_SIZE	0x400

#define M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET \
	(M3_RDR_SYS_CONTEXT_M3_COREREG_OFFSET + M3_RDR_SYS_CONTEXT_M3_COREREG_SIZE)
/* 0x600 */
#define M3_RDR_SYS_CONTEXT_M3_NVICREG_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET)
#define M3_RDR_SYS_CONTEXT_M3_NVICREG_SIZE	(0x3A00)

#define M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET \
	(M3_RDR_SYS_CONTEXT_M3_NVICREG_OFFSET + M3_RDR_SYS_CONTEXT_M3_NVICREG_SIZE)
/* 0x4000 */
#define M3_RDR_SYS_CONTEXT_M3_LOG_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET)
#define M3_RDR_SYS_CONTEXT_M3_LOG_SIZE		0x1000

#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET \
	(M3_RDR_SYS_CONTEXT_M3_LOG_OFFSET + M3_RDR_SYS_CONTEXT_M3_LOG_SIZE)
/* 0x5000 */
#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_ADDR \
	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET)
#define M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_SIZE	0x400

#define M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET \
	(M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_OFFSET + M3_RDR_SYS_CONTEXT_M3_PRIVATE_DATA_SIZE)
/* 0x5400 */
#define M3_RDR_SYS_CONTEXT_PERI_IPREG_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET)
#define M3_RDR_SYS_CONTEXT_PERI_IPREG_SIZE	0x400

#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET \
	(M3_RDR_SYS_CONTEXT_PERI_IPREG_OFFSET + M3_RDR_SYS_CONTEXT_PERI_IPREG_SIZE)
/* 0x5800 */
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_ADDR \
	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET)
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_SIZE	0x100

#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET \
	(M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_OFFSET + M3_RDR_SYS_CONTEXT_RUNTIME_VAR_RESERVED_SIZE)
/* 0x5900 */
#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET)
#define M3_RDR_SYS_CONTEXT_LPMCU_STAT_SIZE	0x1000

#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET \
	(M3_RDR_SYS_CONTEXT_LPMCU_STAT_OFFSET + M3_RDR_SYS_CONTEXT_LPMCU_STAT_SIZE)
/* 0x6900 */
#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET)
#define M3_RDR_SYS_CONTEXT_KERNEL_STAT_SIZE	0x200

#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET \
	(M3_RDR_SYS_CONTEXT_KERNEL_STAT_OFFSET + M3_RDR_SYS_CONTEXT_KERNEL_STAT_SIZE)
/* 0x6B00 */
#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR +M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET)
#define M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_SIZE	0xF00

#define M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET \
	(M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_OFFSET + M3_RDR_SYS_CONTEXT_EXPOSE_STORAGE_SIZE)
/* 0x7A00 */
#define M3_RDR_SYS_CONTEXT_NOC_REG_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET)
#define M3_RDR_SYS_CONTEXT_NOC_REG_SIZE		0x200

#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET	(M3_RDR_SYS_CONTEXT_NOC_REG_OFFSET + M3_RDR_SYS_CONTEXT_NOC_REG_SIZE)
/* 0x7C00 */
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET)
#define M3_RDR_SYS_CONTEXT_RUNTIME_VAR_SIZE	0x400

#define M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET \
	(M3_RDR_SYS_CONTEXT_RUNTIME_VAR_OFFSET + M3_RDR_SYS_CONTEXT_RUNTIME_VAR_SIZE)
/* 0x8000 */
#define M3_RDR_SYS_CONTEXT_MODEM_DATA_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET)
#define M3_RDR_SYS_CONTEXT_MODEM_DATA_SIZE	0x0

#define M3_RDR_CRG_PERI_OFFSET		(M3_RDR_SYS_CONTEXT_MODEM_DATA_OFFSET + M3_RDR_SYS_CONTEXT_MODEM_DATA_SIZE)
/* 0x8000 */
#define M3_RDR_CRG_PERI_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_CRG_PERI_OFFSET)
#define M3_RDR_CRG_PERI_SIZE			0x1000

#define M3_RDR_SCTRL_OFFSET			(M3_RDR_CRG_PERI_OFFSET + M3_RDR_CRG_PERI_SIZE)
/* 0x9000 */
#define M3_RDR_SCTRL_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SCTRL_OFFSET)
#define M3_RDR_SCTRL_SIZE			0x1000

#define M3_RDR_PMCTRL_OFFSET			(M3_RDR_SCTRL_OFFSET + M3_RDR_SCTRL_SIZE)
/* 0xA000 */
#define M3_RDR_PMCTRL_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMCTRL_OFFSET)
#define M3_RDR_PMCTRL_SIZE			0x1000

#define M3_RDR_PCTRL_OFFSET			(M3_RDR_PMCTRL_OFFSET + M3_RDR_PMCTRL_SIZE)
/* 0xB000 */
#define M3_RDR_PCTRL_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PCTRL_OFFSET)
#define M3_RDR_PCTRL_SIZE			0x2000

#define M3_RDR_ACTRL_OFFSET			(M3_RDR_PCTRL_OFFSET + M3_RDR_PCTRL_SIZE)
/* 0xD000 */
#define M3_RDR_ACTRL_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_ACTRL_OFFSET)
#define M3_RDR_ACTRL_SIZE			0x1000

#define M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET	(M3_RDR_ACTRL_OFFSET + M3_RDR_ACTRL_SIZE)
/* 0xE000 */
#define M3_RDR_SYS_CONTEXT_IOMCU_REG_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET)
#define M3_RDR_SYS_CONTEXT_IOMCU_REG_SIZE	0x100

#define M3_RDR_DDR_REG_OFFSET		(M3_RDR_SYS_CONTEXT_IOMCU_REG_OFFSET + M3_RDR_SYS_CONTEXT_IOMCU_REG_SIZE)
/* 0xE100 */
#define M3_RDR_DDR_REG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_DDR_REG_OFFSET)
#define M3_RDR_DDR_REG_SIZE			0xC00

#define M3_RDR_PMU_REG_OFFSET			(M3_RDR_DDR_REG_OFFSET + M3_RDR_DDR_REG_SIZE)
/* 0xED00 */
#define M3_RDR_PMU_REG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMU_REG_OFFSET)
#define M3_RDR_PMU_REG_SIZE			0x100

/* ddr mntn used 5K in fastboot */
#define M3_RDR_DDR_MNTN_OFFSET			(M3_RDR_PMU_REG_OFFSET + M3_RDR_PMU_REG_SIZE)
/* 0xEE00 */
#define M3_RDR_DDR_MNTN_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_DDR_MNTN_OFFSET)
#define M3_RDR_DDR_MNTN_SIZE			(5 * 1024)

/* save big/little/GPU profile */
#define M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET	(M3_RDR_DDR_MNTN_OFFSET + M3_RDR_DDR_MNTN_SIZE)
/* 0x10200 */
#define M3_RDR_LITTLE_CLUSTER_PROFILE_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET)
#define M3_RDR_LITTLE_CLUSTER_PROFILE_SIZE	0X270

#define M3_RDR_MID_CLUSTER_PROFILE_OFFSET \
	(M3_RDR_LITTLE_CLUSTER_PROFILE_OFFSET + M3_RDR_LITTLE_CLUSTER_PROFILE_SIZE)
/* 0x10470 */
#define M3_RDR_MID_CLUSTER_PROFILE_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_MID_CLUSTER_PROFILE_OFFSET)
#define M3_RDR_MID_CLUSTER_PROFILE_SIZE		0X270

#define M3_RDR_BIG_CLUSTER_PROFILE_OFFSET	(M3_RDR_MID_CLUSTER_PROFILE_OFFSET + M3_RDR_MID_CLUSTER_PROFILE_SIZE)
/* 0x106E0 */
#define M3_RDR_BIG_CLUSTER_PROFILE_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_BIG_CLUSTER_PROFILE_OFFSET)
#define M3_RDR_BIG_CLUSTER_PROFILE_SIZE		0X270

#define M3_RDR_L3_CLUSTER_PROFILE_OFFSET	(M3_RDR_BIG_CLUSTER_PROFILE_OFFSET + M3_RDR_BIG_CLUSTER_PROFILE_SIZE)
/* 0x10950 */
#define M3_RDR_L3_CLUSTER_PROFILE_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_L3_CLUSTER_PROFILE_OFFSET)
#define M3_RDR_L3_CLUSTER_PROFILE_SIZE		0X270

#define M3_RDR_GPU_BASE_PROFILE_OFFSET		(M3_RDR_L3_CLUSTER_PROFILE_OFFSET + M3_RDR_L3_CLUSTER_PROFILE_SIZE)
/* 0x10BC0 */
#define M3_RDR_GPU_BASE_PROFILE_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_GPU_BASE_PROFILE_OFFSET)
#define M3_RDR_GPU_BASE_PROFILE_SIZE		0X240

#define M3_RDR_GIC_REG_OFFSET			(M3_RDR_GPU_BASE_PROFILE_OFFSET + M3_RDR_GPU_BASE_PROFILE_SIZE)
/* 0x10E00 */
#define M3_RDR_GIC_REG_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_GIC_REG_OFFSET)
#define M3_RDR_GIC_REG_SIZE			0x7000

#define M3_RDR_PERIAVS_PARA_OFFSET		(M3_RDR_GIC_REG_OFFSET + M3_RDR_GIC_REG_SIZE)
/* 0x17E00 */
#define M3_RDR_PERIAVS_PARA_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PERIAVS_PARA_OFFSET)
#define M3_RDR_PERIAVS_PARA_SIZE		0xC00

#define M3_RDR_AOAVS_PARA_OFFSET		(M3_RDR_PERIAVS_PARA_OFFSET + M3_RDR_PERIAVS_PARA_SIZE)
/* 0x18A00 */
#define M3_RDR_AOAVS_PARA_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_AOAVS_PARA_OFFSET)
#define M3_RDR_AOAVS_PARA_SIZE			0x200

#define M3_RDR_AOTCP_OFFSET			(M3_RDR_AOAVS_PARA_OFFSET + M3_RDR_AOAVS_PARA_SIZE)
/* 0x18C00 */
#define M3_RDR_AOTCP_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_AOTCP_OFFSET)
#define M3_RDR_AOTCP_SIZE			0xD00

#define M3_RDR_PMCTRL_CPU_OFFSET		(M3_RDR_AOTCP_OFFSET + M3_RDR_AOTCP_SIZE)
/* 0x19900 */
#define M3_RDR_PMCTRL_CPU_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMCTRL_CPU_OFFSET)
#define M3_RDR_PMCTRL_CPU_SIZE			0x1000

#define M3_RDR_PMCTRL_GPU_OFFSET		(M3_RDR_PMCTRL_CPU_OFFSET + M3_RDR_PMCTRL_CPU_SIZE)
/* 0x1A900 */
#define M3_RDR_PMCTRL_GPU_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_PMCTRL_GPU_OFFSET)
#define M3_RDR_PMCTRL_GPU_SIZE			0x1000

#define M3_RDR_DDR_VOTE_TIME_OFFSET		(M3_RDR_PMCTRL_GPU_OFFSET + M3_RDR_PMCTRL_GPU_SIZE)
/* 0x1B900 */
#define M3_RDR_DDR_VOTE_TIME_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_DDR_VOTE_TIME_OFFSET)
#define M3_RDR_DDR_VOTE_TIME_SIZE		0x5A0

#define M3_RDR_DDR_LOWPOWER_TIME_OFFSET		(M3_RDR_DDR_VOTE_TIME_OFFSET + M3_RDR_DDR_VOTE_TIME_SIZE)
#define M3_RDR_DDR_LOWPOWER_TIME_ADDR \
	(M3_RDR_SYS_CONTEXT_BASE_ADDR +  M3_RDR_DDR_LOWPOWER_TIME_OFFSET) /* 0x1BEA0 */
#define M3_RDR_DDR_LOWPOWER_TIME_SIZE		0x400

#define M3_RDR_CXPU_RAM_OFFSET			(M3_RDR_DDR_LOWPOWER_TIME_OFFSET + M3_RDR_DDR_LOWPOWER_TIME_SIZE)
/* 0x1C2A0 */
#define M3_RDR_CXPU_RAM_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_CXPU_RAM_OFFSET)
#define M3_RDR_CXPU_RAM_SIZE			0x8000
#define M3_RDR_CXPU_SEC_DATA_OFFSET		(M3_RDR_CXPU_RAM_OFFSET + 0xB40)
#define M3_RDR_CXPU_SEC_DATA_SIZE		0x1000

#define M3_RDR_GXPU_RAM_OFFSET			(M3_RDR_CXPU_RAM_OFFSET + M3_RDR_CXPU_RAM_SIZE)
#define M3_RDR_GXPU_DATA_SIZE			0xA00
/* 0x242A0 */
#define M3_RDR_GXPU_RAM_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_GXPU_RAM_OFFSET)
#define M3_RDR_GXPU_RAM_SIZE			0x8000

/* 0x2C2A0 */
#define M3_RDR_SR_INFO_OFFSET			(M3_RDR_GXPU_RAM_OFFSET + M3_RDR_GXPU_RAM_SIZE)
#define M3_RDR_SR_INFO_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SR_INFO_OFFSET)
#define M3_RDR_SR_INFO_SIZE			(0x400)

/* 0x2C6A0 */
#define M3_RDR_IPC_TRACK_OFFSET			(M3_RDR_SR_INFO_OFFSET + M3_RDR_SR_INFO_SIZE)
#define M3_RDR_IPC_TRACK_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_IPC_TRACK_OFFSET)
#define M3_RDR_IPC_TRACK_SIZE			(0x1000)

/* 0x2D6A0 */
#define M3_RDR_THERMAL_FREQ_LIMIT_OFFSET (M3_RDR_IPC_TRACK_OFFSET + M3_RDR_IPC_TRACK_SIZE)
#define M3_RDR_THERMAL_FREQ_LIMIT_ADDR	 (M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_THERMAL_FREQ_LIMIT_OFFSET)
#define M3_RDR_THERMAL_FREQ_LIMIT_SIZE	 (0x80)

/* 0x2D720 */
#define M3_RDR_LPCS_OFFSET			(M3_RDR_THERMAL_FREQ_LIMIT_OFFSET + M3_RDR_THERMAL_FREQ_LIMIT_SIZE)
#define M3_RDR_LPCS_ADDR			(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_LPCS_OFFSET)
#define M3_RDR_LPCS_SIZE			(0x1000)

/* 0x2E720 */
#define M3_RDR_FCM_LOCAL_PERI_OFFSET	(M3_RDR_LPCS_OFFSET + M3_RDR_LPCS_SIZE)
#define M3_RDR_FCM_LOCAL_PERI_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_FCM_LOCAL_PERI_OFFSET)
#define M3_RDR_FCM_LOCAL_PERI_SIZE		(0x1000)

/* 0x2F720 */
#define M3_RDR_RSV_CORE_STAT_OFFSET		(M3_RDR_FCM_LOCAL_PERI_OFFSET + M3_RDR_FCM_LOCAL_PERI_SIZE)
#define M3_RDR_RSV_CORE_STAT_ADDR		(M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_RSV_CORE_STAT_OFFSET)
#define M3_RDR_RSV_CORE_STAT_SIZE		(0x100)

/* 0x2F820 */
#define M3_RDR_SC_DFX_INFO_OFFSET		(M3_RDR_RSV_CORE_STAT_OFFSET + M3_RDR_RSV_CORE_STAT_SIZE)
#define M3_RDR_SC_DFX_INFO_ADDR		    (M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SC_DFX_INFO_OFFSET)
#define M3_RDR_SC_DFX_INFO_SIZE		    (0x120)

/* 0x2F940 */
#define M3_RDR_SYS_CONTEXT_RESERVED_ADDR	(M3_RDR_SC_DFX_INFO_ADDR + M3_RDR_SC_DFX_INFO_SIZE)

#if ((M3_RDR_SYS_CONTEXT_RESERVED_ADDR) > (M3_RDR_SYS_CONTEXT_BASE_ADDR + 0x30000))
#error "rdr space overflow! please reorganize the rdr space"
#endif

/* m3 sysimage at the last 200K sys img offset 0x30000 */
#define M3_RDR_SYS_CONTEXT_M3_IMAGE_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + 0x30000)
#define M3_RDR_SYS_CONTEXT_M3_IMAGE_SIZE	0x32000

#define M3_RDR_SR_GPIO_DEBUG_ADDR			(M3_RDR_SYS_CONTEXT_M3_IMAGE_ADDR)
#define M3_RDR_SR_GPIO_DEBUG_SIZE			0x2800
/* ddr mntn user used 28K in fastboot */
#define M3_RDR_DDR_MNTN_USER_SAVE_OFFSET		(M3_RDR_SR_GPIO_DEBUG_SIZE + 0x30000)
#define M3_RDR_DDR_MNTN_USER_SAVE_ADDR			(M3_RDR_SR_GPIO_DEBUG_ADDR + M3_RDR_SR_GPIO_DEBUG_SIZE)
#define M3_RDR_DDR_MNTN_USER_SAVE_SIZE			(28 * 1024)

/* acpu djtag save offset 0x70000 */
#define M3_RDR_ACPU_DJTAG_SAVE_ADDR	(M3_RDR_SYS_CONTEXT_BASE_ADDR + 0x70000)
#define M3_RDR_ACPU_DJTAG_CUR_SIZE 0xc000
#define M3_RDR_ACPU_DJTAG_SAVE_SIZE	0x20000

#if ((M3_RDR_ACPU_DJTAG_SAVE_ADDR + M3_RDR_ACPU_DJTAG_SAVE_SIZE) > (M3_RDR_SYS_CONTEXT_BASE_ADDR + M3_RDR_SYS_CONTEXT_SIZE))
#error "rdr space overflow! please reorganize the space"
#endif

#undef M3_RDR_SYS_CONTEXT_BASE_ADDR
#if defined(__KERNEL__)
#if defined(CONFIG_LPMCU_BB)
extern char *g_lpmcu_rdr_ddr_addr;
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        g_lpmcu_rdr_ddr_addr
#else
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        0
#endif
#elif defined(__CMSIS_RTOS)
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        LPM3_RDR_DDR_ADDR
#elif defined(CONFIG_BL31_LOAD_LPMCU) || defined(CONFIG_LOAD_LPMCU_TZSP)
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        LPM3_RDR_DDR_ADDR
#else
#define M3_RDR_SYS_CONTEXT_BASE_ADDR                        0
#endif

#endif /* __M3_RDR_DDR_MAP_H__ */
