/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2001-2021. All rights reserved.
 *
 * Description: file name soc_idi2axi_interface.h
 * Author     : Generated by tool
 * Create     : 2021-10-23 11:05:40
 */

/*****************************************************************************
  1 其他头文件包含
*****************************************************************************/

#ifndef __SOC_IDI2AXI_INTERFACE_H__
#define __SOC_IDI2AXI_INTERFACE_H__

#ifdef __cplusplus
    #if __cplusplus
        extern "C" {
    #endif
#endif



/*****************************************************************************
  2 宏定义
*****************************************************************************/

/****************************************************************************
                     (1/1) reg_define
 ****************************************************************************/
#ifndef __SOC_H_FOR_ASM__


/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR0_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR0_LOW_ADDR(base)             ((base) + (0x000UL))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR0_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR0_HIGH_ADDR(base)            ((base) + (0x004UL))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR1_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR1_LOW_ADDR(base)             ((base) + (0x008UL))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR1_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR1_HIGH_ADDR(base)            ((base) + (0x00CUL))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR2_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR2_LOW_ADDR(base)             ((base) + (0x010UL))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR2_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR2_HIGH_ADDR(base)            ((base) + (0x014UL))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR3_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR3_LOW_ADDR(base)             ((base) + (0x018UL))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR3_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR3_HIGH_ADDR(base)            ((base) + (0x01CUL))

/* 寄存器说明：帧个数寄存器。用于设置本次启动IDI2AXI接受几帧指纹数据。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_NUM_UNION */
#define SOC_IDI2AXI_FRAME_NUM_ADDR(base)                      ((base) + (0x0020UL))

/* 寄存器说明：帧结束标识寄存器。
            用于设置64bit帧结束flag的低32bit。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_LOW_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_LOW_ADDR(base)             ((base) + (0x0024UL))

/* 寄存器说明：帧结束标识寄存器。
            用于设置64bit帧结束flag的高32bit。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_HIGH_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_HIGH_ADDR(base)            ((base) + (0x0028UL))

/* 寄存器说明：帧结束标识使能寄存器。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_ADDR(base)          ((base) + (0x002CUL))

/* 寄存器说明：IDI2AXI配置寄存器。
            用于设置IDI2AXI所支持的功能相关参数。
   位域定义UNION结构:  SOC_IDI2AXI_CFG_UNION */
#define SOC_IDI2AXI_CFG_ADDR(base)                            ((base) + (0x0030UL))

/* 寄存器说明：masterID设置寄存器。
   位域定义UNION结构:  SOC_IDI2AXI_MID_UNION */
#define SOC_IDI2AXI_MID_ADDR(base)                            ((base) + (0x0034UL))

/* 寄存器说明：QoS设置寄存器。用于设置发送不同awqos的水线。
   位域定义UNION结构:  SOC_IDI2AXI_QOS_CFG0_UNION */
#define SOC_IDI2AXI_QOS_CFG0_ADDR(base)                       ((base) + (0x0038UL))

/* 寄存器说明：QoS设置寄存器。用于设置发送不同awqos的水线。
   位域定义UNION结构:  SOC_IDI2AXI_QOS_CFG1_UNION */
#define SOC_IDI2AXI_QOS_CFG1_ADDR(base)                       ((base) + (0x003CUL))

/* 寄存器说明：流控请求水线设置寄存器。
            用于设置非DDR DVFS期间拉起和拉低流控请求的水线。
   位域定义UNION结构:  SOC_IDI2AXI_FLUX_REQ_CFG_UNION */
#define SOC_IDI2AXI_FLUX_REQ_CFG_ADDR(base)                   ((base) + (0x0040UL))

/* 寄存器说明：timeout计时器设置寄存器
   位域定义UNION结构:  SOC_IDI2AXI_TIMER_UNION */
#define SOC_IDI2AXI_TIMER_ADDR(base)                          ((base) + (0x0044UL))

/* 寄存器说明：中断使能寄存器。
            0：屏蔽中断；
            1：使能中断；
   位域定义UNION结构:  SOC_IDI2AXI_INT_EN_UNION */
#define SOC_IDI2AXI_INT_EN_ADDR(base)                         ((base) + (0x0048UL))

/* 寄存器说明：中断原始状态寄存器。
            读返回中断屏蔽前的原始状态。
            0：有中断；
            1：无中断；
            写无效。
   位域定义UNION结构:  SOC_IDI2AXI_INT_RAW_UNION */
#define SOC_IDI2AXI_INT_RAW_ADDR(base)                        ((base) + (0x004CUL))

/* 寄存器说明：中断屏蔽后的状态寄存器。
            0：有中断；
            1：无中断；
            读返回中断屏蔽后的状态。
            0：有中断；
            1：无中断；
            写无效。
   位域定义UNION结构:  SOC_IDI2AXI_INT_MSK_UNION */
#define SOC_IDI2AXI_INT_MSK_ADDR(base)                        ((base) + (0x0050UL))

/* 寄存器说明：中断清除寄存器。
            写1清除中断，写0无效。
            读总是返回0x0。
   位域定义UNION结构:  SOC_IDI2AXI_INT_CLR_UNION */
#define SOC_IDI2AXI_INT_CLR_ADDR(base)                        ((base) + (0x0054UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT0_UNION */
#define SOC_IDI2AXI_STAT0_ADDR(base)                          ((base) + (0x0058UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT1_UNION */
#define SOC_IDI2AXI_STAT1_ADDR(base)                          ((base) + (0x005CUL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT2_UNION */
#define SOC_IDI2AXI_STAT2_ADDR(base)                          ((base) + (0x0060UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT3_UNION */
#define SOC_IDI2AXI_STAT3_ADDR(base)                          ((base) + (0x0064UL))

/* 寄存器说明：内部buffer溢出水线设置寄存器。
            当内部buffer数据个数大于或者等于该寄存器设置值时，认为buffer溢出。
   位域定义UNION结构:  SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_UNION */
#define SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_ADDR(base)          ((base) + (0x0068UL))

/* 寄存器说明：memory时序控制寄存器。
            用于设置模块内部模块的低功耗和时序控制。
   位域定义UNION结构:  SOC_IDI2AXI_MEM_CTRL_UNION */
#define SOC_IDI2AXI_MEM_CTRL_ADDR(base)                       ((base) + (0x006CUL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT4_UNION */
#define SOC_IDI2AXI_STAT4_ADDR(base)                          ((base) + (0x0070UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT5_UNION */
#define SOC_IDI2AXI_STAT5_ADDR(base)                          ((base) + (0x0074UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT6_UNION */
#define SOC_IDI2AXI_STAT6_ADDR(base)                          ((base) + (0x0078UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT7_UNION */
#define SOC_IDI2AXI_STAT7_ADDR(base)                          ((base) + (0x007CUL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT8_UNION */
#define SOC_IDI2AXI_STAT8_ADDR(base)                          ((base) + (0x0080UL))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT9_UNION */
#define SOC_IDI2AXI_STAT9_ADDR(base)                          ((base) + (0x0084UL))

/* 寄存器说明：IDI2AXI启动寄存器。初始化IDI2AXI的最后一步，配置该寄存器为1之后，模块内部按照设置好的参数从CSI接受数据，并写入DDR，写完后将该寄存器bit拉低，表示处理完成。
   位域定义UNION结构:  SOC_IDI2AXI_EN_UNION */
#define SOC_IDI2AXI_EN_ADDR(base)                             ((base) + (0x00FCUL))

/* 寄存器说明：安全数据设置寄存器。
            该寄存器仅允许安全操作访问。用于设置IDI2AXI的APB配置接口中除该寄存器以外的安全属性，以及设置AXI写数据接口的安全属性。
   位域定义UNION结构:  SOC_IDI2AXI_SEC_UNION */
#define SOC_IDI2AXI_SEC_ADDR(base)                            ((base) + (0x0100UL))

/* 寄存器说明：used to configure the sensor (Height, Width, Start/Stop)，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CFG_UNION */
#define SOC_IDI2AXI_SENSORGEN_CFG_ADDR(base)                  ((base) + (0x290UL))

/* 寄存器说明：used to control the speed of the sensor generator (PCLK, blanking)，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CTRL_1_UNION */
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_ADDR(base)               ((base) + (0x294UL))

/* 寄存器说明：used to control the vsize and hsize，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CTRL_2_UNION */
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_ADDR(base)               ((base) + (0x298UL))

/* 寄存器说明：used to control the pixel data，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_DATA_UNION */
#define SOC_IDI2AXI_SENSORGEN_DATA_ADDR(base)                 ((base) + (0x29CUL))

/* 寄存器说明：used to know the state of the sensor gen - useful when 1 frame is generrated，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_STATUS_UNION */
#define SOC_IDI2AXI_SENSORGEN_STATUS_ADDR(base)               ((base) + (0x2A0UL))


#else


/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR0_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR0_LOW_ADDR(base)             ((base) + (0x000))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR0_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR0_HIGH_ADDR(base)            ((base) + (0x004))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR1_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR1_LOW_ADDR(base)             ((base) + (0x008))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR1_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR1_HIGH_ADDR(base)            ((base) + (0x00C))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR2_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR2_LOW_ADDR(base)             ((base) + (0x010))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR2_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR2_HIGH_ADDR(base)            ((base) + (0x014))

/* 寄存器说明：起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR3_LOW_UNION */
#define SOC_IDI2AXI_WR_START_ADDR3_LOW_ADDR(base)             ((base) + (0x018))

/* 寄存器说明：起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
   位域定义UNION结构:  SOC_IDI2AXI_WR_START_ADDR3_HIGH_UNION */
#define SOC_IDI2AXI_WR_START_ADDR3_HIGH_ADDR(base)            ((base) + (0x01C))

/* 寄存器说明：帧个数寄存器。用于设置本次启动IDI2AXI接受几帧指纹数据。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_NUM_UNION */
#define SOC_IDI2AXI_FRAME_NUM_ADDR(base)                      ((base) + (0x0020))

/* 寄存器说明：帧结束标识寄存器。
            用于设置64bit帧结束flag的低32bit。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_LOW_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_LOW_ADDR(base)             ((base) + (0x0024))

/* 寄存器说明：帧结束标识寄存器。
            用于设置64bit帧结束flag的高32bit。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_HIGH_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_HIGH_ADDR(base)            ((base) + (0x0028))

/* 寄存器说明：帧结束标识使能寄存器。
   位域定义UNION结构:  SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_UNION */
#define SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_ADDR(base)          ((base) + (0x002C))

/* 寄存器说明：IDI2AXI配置寄存器。
            用于设置IDI2AXI所支持的功能相关参数。
   位域定义UNION结构:  SOC_IDI2AXI_CFG_UNION */
#define SOC_IDI2AXI_CFG_ADDR(base)                            ((base) + (0x0030))

/* 寄存器说明：masterID设置寄存器。
   位域定义UNION结构:  SOC_IDI2AXI_MID_UNION */
#define SOC_IDI2AXI_MID_ADDR(base)                            ((base) + (0x0034))

/* 寄存器说明：QoS设置寄存器。用于设置发送不同awqos的水线。
   位域定义UNION结构:  SOC_IDI2AXI_QOS_CFG0_UNION */
#define SOC_IDI2AXI_QOS_CFG0_ADDR(base)                       ((base) + (0x0038))

/* 寄存器说明：QoS设置寄存器。用于设置发送不同awqos的水线。
   位域定义UNION结构:  SOC_IDI2AXI_QOS_CFG1_UNION */
#define SOC_IDI2AXI_QOS_CFG1_ADDR(base)                       ((base) + (0x003C))

/* 寄存器说明：流控请求水线设置寄存器。
            用于设置非DDR DVFS期间拉起和拉低流控请求的水线。
   位域定义UNION结构:  SOC_IDI2AXI_FLUX_REQ_CFG_UNION */
#define SOC_IDI2AXI_FLUX_REQ_CFG_ADDR(base)                   ((base) + (0x0040))

/* 寄存器说明：timeout计时器设置寄存器
   位域定义UNION结构:  SOC_IDI2AXI_TIMER_UNION */
#define SOC_IDI2AXI_TIMER_ADDR(base)                          ((base) + (0x0044))

/* 寄存器说明：中断使能寄存器。
            0：屏蔽中断；
            1：使能中断；
   位域定义UNION结构:  SOC_IDI2AXI_INT_EN_UNION */
#define SOC_IDI2AXI_INT_EN_ADDR(base)                         ((base) + (0x0048))

/* 寄存器说明：中断原始状态寄存器。
            读返回中断屏蔽前的原始状态。
            0：有中断；
            1：无中断；
            写无效。
   位域定义UNION结构:  SOC_IDI2AXI_INT_RAW_UNION */
#define SOC_IDI2AXI_INT_RAW_ADDR(base)                        ((base) + (0x004C))

/* 寄存器说明：中断屏蔽后的状态寄存器。
            0：有中断；
            1：无中断；
            读返回中断屏蔽后的状态。
            0：有中断；
            1：无中断；
            写无效。
   位域定义UNION结构:  SOC_IDI2AXI_INT_MSK_UNION */
#define SOC_IDI2AXI_INT_MSK_ADDR(base)                        ((base) + (0x0050))

/* 寄存器说明：中断清除寄存器。
            写1清除中断，写0无效。
            读总是返回0x0。
   位域定义UNION结构:  SOC_IDI2AXI_INT_CLR_UNION */
#define SOC_IDI2AXI_INT_CLR_ADDR(base)                        ((base) + (0x0054))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT0_UNION */
#define SOC_IDI2AXI_STAT0_ADDR(base)                          ((base) + (0x0058))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT1_UNION */
#define SOC_IDI2AXI_STAT1_ADDR(base)                          ((base) + (0x005C))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT2_UNION */
#define SOC_IDI2AXI_STAT2_ADDR(base)                          ((base) + (0x0060))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT3_UNION */
#define SOC_IDI2AXI_STAT3_ADDR(base)                          ((base) + (0x0064))

/* 寄存器说明：内部buffer溢出水线设置寄存器。
            当内部buffer数据个数大于或者等于该寄存器设置值时，认为buffer溢出。
   位域定义UNION结构:  SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_UNION */
#define SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_ADDR(base)          ((base) + (0x0068))

/* 寄存器说明：memory时序控制寄存器。
            用于设置模块内部模块的低功耗和时序控制。
   位域定义UNION结构:  SOC_IDI2AXI_MEM_CTRL_UNION */
#define SOC_IDI2AXI_MEM_CTRL_ADDR(base)                       ((base) + (0x006C))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT4_UNION */
#define SOC_IDI2AXI_STAT4_ADDR(base)                          ((base) + (0x0070))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT5_UNION */
#define SOC_IDI2AXI_STAT5_ADDR(base)                          ((base) + (0x0074))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT6_UNION */
#define SOC_IDI2AXI_STAT6_ADDR(base)                          ((base) + (0x0078))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT7_UNION */
#define SOC_IDI2AXI_STAT7_ADDR(base)                          ((base) + (0x007C))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT8_UNION */
#define SOC_IDI2AXI_STAT8_ADDR(base)                          ((base) + (0x0080))

/* 寄存器说明：STAT寄存器。用于查询模块内部状态信息。
   位域定义UNION结构:  SOC_IDI2AXI_STAT9_UNION */
#define SOC_IDI2AXI_STAT9_ADDR(base)                          ((base) + (0x0084))

/* 寄存器说明：IDI2AXI启动寄存器。初始化IDI2AXI的最后一步，配置该寄存器为1之后，模块内部按照设置好的参数从CSI接受数据，并写入DDR，写完后将该寄存器bit拉低，表示处理完成。
   位域定义UNION结构:  SOC_IDI2AXI_EN_UNION */
#define SOC_IDI2AXI_EN_ADDR(base)                             ((base) + (0x00FC))

/* 寄存器说明：安全数据设置寄存器。
            该寄存器仅允许安全操作访问。用于设置IDI2AXI的APB配置接口中除该寄存器以外的安全属性，以及设置AXI写数据接口的安全属性。
   位域定义UNION结构:  SOC_IDI2AXI_SEC_UNION */
#define SOC_IDI2AXI_SEC_ADDR(base)                            ((base) + (0x0100))

/* 寄存器说明：used to configure the sensor (Height, Width, Start/Stop)，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CFG_UNION */
#define SOC_IDI2AXI_SENSORGEN_CFG_ADDR(base)                  ((base) + (0x290))

/* 寄存器说明：used to control the speed of the sensor generator (PCLK, blanking)，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CTRL_1_UNION */
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_ADDR(base)               ((base) + (0x294))

/* 寄存器说明：used to control the vsize and hsize，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_CTRL_2_UNION */
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_ADDR(base)               ((base) + (0x298))

/* 寄存器说明：used to control the pixel data，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_DATA_UNION */
#define SOC_IDI2AXI_SENSORGEN_DATA_ADDR(base)                 ((base) + (0x29C))

/* 寄存器说明：used to know the state of the sensor gen - useful when 1 frame is generrated，only valid for EMU simulation
   位域定义UNION结构:  SOC_IDI2AXI_SENSORGEN_STATUS_UNION */
#define SOC_IDI2AXI_SENSORGEN_STATUS_ADDR(base)               ((base) + (0x2A0))


#endif




/*****************************************************************************
  3 枚举定义
*****************************************************************************/



/*****************************************************************************
  4 消息头定义
*****************************************************************************/


/*****************************************************************************
  5 消息定义
*****************************************************************************/



/*****************************************************************************
  6 STRUCT定义
*****************************************************************************/



/*****************************************************************************
  7 UNION定义
*****************************************************************************/

/****************************************************************************
                     (1/1) reg_define
 ****************************************************************************/
/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR0_LOW_UNION
 结构说明  : WR_START_ADDR0_LOW 寄存器结构定义。地址偏移量:0x000，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr0_low : 32; /* bit[0-31]: 写数据到DDR中的起始地址的低32bit.要求128bit对齐,如果配置的地址不是128bit对齐，会按照128bit对齐方式截取后发出写操作。即bit[3:0]总是被认为是4'b0000。 */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR0_LOW_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR0_LOW_wr_start_addr0_low_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR0_LOW_wr_start_addr0_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR0_HIGH_UNION
 结构说明  : WR_START_ADDR0_HIGH 寄存器结构定义。地址偏移量:0x004，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr0_high : 32; /* bit[0-31]: 写数据到DDR中的起始地址的高32bit */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR0_HIGH_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR0_HIGH_wr_start_addr0_high_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR0_HIGH_wr_start_addr0_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR1_LOW_UNION
 结构说明  : WR_START_ADDR1_LOW 寄存器结构定义。地址偏移量:0x008，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr1_low : 32; /* bit[0-31]: 写数据到DDR中的起始地址的低32bit.要求128bit对齐,如果配置的地址不是128bit对齐，会按照128bit对齐方式截取后发出写操作。即bit[3:0]总是被认为是4'b0000。 */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR1_LOW_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR1_LOW_wr_start_addr1_low_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR1_LOW_wr_start_addr1_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR1_HIGH_UNION
 结构说明  : WR_START_ADDR1_HIGH 寄存器结构定义。地址偏移量:0x00C，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr1_high : 32; /* bit[0-31]: 写数据到DDR中的起始地址的高32bit */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR1_HIGH_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR1_HIGH_wr_start_addr1_high_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR1_HIGH_wr_start_addr1_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR2_LOW_UNION
 结构说明  : WR_START_ADDR2_LOW 寄存器结构定义。地址偏移量:0x010，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr2_low : 32; /* bit[0-31]: 写数据到DDR中的起始地址的低32bit.要求128bit对齐,如果配置的地址不是128bit对齐，会按照128bit对齐方式截取后发出写操作。即bit[3:0]总是被认为是4'b0000。 */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR2_LOW_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR2_LOW_wr_start_addr2_low_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR2_LOW_wr_start_addr2_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR2_HIGH_UNION
 结构说明  : WR_START_ADDR2_HIGH 寄存器结构定义。地址偏移量:0x014，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr2_high : 32; /* bit[0-31]: 写数据到DDR中的起始地址的高32bit */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR2_HIGH_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR2_HIGH_wr_start_addr2_high_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR2_HIGH_wr_start_addr2_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR3_LOW_UNION
 结构说明  : WR_START_ADDR3_LOW 寄存器结构定义。地址偏移量:0x018，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于设置写数据到DDR中的起始地址的低32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr3_low : 32; /* bit[0-31]: 写数据到DDR中的起始地址的低32bit.要求128bit对齐,如果配置的地址不是128bit对齐，会按照128bit对齐方式截取后发出写操作。即bit[3:0]总是被认为是4'b000。 */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR3_LOW_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR3_LOW_wr_start_addr3_low_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR3_LOW_wr_start_addr3_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_WR_START_ADDR3_HIGH_UNION
 结构说明  : WR_START_ADDR3_HIGH 寄存器结构定义。地址偏移量:0x01C，初值:0x00000000，宽度:32
 寄存器说明: 起始地址寄存器。
            用于写数据到DDR中的起始地址的高32bit
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  wr_start_addr3_high : 32; /* bit[0-31]: 写数据到DDR中的起始地址的高32bit */
    } reg;
} SOC_IDI2AXI_WR_START_ADDR3_HIGH_UNION;
#endif
#define SOC_IDI2AXI_WR_START_ADDR3_HIGH_wr_start_addr3_high_START  (0)
#define SOC_IDI2AXI_WR_START_ADDR3_HIGH_wr_start_addr3_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_FRAME_NUM_UNION
 结构说明  : FRAME_NUM 寄存器结构定义。地址偏移量:0x0020，初值:0x00000001，宽度:32
 寄存器说明: 帧个数寄存器。用于设置本次启动IDI2AXI接受几帧指纹数据。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  frame_num : 3;  /* bit[0-2] : 正常情况下，一帧数据就可完成指纹识别，极限场景下，可能需要采集多帧数据进行合成后完成指纹识别。需要多帧的场景，可以通过多次启动IDI2AXI，每次采集一帧数据的方式实现，也可以通过一次启动采集完多帧数据的方式实现。
                                                    3'b000:非法值，模块不接受数据，因此不会产生数据接收完成和发送完成相关的状态指示。
                                                    3'b001:接收并发送一帧数据，如果有超过一帧的数据从IDI接口发送过来，则超过一帧的数据部分会被忽略。
                                                    3'b010:接收并发送2帧数据，如果有超过2帧的数据从IDI接口发送过来，则超过2帧的数据部分会被忽略。
                                                    3'b011:接收并发送3帧数据，如果有超过3帧的数据从IDI接口发送过来，则超过3帧的数据部分会被忽略。
                                                    3'b100，3'b101，3'b110，3’b111:接收并发送4帧数据.如果有超过4帧的数据从IDI接口发送过来，则超过4帧的数据部分会被忽略。
                                                    IDI2AXI检测到超过配置frame_num的帧数据从IDI接口发送过来，会报frame_error中断（若该中断使能的话）。 */
        unsigned int  reserved  : 29; /* bit[3-31]: 保留 */
    } reg;
} SOC_IDI2AXI_FRAME_NUM_UNION;
#endif
#define SOC_IDI2AXI_FRAME_NUM_frame_num_START  (0)
#define SOC_IDI2AXI_FRAME_NUM_frame_num_END    (2)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_FRAME_END_FLAG_LOW_UNION
 结构说明  : FRAME_END_FLAG_LOW 寄存器结构定义。地址偏移量:0x0024，初值:0x00000000，宽度:32
 寄存器说明: 帧结束标识寄存器。
            用于设置64bit帧结束flag的低32bit。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  frame_end_flag_low : 32; /* bit[0-31]: 帧结束flag的低32bit。
                                                             frame_end_flag_en为1时，在每一帧数据结束时，添加在frame data的末尾。
                                                             frame_end_flag_en为0时，忽略该寄存器的值。 */
    } reg;
} SOC_IDI2AXI_FRAME_END_FLAG_LOW_UNION;
#endif
#define SOC_IDI2AXI_FRAME_END_FLAG_LOW_frame_end_flag_low_START  (0)
#define SOC_IDI2AXI_FRAME_END_FLAG_LOW_frame_end_flag_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_FRAME_END_FLAG_HIGH_UNION
 结构说明  : FRAME_END_FLAG_HIGH 寄存器结构定义。地址偏移量:0x0028，初值:0x00000000，宽度:32
 寄存器说明: 帧结束标识寄存器。
            用于设置64bit帧结束flag的高32bit。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  frame_end_flag_high : 32; /* bit[0-31]: 帧结束flag的高32bit。frame_end_flag_en为1时，在每一帧数据结束时，添加在frame data的末尾。
                                                              frame_end_flag_en为0时，忽略该寄存器的值。 */
    } reg;
} SOC_IDI2AXI_FRAME_END_FLAG_HIGH_UNION;
#endif
#define SOC_IDI2AXI_FRAME_END_FLAG_HIGH_frame_end_flag_high_START  (0)
#define SOC_IDI2AXI_FRAME_END_FLAG_HIGH_frame_end_flag_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_UNION
 结构说明  : FRAME_END_FLAG_ENABLE 寄存器结构定义。地址偏移量:0x002C，初值:0x00000000，宽度:32
 寄存器说明: 帧结束标识使能寄存器。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  frame_end_flag_en : 1;  /* bit[0]   : 0:不在帧尾添加帧结束标识字段。
                                                            1：在帧尾添加帧结束标识字段。 */
        unsigned int  reserved          : 31; /* bit[1-31]: 保留 */
    } reg;
} SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_UNION;
#endif
#define SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_frame_end_flag_en_START  (0)
#define SOC_IDI2AXI_FRAME_END_FLAG_ENABLE_frame_end_flag_en_END    (0)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_CFG_UNION
 结构说明  : CFG 寄存器结构定义。地址偏移量:0x0030，初值:0x000006A0，宽度:32
 寄存器说明: IDI2AXI配置寄存器。
            用于设置IDI2AXI所支持的功能相关参数。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  vld_vc             : 4;  /* bit[0-3]  : 配置当前所使用virtual channel。若CSI发送数据时的vc与此寄存器配置值不一致，则会上报vc_error中断。 */
        unsigned int  vld_dt             : 6;  /* bit[4-9]  : 配置当前支持的data type。若CSI发送数据时的dt与此寄存器配置值不一致，则会上报vc_error中断。 */
        unsigned int  max_wr_outstanding : 4;  /* bit[10-13]: 配置支持的最大写outstanding能力。写0对应outstanding为1，写1对应outstanding能力为2；以此类推。逻辑能够支持的最大outstanding能力为16，对应的配置值是0xF。 */
        unsigned int  reserved           : 18; /* bit[14-31]: 保留 */
    } reg;
} SOC_IDI2AXI_CFG_UNION;
#endif
#define SOC_IDI2AXI_CFG_vld_vc_START              (0)
#define SOC_IDI2AXI_CFG_vld_vc_END                (3)
#define SOC_IDI2AXI_CFG_vld_dt_START              (4)
#define SOC_IDI2AXI_CFG_vld_dt_END                (9)
#define SOC_IDI2AXI_CFG_max_wr_outstanding_START  (10)
#define SOC_IDI2AXI_CFG_max_wr_outstanding_END    (13)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_MID_UNION
 结构说明  : MID 寄存器结构定义。地址偏移量:0x0034，初值:0x0000000F，宽度:32
 寄存器说明: masterID设置寄存器。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  reserved_0: 6;  /* bit[0-5] : 原用于配置master id的寄存器，默认值6'b001111。
                                                    先保留。MID由逻辑内部接固定值，非寄存器可配置。 */
        unsigned int  reserved_1: 26; /* bit[6-31]: 保留 */
    } reg;
} SOC_IDI2AXI_MID_UNION;
#endif


/*****************************************************************************
 结构名    : SOC_IDI2AXI_QOS_CFG0_UNION
 结构说明  : QOS_CFG0 寄存器结构定义。地址偏移量:0x0038，初值:0x80404E27，宽度:32
 寄存器说明: QoS设置寄存器。用于设置发送不同awqos的水线。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  qos1_stop_level  : 8;  /* bit[0-7]  : awqos默认输出0，当内部buffer的数据个数小于qos1_start_level*8时，输出的awqos为0。
                                                            内部buffer的数据个数大于qos1_start_level*8时，输出的awqos为1，当内部buffer的数据个数降低到qos1_stop_level*8及以下时，awqos才会再次输出为0。 */
        unsigned int  qos1_start_level : 8;  /* bit[8-15] : awqos默认输出0，当内部buffer的数据个数小于qos1_start_level*8时，输出的awqos为0。
                                                            内部buffer的数据个数大于qos1_start_level*8时，输出的awqos为1，当内部buffer的数据个数降低到qos1_stop_level*8及以下时，awqos才会再次输出为0。 */
        unsigned int  qos2_stop_level  : 8;  /* bit[16-23]: 当内部buffer的数据个数小于qos2_start_level*8时，输出的awqos为小于2。
                                                            内部buffer的数据个数大于qos2_start_level*8时，输出的awqos为2，当内部buffer的数据个数降低到qos2_stop_level*8及以下时，awqos才会的输出值才会小于2。 */
        unsigned int  qos2_start_level : 8;  /* bit[24-31]: 当内部buffer的数据个数小于qos2_start_level*8时，输出的awqos为小于2。
                                                            内部buffer的数据个数大于qos2_start_level*8时，输出的awqos为2，当内部buffer的数据个数降低到qos2_stop_level*16及以下时，awqos才会的输出值才会小于2。 */
    } reg;
} SOC_IDI2AXI_QOS_CFG0_UNION;
#endif
#define SOC_IDI2AXI_QOS_CFG0_qos1_stop_level_START   (0)
#define SOC_IDI2AXI_QOS_CFG0_qos1_stop_level_END     (7)
#define SOC_IDI2AXI_QOS_CFG0_qos1_start_level_START  (8)
#define SOC_IDI2AXI_QOS_CFG0_qos1_start_level_END    (15)
#define SOC_IDI2AXI_QOS_CFG0_qos2_stop_level_START   (16)
#define SOC_IDI2AXI_QOS_CFG0_qos2_stop_level_END     (23)
#define SOC_IDI2AXI_QOS_CFG0_qos2_start_level_START  (24)
#define SOC_IDI2AXI_QOS_CFG0_qos2_start_level_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_QOS_CFG1_UNION
 结构说明  : QOS_CFG1 寄存器结构定义。地址偏移量:0x003C，初值:0x0000C361，宽度:32
 寄存器说明: QoS设置寄存器。用于设置发送不同awqos的水线。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  qos3_stop_level  : 8;  /* bit[0-7]  : 当内部buffer的数据个数小于qos3_start_level*8时，输出的awqos小于3。
                                                            内部buffer的数据个数大于qos3_start_level*8时，输出的awqos为3，当内部buffer的数据个数降低到qos3_stop_level*8及以下时，awqos才会的输出值才会小于3。 */
        unsigned int  qos3_start_level : 8;  /* bit[8-15] : 当内部buffer的数据个数小于qos3_start_level*8时，输出的awqos小于3。
                                                            内部buffer的数据个数大于qos3_start_level*8时，输出的awqos为3，当内部buffer的数据个数降低到qos3_stop_level*8及以下时，awqos才会的输出值才会小于3。 */
        unsigned int  reserved         : 16; /* bit[16-31]: 保留 */
    } reg;
} SOC_IDI2AXI_QOS_CFG1_UNION;
#endif
#define SOC_IDI2AXI_QOS_CFG1_qos3_stop_level_START   (0)
#define SOC_IDI2AXI_QOS_CFG1_qos3_stop_level_END     (7)
#define SOC_IDI2AXI_QOS_CFG1_qos3_start_level_START  (8)
#define SOC_IDI2AXI_QOS_CFG1_qos3_start_level_END    (15)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_FLUX_REQ_CFG_UNION
 结构说明  : FLUX_REQ_CFG 寄存器结构定义。地址偏移量:0x0040，初值:0x0003CAC7，宽度:32
 寄存器说明: 流控请求水线设置寄存器。
            用于设置非DDR DVFS期间拉起和拉低流控请求的水线。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  flux_req_high_level : 10; /* bit[0-9]  : 在flux_req_bypass为0，且内部buffe中已接收到的数据个数大于等于flux_req_high_level时，拉起flux_req。 */
        unsigned int  flux_req_low_level  : 10; /* bit[10-19]: 在flux_req_bypass为0，且内部buffe中已接收到的数据个数小于等于flux_req_low_level时，撤销flux_req。 */
        unsigned int  reserved            : 11; /* bit[20-30]: 保留 */
        unsigned int  flux_req_bypass     : 1;  /* bit[31]   : 流控请求使能寄存器。用于设置是否允许IDI2AXI发送流控请求：
                                                               0：允许流控请求；
                                                               1：禁止流控请求； */
    } reg;
} SOC_IDI2AXI_FLUX_REQ_CFG_UNION;
#endif
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_high_level_START  (0)
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_high_level_END    (9)
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_low_level_START   (10)
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_low_level_END     (19)
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_bypass_START      (31)
#define SOC_IDI2AXI_FLUX_REQ_CFG_flux_req_bypass_END        (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_TIMER_UNION
 结构说明  : TIMER 寄存器结构定义。地址偏移量:0x0044，初值:0x00989680，宽度:32
 寄存器说明: timeout计时器设置寄存器
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  timeout_cnt : 32; /* bit[0-31]: 内部counter在IDI2AXI_EN配置为1之后开始计数，如果当前帧数据在timeout_cnt所设置的cycle之内没有完成数据传输，会上报timeout_int中断。 */
    } reg;
} SOC_IDI2AXI_TIMER_UNION;
#endif
#define SOC_IDI2AXI_TIMER_timeout_cnt_START  (0)
#define SOC_IDI2AXI_TIMER_timeout_cnt_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_INT_EN_UNION
 结构说明  : INT_EN 寄存器结构定义。地址偏移量:0x0048，初值:0x00000000，宽度:32
 寄存器说明: 中断使能寄存器。
            0：屏蔽中断；
            1：使能中断；
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  trans_end_int_en            : 4;  /* bit[0-3]  : 数据处理结束中断使能/屏蔽设置。
                                                                       bit0-frame0的数据处理结束中断使能/屏蔽设置；
                                                                       bit1-frame1的数据处理结束中断使能/屏蔽设置；
                                                                       bit2-frame2的数据处理结束中断使能/屏蔽设置；
                                                                       bit3-frame2的数据处理结束中断使能/屏蔽设置； */
        unsigned int  timeout_int_en              : 1;  /* bit[4]    : 超时中断使能/屏蔽设置。 */
        unsigned int  reserved_0                  : 11; /* bit[5-15] : 保留 */
        unsigned int  dt_error_int_en             : 1;  /* bit[16]   : data type中断使能/屏蔽设置。 */
        unsigned int  vc_error_int_en             : 1;  /* bit[17]   : virtual channel error中断使能/屏蔽设置。 */
        unsigned int  axi_wr_error_int_en         : 1;  /* bit[18]   : axi_wr_error中断使能/屏蔽设置。 */
        unsigned int  sfifo_overflow_error_int_en : 1;  /* bit[19]   : 内部buffer溢出中断使能/屏蔽设置。 */
        unsigned int  frame_cnt_error_int_en      : 1;  /* bit[20]   : 实际接受的frame个数大于frame_num设置的frame个数异常中断使能/屏蔽设置。 */
        unsigned int  pslverr_int_en              : 1;  /* bit[21]   : 访问reserved寄存器或者非安全操作访问安全寄存器的pslverr中断使能/屏蔽设置。 */
        unsigned int  reserved_1                  : 10; /* bit[22-31]: 保留 */
    } reg;
} SOC_IDI2AXI_INT_EN_UNION;
#endif
#define SOC_IDI2AXI_INT_EN_trans_end_int_en_START             (0)
#define SOC_IDI2AXI_INT_EN_trans_end_int_en_END               (3)
#define SOC_IDI2AXI_INT_EN_timeout_int_en_START               (4)
#define SOC_IDI2AXI_INT_EN_timeout_int_en_END                 (4)
#define SOC_IDI2AXI_INT_EN_dt_error_int_en_START              (16)
#define SOC_IDI2AXI_INT_EN_dt_error_int_en_END                (16)
#define SOC_IDI2AXI_INT_EN_vc_error_int_en_START              (17)
#define SOC_IDI2AXI_INT_EN_vc_error_int_en_END                (17)
#define SOC_IDI2AXI_INT_EN_axi_wr_error_int_en_START          (18)
#define SOC_IDI2AXI_INT_EN_axi_wr_error_int_en_END            (18)
#define SOC_IDI2AXI_INT_EN_sfifo_overflow_error_int_en_START  (19)
#define SOC_IDI2AXI_INT_EN_sfifo_overflow_error_int_en_END    (19)
#define SOC_IDI2AXI_INT_EN_frame_cnt_error_int_en_START       (20)
#define SOC_IDI2AXI_INT_EN_frame_cnt_error_int_en_END         (20)
#define SOC_IDI2AXI_INT_EN_pslverr_int_en_START               (21)
#define SOC_IDI2AXI_INT_EN_pslverr_int_en_END                 (21)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_INT_RAW_UNION
 结构说明  : INT_RAW 寄存器结构定义。地址偏移量:0x004C，初值:0x00000000，宽度:32
 寄存器说明: 中断原始状态寄存器。
            读返回中断屏蔽前的原始状态。
            0：有中断；
            1：无中断；
            写无效。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  trans_end_int_raw            : 4;  /* bit[0-3]  : 数据处理结束原始中断状态。
                                                                        数据处理结束，是指指定的frame_num对应的数据帧都正确已经全部写入DDR。如果传输未完成，或者传输过程中出错，则不会触发该中断。
                                                                        bit0-frame0的数据处理结束中断状态；
                                                                        bit1-frame1的数据处理结束中断状态；
                                                                        bit2-frame2的数据处理结束中断状态；
                                                                        bit3-frame2的数据处理结束中断状态； */
        unsigned int  timeout_int_raw              : 1;  /* bit[4]    : 超时中断状态； */
        unsigned int  reserved_0                   : 11; /* bit[5-15] : 保留 */
        unsigned int  dt_error_int_raw             : 1;  /* bit[16]   : data type原始中断状态。 */
        unsigned int  vc_error_int_raw             : 1;  /* bit[17]   : virtual channel error原始中断状态。 */
        unsigned int  axi_wr_error_int_raw         : 1;  /* bit[18]   : axi_wr_error原始中断状态。 */
        unsigned int  sfifo_overflow_error_int_raw : 1;  /* bit[19]   : 内部buffer溢出原始中断状态。 */
        unsigned int  frame_cnt_error_int_raw      : 1;  /* bit[20]   : 实际接受的frame个数大于frame_num设置的frame个数异常中断原始状态。 */
        unsigned int  pslverr_int_raw              : 1;  /* bit[21]   : 访问reserved寄存器或者非安全操作访问安全寄存器的pslverr中断原始状态。 */
        unsigned int  reserved_1                   : 10; /* bit[22-31]: 保留 */
    } reg;
} SOC_IDI2AXI_INT_RAW_UNION;
#endif
#define SOC_IDI2AXI_INT_RAW_trans_end_int_raw_START             (0)
#define SOC_IDI2AXI_INT_RAW_trans_end_int_raw_END               (3)
#define SOC_IDI2AXI_INT_RAW_timeout_int_raw_START               (4)
#define SOC_IDI2AXI_INT_RAW_timeout_int_raw_END                 (4)
#define SOC_IDI2AXI_INT_RAW_dt_error_int_raw_START              (16)
#define SOC_IDI2AXI_INT_RAW_dt_error_int_raw_END                (16)
#define SOC_IDI2AXI_INT_RAW_vc_error_int_raw_START              (17)
#define SOC_IDI2AXI_INT_RAW_vc_error_int_raw_END                (17)
#define SOC_IDI2AXI_INT_RAW_axi_wr_error_int_raw_START          (18)
#define SOC_IDI2AXI_INT_RAW_axi_wr_error_int_raw_END            (18)
#define SOC_IDI2AXI_INT_RAW_sfifo_overflow_error_int_raw_START  (19)
#define SOC_IDI2AXI_INT_RAW_sfifo_overflow_error_int_raw_END    (19)
#define SOC_IDI2AXI_INT_RAW_frame_cnt_error_int_raw_START       (20)
#define SOC_IDI2AXI_INT_RAW_frame_cnt_error_int_raw_END         (20)
#define SOC_IDI2AXI_INT_RAW_pslverr_int_raw_START               (21)
#define SOC_IDI2AXI_INT_RAW_pslverr_int_raw_END                 (21)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_INT_MSK_UNION
 结构说明  : INT_MSK 寄存器结构定义。地址偏移量:0x0050，初值:0x00000000，宽度:32
 寄存器说明: 中断屏蔽后的状态寄存器。
            0：有中断；
            1：无中断；
            读返回中断屏蔽后的状态。
            0：有中断；
            1：无中断；
            写无效。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  trans_end_int_msk            : 4;  /* bit[0-3]  : 数据处理结束屏蔽后的中断状态。
                                                                        数据处理结束，是指指定的frame_num对应的数据帧都正确已经全部写入DDR。如果传输未完成，或者传输过程中出错，则不会触发该中断。
                                                                        bit0-frame0的数据处理结束屏蔽后的中断状态；
                                                                        bit1-frame1的数据处理结束屏蔽后的中断状态；
                                                                        bit2-frame2的数据处理结束屏蔽后的中断状态；
                                                                        bit3-frame2的数据处理结束屏蔽后的中断状态； */
        unsigned int  timeout_int_msk              : 1;  /* bit[4]    : 超时中断屏蔽后的状态； */
        unsigned int  reserved_0                   : 11; /* bit[5-15] : 保留 */
        unsigned int  dt_error_int_msk             : 1;  /* bit[16]   : data type屏蔽后的中断状态 */
        unsigned int  vc_error_int_msk             : 1;  /* bit[17]   : virtual channel error屏蔽后的中断状态 */
        unsigned int  axi_wr_error_int_msk         : 1;  /* bit[18]   : axi_wr_error屏蔽后的中断状态 */
        unsigned int  sfifo_overflow_error_int_msk : 1;  /* bit[19]   : 内部buffer溢出屏蔽后的中断状态。 */
        unsigned int  frame_cnt_error_int_msk      : 1;  /* bit[20]   : 实际接受的frame个数大于frame_num设置的frame个数异常中断屏蔽后中断状态。 */
        unsigned int  pslverr_int_msk              : 1;  /* bit[21]   : 访问reserved寄存器或者非安全操作访问安全寄存器的pslverr中断屏蔽后中断状态。 */
        unsigned int  reserved_1                   : 10; /* bit[22-31]: 保留 */
    } reg;
} SOC_IDI2AXI_INT_MSK_UNION;
#endif
#define SOC_IDI2AXI_INT_MSK_trans_end_int_msk_START             (0)
#define SOC_IDI2AXI_INT_MSK_trans_end_int_msk_END               (3)
#define SOC_IDI2AXI_INT_MSK_timeout_int_msk_START               (4)
#define SOC_IDI2AXI_INT_MSK_timeout_int_msk_END                 (4)
#define SOC_IDI2AXI_INT_MSK_dt_error_int_msk_START              (16)
#define SOC_IDI2AXI_INT_MSK_dt_error_int_msk_END                (16)
#define SOC_IDI2AXI_INT_MSK_vc_error_int_msk_START              (17)
#define SOC_IDI2AXI_INT_MSK_vc_error_int_msk_END                (17)
#define SOC_IDI2AXI_INT_MSK_axi_wr_error_int_msk_START          (18)
#define SOC_IDI2AXI_INT_MSK_axi_wr_error_int_msk_END            (18)
#define SOC_IDI2AXI_INT_MSK_sfifo_overflow_error_int_msk_START  (19)
#define SOC_IDI2AXI_INT_MSK_sfifo_overflow_error_int_msk_END    (19)
#define SOC_IDI2AXI_INT_MSK_frame_cnt_error_int_msk_START       (20)
#define SOC_IDI2AXI_INT_MSK_frame_cnt_error_int_msk_END         (20)
#define SOC_IDI2AXI_INT_MSK_pslverr_int_msk_START               (21)
#define SOC_IDI2AXI_INT_MSK_pslverr_int_msk_END                 (21)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_INT_CLR_UNION
 结构说明  : INT_CLR 寄存器结构定义。地址偏移量:0x0054，初值:0x00000000，宽度:32
 寄存器说明: 中断清除寄存器。
            写1清除中断，写0无效。
            读总是返回0x0。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  trans_end_int_clr            : 4;  /* bit[0-3]  : 数据处理结束屏蔽后的中断清除。 */
        unsigned int  timeout_int_clr              : 1;  /* bit[4]    : 超时中断状态清除； */
        unsigned int  reserved_0                   : 11; /* bit[5-15] : 保留 */
        unsigned int  dt_error_int_clr             : 1;  /* bit[16]   : data type中断清除 */
        unsigned int  vc_error_int_clr             : 1;  /* bit[17]   : virtual channel error中断清除 */
        unsigned int  axi_wr_error_int_clr         : 1;  /* bit[18]   : axi_wr_error中断清除 */
        unsigned int  sfifo_overflow_error_int_clr : 1;  /* bit[19]   : 内部buffer溢出中断清除。 */
        unsigned int  frame_cnt_error_int_clr      : 1;  /* bit[20]   : 实际接受的frame个数大于frame_num设置的frame个数异常中断屏蔽后中断清除。 */
        unsigned int  pslverr_int_clr              : 1;  /* bit[21]   : 访问reserved寄存器或者非安全操作访问安全寄存器的pslverr中断屏蔽后中断清除。 */
        unsigned int  reserved_1                   : 10; /* bit[22-31]: 保留 */
    } reg;
} SOC_IDI2AXI_INT_CLR_UNION;
#endif
#define SOC_IDI2AXI_INT_CLR_trans_end_int_clr_START             (0)
#define SOC_IDI2AXI_INT_CLR_trans_end_int_clr_END               (3)
#define SOC_IDI2AXI_INT_CLR_timeout_int_clr_START               (4)
#define SOC_IDI2AXI_INT_CLR_timeout_int_clr_END                 (4)
#define SOC_IDI2AXI_INT_CLR_dt_error_int_clr_START              (16)
#define SOC_IDI2AXI_INT_CLR_dt_error_int_clr_END                (16)
#define SOC_IDI2AXI_INT_CLR_vc_error_int_clr_START              (17)
#define SOC_IDI2AXI_INT_CLR_vc_error_int_clr_END                (17)
#define SOC_IDI2AXI_INT_CLR_axi_wr_error_int_clr_START          (18)
#define SOC_IDI2AXI_INT_CLR_axi_wr_error_int_clr_END            (18)
#define SOC_IDI2AXI_INT_CLR_sfifo_overflow_error_int_clr_START  (19)
#define SOC_IDI2AXI_INT_CLR_sfifo_overflow_error_int_clr_END    (19)
#define SOC_IDI2AXI_INT_CLR_frame_cnt_error_int_clr_START       (20)
#define SOC_IDI2AXI_INT_CLR_frame_cnt_error_int_clr_END         (20)
#define SOC_IDI2AXI_INT_CLR_pslverr_int_clr_START               (21)
#define SOC_IDI2AXI_INT_CLR_pslverr_int_clr_END                 (21)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT0_UNION
 结构说明  : STAT0 寄存器结构定义。地址偏移量:0x0058，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  cur_axi_waddr_low : 32; /* bit[0-31]: 当前写操作的起始地址的低32bit。 */
    } reg;
} SOC_IDI2AXI_STAT0_UNION;
#endif
#define SOC_IDI2AXI_STAT0_cur_axi_waddr_low_START  (0)
#define SOC_IDI2AXI_STAT0_cur_axi_waddr_low_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT1_UNION
 结构说明  : STAT1 寄存器结构定义。地址偏移量:0x005C，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  cur_axi_waddr_high : 32; /* bit[0-31]: 当前写操作的起始地址的高32bit。 */
    } reg;
} SOC_IDI2AXI_STAT1_UNION;
#endif
#define SOC_IDI2AXI_STAT1_cur_axi_waddr_high_START  (0)
#define SOC_IDI2AXI_STAT1_cur_axi_waddr_high_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT2_UNION
 结构说明  : STAT2 寄存器结构定义。地址偏移量:0x0060，初值:0x40000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  error_dt      : 6;  /* bit[0-5]  : 发生dt error时的dt值。 */
        unsigned int  reserved_0    : 2;  /* bit[6-7]  : 保留 */
        unsigned int  error_vc      : 4;  /* bit[8-11] : 发生vc error时的vc值。 */
        unsigned int  reserved_1    : 2;  /* bit[12-13]: 保留 */
        unsigned int  cur_qos       : 2;  /* bit[14-15]: 当前输出的qos值。 */
        unsigned int  cur_press     : 2;  /* bit[16-17]: 当前输出的qos值。 */
        unsigned int  max_sfifo_cnt : 11; /* bit[18-28]: 内部buffer中数据个数在一次idi2axi使能过程中曾经达到的最大值。 */
        unsigned int  sfifo_af      : 1;  /* bit[29]   : 内部buffer将满状态信息。 */
        unsigned int  sfifo_ae      : 1;  /* bit[30]   : 内部buffer将空状态信息。 */
        unsigned int  cur_flux_req  : 1;  /* bit[31]   : 当前输出的flux_req信息。 */
    } reg;
} SOC_IDI2AXI_STAT2_UNION;
#endif
#define SOC_IDI2AXI_STAT2_error_dt_START       (0)
#define SOC_IDI2AXI_STAT2_error_dt_END         (5)
#define SOC_IDI2AXI_STAT2_error_vc_START       (8)
#define SOC_IDI2AXI_STAT2_error_vc_END         (11)
#define SOC_IDI2AXI_STAT2_cur_qos_START        (14)
#define SOC_IDI2AXI_STAT2_cur_qos_END          (15)
#define SOC_IDI2AXI_STAT2_cur_press_START      (16)
#define SOC_IDI2AXI_STAT2_cur_press_END        (17)
#define SOC_IDI2AXI_STAT2_max_sfifo_cnt_START  (18)
#define SOC_IDI2AXI_STAT2_max_sfifo_cnt_END    (28)
#define SOC_IDI2AXI_STAT2_sfifo_af_START       (29)
#define SOC_IDI2AXI_STAT2_sfifo_af_END         (29)
#define SOC_IDI2AXI_STAT2_sfifo_ae_START       (30)
#define SOC_IDI2AXI_STAT2_sfifo_ae_END         (30)
#define SOC_IDI2AXI_STAT2_cur_flux_req_START   (31)
#define SOC_IDI2AXI_STAT2_cur_flux_req_END     (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT3_UNION
 结构说明  : STAT3 寄存器结构定义。地址偏移量:0x0064，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  reserved_0     : 3;  /* bit[0-2]  : 保留。 */
        unsigned int  recv_finish    : 4;  /* bit[3-6]  : 0000:数据传输未开始或未结束；
                                                          xxx1：第一帧数据接收完毕；
                                                          xx1x：第二帧数据接受完毕；
                                                          x100：第二帧数据接受完毕；
                                                          1xxx：第四帧数据接收完毕； */
        unsigned int  send_finish    : 4;  /* bit[7-10] : 0000:数据传输未开始或未结束；
                                                          xxx1：第一帧数据发送完毕；
                                                          xx1x：第二帧数据发送完毕；
                                                          x100：第二帧数据发送完毕；
                                                          1xxx：第四帧数据发送完毕； */
        unsigned int  recv_frame_cnt : 3;  /* bit[11-13]: 已接收数据帧的帧个数。 */
        unsigned int  frame_valid    : 4;  /* bit[14-17]: frame_valid从每一帧的vvalid上升沿开始到当前帧写完成期间为高。 */
        unsigned int  send_valid     : 4;  /* bit[18-21]: send_valid从每一帧的第一笔数据写入CMD_FIFO到到当前帧写完成期间为高。 */
        unsigned int  reserved_1     : 7;  /* bit[22-28]: 保留 */
        unsigned int  wr_beat_num    : 3;  /* bit[29-31]: 当前写操作对应的burst长度。 */
    } reg;
} SOC_IDI2AXI_STAT3_UNION;
#endif
#define SOC_IDI2AXI_STAT3_recv_finish_START     (3)
#define SOC_IDI2AXI_STAT3_recv_finish_END       (6)
#define SOC_IDI2AXI_STAT3_send_finish_START     (7)
#define SOC_IDI2AXI_STAT3_send_finish_END       (10)
#define SOC_IDI2AXI_STAT3_recv_frame_cnt_START  (11)
#define SOC_IDI2AXI_STAT3_recv_frame_cnt_END    (13)
#define SOC_IDI2AXI_STAT3_frame_valid_START     (14)
#define SOC_IDI2AXI_STAT3_frame_valid_END       (17)
#define SOC_IDI2AXI_STAT3_send_valid_START      (18)
#define SOC_IDI2AXI_STAT3_send_valid_END        (21)
#define SOC_IDI2AXI_STAT3_wr_beat_num_START     (29)
#define SOC_IDI2AXI_STAT3_wr_beat_num_END       (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_UNION
 结构说明  : BUFFER_OVERFLOW_LEVEL 寄存器结构定义。地址偏移量:0x0068，初值:0x00000000，宽度:32
 寄存器说明: 内部buffer溢出水线设置寄存器。
            当内部buffer数据个数大于或者等于该寄存器设置值时，认为buffer溢出。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  buffer_over_flow_level : 10; /* bit[0-9]  : 该寄存器的值为0，则buffer满时仍然接收到IDI接口的写数据认为buffer overflow。
                                                                  该寄存器的值不为0，则buffer中的数据个数大于等于该寄存器的设置值时，认为buffer overflow。
                                                                  buffer overflow时，会触发sfifo_overflow_error中断。 */
        unsigned int  reserved               : 22; /* bit[10-31]: 保留 */
    } reg;
} SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_UNION;
#endif
#define SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_buffer_over_flow_level_START  (0)
#define SOC_IDI2AXI_BUFFER_OVERFLOW_LEVEL_buffer_over_flow_level_END    (9)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_MEM_CTRL_UNION
 结构说明  : MEM_CTRL 寄存器结构定义。地址偏移量:0x006C，初值:0x00004858，宽度:32
 寄存器说明: memory时序控制寄存器。
            用于设置模块内部模块的低功耗和时序控制。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  mem_ctrl_d1w2r : 16; /* bit[0-15] : 用于设置模块内部模块的低功耗和时序控制。 */
        unsigned int  reserved       : 16; /* bit[16-31]: 保留 */
    } reg;
} SOC_IDI2AXI_MEM_CTRL_UNION;
#endif
#define SOC_IDI2AXI_MEM_CTRL_mem_ctrl_d1w2r_START  (0)
#define SOC_IDI2AXI_MEM_CTRL_mem_ctrl_d1w2r_END    (15)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT4_UNION
 结构说明  : STAT4 寄存器结构定义。地址偏移量:0x0070，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  reserved       : 10; /* bit[0-9]  : 保留 */
        unsigned int  aw_remain_cnt0 : 11; /* bit[10-20]: 第一帧中已接收并写入DATA_FIFO但尚未写入CMD_FIFO的数据个数 */
        unsigned int  aw_remain_cnt1 : 11; /* bit[21-31]: 第二帧中已接收并写入DATA_FIFO但尚未写入CMD_FIFO的数据个数 */
    } reg;
} SOC_IDI2AXI_STAT4_UNION;
#endif
#define SOC_IDI2AXI_STAT4_aw_remain_cnt0_START  (10)
#define SOC_IDI2AXI_STAT4_aw_remain_cnt0_END    (20)
#define SOC_IDI2AXI_STAT4_aw_remain_cnt1_START  (21)
#define SOC_IDI2AXI_STAT4_aw_remain_cnt1_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT5_UNION
 结构说明  : STAT5 寄存器结构定义。地址偏移量:0x0074，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  reserved       : 10; /* bit[0-9]  : 保留。 */
        unsigned int  aw_remain_cnt2 : 11; /* bit[10-20]: 第三帧中已接收并写入DATA_FIFO但尚未写入CMD_FIFO的数据个数 */
        unsigned int  aw_remain_cnt3 : 11; /* bit[21-31]: 第四帧中已接收并写入DATA_FIFO但尚未写入CMD_FIFO的数据个数 */
    } reg;
} SOC_IDI2AXI_STAT5_UNION;
#endif
#define SOC_IDI2AXI_STAT5_aw_remain_cnt2_START  (10)
#define SOC_IDI2AXI_STAT5_aw_remain_cnt2_END    (20)
#define SOC_IDI2AXI_STAT5_aw_remain_cnt3_START  (21)
#define SOC_IDI2AXI_STAT5_aw_remain_cnt3_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT6_UNION
 结构说明  : STAT6 寄存器结构定义。地址偏移量:0x0078，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  aw_fifo_num : 5;  /* bit[0-4]  : 已写入CMD_FIFO但尚未发送到AW通道上的命令个数。 */
        unsigned int  w_fifo_num  : 5;  /* bit[5-9]  : 已写入CMD_FIFO但尚未发送到W通道上的命令个数。 */
        unsigned int  b_fifo_num  : 5;  /* bit[10-14]: 已写入CMD_FIFO但尚未发送到AXI接口或者以发送到AXI接口但尚未接收到BRESP的命令个数。 */
        unsigned int  sfifo_num   : 12; /* bit[15-26]: 已从IDI接口接收但尚未发送到AXI接口的数据个数。 */
        unsigned int  reserved    : 5;  /* bit[27-31]: 保留 */
    } reg;
} SOC_IDI2AXI_STAT6_UNION;
#endif
#define SOC_IDI2AXI_STAT6_aw_fifo_num_START  (0)
#define SOC_IDI2AXI_STAT6_aw_fifo_num_END    (4)
#define SOC_IDI2AXI_STAT6_w_fifo_num_START   (5)
#define SOC_IDI2AXI_STAT6_w_fifo_num_END     (9)
#define SOC_IDI2AXI_STAT6_b_fifo_num_START   (10)
#define SOC_IDI2AXI_STAT6_b_fifo_num_END     (14)
#define SOC_IDI2AXI_STAT6_sfifo_num_START    (15)
#define SOC_IDI2AXI_STAT6_sfifo_num_END      (26)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT7_UNION
 结构说明  : STAT7 寄存器结构定义。地址偏移量:0x007C，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  idi2axi_timer_cnt : 32; /* bit[0-31]: 内部超时计时器的当前计数值。 */
    } reg;
} SOC_IDI2AXI_STAT7_UNION;
#endif
#define SOC_IDI2AXI_STAT7_idi2axi_timer_cnt_START  (0)
#define SOC_IDI2AXI_STAT7_idi2axi_timer_cnt_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT8_UNION
 结构说明  : STAT8 寄存器结构定义。地址偏移量:0x0080，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  vc       : 4;  /* bit[0-3]  : IDI接口输入的vc信号 */
        unsigned int  dt       : 6;  /* bit[4-9]  : IDI接口输入的dt信号 */
        unsigned int  reserved : 22; /* bit[10-31]: 保留 */
    } reg;
} SOC_IDI2AXI_STAT8_UNION;
#endif
#define SOC_IDI2AXI_STAT8_vc_START        (0)
#define SOC_IDI2AXI_STAT8_vc_END          (3)
#define SOC_IDI2AXI_STAT8_dt_START        (4)
#define SOC_IDI2AXI_STAT8_dt_END          (9)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_STAT9_UNION
 结构说明  : STAT9 寄存器结构定义。地址偏移量:0x0084，初值:0x00000000，宽度:32
 寄存器说明: STAT寄存器。用于查询模块内部状态信息。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  vvalid : 16; /* bit[0-15] : IDI接口输入的vvalid信号 */
        unsigned int  dvalid : 16; /* bit[16-31]: IDI接口输入的dvalid信号 */
    } reg;
} SOC_IDI2AXI_STAT9_UNION;
#endif
#define SOC_IDI2AXI_STAT9_vvalid_START  (0)
#define SOC_IDI2AXI_STAT9_vvalid_END    (15)
#define SOC_IDI2AXI_STAT9_dvalid_START  (16)
#define SOC_IDI2AXI_STAT9_dvalid_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_EN_UNION
 结构说明  : EN 寄存器结构定义。地址偏移量:0x00FC，初值:0x00000000，宽度:32
 寄存器说明: IDI2AXI启动寄存器。初始化IDI2AXI的最后一步，配置该寄存器为1之后，模块内部按照设置好的参数从CSI接受数据，并写入DDR，写完后将该寄存器bit拉低，表示处理完成。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  idi2axi_en : 1;  /* bit[0]   : 写1表示启动IDI2AXI模块开始工作；
                                                     写0无效/无影响。
                                                     读出为0表示IDI2AXI模块处于IDLE态，未开始工作，或者已经完成相应处理。
                                                     读出为1，表示IDI2AXI模块处于Busy状态。 */
        unsigned int  reserved   : 31; /* bit[1-31]: 保留 */
    } reg;
} SOC_IDI2AXI_EN_UNION;
#endif
#define SOC_IDI2AXI_EN_idi2axi_en_START  (0)
#define SOC_IDI2AXI_EN_idi2axi_en_END    (0)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SEC_UNION
 结构说明  : SEC 寄存器结构定义。地址偏移量:0x0100，初值:0x00000000，宽度:32
 寄存器说明: 安全数据设置寄存器。
            该寄存器仅允许安全操作访问。用于设置IDI2AXI的APB配置接口中除该寄存器以外的安全属性，以及设置AXI写数据接口的安全属性。
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  idi2axi_apb_sec    : 1;  /* bit[0]    : 0:idi2axi的寄存器空间中，除IDI2AXI_SEC寄存器以外的空间为安全属性，仅允许安全操作访问。
                                                              1:idi2axi的寄存器空间中，除IDI2AXI_SEC寄存器以外的空间为非安全属性，仅允许安全操作访问。 */
        unsigned int  reserved_0         : 15; /* bit[1-15] : 保留 */
        unsigned int  idi2axi_axi_wr_sec : 1;  /* bit[16]   : 0:idi2axi访问DDR的AWPROT[1]为0，即写操作为安全属性。
                                                              1:idi2axi访问DDR的AWPROT[1]为1，即写操作为非安全属性。 */
        unsigned int  reserved_1         : 15; /* bit[17-31]: 保留 */
    } reg;
} SOC_IDI2AXI_SEC_UNION;
#endif
#define SOC_IDI2AXI_SEC_idi2axi_apb_sec_START     (0)
#define SOC_IDI2AXI_SEC_idi2axi_apb_sec_END       (0)
#define SOC_IDI2AXI_SEC_idi2axi_axi_wr_sec_START  (16)
#define SOC_IDI2AXI_SEC_idi2axi_axi_wr_sec_END    (16)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SENSORGEN_CFG_UNION
 结构说明  : SENSORGEN_CFG 寄存器结构定义。地址偏移量:0x290，初值:0x00000000，宽度:32
 寄存器说明: used to configure the sensor (Height, Width, Start/Stop)，only valid for EMU simulation
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  sensorgen_dt          : 6;  /* bit[0-5]  : DT value to use whens sensorgen feature is used (sensorgen_start=1) */
        unsigned int  sensorgen_vc          : 4;  /* bit[6-9]  : VC value to use whens sensorgen feature is used (sensorgen_start=1) */
        unsigned int  reserved              : 19; /* bit[10-28]: reserved */
        unsigned int  sensorgen_single_shot : 1;  /* bit[29]   : used to generate 1 frame or generate frames continuously.
                                                                 0: frames are generated continuously until sensorgen_start = 0
                                                                 1: 1 frame generated */
        unsigned int  sensorgen_mode        : 1;  /* bit[30]   : Used to configure the way the 32 bits data is sent.
                                                                 0: fixed pattern using SENSORGEN_DATA
                                                                 1: incremental mode, 32-bits data starting from sensorgen_data[15:0] and incremented by sensorgen_data[23:16]. In this mode, the counter is only reseted to sensorgen_data[15:0] at frame start.  */
        unsigned int  sensorgen_start       : 1;  /* bit[31]   : The software must set the bit to 1 to start the emulated sensor interface.
                                                                 The software must clear the bit to 0 to stop the emulated sensor interface.
                                                                 Note that, the harware will start/stop immediately based on SW decision.
                                                                 When the software clears the bit, then the harware stops immediatly, and get back to idle state (VVALID, DVALID to 0).
                                                                 0: the CSI interface is directly routed to the filters and the back pressure FIFO
                                                                 1: the CSI has no effect, only the sensorgen is able to send data to the filters and back pressure FIFO */
    } reg;
} SOC_IDI2AXI_SENSORGEN_CFG_UNION;
#endif
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_dt_START           (0)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_dt_END             (5)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_vc_START           (6)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_vc_END             (9)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_single_shot_START  (29)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_single_shot_END    (29)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_mode_START         (30)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_mode_END           (30)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_start_START        (31)
#define SOC_IDI2AXI_SENSORGEN_CFG_sensorgen_start_END          (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SENSORGEN_CTRL_1_UNION
 结构说明  : SENSORGEN_CTRL_1 寄存器结构定义。地址偏移量:0x294，初值:0x00000000，宽度:32
 寄存器说明: used to control the speed of the sensor generator (PCLK, blanking)，only valid for EMU simulation
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  sensorgen_dataen_pattern : 16; /* bit[0-15] : Pattern to use to generate the traffic.
                                                                    Note that the configuration of this pattern depends on the targeted Pixel clock as well as the pixel type and also impacts the vertical blanking duration.
                                                                    C-code is provided into the HLD.
                                                                    The bits are used in following order: from bit 15 to bit 0 (bit 15 is evaluated first) */
        unsigned int  sensorgen_vblanking      : 8;  /* bit[16-23]: Number of vertical blanking lines (duration is based on idigen_dataen_pattern and idi_hblanking)
                                                                    0: 2 lines
                                                                    1: 4 lines
                                                                    2: 6 lines
                                                                    ….
                                                                    255: 512 lines */
        unsigned int  sensorgen_hblanking      : 8;  /* bit[24-31]: Number of horizontal blanking clock cycles (starting as soon as the number of generated data is completed)
                                                                    0: 2 cycles
                                                                    1: 4 cycles
                                                                    2: 6 cycles
                                                                    ….
                                                                    255: 512 cycles */
    } reg;
} SOC_IDI2AXI_SENSORGEN_CTRL_1_UNION;
#endif
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_dataen_pattern_START  (0)
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_dataen_pattern_END    (15)
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_vblanking_START       (16)
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_vblanking_END         (23)
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_hblanking_START       (24)
#define SOC_IDI2AXI_SENSORGEN_CTRL_1_sensorgen_hblanking_END         (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SENSORGEN_CTRL_2_UNION
 结构说明  : SENSORGEN_CTRL_2 寄存器结构定义。地址偏移量:0x298，初值:0x013F013F，宽度:32
 寄存器说明: used to control the vsize and hsize，only valid for EMU simulation
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  sensorgen_hsize : 14; /* bit[0-13] : Number of 32-bits data per line (horizontal)
                                                           0: 1 32-bits
                                                           …
                                                           0xFFF: 4096 32-bits */
        unsigned int  reserved_0      : 2;  /* bit[14-15]: reserved */
        unsigned int  sensorgen_vsize : 14; /* bit[16-29]: Number of lines in the frame (vertical)
                                                           0: 1 line
                                                           …
                                                           0x1FFF: 8192 lines */
        unsigned int  reserved_1      : 2;  /* bit[30-31]: reserved */
    } reg;
} SOC_IDI2AXI_SENSORGEN_CTRL_2_UNION;
#endif
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_sensorgen_hsize_START  (0)
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_sensorgen_hsize_END    (13)
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_sensorgen_vsize_START  (16)
#define SOC_IDI2AXI_SENSORGEN_CTRL_2_sensorgen_vsize_END    (29)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SENSORGEN_DATA_UNION
 结构说明  : SENSORGEN_DATA 寄存器结构定义。地址偏移量:0x29C，初值:0x04030201，宽度:32
 寄存器说明: used to control the pixel data，only valid for EMU simulation
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  sensorgen_data : 32; /* bit[0-31]: IDI pixel data.
                                                         If sensorgen_mode=0: csi_data[31:0] = sensorgen_data (fixed pattern)
                                                         If sensorgen_mode=1: csi_data[31:0] is resetted to sensorgen_data[15:0] at frame start, then incremented by sensorgen_data[23:16] at every valid csi_data.  */
    } reg;
} SOC_IDI2AXI_SENSORGEN_DATA_UNION;
#endif
#define SOC_IDI2AXI_SENSORGEN_DATA_sensorgen_data_START  (0)
#define SOC_IDI2AXI_SENSORGEN_DATA_sensorgen_data_END    (31)


/*****************************************************************************
 结构名    : SOC_IDI2AXI_SENSORGEN_STATUS_UNION
 结构说明  : SENSORGEN_STATUS 寄存器结构定义。地址偏移量:0x2A0，初值:0x00000000，宽度:32
 寄存器说明: used to know the state of the sensor gen - useful when 1 frame is generrated，only valid for EMU simulation
*****************************************************************************/
#ifndef __SOC_H_FOR_ASM__
typedef union
{
    unsigned int      value;
    struct
    {
        unsigned int  sensorgen_running : 1;  /* bit[0]   : status bit 
                                                            0: the sensor gen is not running and can be re-configured when 1 frame is generated
                                                            1: the sensor gen is running and can not be re-configured  */
        unsigned int  reserved          : 31; /* bit[1-31]: reserved */
    } reg;
} SOC_IDI2AXI_SENSORGEN_STATUS_UNION;
#endif
#define SOC_IDI2AXI_SENSORGEN_STATUS_sensorgen_running_START  (0)
#define SOC_IDI2AXI_SENSORGEN_STATUS_sensorgen_running_END    (0)






/*****************************************************************************
  8 OTHERS定义
*****************************************************************************/



/*****************************************************************************
  9 全局变量声明
*****************************************************************************/


/*****************************************************************************
  10 函数声明
*****************************************************************************/


#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif

#endif /* end of soc_idi2axi_interface.h */
