#
# Makefile for kernel vendor HSDT BUS.
#
ccflags-y += -Wextra  -Wdate-time -Wfloat-equal -Wshadow -Wformat=2
obj-$(CONFIG_HSDT_BUS_DOMAIN) += hsdt_bus_core.o
obj-$(CONFIG_HSDT_BUS_DOMAIN) += platform/
