# dpa load module
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/load
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/pm
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/pm/hal

obj-y += load.o

