ccflags-y += -I$(srctree)/platform_source/audio/drivers/hifi_mailbox/mailbox/
ccflags-y += -I$(srctree)/platform_source/audio/include/
ccflags-y += -I$(srctree)/include/platform_include/audio/ipc
ccflags-y += -I$(srctree)/audiodsp/include/modem/drv/mbb/

obj-$(CONFIG_AUDIO_HIFI_REPORT) += hifi_report.o