/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: Hmseharmony head file for policydb cap define
 * Author: Huawei OS Kernel Lab
 * Create: Tue Jan 31 11:49:29 2023
 */

#ifndef HMSEL_EXPORT_POLICYCAP_H
#define HMSEL_EXPORT_POLICYCAP_H

enum {
	HMSEL_POLICYDB_CAPABILITY_NETPEER,
	HMSEL_POLICYDB_CAPABILITY_OPENPERM,
	HMSEL_POLICYDB_CAPABILITY_EXTSOCKCLASS,
	HMSEL_POLICYDB_CAPABILITY_ALWAYSNETWORK,
	HMSEL_POLICYDB_CAPABILITY_CGROUPSECLABEL,
	HMSEL_POLICYDB_CAPABILITY_NNP_NOSUID_TRANSITION,
	HMSEL_POLICYDB_CAPABILITY_GENFS_SECLABEL_SYMLINKS,
	HMSEL_POLICYDB_CAPABILITY_IOCTL_SKIP_CLOEXEC,
	HMSEL_POLICYDB_CAPABILITY_MAX
};

#endif
