/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: lsyscall map `fast-syscall` which the server is kernel
 * Author: Huawei OS Kernel Lab
 * Create: Sat Jul 29 16:14:15 2023
 */


/*
 * This function is used to define the kernel syscall which
 * are dealed with lsyscall.
 */

#if !defined(DEFINE_SERVER) || !defined(AARCH64_LSYSCALL_MAP_ITEM) ||          \
	!defined(ARM_LSYSCALL_MAP_ITEM)
#error This file should not be directly included
#endif

#define LSYSCALL_MAP_ITEM  AARCH64_LSYSCALL_MAP_ITEM
#define LSYSCALL_MAP_ITEM_COMPAT ARM_LSYSCALL_MAP_ITEM

DEFINE_SERVER(SVR_KERNEL)

/*
 * format:
 * AARCH64_LSYSCALL_MAP_ITEM/LSYSCALL_MAP_ITEM_COMPAT(svr, lscno, fast_call_no, param_num, return
 * type).
 * Note: Use LSYSCALL_MAP_ITEM_COMPAT to define the lsyscalls of arch arm and
 * compat mode for arch aarch64
 */
LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_futex, __FAST_SYSCALL_lsyscall_private_futex, 6,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_futex,
			 __FAST_SYSCALL_lsyscall_private_futex, 6, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_pause, __FAST_SYSCALL_pause, 0,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_pause,
			 __FAST_SYSCALL_pause, 0, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_clock_gettime, __FAST_SYSCALL_clock_gettime, 2,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_clock_gettime32, __FAST_SYSCALL_clock_gettime,
			 2, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_gettimeofday, __FAST_SYSCALL_gettimeofday, 2,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_gettimeofday_time32, __FAST_SYSCALL_gettimeofday,
			 2, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_nanosleep, __FAST_SYSCALL_nanosleep, 2,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_nanosleep, __FAST_SYSCALL_nanosleep,
			 2, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_clock_nanosleep, __FAST_SYSCALL_clock_nanosleep, 4,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_clock_nanosleep_time32, __FAST_SYSCALL_clock_nanosleep,
			 4, __LSYSCALL_RET_TYPE_INT)

#ifdef CONFIG_DOPRA_TICK
LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_dopra_tick, __FAST_SYSCALL_dopra_tick, 1,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_dopra_tick, __FAST_SYSCALL_dopra_tick,
			 1, __LSYSCALL_RET_TYPE_INT)
#endif

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_sched_yield, __FAST_SYSCALL_sched_yield, 0,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_sched_yield,
			 __FAST_SYSCALL_sched_yield, 0, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_getcpu, __FAST_SYSCALL_thread_get_cpu, 1,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_getcpu, __FAST_SYSCALL_thread_get_cpu,
			 1, __LSYSCALL_RET_TYPE_INT)

#ifdef CONFIG_ACTV_BINDER
LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_ioctl, __FAST_SYSCALL_actv_binder_ioctl, 3,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_ioctl,
			 __FAST_SYSCALL_actv_binder_ioctl, 3,
			 __LSYSCALL_RET_TYPE_INT)
#endif

LSYSCALL_MAP_ITEM(SVR_KERNEL, __LSYSCALL_COMPAT_EPOLL_WAIT,
		  __FAST_SYSCALL_epoll_wait, 4, __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_epoll_wait, __FAST_SYSCALL_epoll_wait,
			 4, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_epoll_pwait, __FAST_SYSCALL_epoll_pwait, 6,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_epoll_pwait,
			 __FAST_SYSCALL_epoll_pwait, 6, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_epoll_ctl, __FAST_SYSCALL_epoll_ctl, 4,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_epoll_ctl, __FAST_SYSCALL_epoll_ctl,
			 4, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_ppoll, __FAST_SYSCALL_ppoll, 5,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_ppoll, __FAST_SYSCALL_ppoll, 5,
			 __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_poll, __FAST_SYSCALL_poll, 3,
			__LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR__newselect, __FAST_SYSCALL_select, 5,
			__LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_pselect6, __FAST_SYSCALL_pselect6, 6,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_pselect6, __FAST_SYSCALL_pselect6, 6,
			 __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_set_thread_area, __FAST_SYSCALL_set_tls, 1,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_set_thread_area,
			 __FAST_SYSCALL_set_tls, 1, __LSYSCALL_RET_TYPE_INT)

#if (defined CONFIG_DEBUG_BUILD) || (defined __HOST_LLT__)
LSYSCALL_MAP_ITEM(SVR_KERNEL, __LSYSCALL_TEST_SYSMGR_THREAD_CREF,
		  __FAST_SYSCALL_thread_cref, 1, __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __LSYSCALL_TEST_SYSMGR_THREAD_CREF,
			 __FAST_SYSCALL_thread_cref, 1, __LSYSCALL_RET_TYPE_INT)
#endif

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_membarrier, __FAST_SYSCALL_membarrier, 2,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_membarrier, __FAST_SYSCALL_membarrier,
			 2, __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_restart_syscall,
		  __FAST_SYSCALL_restart_syscall, 0, __LSYSCALL_RET_TYPE_LONG)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_restart_syscall,
			 __FAST_SYSCALL_restart_syscall, 0,
			 __LSYSCALL_RET_TYPE_LONG)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __LSYSCALL_KEVENTFD_CREATE,
		  __FAST_SYSCALL_keventfd_create, 2, __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __LSYSCALL_KEVENTFD_CREATE,
			 __FAST_SYSCALL_keventfd_create, 2,
			 __LSYSCALL_RET_TYPE_INT)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_read, __FAST_SYSCALL_kernel_read, 3,
		  __LSYSCALL_RET_TYPE_LONG)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_read, __FAST_SYSCALL_kernel_read, 3,
			 __LSYSCALL_RET_TYPE_LONG)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_write, __FAST_SYSCALL_kernel_write, 3,
		  __LSYSCALL_RET_TYPE_LONG)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_write, __FAST_SYSCALL_kernel_write, 3,
			 __LSYSCALL_RET_TYPE_LONG)

LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_close, __FAST_SYSCALL_kernel_close, 1,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_close, __FAST_SYSCALL_kernel_close, 1,
			 __LSYSCALL_RET_TYPE_INT)

#ifdef CONFIG_RRU_PEK
LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_ext_wait, __FAST_SYSCALL_trigger_wait, 2,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_ext_wait, __FAST_SYSCALL_trigger_wait, 2,
			 __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM(SVR_KERNEL, __NR_ext_ctrl, __FAST_SYSCALL_ext_global_2, 5,
		  __LSYSCALL_RET_TYPE_INT)
LSYSCALL_MAP_ITEM_COMPAT(SVR_KERNEL, __NR_ext_ctrl, __FAST_SYSCALL_ext_global_2, 5,
			 __LSYSCALL_RET_TYPE_INT)
#endif
