/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023-2023. All rights reserved.
 * Description: boottrace stages.
 * Author: Huawei OS Kernel Lab
 * Create: Sat Dec 9 16:20:11 2023
 */

#ifndef UAPI_HMKERNEL_BOOTTRACE_H
#define UAPI_HMKERNEL_BOOTTRACE_H

#define __BOOTTRACE_ELFLOADER_START	0
#define __BOOTTRACE_ELFLOADER_FINISH	1
#define __BOOTTRACE_KERNEL_START	2
#define __BOOTTRACE_KERNEL_POST_START	3
#define __BOOTTRACE_KERNEL_FINISH	4
#define __BOOTTRACE_KERNEL_NR		5

#define __BOOTTRACE_SYSMGR_START		10
#define __BOOTTRACE_SYSMGR_PRE_INIT		12
#define __BOOTTRACE_SYSMGR_EARLY_BOOT_DONE	14
#define __BOOTTRACE_SYSMGR_MEM_INIT		16
#define __BOOTTRACE_SYSMGR_PROCESS_INIT		18
#define __BOOTTRACE_SYSMGR_BOOT_DONE		20

#define __BOOTTRACE_KERNEL_EARLY_MAP		21
#define __BOOTTRACE_KERNEL_DEVICETREE_BOOT_DONE	22
#define __BOOTTRACE_KERNEL_SWITCH_VECTOR	23
#define __BOOTTRACE_KERNEL_PGSTRTBL_INIT_DONE	24
#define __BOOTTRACE_KERNEL_SWITCH_PGD		25
#define __BOOTTRACE_KERNEL_COREDEV_INIT_DONE	26
#define __BOOTTRACE_KERNEL_MODULES_INIT_DONE	27
#define __BOOTTRACE_KERNEL_CORE_INIT_DONE	28
#define __BOOTTRACE_KERNEL_KP_END   29

/* total: [200, 250] ; used: [200, 239] */
#define __BOOTTRACE_ELFLOADER_KP_START		40
#define __BOOTTRACE_ELFLOADER_KP_FINISH		41

#define __BOOTTRACE_ELFLOADER_KP_EARLYDEV	42
#define __BOOTTRACE_ELFLOADER_KP_PRE_MAIN	43
#define __BOOTTRACE_ELFLOADER_KP_DEVMAP_INIT	44
#define __BOOTTRACE_ELFLOADER_KP_MAPMEM		45
#define __BOOTTRACE_ELFLOADER_KP_MAPDEV		46
#define __BOOTTRACE_ELFLOADER_KP_EN_MMU		47
#define __BOOTTRACE_ELFLOADER_KP_VIRTMOD	48
#define __BOOTTRACE_ELFLOADER_KP_CTX_INIT_DONE	49
#define __BOOTTRACE_ELFLOADER_KP_BF_PIPE_MAIN	50

#define __BOOTTRACE_ELFLOADER_KP_MAIN_STAGE_START	51
#define __BOOTTRACE_ELFLOADER_KP_STATGE_NR		28
#define __BOOTTRACE_ELFLOADER_KP_MAIN_STATE_END		(__BOOTTRACE_ELFLOADER_KP_BF_PIPE_MAIN + __BOOTTRACE_ELFLOADER_KP_STATGE_NR) /* 79 */

#define __BOOTTRACE_ELFLOADER_KP_END	__BOOTTRACE_ELFLOADER_KP_MAIN_STATE_END
#endif
