EXTRA_CFLAGS += -I$(srctree)/include/platform_include/ffrt/uniform_id
EXTRA_CFLAGS += -I$(srctree)/samples/ldk/vendor
obj-$(CONFIG_FFRT_UNIFORM_ID_OHOS) += uniform_id.o
uniform_id-objs := uniform_id.o