ccflags-y += -I$(srctree)/include/
obj-y += mm_lb_v550.o
obj-y += mm_lb_drv_v550.o
obj-y += mm_lb_plat_v550.o
obj-y += mm_lb_sec_ops_v550.o
obj-y += mm_lb_pmu_v550.o
obj-$(CONFIG_MM_LB_GM_TEST) += mm_lb_gm_test.o
obj-$(CONFIG_MM_LB_TST) += mm_lb_tst_v550.o
