#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_HALL_INPUTHUB) += hall/
obj-$(CONFIG_FINGERPRINT) += fingerprint/
obj-$(CONFIG_SENSORS_COLOR_AP) += color_sensor/
obj-$(CONFIG_POS_HALL) += pos_hall/
obj-y += hw_pmic/
obj-y += weld/ privacy_mask/
obj-$(CONFIG_HUAWEI_OHOS_DSM) += dsm/
obj-${CONFIG_EXT_INPUTHUB} += ext_inputhub/
obj-$(CONFIG_POS_OPTOCOUPLER) += pos_optocoupler/
obj-$(CONFIG_SUPER_PRIVACY) += super_privacy/
