# dpa dump module
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/dump
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/pm
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/debugfs

obj-y += dump.o
