/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Description: Interfaces of uev list in sysmgr
 * Author: Huawei OS Kernel Lab
 * Create: Fri Nov 29 20:36:33 2019
 */

#ifndef LIBHMSYNC_UEV_UEV_TYPES_H
#define LIBHMSYNC_UEV_UEV_TYPES_H

enum locktrace_event_type {
	LOCKTRACE_EVENT_TYPE_UNINITIALIZED,
	LOCKTRACE_EVENT_TYPE_BEFORE_WAITING,
	LOCKTRACE_EVENT_TYPE_RWLOCK_INIT,
	LOCKTRACE_EVENT_TYPE_RWLOCK_READ_TRY_ACQUIRE_OK,
	LOCKTRACE_EVENT_TYPE_RWLOCK_READ_TRY_ACQUIRE_FAIL,
	LOCKTRACE_EVENT_TYPE_RWLOCK_READ_ACQUIRE,
	LOCKTRACE_EVENT_TYPE_RWLOCK_WRITE_TRY_ACQUIRE_OK,
	LOCKTRACE_EVENT_TYPE_RWLOCK_WRITE_TRY_ACQUIRE_FAIL,
	LOCKTRACE_EVENT_TYPE_RWLOCK_WRITE_ACQUIRE,
	LOCKTRACE_EVENT_TYPE_RWLOCK_UNLOCK,
	LOCKTRACE_EVENT_TYPE_MUTEX_INIT,
	LOCKTRACE_EVENT_TYPE_MUTEX_TRY_ACQUIRE_OK,
	LOCKTRACE_EVENT_TYPE_MUTEX_TRY_ACQUIRE_FAIL,
	LOCKTRACE_EVENT_TYPE_MUTEX_ACQUIRE,
	LOCKTRACE_EVENT_TYPE_MUTEX_UNLOCK,
	LOCKTRACE_EVENT_TYPE_MUTEX_INC_WAITERS,
	LOCKTRACE_EVENT_TYPE_MUTEX_DEC_WAITERS,
	LOCKTRACE_EVENT_TYPE_MUTEX_PAIR_ACQUIRE,
	LOCKTRACE_EVENT_TYPE_MUTEX_PAIR_UNLOCK,
	LOCKTRACE_EVENT_TYPE_PREEMPT_ENABLE,
	LOCKTRACE_EVENT_TYPE_PREEMPT_DISABLE,
	LOCKTRACE_EVENT_TYPE_PREEMPT_PROCESS_ENABLE,
	LOCKTRACE_EVENT_TYPE_PREEMPT_PROCESS_DISABLE,
	LOCKTRACE_EVENT_TYPE_PREEMPT_PROCESS_SET_SLV,
	LOCKTRACE_EVENT_TYPE_PREEMPT_THREAD_SET_SLV,
	LOCKTRACE_EVENT_TYPE_MAX,
};

#endif
