ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor

subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/platform
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera/sensor
subdir-ccflags-y += -I$(srctree)/platform_source/camera/drivers/media/native/camera

obj-y += power_utils.o
obj-y += extisp_driver.o
obj-y += extisp_sub_sensor.o
obj-y += extisp_xxw_xc8132_cfgs.o
obj-y += extisp_yhw_fic7609_cfgs.o

