obj-$(CONFIG_HW_PD_COMMON) += hw_pd_common.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_sysfs.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_ops.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_state.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_dsm.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_pps_charger.o
obj-$(CONFIG_HW_PD_COMMON) += hw_pd_quirks.o
obj-$(CONFIG_REVERSE_CHARGE) += hw_pd_reverse_sc.o