# analog headset pop window driver
ifdef CONFIG_ANA_HS_POP_WINDOW
	ccflags-y += -Idrivers/devkit/audiokit/
	ccflags-y += -I$(srctree)/drivers/devkit/audiokit/
endif
obj-$(CONFIG_ANA_HS_POP_WINDOW) += ana_hs_pop_window.o
