# dpa pm module
-include $(srctree)/drivers/platform_drivers/modem/drv/product_config/product_config.mk
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/pm
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/pm/hal
subdir-ccflags-y += -I$(srctree)/drivers/platform_drivers/modem/drv/dpa/base/dump


obj-y += pm.o
obj-y += rpm.o
obj-y += wakeup.o
obj-y += dbg.o
obj-y += hal/
