obj-m += tracefs.o
ccflags-y += ${DEVHOST_API_CFLAGS}
ccflags-y += "-I$(srctree)/uapps/devhost/ldk_ext/tracefs/include"
ccflags-y += "-I$(srctree)/uapps/devhost/include"
ccflags-y += -I${HMSDKSYSROOTPATH}/usr/include