obj-$(CONFIG_HUAWEI_SMARTCOM) += smartcom_netlink.o smartcom_utils.o smartcom_impl.o
obj-$(CONFIG_HUAWEI_SCHEDULE_DRIVER) += schedule_driver/
obj-$(CONFIG_HUAWEI_SMARTCOM) += nstack/
obj-$(CONFIG_HUAWEI_SMARTCOM_MPFLOW) += mpflow/
obj-$(CONFIG_HUAWEI_NAT_TRAV) += nat_trav/