/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2022-2022. All rights reserved.
 */

#ifndef _SMARTCOM_NETLINK_H
#define _SMARTCOM_NETLINK_H

#include <net/sock.h>
#include <linux/netlink.h>

#define SMARTCOM_SOCKET_BASE_EVENT 6
#define SMARTCOM_SOCKET_INFO_EVENT 7

#define SMARTCOM_NETLINK_INIT 1
#define SMARTCOM_NETLINK_EXIT 0

#define SMARTCOM_SUB_MOD_COMMON 0
#define SMARTCOM_SUB_MOD_SCHEDULE_DRIVE 1
#define SMARTCOM_SUB_MOD_NSTACK 5
#define SMARTCOM_SUB_MOD_MPFLOW 6
#define SMARTCOM_SUB_MOD_MAX 7

#define SMARTCOM_SUB_MOD_MASK 0xFF00
#define SMARTCOM_SUB_EVT_MASK 0x00FF
#define SMARTCOM_SUB_MOD_MASK_LEN 8

#define SMARTCOM_SUB_MOD_COMMON_BASE (SMARTCOM_SUB_MOD_COMMON << 8)
#define SMARTCOM_SUB_MOD_SCHEDULE_DRIVE_BASE (SMARTCOM_SUB_MOD_SCHEDULE_DRIVE << 8)
#define SMARTCOM_SUB_MOD_NSTACK_BASE (SMARTCOM_SUB_MOD_NSTACK << 8)
#define SMARTCOM_SUB_MOD_MPFLOW_BASE (SMARTCOM_SUB_MOD_MPFLOW << 8)

typedef enum monk_knl_msg_type {
	NETLINK_SMARTCOM_DK_BASE = SMARTCOM_SUB_MOD_COMMON_BASE | NLMSG_MIN_TYPE,
	NETLINK_SMARTCOM_DK_REG,    /* send from apk to register the PID for netlink kernel socket */
	NETLINK_SMARTCOM_DK_UNREG,      /* when apk exit send this type message to unregister */

	NETLINK_SMARTCOM_DK_SCHEDULE_DRIVE_BASE = SMARTCOM_SUB_MOD_SCHEDULE_DRIVE_BASE,
	NETLINK_SMARTCOM_DK_START_ACC,
	NETLINK_SMARTCOM_DK_STOP_ACC,
	NETLINK_SMARTCOM_DK_CLEAR,

	NETLINK_SMARTCOM_DK_NSTACK_BASE = SMARTCOM_SUB_MOD_NSTACK_BASE,
	NETLINK_SMARTCOM_DK_NSTACK_FI_CFG,  /* FI cfg */

	NETLINK_SMARTCOM_DK_MPFLOW_BASE = SMARTCOM_SUB_MOD_MPFLOW_BASE,
	NETLINK_SMARTCOM_DK_MPFLOW_START,
	NETLINK_SMARTCOM_DK_MPFLOW_STOP,
	NETLINK_SMARTCOM_DK_MPFLOW_RESET_FLOW,
	NETLINK_SMARTCOM_DK_MPFLOW_RESET_ALL_FLOW,
	NETLINK_SMARTCOM_DK_MPFLOW_IP_BIND_CONFIG,
	NETLINK_SMARTCOM_DK_MPFLOW_PORT_BIND_CONFIG,
	NETLINK_SMARTCOM_DK_MPFLOW_UPDATE_NETWORK_INFO,
	NETLINK_SMARTCOM_DK_MPFLOW_CHANGE_BURST_RADIO,
} smartcom_msg_type_en;

typedef enum monk_unsol_knl_msgtype {
	NETLINK_SMARTCOM_KD_COMM_BASE = SMARTCOM_SUB_MOD_COMMON_BASE | NLMSG_MIN_TYPE,

	NETLINK_SMARTCOM_KD_MPFLOW_BASE = SMARTCOM_SUB_MOD_MPFLOW_BASE,
	NETLINK_SMARTCOM_KD_MPFLOW_FALLBACK,
} smartcom_unsol_msg_type_en;

void smartcom_send_msg2daemon(int cmd, const void *data, int len);
#endif /* _SMARTCOM_NETLINK_H */
