/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2023. All rights reserved.
 * Description: ULWT thread monitor UAPI
 * Author: Huawei OS Kernel Lab
 * Create: Fri Jul 14 18:33:33 2023
 */
#ifndef UAPI_HMKERNEL_ULWT_MONITOR_H
#define UAPI_HMKERNEL_ULWT_MONITOR_H

#include <hmkernel/types.h>
#include <hmasm/page.h>

#define ULWT_MONITOR_INIT_FLAG				0x01
#define ULWT_MONITOR_ENABLE_FLAG			0x02
#define ULWT_MONITOR_DISABLE_FLAG			0x03
#define ULWT_MONITOR_WAIT_FLAG				0x04
#define ULWT_MONITOR_WAKE_FLAG				0x05
#define ULWT_MONITOR_SET_LIMIT_FLAG			0x06
#define ULWT_MONITOR_EPOLL_WAIT_FLAG			0x07
#define ULWT_MONITOR_EXECVE_FLAG			0x08
#define ULWT_MONITOR_CREATE_WORKER_FLAG			0x09

#define ULWT_MONITOR_NR_DOMAINS				13UL
#define ULWT_MONITOR_EPOLL_NUM				16UL
#define ULWT_MONITOR_CACHELINE_SIZE			64UL

#define ULWT_MONITOR_WAIT_FASTPATH_RETVAL		2UL
#define ULWT_MONITOR_WAIT_TIMEOUT_RETVAL		3UL

union __ulwt_value_per_cacheline_s {
	unsigned int value;
	unsigned char cacheline[ULWT_MONITOR_CACHELINE_SIZE];
} __attribute__((aligned(ULWT_MONITOR_CACHELINE_SIZE)));

struct __ulwt_mon_page_s {
	/* offset = 0 bytes */
	union __ulwt_value_per_cacheline_s sem[ULWT_MONITOR_NR_DOMAINS];
	/* offset = 832 bytes */
	int epfd_array[ULWT_MONITOR_EPOLL_NUM];
	/* offset = 896 bytes */
	unsigned int create_mask;
} __attribute__((aligned(PAGE_SIZE)));

#define ULWT_PROCESS_MAX_XSTREAM_NUM 512
struct ulwt_infopage_s {
	/* map thread (xstream in silk) to current ulwt (wu in silk) */
	struct ulwt_ns_vec_s {
		int rtid;
		int vtid;
	} thread_ulwt_vec[ULWT_PROCESS_MAX_XSTREAM_NUM];
};

/* Magic 'S', 'I', 'L', 'K' */
#define HM_PR_SILK_OPS 0x53494C4B
#define SILK_SYSFAST_OPS_START 0x1000

enum {
	SILK_SPECIAL_OPS_NONE,
	SILK_SPECIAL_OPS_CREATE_ULWT,
	SILK_SPECIAL_OPS_DESTROY_ULWT,
	SILK_SPECIAL_OPS_SET_SIG_ENTRY,
	SILK_SPECIAL_OPS_ULWT_BIND_KLT,
	SILK_SPECIAL_OPS_READ_ULWT_VEC_IDX,
	SILK_SPECIAL_OPS_DOWNGRADE_MAIN_KLT,
	SILK_SPECIAL_OPS_XSTREAM_GETTID,
	SILK_SPECIAL_OPS_RECEIVE_EVENT,
	SILK_SPECIAL_OPS_MONITOR_INIT,
	SILK_SPECIAL_OPS_CURR_CGROUP,
	SILK_SPECIAL_OPS_SIGTIMEDWAIT_BEGIN,
	SILK_SPECIAL_OPS_SIGTIMEDWAIT_END,
	SILK_SPECIAL_OPS_REGISTER_INFOPAGE,
	SILK_SPECIAL_OPS_INSTALL_EMU_HANDLER,
	SILK_SPECIAL_OPS_SET_EMU_CALLSITE,
	SILK_SPECIAL_OPS_CREATE_XSTREAM,
	SILK_SPECIAL_OPS_SET_XSTREAM_NAME,
	SILK_SPECIAL_OPS_UPDATE_CGROUP,
	SILK_SPECIAL_OPS_SCHED_TRANS,
	SILK_SPECIAL_OPS_REINIT_INFOPAGE,
	SILK_SPECIAL_OPS_HMERRNO2POSIX,
	SILK_SPECIAL_OPS_GETRPID,
	SILK_SPECIAL_OPS_WAKEUP_XSTREAM,
	SILK_SPECIAL_OPS_XSTREAM_SYNC_CRED,
	SILK_SPECIAL_OPS_XSTREAM_SYNC_SCHED,
	SILK_SPECIAL_OPS_GET_DOMAIN_ID,
	SILK_NATIVE_OPS_GETPID,
	SILK_NATIVE_OPS_GETTID,
	SILK_NATIVE_OPS_EXIT_GROUP,
	SILK_NATIVE_OPS_MUNMAP,
	SILK_NATIVE_OPS_EXIT,
	SILK_NATIVE_OPS_RT_SIGPROCMASK,
	SILK_NATIVE_OPS_RT_SIGRETURN,
	SILK_SYSFAST_OPS_SCHED_YIELD = SILK_SYSFAST_OPS_START,
	SILK_SYSFAST_OPS_FUTEX_WAIT,
	SILK_SYSFAST_OPS_MISCDATA_READ,
	SILK_SYSFAST_OPS_MISCDATA_WRITE,
	SILK_SYSFAST_OPS_MISCDATA_READV,
	SILK_SYSFAST_OPS_SET_TLS,
	SILK_SYSFAST_OPS_EPOLL_WAIT,
	SILK_SYSFAST_OPS_ULWT_THREAD_MONITOR,
	SILK_SYSFAST_OPS_THREAD_CREF,
};

#endif
