obj-$(CONFIG_HUAWEI_AUDIO_MISC) += audio_misc.o
obj-$(CONFIG_HUAWEI_AUDIO_MISC) += buck_boost_notifier/
obj-$(CONFIG_AUDIO_VIBRATOR_STATE) += vibrator_state/
obj-$(CONFIG_AUDIO_HIFI_REPORT) += hifi_report/
obj-$(CONFIG_AUDIO_BATTERY_STATE) += battery_state/
obj-$(CONFIG_COLLEC_AUDIO_INFO) += collec_audio_info/
obj-$(CONFIG_AUDIO_VENDORCOUNTRY_STATE) += vendorcountry_state/
obj-$(CONFIG_AUDIO_MIC_BLOCK) += audio_mic_block/
