/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description: power_reboot.h for uapi
 * Author: Huawei OS Kernel Lab
 * Create: Tue Sep 28 018:44:43 2021
 */

#ifndef UAPI_HMKERNEL_POWER_REBOOT_H
#define UAPI_HMKERNEL_POWER_REBOOT_H

enum system_reboot_type {
	SYSTEM_REBOOT_BASE = 0xffff0000,

	SYSTEM_REBOOT_PANIC_START = SYSTEM_REBOOT_BASE,
	SYSTEM_REBOOT_KERNEL_PANIC = SYSTEM_REBOOT_PANIC_START,
	SYSTEM_REBOOT_SYSMGR_PANIC,
	SYSTEM_REBOOT_INIT_PANIC,
	SYSTEM_REBOOT_NOREASON,
	SYSTEM_REBOOT_DEVHOST_PANIC,
	SYSTEM_REBOOT_HARDDOG_HUNGRY,
	SYSTEM_REBOOT_LOWDOG_HUNGRY,
	SYSTEM_REBOOT_HIGHDOG_HUNGRY,
	SYSTEM_REBOOT_HKIP_PANIC,
	SYSTEM_REBOOT_INJECT_PANIC,
	SYSTEM_REBOOT_SERROR_PANIC,
	SYSTEM_REBOOT_OOM_PANIC,
	SYSTEM_REBOOT_PANIC_END = SYSTEM_REBOOT_OOM_PANIC,

	SYSTEM_REBOOT_COLDBOOT,
	SYSTEM_REBOOT_KEXEC,
	SYSTEM_REBOOT_SNAPSHOT,
	SYSTEM_REBOOT_MAX,
};

enum highdog_reboot_type {
	HIGHDOG_REASON_NONE = 0,
	HIGHDOG_REASON_BASE = 0xfffe0000,
	HIGHDOG_REASON_HGUARD_ABNORMAL = HIGHDOG_REASON_BASE,
	HIGHDOG_REASON_USER_SERVICE_FAIL,
	HIGHDOG_REASON_USER_SERVICE_HEARTBEAT,
	HIGHDOG_REASON_USER_CONFIG_HANGTASK,
	HIGHDOG_REASON_SYSTEM_SERVICE_FAIL,
	HIGHDOG_REASON_SYSTEM_DEADSCHED,
	HIGHDOG_REASON_SYSTEM_DEADLOCK,
	HIGHDOG_REASON_SYSTEM_STARTUP_STUCK,
	HIGHDOG_REASON_SYSTEM_SHUTDOWN_STUCK,
	HIGHDOG_REASON_MAX,
};

#define SYSTEM_REBOOT_MAX_NUM	(((unsigned int)(SYSTEM_REBOOT_MAX)) - ((unsigned int)(SYSTEM_REBOOT_BASE)))
#define HIGHDOG_REBOOT_MAX_NUM	(((unsigned int)(HIGHDOG_REASON_MAX)) - ((unsigned int)(HIGHDOG_REASON_BASE)))
#define REBOOT_TYPE_IS_PANIC(reboot_type) \
	(((reboot_type) >= SYSTEM_REBOOT_PANIC_START && (reboot_type) <= SYSTEM_REBOOT_PANIC_END) || \
	((reboot_type) >= HIGHDOG_REASON_BASE && (reboot_type) < HIGHDOG_REASON_MAX))

#endif
