EXTRA_CFLAGS += -Idrivers/hisi/tzdriver

obj-$(CONFIG_HW_BINDER_RECORD)       += hw_binder_record.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kstate.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kcollect.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_procnetstat.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kpg.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kpwd.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_astate_dispatch.o
