/* The first entry is a catch-all for codes not enumerated here.
 * This file is included multiple times to declare and define a structure
 * with these messages, and then to define a lookup table translating
 * error codes to offsets of corresponding fields in the structure. */

E(0,            "No error information")

E(EILSEQ,       "Invalid or incomplete multibyte or wide character")
E(EDOM,         "Numerical argument out of domain")
E(ERANGE,       "Numerical result out of range")

E(ENOTTY,       "Inappropriate ioctl for device")
E(EACCES,       "Permission denied")
E(EPERM,        "Operation not permitted")
E(ENOENT,       "No such file or directory")
E(ESRCH,        "No such process")
E(EEXIST,       "File exists")

E(EOVERFLOW,    "Value too large for defined data type")
E(ENOSPC,       "No space left on device")
E(ENOMEM,       "Cannot allocate memory")

E(EBUSY,        "Device or resource busy")
E(EINTR,        "Interrupted system call")
E(EAGAIN,       "Resource temporarily unavailable")
E(ESPIPE,       "Invalid seek")

E(EXDEV,        "Invalid cross-device link")
E(EROFS,        "Read-only file system")
E(ENOTEMPTY,    "Directory not empty")

E(ECONNRESET,   "Connection reset by peer")
E(ETIMEDOUT,    "Connection timed out")
E(ECONNREFUSED, "Connection refused")
E(EHOSTDOWN,    "Host is down")
E(EHOSTUNREACH, "No route to host")
E(EADDRINUSE,   "Address already in use")

E(EPIPE,        "Broken pipe")
E(EIO,          "Input/Output error")
E(ENXIO,        "No such device or address")
E(ENOTBLK,      "Block device required")
E(ENODEV,       "No such device")
E(ENOTDIR,      "Not a directory")
E(EISDIR,       "Is a directory")
E(ETXTBSY,      "Text file busy")
E(ENOEXEC,      "Exec format error")

E(EINVAL,       "Invalid argument")

E(E2BIG,        "Argument list too long")
E(ELOOP,        "Too many levels of symbolic links")
E(ENAMETOOLONG, "File name too long")
E(ENFILE,       "Too many open files in system")
E(EMFILE,       "Too many open files")
E(EBADF,        "Bad file descriptor")
E(ECHILD,       "No child processes")
E(EFAULT,       "Bad address")
E(EFBIG,        "File too large")
E(EMLINK,       "Too many links")
E(ENOLCK,       "No locks available")

E(EDEADLK,      "Resource deadlock avoided")
E(ENOTRECOVERABLE, "State not recoverable")
E(EOWNERDEAD,   "Owner died")
E(ECANCELED,    "Operation canceled")
E(ENOSYS,       "Function not implemented")
E(ENOMSG,       "No message of desired type")
E(EIDRM,        "Identifier removed")
E(ENOSTR,       "Device not a stream")
E(ENODATA,      "No data available")
E(ETIME,        "Timer expired")
E(ENOSR,        "Out of streams resources")
E(ENOLINK,      "Link has been severed")
E(EPROTO,       "Protocol error")
E(EBADMSG,      "Bad message")
E(EBADFD,       "File descriptor in bad state")
E(ENOTSOCK,     "Socket operation on non-socket")
E(EDESTADDRREQ, "Destination address required")
E(EMSGSIZE,     "Message too large")
E(EPROTOTYPE,   "Protocol wrong type for socket")
E(ENOPROTOOPT,  "Protocol not available")
E(EPROTONOSUPPORT,"Protocol not supported")
E(ESOCKTNOSUPPORT,"Socket type not supported")
E(ENOTSUP,      "Operation not supported")
E(EPFNOSUPPORT, "Protocol family not supported")
E(EAFNOSUPPORT, "Address family not supported by protocol")
E(EADDRNOTAVAIL,"Cannot assign requested address")
E(ENETDOWN,     "Network is down")
E(ENETUNREACH,  "Network is unreachable")
E(ENETRESET,    "Network dropped connection on reset")
E(ECONNABORTED, "Software caused connection abort")
E(ENOBUFS,      "No buffer space available")
E(EISCONN,      "Transport endpoint is already connected")
E(ENOTCONN,     "Transport endpoint is not connected")
E(ESHUTDOWN,    "Cannot send after transport endpoint shutdown")
E(EALREADY,     "Operation already in progress")
E(EINPROGRESS,  "Operation now in progress")
E(ESTALE,       "Stale file handle")
E(EREMOTEIO,    "Remote I/O error")
E(EDQUOT,       "Disk quota exceeded")
E(ENOMEDIUM,    "No medium found")
E(EMEDIUMTYPE,  "Wrong medium type")
E(EMULTIHOP,    "Multihop attempted")

E(ECHRNG,       "Channel number out of range")
E(EL2NSYNC,     "Level 2 not synchronized")
E(EL3HLT,       "Level 3 halted")
E(EL3RST,       "Level 3 reset")
E(ELNRNG,       "Link number out of range")
E(EUNATCH,      "Protocol driver not attached")
E(ENOCSI,       "No CSI structure available")
E(EL2HLT,       "Level 2 haltd")
E(EBADE,        "Invalid exchange")
E(EBADR,        "Invalid request descriptor")
E(EXFULL,       "Exchange full")
E(ENOANO,       "No anode")
E(EBADRQC,      "Invalid request code")
E(EBADSLT,      "Invalid slot")
E(EBFONT,       "Bad font file format")
E(ENONET,       "Machine is not on the network")
E(ENOPKG,       "Package not installed")
E(EREMOTE,      "Object is remote")
E(EADV,         "Advertise error")
E(ESRMNT,       "Srmount error")
E(ECOMM,        "Communication error on send")
E(EDOTDOT,      "RFS specific error")
E(ENOTUNIQ,     "Name not unique on network")
E(EREMCHG,      "Remote address changed")
E(ELIBACC,      "Can not access a needed shared library")
E(ELIBBAD,      "Accessing a corrupted shared library")
E(ELIBSCN,      ".lib section in a.out corrupted")
E(ELIBMAX,      "Attempting to link in too many shared libraries")
E(ELIBEXEC,     "Cannot exec a shared library directly")
E(ERESTART,     "Interrupted system call should be restarte")
E(ESTRPIPE,     "Streams pipe error")
E(EUSERS,       "Too many users")
E(ETOOMANYREFS, "Too many references: cannot splice")
E(EUCLEAN,      "Structure needs cleaning")
E(ENOTNAM,      "Not a XENIX named type file")
E(ENAVAIL,      "No XENIX semaphores available")
E(EISNAM,       "Is a named type file")
E(ENOKEY,       "Required key not available")
E(EKEYEXPIRED,  "Key has expired")
E(EKEYREVOKED,  "Key has been revoked")
E(EKEYREJECTED, "Key was rejected by service")
E(ERFKILL,      "Operation not possible due to RF-kill")
E(EHWPOISON,    "Memory page has hardware error")

