/*
 * Copyright (c Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Description: ddr sec rdr mntn header file
 * Create: 2024-09-01
 */

#ifndef __DDR_SEC_RDR_MNTN_H__
#define __DDR_SEC_RDR_MNTN_H__

/* immediate number from global_ddr_map */
#define ATF_SUB_RESERVED_BL31_SHARE_MEM_PHYMEM_BASE_DDR_SEC    (0x10941000)

enum dmss_subreason{
	/* DDRC_SEC SUBTYPE REASON */
	MODID_DDR_SEC_BEGIN  = 0x80000100,
	MODID_DDR_SEC_CPU_RTM,
	MODID_DDR_SEC_PERF_STAT0,
	MODID_DDR_SEC_IPF,
	MODID_DDR_SEC_DJTAG_M,
	MODID_DDR_SEC_AO_TCP,
	MODID_DDR_SEC_QSPI,
	MODID_DDR_SEC_GICV600,
	MODID_DDR_SEC_SPI3_DMA,
	MODID_DDR_SEC_TOP_CSSYS,
	MODID_DDR_SEC_IOMCU_M7,
	MODID_DDR_SEC_SOCP,
	MODID_DDR_SEC_USB3,
	MODID_DDR_SEC_ASP_DMA_HDMI,
	MODID_DDR_SEC_DMAC,
	MODID_DDR_SEC_ASP_LINGLONG,
	MODID_DDR_SEC_FFTS,
	MODID_DDR_SEC_SPE,
	MODID_DDR_SEC_MAA,
	MODID_DDR_SEC_POWER_STAT,
	MODID_DDR_SEC_MSPC,
	MODID_DDR_SEC_DDR_LPCTRL,
	MODID_DDR_SEC_EICC,
	MODID_DDR_SEC_IOMCU_DMA,
	MODID_DDR_SEC_SDIO,
	MODID_DDR_SEC_LPMCU,
	MODID_DDR_SEC_NPU,
	MODID_DDR_SEC_GPU,
	MODID_DDR_SEC_FCM,
	MODID_DDR_SEC_ISP,
	MODID_DDR_SEC_VENC,
	MODID_DDR_SEC_VDEC,
	MODID_DDR_SEC_DSS,
	MODID_DDR_SEC_MEDIA1,
	MODID_DDR_SEC_MEDIA2,
	MODID_DDR_SEC_IDI2AXI,
	MODID_DDR_SEC_IPP_SUBSYS,
	MODID_DDR_SEC_SYSTEM_CACHE,
	MODID_DDR_SEC_MODEM,
	MODID_DDR_SEC_HTS_MSG,
	MODID_DDR_SEC_FFTS_MSG,
	MODID_DDR_SEC_FFA2_MSG,
	MODID_DDR_SEC_FFA1_MSG,
	MODID_DDR_SEC_DFA,
	MODID_DDR_SEC_MUDP,
	MODID_DDR_SEC_PCIE,
	MODID_DDR_SEC_MSPE,
	MODID_DDR_SEC_MAX
};

#endif