#
# Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
#

INCLUDE_DIR += \
	-I$(HVGR_PATH)/platform \
	-I$(HVGR_PATH)/platform/$(HVGR_PLATFORM_NAME) \
	-I$(HVGR_PATH)/platform/pdefault

SRC += \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_map.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_reset.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_ecc.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_cq.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_smc.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_mem.c \
	$(HVGR_ROOT)/platform/pdefault/hvgr_platform_cfg.c

ifeq ($(CONFIG_HVGR_DFX_SH), y)
	SRC += $(HVGR_ROOT)/platform/pdefault/hvgr_platform_dfx.c
endif

ifeq ($(HVGR_FEATURE_SYSTEM_CACHE), 1)
	SRC += $(HVGR_ROOT)/platform/pdefault/hvgr_platform_mem_sc.c
endif
