/*
* Copyright (c) @CompanyNameMagicTag 2021-2023. All rights reserved.
* 功能说明   : CSI功能
* 作者       : wifi
* 创建日期   : 2020年11月17日
*/
#ifndef HOST_CSI_MP17C_H
#define HOST_CSI_MP17C_H

#include "host_mac_mp17c.h"
#include "host_dscr_mp17c.h"

#define MAC_PPU_REG_CFG_ML0_CSI_SAMPLE_PERIOD_LEN 4
#define MAC_PPU_REG_CFG_ML0_CSI_SAMPLE_PERIOD_OFFSET 24
#define MAC_PPU_REG_CFG_ML0_CSI_SAMPLE_PERIOD_MASK  0xF000000
#define MAC_PPU_REG_CFG_ML1_CSI_SAMPLE_PERIOD_LEN 4
#define MAC_PPU_REG_CFG_ML1_CSI_SAMPLE_PERIOD_OFFSET 24
#define MAC_PPU_REG_CFG_ML1_CSI_SAMPLE_PERIOD_MASK  0xF000000

#define MAC_PPU_REG_CFG_ML0_CSI_BAND_WIDTH_MASK_LEN 4
#define MAC_PPU_REG_CFG_ML0_CSI_BAND_WIDTH_MASK_OFFSET 20
#define MAC_PPU_REG_CFG_ML0_CSI_BAND_WIDTH_MASK_MASK  0xF00000
#define MAC_PPU_REG_CFG_ML1_CSI_BAND_WIDTH_MASK_LEN 4
#define MAC_PPU_REG_CFG_ML1_CSI_BAND_WIDTH_MASK_OFFSET 20
#define MAC_PPU_REG_CFG_ML1_CSI_BAND_WIDTH_MASK_MASK  0xF00000

#define MAC_PPU_REG_CFG_ML0_CSI_FRAME_TYPE_MASK_LEN 4
#define MAC_PPU_REG_CFG_ML0_CSI_FRAME_TYPE_MASK_OFFSET 16
#define MAC_PPU_REG_CFG_ML0_CSI_FRAME_TYPE_MASK_MASK  0xF0000
#define MAC_PPU_REG_CFG_ML1_CSI_FRAME_TYPE_MASK_LEN 4
#define MAC_PPU_REG_CFG_ML1_CSI_FRAME_TYPE_MASK_OFFSET 16
#define MAC_PPU_REG_CFG_ML1_CSI_FRAME_TYPE_MASK_MASK  0xF0000

#define MAC_PPU_REG_CFG_ML0_CSI_H_MATRIX_RPT_EN_LEN 1
#define MAC_PPU_REG_CFG_ML0_CSI_H_MATRIX_RPT_EN_OFFSET 1
#define MAC_PPU_REG_CFG_ML0_CSI_H_MATRIX_RPT_EN_MASK  0x2
#define MAC_PPU_REG_CFG_ML1_CSI_H_MATRIX_RPT_EN_LEN 1
#define MAC_PPU_REG_CFG_ML1_CSI_H_MATRIX_RPT_EN_OFFSET 1
#define MAC_PPU_REG_CFG_ML1_CSI_H_MATRIX_RPT_EN_MASK  0x2

#define MAC_PPU_REG_CFG_ML0_CSI_EN_LEN 1
#define MAC_PPU_REG_CFG_ML0_CSI_EN_OFFSET 0
#define MAC_PPU_REG_CFG_ML0_CSI_EN_MASK  0x1
#define MAC_PPU_REG_CFG_ML1_CSI_EN_LEN 1
#define MAC_PPU_REG_CFG_ML1_CSI_EN_OFFSET 0
#define MAC_PPU_REG_CFG_ML1_CSI_EN_MASK  0x1

#define MAC_RPU_REG_CFG_RX_PPDU_DESC_MODE_LEN    2
#define MAC_RPU_REG_CFG_RX_PPDU_DESC_MODE_OFFSET    16
#define MAC_RPU_REG_CFG_RX_PPDU_DESC_MODE_MASK  0x30000

#define RX_CHN_EST_REG_BANK_CFG_CHN_CONDITION_NUM_RPT_EN_LEN    1
#define RX_CHN_EST_REG_BANK_CFG_CHN_CONDITION_NUM_RPT_EN_OFFSET    10
#define RX_CHN_EST_REG_BANK_CFG_CHN_CONDITION_NUM_RPT_EN_MASK  0x400

#define MAC_COMMON_REG_RPT_DMAC_INTR_LOCATION_COMPLETE_LEN 1
#define MAC_COMMON_REG_RPT_DMAC_INTR_LOCATION_COMPLETE_OFFSET 1
#define MAC_COMMON_REG_RPT_DMAC_INTR_LOCATION_COMPLETE_MASK  0x2

#define MAC_PPU_REG_RPT_LOCATION_INFO_MASK_LEN 3
#define MAC_PPU_REG_RPT_LOCATION_INFO_MASK_OFFSET 0
#define MAC_PPU_REG_RPT_LOCATION_INFO_MASK_MASK  0x7

#define MAC_COMMON_REG_RPT_HOST_INTR_LOCATION_COMPLETE_LEN 1
#define MAC_COMMON_REG_RPT_HOST_INTR_LOCATION_COMPLETE_OFFSET 0
#define MAC_COMMON_REG_RPT_HOST_INTR_LOCATION_COMPLETE_MASK  0x1

#ifdef _PRE_WLAN_FEATURE_CSI

uint32_t mp17c_get_host_ftm_csi_locationinfo(hal_host_device_stru *hal_device);
uint32_t mp17c_get_csi_info(hmac_csi_info_stru *hmac_csi_info, uint8_t *addr);
uint32_t mp17c_csi_config(uint16_t vap_idx, uint16_t len, uint8_t *param);
uint32_t mp17c_host_ftm_csi_init(hal_host_device_stru *hal_device);
#endif
#endif
