// SPDX-License-Identifier: GPL-2.0
/*
 * power_dsm_config_single.c
 *
 * dsm for power module
 *
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#include <chipset_common/hwpower/common_module/power_dsm_config_single.h>
#include <chipset_common/hwpower/common_module/power_printk.h>
#include <chipset_common/hwpower/common_module/power_dsm.h>
#include <securec.h>

#define HWLOG_TAG power_dsm_single
HWLOG_REGIST();

struct hisysevent_error_no_map hisysevent_map[] = {
	{ DSM_BATTERY_DETECT_ERROR_NO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_ID_DET_ABNORMAL", "CONTENT", 0 },
	{ DSM_BATTERY_ROM_ID_CERTIFICATION_FAIL, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"BAT_ROM_ID_CERTIFICATION_FAIL", "CONTENT", 1 },
	{ DSM_BATTERY_IC_EEPROM_STATE_ERROR, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"BAT_IC_EEPROM_STATE_ERROR", "CONTENT", 1 },
	{ DSM_BATTERY_IC_KEY_CERTIFICATION_FAIL, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"BAT_IC_KEY_CERTIFICATION_FAIL", "CONTENT", 1 },
	{ DSM_OLD_BOARD_AND_OLD_BATTERY_UNMATCH, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"OLD_BOARD_AND_OLD_BAT_UNMATCH", "CONTENT", 1 },
	{ DSM_OLD_BOARD_AND_NEW_BATTERY_UNMATCH, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"OLD_BOARD_AND_NEW_BAT_UNMATCH", "CONTENT", 0 },
	{ DSM_NEW_BOARD_AND_OLD_BATTERY_UNMATCH, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"NEW_BOARD_AND_OLD_BAT_UNMATCH", "CONTENT", 0 },
	{ DSM_BATTERY_NV_DATA_READ_FAIL, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_NV_DATA_READ_FAIL", "CONTENT", 1 },
	{ DSM_CERTIFICATION_SERVICE_IS_NOT_RESPONDING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"CERT_SERVICE_NOT_RESPONDING", "CONTENT", 1 },
	{ DSM_UNMATCH_BATTERYS, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "SN_OF_BATTERIES_MISMATCHED", "CONTENT", 0 },
	{ DSM_LIGHTSTRAP_STATUS, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "RING_FLASH_HOUSING", "CONTENT", 0 },
	{ DSM_DUAL_BATTERY_CURRENT_BIAS_DETECT, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DUAL_BAT_CUR_BIAS_DETECT", "CONTENT", 0 },
	{ DSM_DUAL_BATTERY_CAPACITY_DIFFERENT_DETECT, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DUAL_BAT_CAP_DIFF_DETECT", "CONTENT", 0 },
	{ DSM_DUAL_BATTERY_OUT_OF_POSITION_DETECTION, POWER_DSM_LEVEL_FAULT, "BATTERY", "DUAL_BAT_ABSENCE", "CONTENT", 0 },

	/* battery */
	{ ERROR_BATT_NOT_EXIST, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_ABSENCE", "CONTENT", 0 },
	{ ERROR_BATT_TEMP_LOW, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_UNDER_TEMPERATURE", "CONTENT", 0 },
	{ ERROR_BATT_VOLT_HIGH, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_OVER_VOLTAGE", "CONTENT", 0 },
	{ ERROR_BATT_VOLT_LOW, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_UNDER_VOLTAGE", "CONTENT", 0 },
	{ ERROR_BATT_TERMINATE_TOO_EARLY, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_CUTOFF_EARLY", "CONTENT", 0 },
	{ ERROR_BATT_NOT_TERMINATE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_CUTOFF_NEVER", "CONTENT", 0 },
	{ ERROR_BATT_BAD_CURR_SENSOR, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_CURRENT_DETECT_ERROR", "CONTENT", 0 },
	{ ERROR_VBUS_VOLT_HIGH, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "VBUS_OVER_VOLTAGE", "CONTENT", 0 },
	{ ERROR_WATCHDOG_RESET, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATCHDOG_OVER_TIME", "CONTENT", 0 },
	{ ERROR_CHARGE_CURR_OVERHIGH, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGING_CURRENT_LARGE", "CONTENT", 0 },
	{ ERROR_DISCHARGE_CURR_OVERHIGH, POWER_DSM_LEVEL_FAULT, "BATTERY", "DISCHARGING_CURRENT_LARGE", "CONTENT", 0 },
	{ ERROR_CHARGE_CURR_ZERO, POWER_DSM_LEVEL_FAULT, "BATTERY", "RESISTER_CURRENT_ZERO", "CONTENT", 0 },
	{ ERROR_CHARGE_TEMP_FAULT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "TEMP_FAULT_NOT_CHARGING", "CONTENT", 0 },
	{ ERROR_CHARGE_BATT_TEMP_SHUTDOWN, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_SHUTDOWN_TEMP", "CONTENT", 0 },
	{ ERROR_CHARGE_BATT_CAPACITY, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_CAPACITY", "CONTENT", 0 },
	{ ERROR_CHARGE_CHARGER_TS, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGER_TS", "CONTENT", 0 },
	{ ERROR_CHARGE_OTG, POWER_DSM_LEVEL_FAULT, "BATTERY", "OTG_TURE_NO_OTG_DEVICE", "CONTENT", 0 },
	{ ERROR_FCP_VOL_OVER_HIGH, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "VBUS_VOLTAGE_ABNORMAL", "CONTENT", 0 },
	{ ERROR_FCP_DETECT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "FCP_DETECT_FAILED", "CONTENT", 0 },
	{ ERROR_FCP_OUTPUT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "FCP_BOOST_FAILED", "CONTENT", 0 },
	{ ERROR_SWITCH_ATTACH, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "FCP_DEATTACH", "CONTENT", 0 },
	{ ERROR_ADAPTER_OVLT, POWER_DSM_LEVEL_FAULT, "BATTERY", "FCP_OVER_VOLTAGE", "CONTENT", 0 },
	{ ERROR_ADAPTER_OCCURRENT, POWER_DSM_LEVEL_FAULT, "BATTERY", "FCP_OVER_CURRENT", "CONTENT", 0 },
	{ ERROR_ADAPTER_OTEMP, POWER_DSM_LEVEL_FAULT, "BATTERY", "FCP_OVER_TEMPERATURE", "CONTENT", 0 },
	{ ERROR_SAFE_PLOICY_LEARN, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_FCC_LEARN", "CONTENT", 0 },
	{ ERROR_SAFE_PLOICY_LEARN1, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_FCC_LEARN_ONLY_90", "CONTENT", 0 },
	{ ERROR_WEAKSOURCE_HAPPEN, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WEAKSOURCE_HAPPENED", "CONTENT", 0 },
	{ ERROR_SAFE_PLOICY_LEARN2, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_FCC_LEARN_ONLY_80", "CONTENT", 0 },
	{ ERROR_SAFE_PLOICY_LEARN3, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_FCC_LEARN_ONLY_60", "CONTENT", 0 },
	{ ERROR_BOOST_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "OTG_OCP", "CONTENT", 0 },
	{ ERROR_CHARGE_I2C_RW, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGER_I2C_RW_FAIL", "CONTENT", 0 },
	{ ERROR_BATT_SOC_CHANGE_FAST, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_SOC_VARY_TOO_FAST", "CONTENT", 0 },
	{ ERROR_CHARGE_VBAT_OVP, POWER_DSM_LEVEL_FAULT, "BATTERY", "VBAT_OVP", "CONTENT", 0 },
	{ ERROR_SAFE_PLOICY_LEARN4, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_FCC_LEARN_ONLY_95", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL0, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "ISC_IS_BELOW_10MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL1, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "ISC_IS_BETWEEN_10_15_MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL2, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "ISC_IS_BETWEEN_15_20_MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL3, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "ISC_IS_BETWEEN_20_25_MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL4, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "ISC_IS_BETWEEN_25_30_MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL5, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_IS_BETWEEN_30_50MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL6, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_IS_BETWEEN_50_100MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL7, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_IS_BETWEEN_100_200MA", "CONTENT", 0 },
	{ DSM_BATTERY_ISCD_LEVEL8, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_IS_ABOVE_200_MA", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_ERR_WITH_NONSTD_CABLE, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DC_FAIL_WITH_NON_STAND_CABLE", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_VOL_ACCURACY, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_VOL_ACCURACY", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_FULL_PATH_RESISTANCE, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DC_FULL_PATH_RESISTANCE", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_ERR_WITH_STD_CABLE, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"DC_DISABLED_ERROR_EXCEED_TIMES", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_USB_PORT_LEAKAGE_CURRENT, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DC_LEAKAGE_CURRENT_OVER_TH", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_VBUS_OVP, POWER_DSM_LEVEL_FAULT, "BATTERY", "DC_VBUS_OVP_HAPPENED", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_REVERSE_OCP, POWER_DSM_LEVEL_FAULT, "BATTERY", "DC_REVERSE_OCP_HAPPENED", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_OTP, POWER_DSM_LEVEL_FAULT, "BATTERY", "DC_OTP_HAPPENED", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_INPUT_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_INPUT_OCP_HAPPENED", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_ADAPTER_OTP, POWER_DSM_LEVEL_FAULT, "BATTERY", "DC_ADAPTOR_OTP", "CONTENT", 0 },
	{ ERROR_WEAKSOURCE_STOP_CHARGE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WEAK_SOURCE_HAPPENED", "CONTENT", 0 },
	{ ERROR_CHARGE_TEMP_WARM, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "TEMPERATURE_WARM", "CONTENT", 0 },
	{ ERROR_VBUS_VOL_OVER_13400MV, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "VBUS_OVER_13400MV", "CONTENT", 0 },
	{ ERROR_COUL_ROLLBACK, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "COUL_ABNORMAL_ROLLBACK", "CONTENT", 0 },
	{ ERROR_LOW_VOL_INT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "LOW_VOLTAGE_INTERRUPT", "CONTENT", 0 },
	{ DSM_BATTERY_COUL_DROP_INT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "VBAT_DROP_INTERRUPT", "CONTENT", 0 },
	{ ERROR_REFRESH_FCC_OUTSIDE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DELTA_FCC_HIGHER_THAN_TH", "CONTENT", 0 },
	{ ERROR_RESUME_SOC_JUMP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "COUL_RESUME_CAP_CHANGE_OVER_5", "CONTENT", 0 },
	{ ERROR_FATAL_ISC_CASE1, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_OVER_50MA_TWICE_FOR_15_DAYS", "CONTENT", 0 },
	{ ERROR_FATAL_ISC_CASE2, POWER_DSM_LEVEL_FAULT, "BATTERY", "ISC_OVER_30MA_THREE_FOR_15_DAYS", "CONTENT", 0 },
	{ ERROR_WIRELESS_CHECK_TX_ABILITY_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "WLC_GET_TX_ABILITY_FAIL", "CONTENT", 0 },
	{ ERROR_WIRELESS_CERTI_COMM_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "WLC_CERT_COMM_FAIL", "CONTENT", 0 },
	{ ERROR_WIRELESS_CERTI_SERVICE_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "WLC_CERT_SVC_EXC", "CONTENT", 0 },
	{ ERROR_WIRELESS_BOOSTING_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "WLC_BOOSTING_FAIL", "CONTENT", 0 },
	{ ERROR_WIRELESS_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY", "WL_SC_EXCEPTION", "CONTENT", 0 },
	{ ERROR_WIRELESS_RX_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WLC_RX_OCP_HAPPENED", "CONTENT", 0 },
	{ ERROR_WIRELESS_RX_OTP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WLC_RX_OTP_HAPPENED", "CONTENT", 0 },
	{ ERROR_WIRELESS_RX_OVP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WLC_RX_OVP_HAPPENED", "CONTENT", 0 },
	{ ERROR_WIRELESS_RX_OPP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WLC_RX_OPP_HAPPENED", "CONTENT", 0 },
	{ ERROR_WIRELESS_STATISTICS, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WLC_POWER_STATISTICAL_INFO", "CONTENT", 0 },
	{ DSM_BATTERY_CHANGED_NO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "CHARGECYCLE_CLEAR", "CONTENT", 0 },
	{ DSM_BATTERY_DRAINED_NO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "LOW_INITIAL_BAT_VOLTAGE", "CONTENT", 0 },
	{ ERROR_WIRELESS_TX_POWER_SUPPLY_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "WL_TX_POWER_SUPPLY_FAIL", "CONTENT", 0 },
	{ ERROR_WIRELESS_TX_BATTERY_OVERHEAT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WL_TX_BATTERY_OVERHEAT", "CONTENT", 0 },
	{ ERROR_WIRELESS_TX_FOD_PING_TIMEOUT, POWER_DSM_LEVEL_STATISTIC, "DSM_BATTERY", "WL_TX_ERRSTATUS", "CONTENT", 0 },
	{ ERROR_WIRELESS_TX_CEP_TIMEOUT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WL_TX_CEP_TIMEOUT", "CONTENT", 0 },
	{ ERROR_WIRELESS_TX_STATISTICS, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WL_TX_STATISTICAL_INFO", "CONTENT", 0 },
	{ DSM_BATTERY_ASW_PROTECT_H1_SCENE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HEAVY_CHARGING_SCENE_1", "CONTENT", 0 },
	{ DSM_BATTERY_ASW_PROTECT_H2_SCENE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HEAVY_CHARGING_SCENE_2", "CONTENT", 0 },
	{ DSM_BATTERY_ASW_PROTECT_NORMAL_SCENE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "NORMAL_CHARGING_SCENE", "CONTENT", 0 },
	{ ERROR_BATT_ACR_OVER_THRESHOLD, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATTERY_ACR_OVER_TH", "CONTENT", 0 },
	{ ERROR_NO_BYPASS_BOOST_FAULT, POWER_DSM_LEVEL_FAULT, "BATTERY", "BPBOOST_STATUS_FAULT", "CONTENT", 0 },
	{ ERROR_NO_BYPASS_BOOST_I2C_TRANS_FAIL, POWER_DSM_LEVEL_FAULT, "BATTERY", "BPBOOST_I2C_TRANS_FAIL", "CONTENT", 0 },
	{ DSM_BATT_COUL_OCV_CALI, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "COUL_OCV_CALI", "CONTENT", 0 },
	{ ERROR_BATT_SOC_JUMP_CHANGE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_SOC_JUMP_CHANGE", "CONTENT", 0 },
	{ ERROR_BATT_SOC_PARAM, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_SOC_PARAM_ERROR", "CONTENT", 0 },
	{ ERROR_BATT_SOC_DROP_FAST, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_SOC_DROP_FAST", "CONTENT", 0 },
	{ ERROR_BATT_AGING_ABNOMAL, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BATT_AGING_ABNOMAL", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_USB, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATER_CHECK_IN_USB", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_EAR, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATER_CHECK_IN_EAR", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_SIM, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATER_CHECK_IN_SIM", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_KEY, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATER_CHECK_IN_KEY", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_TWO_POSITIONS, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "WATER_CHECK_IN_TWO", "CONTENT", 0 },
	{ ERROR_NO_WATER_CHECK_IN_THREE_POSITIONS, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"WATER_CHECK_IN_THREE", "CONTENT", 0 },
	{ ERROR_NO_TYPEC_CC_OVP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "PORT_OVP_IN_CC_SBU_DPDM", "CONTENT", 0 },
	{ POWER_DSM_ACR_ERROR_NO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "", "CONTENT", 0 },
	{ DSM_POWER_DEVICES_INFO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HARDWARE_INFO_LOG", "CONTENT", 0 },
	{ POWER_DSM_ASW_SCENE_H3, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "SMART_CHARGING_SCENE_3", "CONTENT", 0 },
	{ POWER_DSM_ASW_SCENE_H4, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HEAVY_CHARGING_SCENE_4", "CONTENT", 0 },
	{ POWER_DSM_ASW_SCENE_H5, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HEAVY_CHARGING_SCENE_5", "CONTENT", 0 },
	{ POWER_DSM_ASW_SCENE_H6, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "HEAVY_CHARGING_SCENE_6", "CONTENT", 0 },
	{ POWER_DSM_ERROR_ADP_AUTH_RECHECK_FAIL, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DIFFERENTIATE_CHARGER", "CONTENT", 0 },
	{ DSM_OTG_VBUS_SHORT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "OTG_SHORT_CIRCUIT_DETECT", "CONTENT", 0 },
	{ DSM_WLPS_GPIO_TXSW, POWER_DSM_LEVEL_FAULT, "BATTERY", "WL_TX_GPIO_CHECK_FAILED", "CONTENT", 0 },
	{ DSM_SOFT_RECHARGE_NO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "SOFT_RECHARGE", "CONTENT", 0 },
	{ DSM_BATTERY_HEATING, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "LOW_TEMP_HEATING_CHARGING_INFO", "CONTENT", 0 },
	{ DSM_USB_PORT_TEMP_EXCEED_50, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "USB_PORT_OVER_TEMP_TH", "CONTENT", 0 },
	{ DSM_USB_PORT_TEMP_EXCEED_55, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "USB_PORT_TEMP_SERIOUSLY_HOT", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_FULL_PATH_RESISTANCE_2ND, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"SECOND_FULL_PATH_RES_OVER_TH", "CONTENT", 0 },
	{ POWER_DSM_CVT_ABNORMAL, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_CV_T_SLOPE_OVER_TH", "CONTENT", 0 },
	{ POWER_DSM_FASTFCC_SLOPE_OVER_THRESHOLD, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"FASTFCC_CYCLE_SLOPE_OVER_TH", "CONTENT", 0 },
	{ POWER_DSM_ACR_SLOPE_OVER_THRESHOLD, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_ACR_SLOPE_OVER_TH", "CONTENT", 0 },
	{ DSM_MULTI_CHARGE_CURRENT_RATIO_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"DC_CUR_BALANCE_FATAL_EXCEPTION", "CONTENT", 0 },
	{ DSM_MULTI_CHARGE_CURRENT_RATIO_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DC_CUR_BALANCE_OVER_TH", "CONTENT", 0 },
	{ DSM_MULTI_CHARGE_CURRENT_RATIO_INFO, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DC_CUR_BALANCE_INFORMATION", "CONTENT", 0 },
	{ DSM_FUELGAGUE_SOFT_RESET, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "JULIA_NOT_CHG_FULL", "CONTENT", 0 },
	{ ERROR_NO_SMPL, POWER_DSM_LEVEL_FAULT, "BATTERY", "SMPL", "CONTENT", 0 },

	/* direct_charge_sc */
	{ DSM_DIRECT_CHARGE_SC_FAULT_IBAT_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_IBAT_OCP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_IBUS_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_IBUS_OCP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_TSBAT_OTP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_TSBAT_OTP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_VBUS_OVP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_VBUS_OVP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_VBAT_OVP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_VBAT_OVP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_TSBUS_OTP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_TSBUS_OTP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_TDIE_OTP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_TDIE_OTP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_AC_OVP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_AC_OVP", "CONTENT", 0 },
	{ DSM_DIRECT_CHARGE_SC_FAULT_CONV_OCP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DC_FAULT_CONV_OCP", "CONTENT", 0 },

	/* scharger */
	{ DSM_CHARGE_SCHARGER_USB_PORT_VDROPMIN_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"USB_VDROPMIN_ERROR", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_SERIAL_PARALLEL_SWITCH_QSW2_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"SERIAL_PARALLEL_SWITCH_QSW2", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_SERIAL_PARALLEL_SWITCH_QSW1_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"SERIAL_PARALLEL_SWITCH_QSW1", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_SERIAL_CHARGE_QSW2_RCP_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY",
		"SERIAL_CHARGE_QSW2_RCP", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_PARALLEL_ONE_BATTERY_DISCHARGE_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"PARALLEL_ONE_BATTERY_DISCHARGE", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_SERIAL_CHARGE_ONE_BATTERY_ERR_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"SERIAL_CHARGE_ONE_BATTERY_ERROR", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_LVC_PATH_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "LVC_PATH_WARNING", "CONTENT", 0 },
	{ DSM_CHARGE_SCHARGER_FUEL_GAUGE_PRECISION_WARNING, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"FUEL_GAUGE_PRECISION_WARNING", "CONTENT", 0 },
	{ DSM_CHARGE_DYNAMIC_CV_TRIM_MAX, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DYNAMIC_CV_TRIM_MAX", "CONTENT", 0 },
	{ DSM_CHARGE_DYNAMIC_CV_TRIM_INFO, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "DYNAMIC_CV_TRIM_INFO", "CONTENT", 0 },
	{ DSM_CHARGE_DYNAMIC_CV_CHARGER_DONE_VBAT_INFO, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"DYNAMIC_CV_CHARGER_DONE_VBAT_INFO", "CONTENT", 0 },
	{ DSM_SC0_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC0_ERROR", "CONTENT", 0 },
	{ DSM_SC0_WARNING, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC0_WARNING", "CONTENT", 0 },
	{ DSM_SC0_INFO, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC0_INFO", "CONTENT", 0 },
	{ DSM_SC1_ERROR, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC1_ERROR", "CONTENT", 0 },
	{ DSM_SC1_WARNING, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC1_WARNING", "CONTENT", 0 },
	{ DSM_SC1_INFO, POWER_DSM_LEVEL_FAULT, "BATTERY", "SC1_INFO", "CONTENT", 0 },

	/* uscp */
	{ ERROR_NO_USB_SHORT_PROTECT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "USB_SHORT_PROTECT", "CONTENT", 0 },
	{ ERROR_NO_USB_SHORT_PROTECT_NTC, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "USB_SHORT_PROTECT_NTC", "CONTENT", 0 },
	{ ERROR_NO_USB_SHORT_PROTECT_HIZ, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "USB_SHORT_PROTECT_HIZ", "CONTENT", 0 },

	/* smartcharge */
	{ SMARTCHARGE_ILLEGAL_BAT_REUSE, POWER_DSM_LEVEL_FAULT, "BATTERY", "ILLEGAL_BAT_REUSE", "CONTENT", 0 },
	{ SMARTCHARGE_DCR_ABNORMAL_WHEN_BOOTUP, POWER_DSM_LEVEL_FAULT, "BATTERY", "DCR_ABNORMAL_WHEN_BOOTUP", "CONTENT", 0 },
	{ SMARTCHARGE_DCR_ABNORMAL_NOW, POWER_DSM_LEVEL_FAULT, "BATTERY", "DCR_ABNORMAL_NOW", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_NO_FAULT_WHEN_BOOTUP, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"BAT_NO_FAULT_WHEN_BOOTUP", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_VOL_TEMP, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_VOL_TEMP", "CONTENT", 0 },
	{ SMARTCHARGE_CCA_BAT_PROTECT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "STATISTICS_CCA_BAT_PROTECT", "CONTENT", 0 },
	{ SMARTCHARGE_ACR_DET, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "STATISTICS_ACR_DET", "CONTENT", 0 },
	{ SMARTCHARGE_DCR_DET0, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "STATISTICS_DCR_DET0", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_VOL_TEMP_SHORT, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_VOL_TEMP_SHORT", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_AGING_SAFE, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_AGING_SAFE", "CONTENT", 0 },
	{ SMARTCHARGE_QNS_BAT_PROTECTION, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"STATISTICS_QNS_BAT_PROTECTION", "CONTENT", 0 },
	{ SMARTCHARGE_CV_T_DET, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "STATISTICS_CV_T_DET", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_ANTI_BIG_DATA, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_ANTI_BIG_DATA", "CONTENT", 0 },
	{ SMARTCHARGE_FAST_FCC_RAW_DATA, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "FAST_FCC_RAW_DATA", "CONTENT", 0 },
	{ SMARTCHARGE_SAFETY_DET_PARAS_IN_BAT, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"SAFETY_DET_PARAS_IN_BAT", "CONTENT", 0 },
	{ SMARTCHARGE_DCR_DET1, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "STATISTICS_DCR_DET1", "CONTENT", 0 },
	{ SMARTCHARGE_REVERSE_SUPER_FAST_CHG, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "REVERSE_SUPER_FAST_CHG", "CONTENT", 0 },
	{ SMARTCHARGE_REVERSE_SUPER_FAST_CHG_FAIL, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"REVERSE_SUPER_FAST_CHG_FAIL", "CONTENT", 0 },
	{ SMARTCHARGE_BAT_HEALTH_RAW_DATA, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "BAT_HEALTH_RAW_DATA", "CONTENT", 0 },
	{ SMARTCHARGE_Q_OFFSET_WLC, POWER_DSM_LEVEL_STATISTIC, "BATTERY", "Q_OFFSET_WLC", "CONTENT", 0 },
	{ SMARTCHARGE_NON_STD_CHARGER_PLUG_IN, POWER_DSM_LEVEL_STATISTIC, "BATTERY",
		"NON_STD_CHARGER_PLUG_IN", "CONTENT", 0 },

	/* bms_behavior */
	{ BMSBEHAVIOR_NOT_CHARGING_IBUS_ZERO, POWER_DSM_LEVEL_FAULT, "BATTERY", "NOT_CHARGING_IBUS_ZERO", "CONTENT", 0 },
	{ BMSBEHAVIOR_NOT_CHARGING_TEMP_OVER, POWER_DSM_LEVEL_FAULT, "BATTERY", "NOT_CHARGING_TEMP_OVER", "CONTENT", 0 },
	{ BMSBEHAVIOR_CHARGING_SLOW_TEMP_OVER, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGING_SLOW_TEMP_OVER", "CONTENT", 0 },
	{ BMSBEHAVIOR_CHARGING_SLOW_IBUS_LOW, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGING_SLOW_IBUS_LOW", "CONTENT", 0 },
	{ BMSBEHAVIOR_CHARGING_OVER_RELEASE, POWER_DSM_LEVEL_FAULT, "BATTERY", "CHARGING_OVER_RELEASE", "CONTENT", 0 },
	{ BMSBEHAVIOR_BATTERY_NOT_PRESENT, POWER_DSM_LEVEL_FAULT, "BATTERY", "BATTERY_NOT_PRESENT", "CONTENT", 0 },
};

int power_dsm_single_battery_register(void)
{
	struct power_dsm_err_map *power_err_map = NULL;
	int i;
	power_err_map = power_dsm_single_map_register("BATTERY");
	if (power_err_map) {
		power_err_map->event_num = sizeof(hisysevent_map) / sizeof(hisysevent_map[0]);
		for (i = 0; i < power_err_map->event_num; i++) {
			power_err_map->map[i].error_no = hisysevent_map[i].error_no;
			power_err_map->map[i].level = hisysevent_map[i].level;
			(void)strncpy_s(power_err_map->map[i].domain, POWER_DSM_BUF_SIZE_0016,
				hisysevent_map[i].domain, strlen(hisysevent_map[i].domain));
			(void)strncpy_s(power_err_map->map[i].name, POWER_DSM_BUF_SIZE_0032,
				hisysevent_map[i].name, strlen(hisysevent_map[i].name));
			(void)strncpy_s(power_err_map->map[i].key, POWER_DSM_BUF_SIZE_0048,
				hisysevent_map[i].key, strlen(hisysevent_map[i].key));
			power_err_map->map[i].running_test_switch = hisysevent_map[i].running_test_switch;
		}
	}
	return 0;
}
EXPORT_SYMBOL(power_dsm_single_battery_register);

int power_dsm_single_domain_check(const char *domain)
{
	return (!strncmp(domain, "BATTERY", POWER_DSM_BUF_SIZE_0016) ||
		!strncmp(domain, "DSM_USB", POWER_DSM_BUF_SIZE_0016) ||
		!strncmp(domain, "PMU_OCP", POWER_DSM_BUF_SIZE_0016));
}
EXPORT_SYMBOL(power_dsm_single_domain_check);