add_hm_library(sysmgr_client.c)
add_hm_library(devmgr_client.c)
add_hm_library(devhost_client.c)
add_hm_library(fs_client.c)
add_hm_library(pwrmgr_client.c)
add_hm_library(freqmgr_client.c)
add_hm_library(utils_ldso.c)
add_hm_library(utils.c)
add_hm_library(utils_devmgr.c)
add_hm_library(srvmgr_client.c)
add_hm_library(hguard_client.c)
add_hm_library(auditmgr_client.c)
add_hm_library(keymgr_client.c)
add_hm_library(uvmm_client.c)
add_hm_library(crypto_client.c)
if (CONFIG_EVENTMGR)
add_hm_library(eventcb_client.c)
endif()

# set_source_files_properties(sysmgr_server.c PROPERTIES COMPILE_FLAGS -Wno-address-of-packed-member)
set_source_files_properties(utils_devmgr.c PROPERTIES COMPILE_FLAGS -D_GNU_SOURCE)
# To solve compilation warning when string.h is refernced under armeb
set_source_files_properties(utils_devmgr.c PROPERTIES COMPILE_FLAGS -Wno-strict-prototypes)
