NPU_ARCH_VERSION=npu_v310
HTS_ARCH_VERSION=v100
FFTS_ARCH_VERSION=ffts_v100
CONFIG_NPU_PM_FUSION=y
CONFIG_NPU_AUTOFS=n
CONFIG_NPU_SDMA=n
CONFIG_NPU_SYSCACHE=y
CONFIG_NPU_DIRECT=y
CONFIG_NPU_SMARTISP=y

ifneq ($(filter y,$(CONFIG_FFRT_FFTS) $(CONFIG_FFRT_FFTS_OHOS)),)
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_FFRT -DCONFIG_NPU_FFRT_V100
CONFIG_NPU_FFRT=y
export CONFIG_NPU_FFRT
endif

export NPU_ARCH_VERSION HTS_ARCH_VERSION FFTS_ARCH_VERSION CONFIG_NPU_PM_FUSION CONFIG_NPU_AUTOFS CONFIG_NPU_SDMA CONFIG_NPU_DIRECT
export CONFIG_NPU_SYSCACHE CONFIG_NPU_SMARTISP

NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SYSCACHE
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SUPPORT_AIV
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_DIRECT
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_ISPNN_INFO
NPU_GLOBAL_CFLAGS += -DPLATFORM_GET_RESMEM_FROM_DTS
NPU_GLOBAL_CFLAGS += -DCONFIG_NPU_SMARTISP
NPU_GLOBAL_CFLAGS += -DCONFIG_SELF_HEALING
NPU_GLOBAL_CFLAGS += -DCONFIG_SELF_HEALING_PV_DIS