/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Description: coulometer hardware schargerv800 configure headfile
 *
 * This software is licensed under the terms of the GNU General Public
 * License, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 */

#ifndef __SCHARGER_V800_REGS_H__
#define __SCHARGER_V800_REGS_H__

#include <soc_schargerV800_interface.h>

/* coul register of smartstar */
#define COUL_CALI_ENABLE                BIT(4)

#define COUL_ECO_FLT_200MS              (BIT(1)|BIT(2))
#define COUL_ALL_REFLASH                0
#define COUL_ECO_REFLASH                BIT(0)
#define DEFAULT_COUL_CTRL_VAL (COUL_ECO_FLT_200MS | COUL_ALL_REFLASH)
#define ECO_COUL_CTRL_VAL     (COUL_ECO_FLT_200MS | COUL_ECO_REFLASH )

#define CALI_AUTO_ONOFF_CTRL            BIT(4)
#define CALI_AUTO_TIME_15S              0
#define CALI_AUTO_TIME_60S              BIT(2)
#define CALI_AUTO_TIME_8MIN             BIT(3)
#define CALI_AUTO_TIME_32MIN            (BIT(2) | BIT(3))

/* Warning: bit change */
#define MASK_CALI_AUTO_OFF     (CALI_AUTO_ONOFF_CTRL)

#define WAIT_COMP_EN      (REG_CLJ_CTRL_REG1_wait_comp_en_START)

#define COUL_CLEAR_IRQ                  0x7F
#define COUL_VBAT_DROP_MASK             BIT(6)               
#define COUL_I_OUT_MASK                 BIT(5)
#define COUL_I_IN_MASK                  BIT(4)
#define COUL_VBAT_INT_MASK              BIT(3)
#define COUL_CL_IN_MASK                 BIT(2)
#define COUL_CL_OUT_MASK                BIT(1)
#define COUL_CL_INT_MASK                BIT(0)
#define COUL_INT_MASK_ALL (COUL_I_OUT_MASK | COUL_I_IN_MASK | \
	COUL_VBAT_INT_MASK | COUL_CL_IN_MASK | \
	COUL_CL_OUT_MASK | COUL_CL_INT_MASK | COUL_VBAT_DROP_MASK)

#define COUL_MSTATE_MASK                0x0f

/* register write lock/unlock */
#define COUL_WRITE_LOCK                 0x5a
#define COUL_WRITE_UNLOCK               0xac

#define SOH_DIS                         0
#define SOH_EN                          1

#define ECO_FIFO_CLEAR                  BIT(REG_CLJ_CTRL_REG2_eco_data_clr_START)
#define ECO_FIFO_EN                     BIT(REG_CLJ_CTRL_REG2_data_eco_en_START)
#define DATA_CLEAR                      BIT(REG_CLJ_CTRL_REG5_reg_data_clr_START)

#define ECO_DELAY_500MS                 0
#define ECO_DELAY_2S                    1
#define ECO_DELAY_5S                    2
#define ECO_DELAY_10S                   3
#define ECO_DELAY_ENTER_EN              BIT(1)
#define ECO_FILTER_OUT_EN               BIT(0)
#define ECO_ENTER                       BIT(2)

#define VBAT_L_DROP_EN_SHIFT            REG_V_DROP_CTRL0_l_vbat_drop_det_en_START
#define VBAT_H_DROP_EN_SHIFT            REG_V_DROP_CTRL0_h_vbat_drop_det_en_START
#define VBAT_L_DROP_TH_SHIFT            REG_V_DROP_CTRL0_l_vbat_drop_det_th_START
#define VBAT_H_DROP_TH_SHIFT            REG_V_DROP_CTRL0_h_vbat_drop_det_th_START

// 0x300
#define COUL_REG_CHIP_VERSION0_ADDR         REG_VERSION0_RO_REG_0_ADDR(REG_GLB_BASE)

// 0x304
#define COUL_REG_CHIP_VERSION4_ADDR         REG_VERSION4_RO_REG_0_ADDR(REG_GLB_BASE)

// 0x510
#define COUL_REG_DEBUG_WRITE_PRO_ADDR      REG_DEBUG_WRITE_PRO_ADDR(REG_COUL_NOPWR0_BASE)
// 0x32f
#define COUL_REG_BAT_CNCT_SEL_ADDR      REG_BAT_CNCT_SEL_ADDR(REG_GLB_BASE)
// 0x51a
#define COUL_REG_V_INT0_ADDR     REG_V_INT0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X51D
#define COUL_REG_I_OUT_GATE0_ADDR  REG_I_OUT_GATE0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X520
#define COUL_REG_I_IN_GATE0_ADDR           REG_I_IN_GATE0_ADDR(REG_COUL_NOPWR0_BASE)
// 0x400
#define COUL_REG_CLJ_CTRL_REG_ADDR        REG_CLJ_CTRL_REG0_ADDR(REG_COUL_PWR_BASE)
// 0X509
#define COUL_REG_CLJ_CTRL_REG1_ADDR        REG_CLJ_CTRL_REG4_ADDR(REG_COUL_NOPWR0_BASE)
// 0X50A
#define COUL_REG_CLJ_CTRL_REGS2_ADDR REG_CLJ_CTRL_REG5_ADDR(REG_COUL_NOPWR0_BASE)
// 0X401
#define COUL_REG_CLJ_CTRL_REGS3_ADDR   REG_CLJ_CTRL_REG1_ADDR(REG_COUL_PWR_BASE)
// 0X402
#define COUL_REG_CLJ_CTRL_REGS4_ADDR  REG_CLJ_CTRL_REG2_ADDR(REG_COUL_PWR_BASE)
// 0X50C
#define COUL_REG_STATE_TEST_ADDR           REG_STATE_TEST_ADDR(REG_COUL_NOPWR0_BASE)
// 0X500
#define COUL_REG_COUL_IRQ_FLAG_ADDR        REG_COUL_IRQ_FLAG_ADDR(REG_COUL_NOPWR0_BASE)
// 0X6A3
#define COUL_REG_L_OFFSET_VOLTAGE0_ADDR    REG_L_OFFSET_VOLTAGE0_ADDR(REG_COUL_NOPWR1_BASE)
// 0x552
#define COUL_REG_L_CL_OUT_RO0_ADDR         REG_L_CL_OUT_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X557
#define COUL_REG_L_CL_IN_RO0_ADDR          REG_L_CL_IN_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X55C
#define COUL_REG_L_CHG_TIMER_RO0_ADDR      REG_L_CHG_TIMER_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X560
#define COUL_REG_L_LOAD_TIMER_RO0_ADDR     REG_L_LOAD_TIMER_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X68C
#define COUL_REG_L_CHG_TIMER0_ADDR         REG_L_CHG_TIMER0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X690
#define COUL_REG_L_LOAD_TIMER0_ADDR        REG_L_LOAD_TIMER0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X69D
#define COUL_REG_L_V_OUT_0_ADDR            REG_L_V_OUT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X69A
#define COUL_REG_L_CURRENT_0_ADDR          REG_L_CURRENT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X6B6
#define COUL_REG_L_V_PRE0_OUT0_ADDR        REG_L_V_PRE0_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X6CE
#define COUL_REG_L_CURRENT_PRE0_OUT0_ADDR  REG_L_CURRENT_PRE0_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X6AC
#define COUL_REG_L_ECO_OUT_CLIN_0_ADDR     REG_L_ECO_OUT_CLIN_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0x6b1
#define COUL_REG_L_ECO_OUT_CLOUT_0_ADDR    REG_L_ECO_OUT_CLOUT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X505
#define COUL_REG_COUL_L_IRQ_MASK_ADDR      REG_COUL_L_IRQ_MASK_ADDR(REG_COUL_NOPWR0_BASE)
// 0X502
#define COUL_REG_COUL_L_IRQ_FLAG_ADDR      REG_COUL_L_IRQ_FLAG_ADDR(REG_COUL_NOPWR0_BASE)
// 0X682
#define COUL_REG_L_CL_OUT0_ADDR            REG_L_CL_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X687
#define COUL_REG_L_CL_IN0_ADDR             REG_L_CL_IN0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X627
#define COUL_REG_H_OFFSET_VOLTAGE0_ADDR    REG_H_OFFSET_VOLTAGE0_ADDR(REG_COUL_NOPWR1_BASE)
// 0x540
#define COUL_REG_H_CL_OUT_RO0_ADDR         REG_H_CL_OUT_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0x545
#define COUL_REG_H_CL_IN_RO0_ADDR          REG_H_CL_IN_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X54A
#define COUL_REG_H_CHG_TIMER_RO0_ADDR      REG_H_CHG_TIMER_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0X54E
#define COUL_REG_H_LOAD_TIMER_RO0_ADDR     REG_H_LOAD_TIMER_RO0_ADDR(REG_COUL_NOPWR0_BASE)
// 0x60a
#define COUL_REG_H_CHG_TIMER0_ADDR         REG_H_CHG_TIMER0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X60E
#define COUL_REG_H_LOAD_TIMER0_ADDR        REG_H_LOAD_TIMER0_ADDR(REG_COUL_NOPWR1_BASE)
// 0x61e
#define COUL_REG_H_V_OUT_0_ADDR            REG_H_V_OUT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X61B
#define COUL_REG_H_CURRENT_0_ADDR          REG_H_CURRENT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X63A
#define COUL_REG_H_V_PRE0_OUT0_ADDR        REG_H_V_PRE0_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X652
#define COUL_REG_H_CURRENT_PRE0_OUT0_ADDR  REG_H_CURRENT_PRE0_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X630
#define COUL_REG_H_ECO_OUT_CLIN_0_ADDR     REG_H_ECO_OUT_CLIN_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X635
#define COUL_REG_H_ECO_OUT_CLOUT_0_ADDR    REG_H_ECO_OUT_CLOUT_0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X504
#define COUL_REG_COUL_H_IRQ_MASK_ADDR       REG_COUL_H_IRQ_MASK_ADDR(REG_COUL_NOPWR0_BASE)
// 0X600
#define COUL_REG_H_CL_OUT0_ADDR            REG_H_CL_OUT0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X605
#define COUL_REG_H_CL_IN0_ADDR             REG_H_CL_IN0_ADDR(REG_COUL_NOPWR1_BASE)
// 0X501
#define COUL_REG_COUL_H_IRQ_FLAG_ADDR       REG_COUL_H_IRQ_FLAG_ADDR(REG_COUL_NOPWR0_BASE)
// 0x508
#define COUL_RD_REQ_ADDR                    REG_COUL_RD_REQ_ADDR(REG_COUL_NOPWR0_BASE)
// 0x5A0
#define COUL_V_DROP_CTRL0_ADDR              REG_V_DROP_CTRL0_ADDR(REG_COUL_NOPWR0_BASE)
// 0x5B0
#define COUL_H_V_DROP_PRE0_OUT0             REG_H_V_DROP_PRE0_OUT0_ADDR(REG_COUL_NOPWR0_BASE)
// 0x5B9
#define COUL_L_V_DROP_PRE0_OUT0             REG_L_V_DROP_PRE0_OUT0_ADDR(REG_COUL_NOPWR0_BASE)
#endif

