/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2019-2021. All rights reserved.
 * Author: Huawei OS Kernel Lab
 * Create: Wed Apr 10 9:24:58 2019
 */

#ifndef HMLDSO_ARCH_AARCH64_RELOC_H
#define HMLDSO_ARCH_AARCH64_RELOC_H

#ifdef __ILP32__
#define LDSO_REL_SYMBOLIC    R_AARCH64_P32_ABS32
#define LDSO_REL_GOT         R_AARCH64_P32_GLOB_DAT
#define LDSO_REL_PLT         R_AARCH64_P32_JUMP_SLOT
#define LDSO_REL_RELATIVE    R_AARCH64_P32_RELATIVE
#define LDSO_REL_COPY        R_AARCH64_P32_COPY
#define LDSO_REL_DTPMOD      R_AARCH64_P32_TLS_DTPMOD
#define LDSO_REL_DTPOFF      R_AARCH64_P32_TLS_DTPREL
#define LDSO_REL_TPOFF       R_AARCH64_P32_TLS_TPREL
#define LDSO_REL_TLSDESC     R_AARCH64_P32_TLSDESC
#else
#define LDSO_REL_SYMBOLIC    R_AARCH64_ABS64
#define LDSO_REL_GOT         R_AARCH64_GLOB_DAT
#define LDSO_REL_PLT         R_AARCH64_JUMP_SLOT
#define LDSO_REL_RELATIVE    R_AARCH64_RELATIVE
#define LDSO_REL_COPY        R_AARCH64_COPY
#define LDSO_REL_DTPMOD      R_AARCH64_TLS_DTPMOD64
#define LDSO_REL_DTPOFF      R_AARCH64_TLS_DTPREL64
#define LDSO_REL_TPOFF       R_AARCH64_TLS_TPREL64
#define LDSO_REL_TLSDESC     R_AARCH64_TLSDESC
#endif

#endif
