obj-y += vibrator_event/
obj-$(CONFIG_HUAWEI_VIBRATOR) += vibrator_common/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw86907/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw8697/
obj-$(CONFIG_CLASSD_VIBRATOR) += classd_vibrator/
obj-$(CONFIG_EXT_VIBRATOR) += ext_vibrator/
obj-$(CONFIG_HISI_EXT_VIBRATOR) += ext_vibrator/
obj-$(CONFIG_HUAWEI_VIBRATOR) += aw_vibrator/
obj-$(CONFIG_HUAWEI_VIBRATOR) += sih6887/
obj-$(CONFIG_PMU_LINEAR_HAPTIC_EVADE) += pmu_vibrator/
obj-$(CONFIG_HUAWEI_VIBRATOR) += cdv2625_haptic/
obj-$(CONFIG_HUAWEI_VIBRATOR) += flat_vibrator/
ifeq ($(CONFIG_AUDIO_HAPTIC), y)
obj-$(CONFIG_HUAWEI_VIBRATOR) += v3/
endif
