#
# Copyright (c) Hisilicon Technologies Co., Ltd. 2024-2024. All rights reserved.
#

INCLUDE_DIR += \
	-I$(HVGR_PATH)/platform \
	-I$(HVGR_PATH)/platform/p0000500

SRC += \
	$(HVGR_ROOT)/platform/p0000500/hvgr_platform_map.c \
	$(HVGR_ROOT)/platform/p0000500/hvgr_platform_reset.c \
	$(HVGR_ROOT)/platform/p0000500/hvgr_platform_ffa.c \
	$(HVGR_ROOT)/platform/p0000500/hvgr_platform_mem.c

ifeq ($(CONFIG_HVGR_DFX_SH), y)
	SRC += $(HVGR_ROOT)/platform/p0000500/hvgr_platform_dfx.c
endif

ifeq ($(HVGR_FEATURE_SYSTEM_CACHE), 1)
	SRC += $(HVGR_ROOT)/platform/p0000500/hvgr_platform_mem_sc.c
endif
