ccflags-y += -I$(srctree)/drivers/platform_drivers/tzdriver

obj-$(CONFIG_LOAD_VENC)	+= load_venc_ca.o
obj-$(CONFIG_LOAD_VENC)	+= load_venc.o

ccflags-y += -Wdate-time -Wextra -Wfloat-equal -Wformat=2 -Wshadow