/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Description: Device header file for Code Decrypt
 * Author: Huawei OS Kernel Lab
 * Create: Thur Jan 04 18:30:00 2024
 */

#ifndef VFS_DEV_CODE_DECRYPT_H
#define VFS_DEV_CODE_DECRYPT_H

#include <sys/ioctl.h>

#define DEV_CODE_DECRYPT_MINOR				0x22
#define HM_CODE_DECRYPT_IOCTL_BASE			'c'
#define HM_CODE_DECRYPT_CMD_SET_KEY_ID			0x01
#define HM_CODE_DECRYPT_CMD_REMOVE_KEY_ID		0x02
#define HM_CODE_DECRYPT_CMD_SET_ASSOCIATE_KEY_ID	0x03
#define HM_CODE_DECRYPT_CMD_REMOVE_ASSOCIATE_KEY_ID	0x04
#define HM_CODE_DECRYPT_CMD_CLEAR_CACHE_BY_KEY_ID	0x05
#define HM_CODE_DECRYPT_CMD_CLEAR_CACHE_BY_FILE_ID	0x06
#define HM_CODE_DECRYPT_CMD_CLEAR_SPECIFIC_CACHE_ID	0x07

#define CODE_DECRYPT_CMD_SET_KEY \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_SET_KEY_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_REMOVE_KEY \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_REMOVE_KEY_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_SET_ASSOCIATE_KEY \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_SET_ASSOCIATE_KEY_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_REMOVE_ASSOCIATE_KEY \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_REMOVE_ASSOCIATE_KEY_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_CLEAR_CACHE_BY_KEY \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_CLEAR_CACHE_BY_KEY_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_CLEAR_CACHE_BY_FILE \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_CLEAR_CACHE_BY_FILE_ID, struct code_decrypt_arg)
#define CODE_DECRYPT_CMD_CLEAR_SPECIFIC_CACHE \
	_IOW(HM_CODE_DECRYPT_IOCTL_BASE, HM_CODE_DECRYPT_CMD_CLEAR_SPECIFIC_CACHE_ID, struct code_decrypt_arg)

struct code_decrypt_arg {
	int arg1_len;
	int arg2_len;
	void *arg1;
	void *arg2;
};

#endif // VFS_DEV_CODE_DECRYPT_H
