/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 * Description: arm spe driver
 * Author: HISI_DRV
 * Create: Mon Mar 25 09:43:36 2024
 */
#ifndef AARCH64_ASM_DRIVERS_SPE_H
#define AARCH64_ASM_DRIVERS_SPE_H

#include <hmasm/processor.h>

enum arm_spe_pmu_buf_fault_action {
	SPE_PMU_BUF_FAULT_ACT_SPURIOUS,
	SPE_PMU_BUF_FAULT_ACT_FATAL,
	SPE_PMU_BUF_FAULT_ACT_OK,
};

#define PMBLIMITR_EL1	"S3_0_C9_C10_0"
#define PMBPTR_EL1	    "S3_0_C9_C10_1"
#define PMBSR_EL1		"S3_0_C9_C10_3"
#define PMBIDR_EL1		"S3_0_C9_C10_7"
#define PMSCR_EL1		"S3_0_C9_C9_0"
#define PMSNEVFR_EL1	"S3_0_C9_C9_1"
#define PMSICR_EL1		"S3_0_C9_C9_2"
#define PMSIRR_EL1		"S3_0_C9_C9_3"
#define PMSFCR_EL1		"S3_0_C9_C9_4"
#define PMSEVFR_EL1	    "S3_0_C9_C9_5"
#define PMSLATFR_EL1	"S3_0_C9_C9_6"
#define PMSIDR_EL1		"S3_0_C9_C9_7"

#define psb_csync()	asm volatile("hint #17" : : : "memory")

#define _DEFINE_SYSREG_READ_FUNC(_name, _reg_name)			\
static inline u64 read_##_name(void)							\
{									\
	return read_sysreg(_reg_name);					\
}

#define _DEFINE_SYSREG_WRITE_FUNC(_name, _reg_name)			\
static inline void write_##_name(u64 v)						\
{									\
	write_sysreg(_reg_name, v);					\
}

/* Define read & write function for renamed system register */
#define DEFINE_RENAME_SYSREG_RW_FUNCS(_name, _reg_name)			\
	_DEFINE_SYSREG_READ_FUNC(_name, _reg_name)			\
	_DEFINE_SYSREG_WRITE_FUNC(_name, _reg_name)

DEFINE_RENAME_SYSREG_RW_FUNCS(pmbidr_el1, PMBIDR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmblimitr_el1, PMBLIMITR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmbptr_el1, PMBPTR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmbsr_el1, PMBSR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmscr_el1, PMSCR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsevfr_el1, PMSEVFR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsnevfr_el1, PMSNEVFR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsfcr_el1, PMSFCR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsicr_el1, PMSICR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsidr_el1, PMSIDR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmsirr_el1, PMSIRR_EL1)
DEFINE_RENAME_SYSREG_RW_FUNCS(pmslatfr_el1, PMSLATFR_EL1)

#define HM_PMSIDR_EL1_FE_SHIFT		0
#define HM_PMSIDR_EL1_FT_SHIFT		1
#define HM_PMSIDR_EL1_FL_SHIFT		2
#define HM_PMSIDR_EL1_ARCHINST_SHIFT	3
#define HM_PMSIDR_EL1_LDS_SHIFT	4
#define HM_PMSIDR_EL1_ERND_SHIFT	5
#define HM_PMSIDR_EL1_FnE_SHIFT	6
#define HM_PMSIDR_EL1_INTERVAL_SHIFT	8
#define HM_PMSIDR_EL1_INTERVAL_MASK	0xfUL
#define HM_PMSIDR_EL1_MAXSIZE_SHIFT	12
#define HM_PMSIDR_EL1_MAXSIZE_MASK	0xfUL
#define HM_PMSIDR_EL1_COUNTSIZE_SHIFT	16
#define HM_PMSIDR_EL1_COUNTSIZE_MASK	0xfUL

#define SYS_PMBIDR_EL1_ALIGN_SHIFT	0
#define SYS_PMBIDR_EL1_ALIGN_MASK	0xfU
#define SYS_PMBIDR_EL1_P_SHIFT		4
#define SYS_PMBIDR_EL1_F_SHIFT		5

#define HM_PMSCR_EL1_E0SPE_SHIFT	0
#define HM_PMSCR_EL1_E1SPE_SHIFT	1
#define HM_PMSCR_EL1_CX_SHIFT		3
#define HM_PMSCR_EL1_PA_SHIFT		4
#define HM_PMSCR_EL1_TS_SHIFT		5
#define HM_PMSCR_EL1_PCT_SHIFT		6

#define HM_PMSCR_EL2_E0HSPE_SHIFT	0
#define HM_PMSCR_EL2_E2SPE_SHIFT	1
#define HM_PMSCR_EL2_CX_SHIFT		3
#define HM_PMSCR_EL2_PA_SHIFT		4
#define HM_PMSCR_EL2_TS_SHIFT		5
#define HM_PMSCR_EL2_PCT_SHIFT		6

#define SYS_PMSIRR_EL1_RND_SHIFT	0
#define SYS_PMSIRR_EL1_INTERVAL_SHIFT	8
#define SYS_PMSIRR_EL1_INTERVAL_MASK	0xffffffUL

#define SYS_PMSFCR_EL1_FE_SHIFT		0
#define SYS_PMSFCR_EL1_FT_SHIFT		1
#define SYS_PMSFCR_EL1_FL_SHIFT		2
#define SYS_PMSFCR_EL1_FnE_SHIFT	3
#define SYS_PMSFCR_EL1_B_SHIFT		16
#define SYS_PMSFCR_EL1_LD_SHIFT		17
#define SYS_PMSFCR_EL1_ST_SHIFT		18

#define SYS_PMSEVFR_EL1_RES0		0x0000FFFF00F90F15UL

#define SYS_PMSNEVFR_EL1_RES0		0x0000FFFF00F90715UL

#define SYS_PMSLATFR_EL1_MINLAT_SHIFT	0

#define SYS_PMBLIMITR_EL1_E_SHIFT	0
#define SYS_PMBLIMITR_EL1_FM_SHIFT	1
#define SYS_PMBLIMITR_EL1_FM_MASK	0x3UL
#define SYS_PMBLIMITR_EL1_FM_STOP_IRQ	(0 << SYS_PMBLIMITR_EL1_FM_SHIFT)
#define SYS_PMBLIMITR_EL1_FM_DISCARD	(2 << SYS_PMBLIMITR_EL1_FM_SHIFT)
#define SYS_PMBLIMITR_EL1_PMFZ_SHIFT	5

#define HM_PMBSR_EL1_COLL_SHIFT	16
#define HM_PMBSR_EL1_S_SHIFT		17
#define HM_PMBSR_EL1_EA_SHIFT		18
#define HM_PMBSR_EL1_DL_SHIFT		19
#define HM_PMBSR_EL1_EC_SHIFT		26
#define HM_PMBSR_EL1_EC_MASK		0x3fUL

#define HM_PMBSR_EL1_EC_BUF		(0x0UL << HM_PMBSR_EL1_EC_SHIFT)
#define HM_PMBSR_EL1_EC_FAULT_S1	(0x24UL << HM_PMBSR_EL1_EC_SHIFT)
#define HM_PMBSR_EL1_EC_FAULT_S2	(0x25UL << HM_PMBSR_EL1_EC_SHIFT)

#define HM_PMBSR_EL1_FAULT_FSC_SHIFT	0
#define HM_PMBSR_EL1_FAULT_FSC_MASK	0x3fUL

#define HM_PMBSR_EL1_BUF_BSC_SHIFT	0
#define HM_PMBSR_EL1_BUF_BSC_MASK	0x3fUL

#define HM_PMBSR_EL1_BUF_BSC_FULL	(0x1UL << HM_PMBSR_EL1_BUF_BSC_SHIFT)

#define HM_SPE_PMU_FEAT_FILT_EVT			(1UL << 0)
#define HM_SPE_PMU_FEAT_FILT_TYP			(1UL << 1)
#define HM_SPE_PMU_FEAT_FILT_LAT			(1UL << 2)
#define HM_SPE_PMU_FEAT_ARCH_INST			(1UL << 3)
#define HM_SPE_PMU_FEAT_LDS			(1UL << 4)
#define HM_SPE_PMU_FEAT_ERND			(1UL << 5)
#define HM_SPE_PMU_FEAT_FILT_NEVT			(1UL << 6)
#define HM_SPE_PMU_FEAT_DISCARD			(1UL << 7)
#define HM_SPE_PMU_FEAT_PMFZ				(1UL << 8)
#define HM_SPE_PMU_FEAT_DEV_PROBED			(1UL << 63)

#endif /* AARCH64_ASM_DRIVERS_SPE_H */
