	.text
	.file	"mas_bkops_sysfs.c"
	.globl	mas_bkops_add_debugfs           // -- Begin function mas_bkops_add_debugfs
	.p2align	2
	.type	mas_bkops_add_debugfs,@function
mas_bkops_add_debugfs:                  // @mas_bkops_add_debugfs
// %bb.0:
	mov	w0, wzr
	ret
.Lfunc_end0:
	.size	mas_bkops_add_debugfs, .Lfunc_end0-mas_bkops_add_debugfs
                                        // -- End function
	.ident	"OHOS (BiSheng Mobile CPU STD 202.1.0.B030) clang version 15.0.4 (llvm-project 7123208073d2)"
	.section	".note.GNU-stack","",@progbits
	.addrsig
