# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_I3C_V100_DESIGNWARE)		+= dw_i3c_v100.o
obj-$(CONFIG_I3C_V200_MASTER)       += i3c_v200_master.o
obj-$(CONFIG_I3C_V200_MASTER)       += i3c_v200_dma.o